window.__subjectData_hist_7r_dreissigj_krieg = [
    { question: "Welcher Frieden beendete den Dreißigjährigen Krieg 1648?", answers: ["Frieden von Paris", "Westfälischer Friede", "Frieden von Wien", "Frieden von Augsburg"], correct: 1, hint: "Vertrag von Münster und Osnabrück", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Der Dreißigjährige Krieg war ursprünglich ein...", answers: ["Handelskonflikt", "Religionskrieg", "Erbfolgekrieg", "Bauernkrieg"], correct: 1, hint: "Katholiken gegen Protestanten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "In welchem Zeitraum fand der Dreißigjährige Krieg statt?", answers: ["1555-1585", "1618-1648", "1648-1678", "1500-1530"], correct: 1, hint: "Beginn mit Prager Fenstersturz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Ereignis löste den Krieg aus?", answers: ["Der Bauernkrieg", "Der Prager Fenstersturz", "Die Reformation", "Der Tod des Kaisers"], correct: 1, hint: "Protestantische Adlige warfen Statthalter aus dem Fenster", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Feldherr kämpfte auf katholischer Seite?", answers: ["Gustav Adolf", "Wallenstein", "Tilly", "Bernhard von Weimar"], correct: 1, hint: "Kaiserlicher General", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher schwedische König kämpfte auf protestantischer Seite?", answers: ["Karl XII.", "Gustav II. Adolf", "Friedrich der Große", "Oskar II."], correct: 1, hint: "Der Löwe aus Mitternacht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Folgen hatte der Krieg für die Bevölkerung?", answers: ["Wirtschaftlicher Aufschwung", "Massive Bevölkerungsverluste und Verwüstung", "Frieden und Wohlstand", "Industrielle Revolution"], correct: 1, hint: "Etwa 1/3 der Bevölkerung starb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bestimmte der Westfälische Friede?", answers: ["Das Ende aller Kriege", "Die Souveränität der deutschen Territorien", "Die Abschaffung der Monarchie", "Die Gründung der UN"], correct: 1, hint: "Stärkung der Landesherren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielte Frankreich im Dreißigjährigen Krieg?", answers: ["Neutral", "Kämpfte auf katholischer Seite gegen die Habsburger", "Kämpfte auf protestantischer Seite", "War nicht beteiligt"], correct: 2, hint: "Kardinal Richelieu", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Warum wird der Krieg als 'Dreißigjährig' bezeichnet?", answers: ["Er dauerte genau 30 Jahre", "Vier Phasen über 30 Jahre", "30 Jahre Frieden folgten", "30 Länder waren beteiligt"], correct: 1, hint: "1618-1648", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war eine 'Stehende Armee'?", answers: ["Armee, die nur im Krieg aufgestellt wurde", "Ein dauerhaft bestehendes Heer", "Freiwillige Kämpfer", "Söldner aus dem Ausland"], correct: 1, hint: "Nach dem Krieg etabliert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Land wurde durch den Westfälischen Frieden unabhängig?", answers: ["Österreich", "Die Schweiz", "Die Niederlande", "Polen"], correct: 2, hint: "Trennung vom Heiligen Römischen Reich", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];