window.__subjectData_hist_7r_fruehe_neuzeit = [
    { question: "Wer entdeckte 1492 Amerika?", answers: ["Vasco da Gama", "Christoph Kolumbus", "Ferdinand Magellan", "James Cook"], correct: 1, hint: "Er suchte den Seeweg nach Indien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Renaissance'?", answers: ["Eine Seuche", "Eine Wiedergeburt der Antike", "Eine Erfindung", "Ein Krieg"], correct: 1, hint: "Wiederentdeckung der Kunst und Wissenschaft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche wichtige Erfindung wurde um 1440 gemacht?", answers: ["Das Schießpulver", "Der Buchdruck", "Die Dampfmaschine", "Das Telefon"], correct: 1, hint: "Johannes Gutenberg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'kognitive Wende' in der Renaissance?", answers: ["Neue Kriegstechniken", "Der Mensch rückte in den Mittelpunkt", "Neue Handelsrouten", "Weniger Bildung"], correct: 1, hint: "Humanismus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Weltbild galt vor der Renaissance?", answers: ["Heliozentrisch (Sonne im Zentrum)", "Geozentrisch (Erde im Zentrum)", "Die Erde ist eine Scheibe", "Es gab kein Weltbild"], correct: 1, hint: "Ptolemäisches System", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wer umsegelte als Erster die Erde?", answers: ["Kolumbus", "Magellan (bzw. seine Crew)", "Vasco da Gama", "Amerigo Vespucci"], correct: 1, hint: "1519-1522", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Kolonialismus'?", answers: ["Friedlicher Kulturaustausch", "Eroberung und Ausbeutung fremder Länder", "Handelsabkommen", "Wissenschaftliche Forschung"], correct: 1, hint: "Europäische Mächte in Übersee", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Gruppe wurde in der Renaissance besonders gefördert?", answers: ["Bauern", "Künstler und Gelehrte", "Handwerker", "Soldaten"], correct: 1, hint: "Mäzene wie die Medici", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Goldene Bulle' (1356)?", answers: ["Ein Goldschatz", "Regelung der Königswahl", "Ein Friedensvertrag", "Eine Steuererhebung"], correct: 1, hint: "7 Kurfürsten wählten den König", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Folgen hatten die Entdeckungsreisen für Europa?", answers: ["Weniger Handel", "Neue Waren und Reichtümer", "Krieg mit Amerika", "Rückgang der Wissenschaft"], correct: 1, hint: "Gold, Silber, Gewürze", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war das 'Indulgenzwesen'?", answers: ["Ein Handelsweg", "Der Ablasshandel der Kirche", "Eine neue Regierungsform", "Ein Gerichtssystem"], correct: 1, hint: "Vergebung von Sünden gegen Geld", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wer malte die Sixtinische Kapelle?", answers: ["Leonardo da Vinci", "Michelangelo", "Raffael", "Donatello"], correct: 1, hint: "Fresko an der Decke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Warum war die Erfindung des Buchdrucks so bedeutend?", answers: ["Bücher wurden billiger und verbreiteten sich schneller", "Menschen hörten auf zu lesen", "Nur Adlige konnten lesen", "Bücher wurden verboten"], correct: 0, hint: "Massenproduktion von Wissen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Reich eroberten die Spanier in Amerika?", answers: ["Das Römische Reich", "Das Aztekenreich", "Das Osmanische Reich", "Das Mongolenreich"], correct: 1, hint: "Hernán Cortés", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];