window.__subjectData_hist_7r_mittelalter = [
    { question: "In welche drei Stände war die Gesellschaft im Mittelalter eingeteilt?", answers: ["König, Adel, Volk", "Adel, Klerus, Bauern", "Richter, Henker, Diebe", "Ritter, Knappen, Pferde"], correct: 1, hint: "Lehrstand, Wehrstand, Nährstand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine 'Marktstadt' im Mittelalter?", answers: ["Eine Stadt mit einem Marktplatz", "Eine Stadt mit Marktrecht", "Eine Stadt an der Grenze", "Eine Stadt ohne Mauern"], correct: 1, hint: "Das Recht, Märkte abzuhalten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die Grundlage der mittelalterlichen Landwirtschaft?", answers: ["Moderne Maschinen", "Dreifelderwirtschaft", "Bewässerungssysteme", "Gewächshäuser"], correct: 1, hint: "Wechselwirtschaft mit Brache", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Lehen'?", answers: ["Ein Darlehen", "Ein vom Lehnsherrn verliehenes Land", "Ein Gesetz", "Eine Steuer"], correct: 1, hint: "Lehnsherr vs. Vasall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Aufgabe hatte ein Ritter?", answers: ["Handel treiben", "Kämpfen und Schutz bieten", "Steuern eintreiben", "Unterricht erteilen"], correct: 1, hint: "Berufskrieger im Dienst des Adels", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Kaiser krönte sich 800 zum Kaiser?", answers: ["Otto der Große", "Karl der Große", "Friedrich Barbarossa", "Heinrich IV."], correct: 1, hint: "Weihnachten in Rom", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was geschah im Investiturstreit?", answers: ["Kampf um die Krone", "Streit zwischen Kaiser und Papst um Ämterbesetzung", "Ein Bauernaufstand", "Krieg gegen die Römer"], correct: 1, hint: "Wer darf Bischöfe einsetzen?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie hieß der oberste Herrscher im Heiligen Römischen Reich?", answers: ["König", "Kaiser", "Papst", "Herzog"], correct: 1, hint: "Wurde von Kurfürsten gewählt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine 'Grundherrschaft'?", answers: ["Der König besitzt alles", "Ein Adliger besitzt Land und die darauf lebenden Bauern", "Die Kirche besitzt Grundstücke", "Bauern besitzen den Grund"], correct: 1, hint: "Wirtschaftliche Einheit im Mittelalter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Warum gingen Menschen im Mittelalter in die Stadt?", answers: ["Urlaub machen", "Freiheit und wirtschaftliche Chancen", "Schule besuchen", "Museen besichtigen"], correct: 1, hint: "Stadtluft macht frei", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was waren die Kreuzzüge?", answers: ["Handelsreisen nach Asien", "Religiös motivierte Kriege ins Heilige Land", "Entdeckungsreisen", "Kriege gegen die Wikinger"], correct: 1, hint: "Ziel: Jerusalem zurückerobern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bedeutung hatte die Hanse?", answers: ["Ein Ritterorden", "Ein Handelsbündnis norddeutscher Städte", "Eine Bauernvereinigung", "Ein Klosterverband"], correct: 1, hint: "Handel in Nord- und Ostsee", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wer stand an der Spitze der mittelalterlichen Kirche?", answers: ["Der Kaiser", "Der Papst", "Der Bischof", "Der König"], correct: 1, hint: "Oberhaupt der katholischen Kirche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Stadtluft macht frei'?", answers: ["In der Stadt gibt es keine Steuern", "Ein Leibeigener wurde nach einem Jahr in der Stadt frei", "Die Luft in der Stadt war gesünder", "Städte durften eigene Gesetze erlassen"], correct: 1, hint: "Rechtlicher Status der Leibeigenen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];