window.__subjectData_hist_7r_reformation = [
    { question: "Wer löste die Reformation in Deutschland aus?", answers: ["Johannes Calvin", "Martin Luther", "Ulrich Zwingli", "Papst Leo X."], correct: 1, hint: "95 Thesen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was waren die 95 Thesen?", answers: ["Ein neues Gesetz", "Eine Kritik am Ablasshandel", "Ein Friedensvertrag", "Ein Kochbuch"], correct: 1, hint: "Luther schrieb sie 1517", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "An welche Tür schlug Luther die 95 Thesen?", answers: ["Schlosskirche zu Wittenberg", "Kölner Dom", "St. Peter in Rom", "Münchner Frauenkirche"], correct: 0, hint: "Allerheiligenkirche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was geschah auf dem Reichstag zu Worms 1521?", answers: ["Luther wurde zum Kaiser gekrönt", "Luther wurde verhört und in die Acht erklärt", "Der Frieden wurde ausgerufen", "Die Bibel wurde gedruckt"], correct: 1, hint: "Luther weigerte sich zu widerrufen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Rechtfertigung allein aus Glauben'?", answers: ["Man muss viele gute Werke tun", "Nur der Glaube an Gott rettet", "Die Kirche entscheidet über Erlösung", "Man muss Ablassbriefe kaufen"], correct: 1, hint: "Luthers Kernlehre", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Folge hatte die Reformation für die Kirche?", answers: ["Die Kirche wurde stärker", "Die Kirche spaltete sich in katholisch und protestantisch", "Die Kirche wurde abgeschafft", "Es gab keine Veränderung"], correct: 1, hint: "Konfessionelle Spaltung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der Bauernkrieg (1524-1525)?", answers: ["Ein Krieg zwischen Bauern und Adel", "Ein Krieg Deutschlands gegen Frankreich", "Ein Religionskrieg", "Ein Handelskonflikt"], correct: 0, hint: "Aufstand gegen die Unterdrückung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Haltung nahm Luther zum Bauernkrieg ein?", answers: ["Er unterstützte die Bauern", "Er forderte die Fürsten zur Niederschlagung auf", "Er hielt sich neutral", "Er führte die Bauern an"], correct: 1, hint: "Schrift 'Wider die mörderischen Rotten der Bauern'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der Augsburger Religionsfriede (1555)?", answers: ["Das Ende des Bauernkriegs", "Die Anerkennung der lutherischen Kirche", "Die Gründung der Jesuiten", "Der Beginn der Kreuzzüge"], correct: 1, hint: "Cuius regio, eius religio", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Cuius regio, eius religio'?", answers: ["Jeder glaubt, was er will", "Wessen Land, dessen Religion", "Der Kaiser bestimmt die Religion", "Alle sind gleich"], correct: 1, hint: "Der Landesherr bestimmt die Konfession", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielte der Buchdruck bei der Reformation?", answers: ["Keine", "Luthers Schriften verbreiteten sich schnell", "Der Buchdruck war verboten", "Nur die katholische Kirche nutzte ihn"], correct: 1, hint: "Flugschriften und Bibelübersetzung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was übersetzte Luther ins Deutsche?", answers: ["Den Koran", "Die Bibel", "Die griechischen Klassiker", "Römische Gesetze"], correct: 1, hint: "Basis der neuhochdeutschen Sprache", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche protestantische Konfession entstand in der Schweiz?", answers: ["Luthertum", "Calvinismus", "Anglikanismus", "Orthodoxie"], correct: 1, hint: "Johannes Calvin in Genf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die Gegenreformation?", answers: ["Die Ausbreitung des Protestantismus", "Die katholische Erneuerung gegen die Reformation", "Ein Friedensabkommen", "Eine neue Bibelübersetzung"], correct: 1, hint: "Konzil von Trient, Jesuiten", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];