window.__subjectData_de_7r_grammatik = [
    { question: "Aktiv oder Passiv? 'Der Brief wird geschrieben.'", answers: ["Aktiv", "Passiv", "Keines von beiden", "Beides möglich"], correct: 1, hint: "werden + Partizip II", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Satz steht im Konjunktiv II?", answers: ["Er geht nach Hause.", "Er ging nach Hause.", "Er würde nach Hause gehen.", "Er ist nach Hause gegangen."], correct: 2, hint: "würde + Infinitiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Satzgefüge?", answers: ["Ein Hauptsatz", "Ein Hauptsatz + Nebensatz", "Zwei Hauptsätze", "Ein Satz ohne Verb"], correct: 1, hint: "HS + NS mit Komma", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Wort ist ein Relativpronomen?", answers: ["und", "der", "weil", "aber"], correct: 1, hint: "Bezieht sich auf ein Nomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Bestimme den Satz: 'Weil es regnet, bleiben wir zu Hause.'", answers: ["Satzreihe", "Satzgefüge (Kausalsatz)", "Einfacher Satz", "Satzgefüge (Konditionalsatz)"], correct: 1, hint: "weil = kausale Konjunktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die richtige Passiv-Form: 'Der Kuchen ____ (backen).'", answers: ["backt", "wird gebacken", "hat gebacken", "bäckt"], correct: 1, hint: "werden + Partizip II von backen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Satz enthält einen Konjunktiv I?", answers: ["Er sagte, er komme morgen.", "Er kommt morgen.", "Er würde morgen kommen.", "Er kam morgen."], correct: 0, hint: "Indirekte Rede", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Adverbialsatz?", answers: ["Ein Satz, der das Verb näher beschreibt", "Ein Satz, der die Umstände angibt", "Ein Satz ohne Subjekt", "Ein Fragesatz"], correct: 1, hint: "Zeit, Grund, Ort, Art und Weise", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Aktiv oder Passiv? 'Die Müllabfuhr leert die Tonnen jeden Dienstag.'", answers: ["Aktiv", "Passiv", "Vorgangspassiv", "Zustandspassiv"], correct: 0, hint: "Subjekt handelt aktiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Konjunktion leitet einen Finalsatz ein?", answers: ["weil", "damit", "obwohl", "wenn"], correct: 1, hint: "Gibt den Zweck an", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Satzgefüge oder Satzreihe? 'Er lernte viel, aber er bestand die Prüfung nicht.'", answers: ["Satzgefüge", "Satzreihe", "Einfacher Satz", "Keines von beiden"], correct: 1, hint: "Zwei Hauptsätze mit 'aber'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Attribut?", answers: ["Ein Satzglied", "Eine nähere Bestimmung zu einem Nomen", "Ein Verb", "Ein Adverb"], correct: 1, hint: "Beifügung, z.B. Adjektiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Forme ins Passiv um: 'Der Mechaniker repariert das Auto.'", answers: ["Das Auto wird repariert.", "Das Auto repariert.", "Der Mechaniker wird repariert.", "Das Auto repariert den Mechaniker."], correct: 0, hint: "Objekt wird Subjekt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was drückt der Konjunktiv II hauptsächlich aus?", answers: ["Tatsachen", "Wünsche und irreale Bedingungen", "Befehle", "Fragen"], correct: 1, hint: "Was wäre, wenn ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Satz ist ein Konsekutivsatz?", answers: ["Weil es kalt ist, bleiben wir drinnen.", "Wenn es kalt ist, bleiben wir drinnen.", "Es ist so kalt, dass wir drinnen bleiben.", "Obwohl es kalt ist, gehen wir raus."], correct: 2, hint: "so ... dass = Folge", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];