window.__subjectData_de_7r_textarten = [
    { question: "Welche Textart berichtet sachlich über ein Ereignis?", answers: ["Erzählung", "Bericht", "Märchen", "Gedicht"], correct: 1, hint: "Wer? Was? Wann? Wo?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Bericht steht in welcher Zeitform?", answers: ["Präsens", "Futur", "Präteritum", "Plusquamperfekt"], correct: 2, hint: "Vergangenheitsform für Berichte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Textart beschreibt eine Person oder einen Gegenstand genau?", answers: ["Bericht", "Beschreibung", "Erzählung", "Dialog"], correct: 1, hint: "Adjektive und Details", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist typisch für eine Erzählung?", answers: ["Sachlichkeit", "Spannungsbogen und Höhepunkt", "Nur Fakten", "Keine Personen"], correct: 1, hint: "Einleitung, Hauptteil, Schluss", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Textart hat oft einen moralischen Schluss?", answers: ["Bericht", "Fabel", "Beschreibung", "Protokoll"], correct: 1, hint: "Tiere als Figuren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Merkmal eines Märchens?", answers: ["Realistische Figuren", "Magische Elemente und Formeln", "Wissenschaftliche Fakten", "Aktuelle Ereignisse"], correct: 1, hint: "Es war einmal ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie ist ein Bericht aufgebaut?", answers: ["Frei und fantasievoll", "Überschrift, Einleitung, Hauptteil, Schluss", "Nur Dialoge", "Reimform"], correct: 1, hint: "Sachlich strukturiert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Zeitform verwendet man in einer Beschreibung?", answers: ["Präteritum", "Plusquamperfekt", "Präsens", "Futur II"], correct: 2, hint: "Beschreibungen sind zeitlos gültig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was unterscheidet eine Nacherzählung von einer Inhaltsangabe?", answers: ["Nacherzählung ist kürzer", "Nacherzählung folgt der Reihenfolge, Inhaltsangabe fasst zusammen", "Inhaltsangabe hat mehr Details", "Nacherzählung hat wörtliche Rede"], correct: 1, hint: "Nacherzählung = ausführlich, Inhaltsangabe = knapp", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche W-Fragen beantwortet ein Bericht?", answers: ["Wer? Was? Wann? Wo? Wie? Warum?", "Wie heißen die Personen?", "Welche Farben gibt es?", "Was denkt der Autor?"], correct: 0, hint: "Vollständige Information", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Gedicht?", answers: ["Ein sachlicher Text", "Ein Text mit Reimen und Rhythmus", "Eine Gebrauchsanweisung", "Ein Protokoll"], correct: 1, hint: "Lyrische Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Textart wird in der Ich-Form geschrieben?", answers: ["Bericht", "Tagebucheintrag", "Protokoll", "Sachtext"], correct: 1, hint: "Persönliche Erlebnisse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Protokoll?", answers: ["Eine literarische Erzählung", "Eine sachliche Mitschrift", "Ein Gedicht", "Ein Brief"], correct: 1, hint: "Ergebnisse einer Sitzung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Merkmale hat ein Sachtext?", answers: ["Fantasievoll und ausgeschmückt", "Informativ, sachlich, klar strukturiert", "Nur Dialoge", "Reim und Rhythmus"], correct: 1, hint: "Vermittelt Wissen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];