window.__subjectData_de_7r_textaufgaben_verstehen = [
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Text beschreibt eine Wanderung im Gebirge. Der Autor schreibt über das Wetter, die Ausrüstung und die Dauer der Wanderung.", possibleQuestions: ["Wie war das Wetter?", "Welche Farbe hat der Rucksack?", "Wie lange dauerte die Wanderung?"], answers: ["Wie war das Wetter?", "Welche Farbe hat der Rucksack?", "Wie lange dauerte die Wanderung?"], correct: 2, hint: "Die Dauer wird im Text erwähnt.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Bericht über ein Schulfest: 120 Besucher kamen. Der Gewinn von 450€ wird gespendet. Das Fest war bei sonnigem Wetter. Die Klasse 7b verkaufte Kuchen.", secondaryQuestion: "Welche Info brauchst du für die Höhe der Spende NICHT?", answers: ["120 Besucher", "450€ Gewinn", "Sonniges Wetter", "Kuchenverkauf"], correct: 2, hint: "Die Spendenhöhe steht direkt im Text", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Lena liest ein Buch mit 240 Seiten. Sie liest jeden Tag 15 Seiten. Sie hat bereits 60 Seiten gelesen.", secondaryQuestion: "Welche Infos brauchst du, um zu berechnen, wie viele Tage Lena noch braucht?", answers: ["240 Seiten, 15 Seiten/Tag, 60 gelesen", "240 Seiten, 60 gelesen", "15 Seiten/Tag, 240 Seiten", "240 Seiten, 15 Seiten/Tag"], correct: 0, hint: "Restseiten ÷ Tagesleistung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Eine E-Mail von Max: 'Liebe Oma, ich bin in den Ferien im Zeltlager. Wir machen Lagerfeuer und schwimmen im See. Am Freitag komme ich zurück. Das Wetter ist super!'", secondaryQuestion: "Welche Info brauchst du NICHT für 'Wann kommt Max zurück?'", answers: ["Zeltlager", "Lagerfeuer", "Freitag", "Schwimmen"], correct: 1, hint: "Nur der Tag der Rückkehr zählt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->KERN übersetzen!", fullText: "Herr Schmidt kauft für seine drei Kinder je ein Eis für 2,50€ und für sich selbst einen Kaffee für 3,00€.", secondaryQuestion: "Welche Kernaussage ist richtig?", answers: ["3×2,50 + 3,00", "2,50 + 3,00", "3 × (2,50 + 3,00)", "3 Kinder + 1 Kaffee"], correct: 0, hint: "Drei Kinder × Eis + ein Kaffee", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Artikel berichtet: 'Die Gemeinde baut einen neuen Spielplatz. Die Kosten betragen 50.000€. Der Bau beginnt im März und dauert 4 Monate. 10.000€ kommen aus Spenden.'", secondaryQuestion: "Welche Infos brauchst du für 'Wie viel muss die Gemeinde selbst zahlen?'", answers: ["50.000€, 10.000€ Spenden", "50.000€, 4 Monate", "März, 50.000€", "10.000€, 4 Monate"], correct: 0, hint: "Kosten minus Spenden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "In einem Zeitungsartikel steht: 'Die 750 Schüler der Schule sammelten 2.500€ für das Kinderhospiz. Die Spendenaktion dauerte 3 Wochen.'", possibleQuestions: ["Wer ist Schulleiter?", "Wie viel Geld sammelte jeder Schüler durchschnittlich?", "Welche Farbe hat die Schule?"], answers: ["Wer ist Schulleiter?", "Wie viel Geld sammelte jeder Schüler durchschnittlich?", "Welche Farbe hat die Schule?"], correct: 1, hint: "2.500€ ÷ 750 Schüler", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Tims Zug fährt um 14:30 Uhr ab. Er muss 15 Minuten zum Bahnhof laufen. Der Zug hat 8 Waggons und fährt 120 km/h. Die Fahrkarte kostet 35€.", secondaryQuestion: "Welche Info brauchst du für 'Wann muss Tim losgehen?' NICHT?", answers: ["14:30 Uhr Abfahrt", "15 Minuten Fußweg", "120 km/h", "Fahrkarte 35€"], correct: 2, hint: "Nur Zeit und Weg zählen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->KERN übersetzen!", fullText: "Eine Klasse mit 28 Schülern fährt ins Museum. Der Eintritt kostet 4€ pro Person. Die Klasse bekommt 10% Gruppenrabatt.", secondaryQuestion: "Was ist die Kernrechnung?", answers: ["28 × 4€ × 0,9", "28 × 4€ - 10%", "28 + 4€", "28 × 4€ × 1,1"], correct: 0, hint: "Anzahl × Preis × (100% - 10%)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "In einem Prospekt steht: 'Fahrradhelm 25€ statt 40€. Fahrradlicht 15€ statt 20€. 10% Extra-Rabatt auf alles.'", possibleQuestions: ["Welche Farbe hat der Helm?", "Wie viel spart man beim Helm insgesamt?", "Wo ist das Geschäft?"], answers: ["Welche Farbe hat der Helm?", "Wie viel spart man beim Helm insgesamt?", "Wo ist das Geschäft?"], correct: 1, hint: "Ersparnis = (40€ - 25€) + 10%", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Rezept für Pfannkuchen: 200g Mehl, 3 Eier, 250ml Milch, 1 Prise Salz. Für 4 Personen. Tim möchte für 6 Personen kochen.", secondaryQuestion: "Welche Infos brauchst du, um die Mengen zu berechnen?", answers: ["Alle Zutaten, 4 Personen, 6 Personen", "200g Mehl, 4 Personen", "3 Eier, 6 Personen", "Milch und Salz"], correct: 0, hint: "Dreisatz über die Personenanzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Film beginnt um 20:15 Uhr und dauert 135 Minuten. Es gibt eine 15-minütige Pause. Der Film hat eine Altersfreigabe ab 12 Jahren.", secondaryQuestion: "Welche Info brauchst du für 'Wann endet der Film?' NICHT?", answers: ["20:15 Uhr", "135 Minuten", "15 Minuten Pause", "Ab 12 Jahren"], correct: 3, hint: "Altersfreigabe ist irrelevant für die Endzeit", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];