window.__subjectData_de_7r_zeichensetzung = [
    { question: "Welches Komma ist richtig?", answers: ["Ich weiß dass er kommt.", "Ich weiß, dass er kommt.", "Ich weiß, das er kommt.", "Ich weiß das, er kommt."], correct: 1, hint: "Komma vor 'dass'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wo steht das Komma? 'Weil es regnet bleiben wir zu Hause.'", answers: ["Nach 'regnet'", "Nach 'Weil'", "Nach 'bleiben'", "Gar kein Komma"], correct: 0, hint: "Nebensatz mit 'weil'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Satz ist richtig kommas gesetzt?", answers: ["Er kam, lachte, und ging.", "Er kam, lachte und ging.", "Er kam lachte, und ging.", "Er kam lachte und ging,"], correct: 1, hint: "Kein Komma vor 'und' bei Aufzählungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Komma oder nicht? 'Ich kaufe ____ wenn es im Angebot ist ____ ein neues Handy.'", answers: ["zwei Kommas", "ein Komma vor 'wenn'", "ein Komma nach 'Angebot'", "kein Komma"], correct: 0, hint: "Eingeschobener Nebensatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Satz hat die richtige Zeichensetzung?", answers: ["Er fragte: Kommst du mit?", "Er fragte: 'Kommst du mit?'", "Er fragte: 'Kommst du mit?'", "Er fragte, 'Kommst du mit'?"], correct: 1, hint: "wörtliche Rede in Anführungszeichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wo gehört das Komma hin? 'Obwohl er müde war lernte er weiter.'", answers: ["Nach 'obwohl'", "Nach 'war'", "Nach 'müde'", "Nach 'lernte'"], correct: 1, hint: "Konzessivsatz mit 'obwohl'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Satzzeichen fehlen? 'Hilf mir bitte'", answers: ["Komma", "Ausrufezeichen", "Fragezeichen", "Punkt"], correct: 1, hint: "Bitte / Befehl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Komma bei Infinitivgruppen: Welcher Satz ist richtig?", answers: ["Er hofft, den Zug zu erreichen.", "Er hofft den Zug zu erreichen.", "Er hofft den Zug, zu erreichen.", "Er, hofft den Zug zu erreichen."], correct: 0, hint: "Komma bei 'um zu', 'ohne zu', 'statt zu'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Richtig oder falsch? 'Das Buch, das ich lese, ist spannend.'", answers: ["Richtig (zwei Kommas)", "Falsch (kein Komma)", "Nur ein Komma nötig", "Falsch gesetzt"], correct: 0, hint: "Relativsatz = Nebensatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Satz ist korrekt?", answers: ["Er sagte: 'Ich komme morgen.'", "Er sagte: Ich komme morgen.", "Er sagte: 'Ich komme morgen'.", "Er sagte 'Ich komme morgen.'"], correct: 0, hint: "Doppelpunkt + Anführungszeichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Komma bei Appositionen? 'Herr Müller unser Nachbar hilft uns.'", answers: ["Herr Müller, unser Nachbar, hilft uns.", "Herr Müller unser Nachbar, hilft uns.", "Herr Müller, unser Nachbar hilft uns.", "Herr Müller unser Nachbar hilft, uns."], correct: 0, hint: "Einschub = zwei Kommas", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wo steht das Komma? 'Nachdem er gegessen hatte ging er spazieren.'", answers: ["Nach 'Nachdem'", "Nach 'hatte'", "Nach 'gegessen'", "Nach 'spazieren'"], correct: 1, hint: "Temporalsatz mit 'nachdem'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Richtig oder falsch? 'Er arbeitet hart, um das Ziel zu erreichen.'", answers: ["Richtig", "Falsch, kein Komma nötig", "Falsch, Komma woanders", "Falsch, zwei Kommas"], correct: 0, hint: "Infinitivgruppe mit 'um'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Zeichensetzung ist bei Aufzählungen richtig?", answers: ["Äpfel, Birnen, und Bananen", "Äpfel, Birnen und Bananen", "Äpfel Birnen und Bananen", "Äpfel, Birnen, Bananen,"], correct: 1, hint: "Kein Komma vor 'und'", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];