window.__subjectData_eng_9g_global_issues = [
    { question: "What is 'climate change' mainly caused by?", answers: ["Volcanoes", "Greenhouse gases", "Solar activity", "Wind"], correct: 1, hint: "CO2, methane, etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'globalization' mean?", answers: ["Local economies", "Worldwide interconnection", "Climate change", "Space travel"], correct: 1, hint: "Global trade, culture, communication", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'renewable energy'?", answers: ["Coal and gas", "Energy from unlimited natural sources", "Nuclear power", "Oil"], correct: 1, hint: "Solar, wind, water", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'biodiversity'?", answers: ["The variety of life on Earth", "The number of humans", "The amount of CO2", "The size of forests"], correct: 0, hint: "Different species", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'urbanization'?", answers: ["People moving to rural areas", "The growth of cities", "Climate change", "Population decline"], correct: 1, hint: "More people live in cities than countryside", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'poverty' mean?", answers: ["Wealth", "Being extremely poor", "Health", "Freedom"], correct: 1, hint: "Lack of basic needs", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the 'carbon footprint'?", answers: ["The size of a shoe", "The total CO2 emissions of a person or activity", "A type of pollution", "A measurement of heat"], correct: 1, hint: "Environmental impact", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'inequality'?", answers: ["Everyone has the same", "Unfair differences in wealth and opportunities", "A type of measurement", "Equal rights"], correct: 1, hint: "Rich vs. poor gap", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'sustainable development' mean?", answers: ["Economic growth at any cost", "Meeting present needs without compromising the future", "Stopping all development", "Only environmental protection"], correct: 1, hint: "Future generations", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'global warming'?", answers: ["Cooling of the Earth", "Rise in average global temperature", "Seasonal changes", "Volcanic activity"], correct: 1, hint: "Mainly caused by human activity", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'migration' mean in a global context?", answers: ["People staying in one place", "Movement of people across borders", "Tourism", "Living abroad temporarily"], correct: 1, hint: "Push and pull factors", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is meant by 'digital divide'?", answers: ["A gap in internet access between groups", "A new computer technology", "Online education", "Social media"], correct: 0, hint: "Connection inequality", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'deforestation'?", answers: ["Planting new forests", "Cutting down forests on a large scale", "Forest fires", "A tree disease"], correct: 1, hint: "Amazon rainforest", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'human rights' mean?", answers: ["Rights only for adults", "Basic rights and freedoms for all people", "Political privileges", "Economic benefits"], correct: 1, hint: "Universal Declaration", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];