window.__subjectData_eng_9g_grammar = [
    { question: "Which sentence uses the subjunctive correctly?", answers: ["If I was you, I would go.", "If I were you, I would go.", "If I am you, I go.", "If I be you, I went."], correct: 1, hint: "Subjunctive for unreal situations", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the correct reported speech? 'She said: I am tired.'", answers: ["She said I am tired.", "She said she was tired.", "She said she is tired.", "She says she was tired."], correct: 1, hint: "Backshift of tenses", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Which tense is used in: 'By next year, I will have finished school.'?", answers: ["Future Simple", "Future Perfect", "Future Continuous", "Present Perfect"], correct: 1, hint: "will have + past participle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'relative clause'?", answers: ["A clause that gives extra info with who/which/that", "A main clause", "A question", "A short sentence"], correct: 0, hint: "The boy who lives next door", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Which passive form is correct? 'The letter ___ yesterday.'", answers: ["is sent", "was sent", "has sent", "sends"], correct: 1, hint: "Past tense passive", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'condone' mean?", answers: ["verurteilen", "billigen / dulden", "verbergen", "bekämpfen"], correct: 1, hint: "To allow or approve", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Which sentence is correct indirect speech?", answers: ["He asked if I was coming.", "He asked if I am coming.", "He asked if I will come.", "He asked that I come."], correct: 0, hint: "Question becomes 'if/whether'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the function of a participle clause?", answers: ["To shorten sentences", "To form questions", "To make negatives", "To compare things"], correct: 0, hint: "Walking home, I met a friend.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Which conditional is used for impossible past situations?", answers: ["Type 1", "Type 2", "Type 3", "Type 0"], correct: 2, hint: "If + had + past participle, would + have + pp", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'gerund'?", answers: ["A verb form ending in -ing used as a noun", "A past tense", "A comparative", "A preposition"], correct: 0, hint: "Swimming is fun.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What tense is used for a past action that happened before another past action?", answers: ["Simple Past", "Past Perfect", "Present Perfect", "Past Continuous"], correct: 1, hint: "had + past participle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Choose the correct sentence with a participle clause:", answers: ["Seen from above, the city looks small.", "Seeing from above, the city looks small.", "Sees from above, the city looks small.", "Saw from above, the city looks small."], correct: 0, hint: "Past participle for passive meaning", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Which is a defining relative clause?", answers: ["My brother, who lives in London, is a doctor.", "The man who called you is my uncle.", "The car, which is red, is fast.", "The teacher, who is nice, helped me."], correct: 1, hint: "No commas = essential info", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the reported version of 'She said: 'I will call you.'''", answers: ["She said she would call me.", "She said she will call me.", "She said she calls me.", "She said she called me."], correct: 0, hint: "will becomes would", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];