window.__subjectData_eng_9g_text_analysis = [
    { question: "What is a 'metaphor'?", answers: ["A comparison with 'like' or 'as'", "A direct comparison without 'like'", "A rhyme", "A question"], correct: 1, hint: "He is a lion = ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the 'tone' of a text?", answers: ["The volume", "The author's attitude", "The topic", "The length"], correct: 1, hint: "Serious, humorous, critical...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'simile'?", answers: ["A direct comparison", "A comparison using 'like' or 'as'", "A metaphor", "An exaggeration"], correct: 1, hint: "He is as brave as a lion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'personification'?", answers: ["Giving human qualities to objects", "A long sentence", "A character description", "A dialogue"], correct: 0, hint: "The wind whispered through the trees", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the 'theme' of a text?", answers: ["The first paragraph", "The central message or idea", "The title", "The final sentence"], correct: 1, hint: "Love, death, friendship...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'alliteration' mean?", answers: ["Repetition of vowel sounds", "Repetition of starting consonant sounds", "A rhythm pattern", "A rhyme scheme"], correct: 1, hint: "Peter Piper picked", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the difference between 'fact' and 'opinion'?", answers: ["No difference", "Fact can be proven, opinion is a belief", "Fact is a belief, opinion is proven", "Both are the same"], correct: 1, hint: "Evidence vs. personal view", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'irony' mean in a text?", answers: ["A coincidence", "A contrast between expectation and reality", "A funny story", "A metaphor"], correct: 1, hint: "The opposite of what is expected", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'climax' in a story?", answers: ["The beginning", "The turning point / highest tension", "The ending", "A side character"], correct: 1, hint: "Peak of the action", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the purpose of a 'topic sentence'?", answers: ["To end a paragraph", "To introduce the main idea of a paragraph", "To ask a question", "To add details"], correct: 1, hint: "Usually the first sentence", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'coherence' mean in a text?", answers: ["The text is long", "Ideas are logically connected", "The text has pictures", "The text rhymes"], correct: 1, hint: "Clear flow of ideas", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is 'characterization'?", answers: ["Describing a setting", "How a character is presented", "The plot twist", "The moral"], correct: 1, hint: "Direct and indirect methods", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is an 'oxymoron'?", answers: ["Two opposite words combined", "A long word", "A new word", "A foreign word"], correct: 0, hint: "Deafening silence, bittersweet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'bias' mean in a text?", answers: ["Objectivity", "A one-sided perspective", "The truth", "The conclusion"], correct: 1, hint: "Unfair preference or prejudice", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];