window.__subjectData_eng_9g_textaufgaben_verstehen = [
    { mode: "text_surgeon", question: "❌ DISTRACTION!", fullText: "A study shows that 60% of teenagers use social media daily. They spend about 3 hours online. The study was conducted in 2024.", secondaryQuestion: "Which info is IRRELEVANT for 'How much time do teens spend online?'", answers: ["60% of teenagers", "3 hours online", "2024", "social media"], correct: 2, hint: "The year doesn't affect the hours.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FIND THE QUESTION!", fullText: "A company produces 5000 smartphones per day. Each phone requires 2 hours of labor. 20% of phones have a minor defect.", possibleQuestions: ["How many phones are produced per week?", "What color are the phones?", "Who is the CEO?"], answers: ["How many phones are produced per week?", "What color are the phones?", "Who is the CEO?"], correct: 0, hint: "5000 × 7", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 FIND NEEDED INFO!", fullText: "A charity raised 1 million dollars. 40% goes to education, 35% to health, and 25% to emergency aid. The charity has 50 employees.", secondaryQuestion: "What do you need to calculate the amount for education?", answers: ["1 million, 40%", "1 million, 35%", "40%, 35%", "50 employees, 1 million"], correct: 0, hint: "Total × percentage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "units_detective", question: "📏 CHECK UNITS!", fullText: "The distance between New York and LA is 4000. A car consumes 8 of fuel per 100. Fuel costs 0.80 per liter.", secondaryQuestion: "Which unit fits in all gaps?", answers: ["km, L, $", "miles, L, cent", "km, gallons, $", "m, L, cent"], correct: 0, hint: "Standard US road trip units", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FIND THE QUESTION!", fullText: "A factory emitted 500 tons of CO2 last year. This year emissions dropped by 15%.", possibleQuestions: ["How much CO2 is emitted this year?", "What is the name of the factory?", "Where is the factory located?"], answers: ["How much CO2 is emitted this year?", "What is the name of the factory?", "Where is the factory located?"], correct: 0, hint: "500 × 0.85", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ DISTRACTION!", fullText: "An article discusses renewable energy. It mentions solar power (cost: 0.05€/kWh), wind power (0.08€/kWh), and coal (0.12€/kWh). The article was written by Dr. Smith.", secondaryQuestion: "Which info is IRRELEVANT for 'Which energy source is cheapest?'", answers: ["0.05€/kWh solar", "0.12€/kWh coal", "Dr. Smith", "0.08€/kWh wind"], correct: 2, hint: "Only prices are relevant", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT TO TERM!", fullText: "A school has 800 students. 45% are female. 60% of female students play a musical instrument.", secondaryQuestion: "Which calculation finds how many female students play an instrument?", answers: ["800 × 0.45 × 0.60", "800 × 0.60", "800 × 0.45", "800 × 0.45 + 800 × 0.60"], correct: 0, hint: "Total × female% × instrument%", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 FIND NEEDED INFO!", fullText: "A university has 10,000 students. 4,000 live on campus. The other students commute. The average commute is 45 minutes.", secondaryQuestion: "What info do you need for 'How many students commute?'", answers: ["10,000 total, 4,000 on campus", "10,000 total, 45 min commute", "4,000 on campus, 45 min", "10,000 total, 4,000 on campus, 45 min"], correct: 0, hint: "Total minus on-campus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FIND THE QUESTION!", fullText: "In a survey of 200 people, 60% preferred online shopping. 25% preferred in-store. The rest had no preference.", possibleQuestions: ["How many people prefer online shopping?", "What was the survey about?", "Who conducted the survey?"], answers: ["How many people prefer online shopping?", "What was the survey about?", "Who conducted the survey?"], correct: 0, hint: "200 × 0.60", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ DISTRACTION!", fullText: "A company has 500 employees. Average salary is 45,000€. 30% work from home. The company was founded in 1998.", secondaryQuestion: "Which info is IRRELEVANT for total annual salary cost?", answers: ["500 employees", "45,000€ average", "30% work from home", "Founded 1998"], correct: 2, hint: "Only employee count and average salary matter", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];