window.__subjectData_de_9g_erroerterung = [
    { question: "Was ist der erste Schritt einer Erörterung?", answers: ["Die Schlussfolgerung", "Die These/Behauptung", "Das Fazit", "Die Überschrift"], correct: 1, hint: "Man beginnt mit einer Behauptung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Eine lineare Erörterung hat welche Struktur?", answers: ["These - Gegenthese - Synthese", "Einleitung - Hauptteil - Schluss", "Frage - Antwort - Beispiel", "Nur Argumente"], correct: 1, hint: "Klassischer Aufbau", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen linearer und dialektischer Erörterung?", answers: ["Linear: eine Seite; Dialektisch: Pro und Contra", "Kein Unterschied", "Linear: Pro/Contra; Dialektisch: eine Seite", "Linear ist länger"], correct: 0, hint: "Sanduhr- vs. Blockprinzip", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine 'These'?", answers: ["Ein Beispiel", "Eine Behauptung, die bewiesen werden soll", "Ein Argument", "Eine Frage"], correct: 1, hint: "Ausgangspunkt einer Erörterung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bestandteile gehören in den Hauptteil einer linearen Erörterung?", answers: ["Nur Beispiele", "Argumente mit Begründungen und Beispielen", "Nur die Meinung", "Die Einleitung"], correct: 1, hint: "Steigerndes Argumentieren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was gehört in die Einleitung einer Erörterung?", answers: ["Das Fazit", "Hinführung zum Thema und These", "Argumente", "Beispiele"], correct: 1, hint: "Leser abholen, Thema vorstellen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was gehört in den Schluss einer Erörterung?", answers: ["Neue Argumente", "Zusammenfassung, Fazit, Ausblick", "Die Einleitung", "Beispiele"], correct: 1, hint: "Abrundung des Textes", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Argument'?", answers: ["Eine Behauptung ohne Begründung", "Eine begründete Aussage zur Stützung einer These", "Eine Frage", "Ein Beispiel"], correct: 1, hint: "These + Begründung + Beispiel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Steigerung' in einer linearen Erörterung?", answers: ["Vom schwächsten zum stärksten Argument", "Vom stärksten zum schwächsten", "Keine Ordnung", "Alle Argumente gleich"], correct: 0, hint: "Überzeugungskraft steigern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Argumenttypen gibt es?", answers: ["Sachargumente, moralische, pragmatische, autoritative", "Nur Fakten", "Nur Meinungen", "Nur Beispiele"], correct: 0, hint: "Verschiedene Überzeugungsstrategien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine 'Antithese' in der dialektischen Erörterung?", answers: ["Die Gegenthese zur eigenen Position", "Der Schluss", "Die Einleitung", "Ein Beispiel"], correct: 0, hint: "Gegenposition darstellen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie widerlegt man eine Gegenthese?", answers: ["Ignorieren", "Mit Gegenargumenten entkräften", "Zustimmen", "Wiederholen"], correct: 1, hint: "Kritische Auseinandersetzung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Sprachform ist in einer Erörterung angemessen?", answers: ["Umgangssprache", "Sachlich, differenziert, treffend", "Poetisch", "Jugendsprache"], correct: 1, hint: "Wissenschaftsnaher Stil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Zweck einer Erörterung?", answers: ["Unterhalten", "Zu einer sachlichen Auseinandersetzung führen", "Informieren", "Vergnügen"], correct: 1, hint: "Den Leser überzeugen oder informieren", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];