window.__subjectData_de_9g_grammatik = [
    { question: "Was ist ein 'Gliedsatz'?", answers: ["Ein Satz ohne Verb", "Ein Nebensatz als Satzglied", "Ein Hauptsatz", "Ein Fragesatz"], correct: 1, hint: "Er kann durch ein Adverb ersetzt werden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Erkenne den Satzgefüge-Typ: 'Ich gehe, weil ich müde bin.'", answers: ["Satzreihe", "Kausalsatz", "Konditionalsatz", "Konzessivsatz"], correct: 1, hint: "Grund oder Ursache", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Konditionalsatz'?", answers: ["Ein Satz, der einen Grund angibt", "Ein Satz, der eine Bedingung ausdrückt", "Ein Satz, der einen Gegengrund angibt", "Ein Satz, der die Zeit angibt"], correct: 1, hint: "Wenn ... dann", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Konzessivsatz'?", answers: ["Ein Satz mit 'weil'", "Ein Satz mit 'obwohl' / 'obgleich'", "Ein Satz mit 'damit'", "Ein Satz mit 'wenn'"], correct: 1, hint: "Gegengrund, unerwartete Folge", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Finalsatz'?", answers: ["Ein Satz, der einen Zweck angibt (damit/um...zu)", "Ein Satz, der die Zeit angibt", "Ein Satz, der einen Grund angibt", "Ein Satz, der eine Folge angibt"], correct: 0, hint: "Absicht / Ziel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Bestimme die Satzart: 'Obwohl er krank war, kam er zur Schule.'", answers: ["Kausalsatz", "Konzessivsatz", "Konditionalsatz", "Modalsatz"], correct: 1, hint: "unerwartetes Ereignis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Relativsatz'?", answers: ["Ein Nebensatz mit 'der', 'die', 'das'", "Ein Hauptsatz", "Ein Fragesatz", "Ein einfacher Satz"], correct: 0, hint: "Bezieht sich auf ein Nomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Gliedteilsatz'?", answers: ["Ein Satz, der ein Satzgliedteil ersetzt", "Ein Hauptsatz", "Ein einfacher Satz", "Ein Fragesatz"], correct: 0, hint: "Z.B. ein Attributsatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Konjunktion leitet einen Konsekutivsatz ein?", answers: ["weil", "so dass", "obwohl", "damit"], correct: 1, hint: "Folge oder Ergebnis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen Satzreihe und Satzgefüge?", answers: ["Satzreihe = HS+HS, Satzgefüge = HS+NS", "Satzreihe = HS+NS, Satzgefüge = HS+HS", "Kein Unterschied", "Satzreihe ist länger"], correct: 0, hint: "Nebensatz vs. Hauptsatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Subjektsatz'?", answers: ["Ein Nebensatz, der das Subjekt ersetzt", "Ein Satz mit vielen Subjekten", "Ein Hauptsatz", "Ein Objektsatz"], correct: 0, hint: "Dass er kommt, freut mich.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Bestimme: 'Er rannte, so schnell er konnte.'", answers: ["Modalsatz", "Kausalsatz", "Temporalsatz", "Konzessivsatz"], correct: 0, hint: "Art und Weise", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Wortart leitet einen Nebensatz meistens ein?", answers: ["Nomen", "Konjunktion (dass, weil, wenn...)", "Verb", "Adjektiv"], correct: 1, hint: "Unterordnende Konjunktionen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Satzgefüge'?", answers: ["Mehrere Hauptsätze", "Ein Hauptsatz mit mindestens einem Nebensatz", "Ein einziger Satz", "Ein Fragesatz"], correct: 1, hint: "Komplexer Satzbau", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];