window.__subjectData_de_9g_textanalyse = [
    { question: "Was ist eine Metapher?", answers: ["Ein Reim", "Eine sprachliche Bildübertragung", "Ein Vergleich mit 'wie'", "Eine Frage"], correct: 1, hint: "Übertragene Bedeutung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Reimschema hat 'ABAB'?", answers: ["Paarreim", "Kreuzreim", "Umarmender Reim", "Kein Reim"], correct: 1, hint: "ABAB = Kreuzreim", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine 'Personifikation'?", answers: ["Vermenschlichung eines Gegenstands", "Ein Vergleich", "Eine Übertreibung", "Ein Reim"], correct: 0, hint: "Der Wind flüstert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Vergleich' in der Literatur?", answers: ["Eine Gegenüberstellung mit 'wie' oder 'als'", "Eine Metapher", "Ein Symbol", "Eine Alliteration"], correct: 0, hint: "Er ist stark wie ein Bär", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Wirkung hat ein Enjambement?", answers: ["Der Satz endet mit dem Vers", "Der Satz läuft über den Vers hinaus", "Ein neuer Absatz", "Ein besonders langer Vers"], correct: 1, hint: "Zeilen sprung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'sprachlichen Mitteln'?", answers: ["Fachbegriffe", "Stilistische Gestaltungsmittel", "Fremdwörter", "Dialekte"], correct: 1, hint: "Metapher, Alliteration, etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie analysiert man einen Gedicht?", answers: ["Inhalt - Form - Sprache - Deutung", "Nur den Reim", "Nur den Inhalt", "Nur den Autor"], correct: 0, hint: "Ganzheitliche Analyse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen Kurzgeschichte und Roman?", answers: ["Kürze, weniger Figuren, Alltagssituation", "Kein Unterschied", "Kurzgeschichte hat Reime", "Roman hat keine Handlung"], correct: 0, hint: "Textlänge und Komplexität", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Interpretation'?", answers: ["Eine Zusammenfassung", "Das Herausarbeiten der Bedeutung eines Textes", "Das Lesen eines Textes", "Die Bewertung eines Textes"], correct: 1, hint: "Sinn und Absicht verstehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine 'Inhaltsangabe'?", answers: ["Eine kurze, sachliche Zusammenfassung", "Eine Bewertung", "Eine Interpretation", "Eine Nacherzählung mit Details"], correct: 0, hint: "Knapp, objektiv, im Präsens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Textsorte ist eine 'Ballade'?", answers: ["Ein Gedicht", "Ein Drama", "Ein Roman", "Eine Mischform aus Lyrik, Epik und Dramatik"], correct: 3, hint: "Goethe, Schiller", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Monolog' im Drama?", answers: ["Ein Gespräch zwischen zwei Personen", "Ein Selbstgespräch einer Figur", "Eine Regieanweisung", "Ein Dialog"], correct: 1, hint: "Lautes Denken auf der Bühne", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Point of View' (Erzählperspektive)?", answers: ["Die Sichtweise, aus der erzählt wird", "Der Höhepunkt der Handlung", "Die Moral der Geschichte", "Der Titel des Werks"], correct: 0, hint: "Ich-Erzähler, auktorial, personal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Funktion hat ein 'Symbol' in einem Text?", answers: ["Es schmückt den Text", "Es steht für etwas Abstraktes", "Es erklärt die Handlung", "Es nennt Fakten"], correct: 1, hint: "Taube = Frieden, Rose = Liebe", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];