window.__subjectData_math_7r_textaufgaben_verstehen = [
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Eine Schulklasse fährt ins Museum. Der Eintritt kostet 3€ pro Schüler. Es sind 28 Schüler in der Klasse. Die Lehrerin heißt Frau Müller.", secondaryQuestion: "Welche Info brauchst du für 'Was kostet der Eintritt insgesamt?' NICHT?", answers: ["3€ pro Schüler", "28 Schüler", "Frau Müller", "Eintrittspreis"], correct: 2, hint: "Der Name ist irrelevant.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Zug fährt mit 80 km/h. Die Strecke ist 240 km lang. Der Zug hat 10 Waggons mit je 80 Sitzplätzen.", possibleQuestions: ["Wie viele Sitzplätze hat der Zug?", "Wie lange braucht der Zug?", "Welche Farbe hat der Zug?"], answers: ["Wie viele Sitzplätze hat der Zug?", "Wie lange braucht der Zug?", "Welche Farbe hat der Zug?"], correct: 1, hint: "t = s / v", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Für eine Party kaufen Lea und Max ein. Lea bringt 15€ mit, Max 20€. Sie kaufen 3 Pizzen für je 8€ und 2 Getränke für je 2€.", secondaryQuestion: "Welche Infos brauchst du für 'Reicht das Geld?'", answers: ["15€ + 20€, 3×8€, 2×2€", "Nur 15€ + 20€", "3 Pizzen, 2 Getränke", "15€, 20€, 3 Pizzen"], correct: 0, hint: "Geld = Ausgaben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "units_detective", question: "📏 EINHEITEN-Prüfung!", fullText: "Ein Klassenzimmer ist 8 lang und 6 breit. Ein Lineal ist 30 lang. Ein Blatt Papier wiegt 80.", secondaryQuestion: "Welche Einheit passt in alle Lücken?", answers: ["m, cm, g", "cm, m, kg", "m, dm, g", "dm, cm, mg"], correct: 0, hint: "Zimmer in m, Lineal in cm, Papier in g", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->TERM übersetzen!", fullText: "Tom hat 30€. Er kauft 4 Hefte für je 2€ und 1 Buch für 12€.", secondaryQuestion: "Welcher Term berechnet, wie viel Tom noch hat?", answers: ["30 + 4×2 + 12", "30 - 4×2 - 12", "30 - 4×2 + 12", "4×2 + 12"], correct: 1, hint: "Startgeld minus Ausgaben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Schwimmbadbecken hat 25 m Länge, 12 m Breite und 2 m Tiefe. Es kostet 4€ Eintritt. Öffnungszeiten: 10-18 Uhr.", secondaryQuestion: "Welche Info brauchst du für 'Wie viel Wasser passt ins Becken?' NICHT?", answers: ["25 m Länge", "4€ Eintritt", "12 m Breite", "2 m Tiefe"], correct: 1, hint: "Wassermenge = Volumen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Paket wiegt 1,5 kg. Das Porto beträgt 3,50€ pro kg. Max hat 10€ dabei.", possibleQuestions: ["Wie schwer ist das Paket in g?", "Wie viel Porto kostet das Paket?", "Wie heißt der Paketbote?"], answers: ["Wie schwer ist das Paket in g?", "Wie viel Porto kostet das Paket?", "Wie heißt der Paketbote?"], correct: 1, hint: "Porto = Gewicht × Preis pro kg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Fahrrad kostet 250€. Lisa spart 12 Wochen. Pro Woche bekommt sie 15€ Taschengeld. Sie hat schon 80€ gespart.", secondaryQuestion: "Welche Infos brauchst du für 'Schafft Lisa es in 12 Wochen?'", answers: ["250€, 12×15€, 80€", "250€, 12×15€", "12×15€, 80€", "250€, 80€, 12"], correct: 0, hint: "Preis vs. Erspartes + Ersparnis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Gärtner pflanzt 48 Blumen in 6 Reihen. Jede Reihe hat die gleiche Anzahl. Die Blumen sind rot, gelb und blau.", possibleQuestions: ["Welche Farbe haben die meisten Blumen?", "Wie viele Blumen sind in jeder Reihe?", "Wann wurden die Blumen gepflanzt?"], answers: ["Welche Farbe haben die meisten Blumen?", "Wie viele Blumen sind in jeder Reihe?", "Wann wurden die Blumen gepflanzt?"], correct: 1, hint: "48 : 6", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Zug fährt von München nach Hamburg (800 km). Er fährt um 8:15 Uhr ab und kommt um 14:15 Uhr an. Es gibt 8 Haltestellen.", secondaryQuestion: "Welche Info brauchst du für 'Wie schnell fährt der Zug?' NICHT?", answers: ["800 km", "8:15 bis 14:15", "8 Haltestellen", "6 Stunden Fahrzeit"], correct: 2, hint: "v = s / t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Eine Bäckerei verkauft 120 Brötchen am Morgen. 3/4 der Brötchen sind Weizenbrötchen, der Rest sind Roggenbrötchen.", possibleQuestions: ["Wie schmecken die Brötchen?", "Wie viele Roggenbrötchen werden verkauft?", "Wann öffnet die Bäckerei?"], answers: ["Wie schmecken die Brötchen?", "Wie viele Roggenbrötchen werden verkauft?", "Wann öffnet die Bäckerei?"], correct: 1, hint: "1/4 von 120", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Rechteck ist 12 cm lang und 8 cm breit. Ein Quadrat hat eine Seitenlänge von 10 cm.", secondaryQuestion: "Welche Infos brauchst du für 'Welche Figur hat den größeren Umfang?'", answers: ["12+8+12+8 vs. 10×4", "12×8 vs. 10×10", "12+8 vs. 10", "Nur die Längen"], correct: 0, hint: "Umfang = Summe aller Seiten", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];