window.__subjectData_math_7r_zuordnungen = [
    { question: "3 Äpfel kosten 1,50€. Wie viel kosten 6 Äpfel?", answers: ["2,00€", "3,00€", "4,50€", "1,50€"], correct: 1, hint: "Doppelte Menge = doppelter Preis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Auto fährt 100 km in 2 Stunden. Wie weit kommt es in 5 Stunden?", answers: ["150 km", "200 km", "250 km", "300 km"], correct: 2, hint: "50 km/h", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "4 Arbeiter bauen eine Mauer in 6 Stunden. Wie lange brauchen 3 Arbeiter?", answers: ["4,5 h", "8 h", "7 h", "9 h"], correct: 1, hint: "Antiproportional: weniger Arbeiter = mehr Zeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "5 kg Kartoffeln kosten 4€. Was kostet 1 kg?", answers: ["0,60€", "0,80€", "1,00€", "0,90€"], correct: 1, hint: "Preis durch Menge teilen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Für 8 Personen reicht der Vorrat 12 Tage. Wie lange reicht er für 6 Personen?", answers: ["9 Tage", "16 Tage", "14 Tage", "10 Tage"], correct: 1, hint: "Antiproportional: weniger Personen = länger", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Zuordnung ist antiproportional?", answers: ["Alter und Körpergröße", "Geschwindigkeit und Fahrzeit", "Anzahl Äpfel und Gesamtpreis", "Stunden lernen und Noten"], correct: 1, hint: "Je mehr, desto weniger", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Rezept für 4 Personen braucht 200 g Mehl. Wie viel Mehl für 7 Personen?", answers: ["300 g", "350 g", "400 g", "280 g"], correct: 1, hint: "Dreisatz: 200 : 4 × 7", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "3 Maschinen produzieren 1200 Teile pro Stunde. Wie viele Teile produzieren 5 Maschinen?", answers: ["1800", "2000", "1500", "2400"], correct: 1, hint: "1200 : 3 × 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Wasserbecken wird mit 2 Pumpen in 9 Stunden geleert. Wie lange mit 3 Pumpen?", answers: ["6 h", "4,5 h", "7 h", "5 h"], correct: 0, hint: "Antiproportional: 9 × 2 : 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Tabelle zeigt eine proportionale Zuordnung?", answers: ["x: 1,2,3 / y: 2,4,6", "x: 1,2,3 / y: 2,3,4", "x: 1,2,3 / y: 5,6,7", "x: 1,2,3 / y: 10,20,40"], correct: 0, hint: "y = x × 2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "15 m Stoff kosten 45€. Wie viel kosten 8 m?", answers: ["20€", "24€", "28€", "30€"], correct: 1, hint: "Preis pro Meter: 45 : 15 = 3€", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Eine Pilzsammlung trocknet von 12 kg auf 3 kg. Wie viel kg getrocknete Pilze aus 20 kg frischen?", answers: ["4 kg", "5 kg", "6 kg", "8 kg"], correct: 1, hint: "3 : 12 = 1 : 4", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Zug fährt 240 km in 3 Stunden. Wie lange braucht er für 400 km?", answers: ["4 h", "5 h", "6 h", "4,5 h"], correct: 1, hint: "80 km/h", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "2 Bagger brauchen 15 Tage für einen Aushub. Wie viele Bagger braucht man für 5 Tage?", answers: ["4", "5", "6", "8"], correct: 2, hint: "Antiproportional: 2 × 15 : 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "10 Liter Farbe reichen für 80 m². Wie viel Farbe für 120 m²?", answers: ["12 L", "15 L", "18 L", "20 L"], correct: 1, hint: "10 : 80 = 0,125 L/m²", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];