window.__subjectData_german_6r_stilmittel = [ { question: "Was ist eine 'Metapher'?", answers: ["Bildhafter Vergleich ohne 'wie'", "Wortwiederholung", "Vermenschlichung", "Gegensatz"], correct: 0, hint: "Rabeneltern, Mauer des Schweigens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Vergleich'?", answers: ["Wortwiederholung", "Verknüpfung mit 'wie' oder 'als'", "Übertreibung", "Satzende"], correct: 1, hint: "Stark wie ein Löwe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Personifikation'?", answers: ["Ein Mensch wird zum Tier", "Sachen/Tiere handeln wie Menschen", "Ein Reim", "Eine Frage"], correct: 1, hint: "Die Sonne lacht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Alliteration'?", answers: ["Gleicher Anlaut benachbarter Wörter", "Gleicher Endreim", "Gleicher Rhythmus", "Gleiche Wortart"], correct: 0, hint: "Milch macht müde Männer munter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Hyperbel'?", answers: ["Untertreibung", "Starke Übertreibung", "Wiederholung", "Vergleich"], correct: 1, hint: "Ein Meer von Tränen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Symbol'?", answers: ["Ein Satz", "Ein Zeichen mit tieferer Bedeutung", "Ein Verb", "Ein Punkt"], correct: 1, hint: "Herz für Liebe, Taube für Friede", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Lautmalerei' (Onomatopoesie)?", answers: ["Musik im Text", "Nachahmung von Geräuschen", "Bunte Buchstaben", "Reime"], correct: 1, hint: "Kuckuck, rums, zisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Anapher'?", answers: ["Wiederholung am Satzanfang", "Wiederholung am Satzende", "Gegensatz", "Frage"], correct: 0, hint: "Wiederholung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'rhetorische Frage'?", answers: ["Frage ohne erwartete Antwort", "Sehr schwere Frage", "Höfliche Frage", "Wissenschaftliche Frage"], correct: 0, hint: "Wer glaubt das schon?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Ironie'?", answers: ["Lüge", "Gegenteil des Gemeinten sagen", "Witz", "Ernsthafte Aussage"], correct: 1, hint: "Das hast du ja toll gemacht! (wenn etwas kaputt ist)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Vergleich?", answers: ["Ein Wort wie 'so...wie'", "Ein Nomen", "Ein Verb", "Ein Punkt"], correct: 0, hint: "Gegenüberstellung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine Metapher?", answers: ["Ein Sprachbild", "Ein Fragezeichen", "Ein Wiewort", "Ein Zeitwort"], correct: 0, hint: "Bildhafter Vergleich ohne 'wie'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine Alliteration?", answers: ["Gleicher Anfangsbuchstabe", "Gleiches Satzende", "Gleiches Wort", "Gleiche Zeitform"], correct: 0, hint: "Klangfigur", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
