window.__subjectData_bio_9g_evolution = [
    { question: "Wer begründete die Evolutionstheorie?", answers: ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Alfred Wegener"], correct: 1, hint: "Reise mit der HMS Beagle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was besagt 'Survival of the Fittest'?", answers: ["Die Stärksten überleben", "Die am besten Angepassten überleben", "Die Schnellsten überleben", "Die Größten überleben"], correct: 1, hint: "Anpassung an die Umwelt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Inselgruppe besuchte Darwin für seine Studien?", answers: ["Hawaii", "Galápagos", "Fidschi", "Malediven"], correct: 1, hint: "Finken, Schildkröten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist natürliche Selektion?", answers: ["Der Mensch wählt nutzliche Merkmale", "Die Umwelt wählt die am besten angepassten Individuen", "Zufällige Veränderung", "Kreuzung verschiedener Arten"], correct: 1, hint: "Überleben und Fortpflanzung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'künstliche Selektion'?", answers: ["Zufällige Auslese", "Zielgerichtete Züchtung durch den Menschen", "Natürliche Auslese", "Sexualauslese"], correct: 1, hint: "Hunderassen, Nutzpflanzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind Fossilien?", answers: ["Überreste vergangener Lebewesen", "Moderne Tiere", "Gesteinsarten", "Pflanzen"], correct: 0, hint: "Versteinerungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Prinzip der Evolution beschreibt die Anpassung von Finken auf Galápagos?", answers: ["Anpassung an verschiedene Nahrungsquellen", "Wegener's Kontinentaldrift", "Mendelsche Regeln", "Gendrift"], correct: 0, hint: "Schnabelformen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Selektionsdruck'?", answers: ["Ein Umweltfaktor, der bestimmte Merkmale begünstigt", "Druck in der Tiefsee", "Eine Mutation", "Ein sozialer Druck"], correct: 0, hint: "Fressfeinde, Klima, Nahrung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Gendrift'?", answers: ["Zufällige Veränderung der Genhäufigkeit in einer Population", "Gezielte Zucht", "Eine Mutation", "Natürliche Selektion"], correct: 0, hint: "Besonders wichtig in kleinen Populationen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie entstehen neue Arten nach Darwin?", answers: ["Durch Isolation und Anpassung", "Plötzlich durch Mutation", "Durch Kreuzung", "Durch Klonen"], correct: 0, hint: "Evolution durch Trennung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Brückentier' (Mosaikform)?", answers: ["Ein Fossil mit Merkmalen zweier Gruppen", "Eine künstliche Kreuzung", "Ein Tier, das ausstarb", "Ein modernes Tier"], correct: 0, hint: "Archaeopteryx (Vogel + Dinosaurier)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Aussage zur Evolution ist korrekt?", answers: ["Der Mensch stammt vom Affen ab", "Mensch und Affe haben einen gemeinsamen Vorfahren", "Evolution ist abgeschlossen", "Alle Arten sind unveränderlich"], correct: 1, hint: "Stammbaum des Lebens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'sexuelle Selektion'?", answers: ["Auswahl von Partnern nach bestimmten Merkmalen", "Natürliche Auslese", "Künstliche Befruchtung", "Gendrift"], correct: 0, hint: "Pfauenrad, Geweih", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Wissenschaftler trug ebenfalls wesentlich zur Evolutionstheorie bei?", answers: ["Lamarck", "Mendel", "Newton", "Einstein"], correct: 0, hint: "Giraffenhals, Vererbung erworbener Eigenschaften", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];