window.__subjectData_bio_9g_genetik = [
    { question: "Wo befindet sich die DNA in der Zelle?", answers: ["Im Zytoplasma", "Im Zellkern", "In der Zellmembran", "In den Ribosomen"], correct: 1, hint: "Chromosomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Gen?", answers: ["Ein Protein", "Ein Abschnitt der DNA mit Information", "Ein Chromosom", "Eine Zelle"], correct: 1, hint: "Erbinformation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Chromosomen hat ein Mensch?", answers: ["23", "46", "48", "24"], correct: 1, hint: "23 Chromosomenpaare", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein dominantes Merkmal?", answers: ["Ein Merkmal, das immer sichtbar ist", "Ein Merkmal, das nur bei Homozygotie sichtbar ist", "Ein Merkmal ohne Auswirkung", "Ein Merkmal auf dem Y-Chromosom"], correct: 0, hint: "Mendelsche Regeln", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein rezessives Merkmal?", answers: ["Das häufigere Merkmal", "Ein Merkmal, das nur bei zwei gleichen Allelen sichtbar wird", "Ein Merkmal auf dem X-Chromosom", "Ein dominant vererbtes Merkmal"], correct: 1, hint: "aa, nicht AA oder Aa", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind die Mendelschen Regeln?", answers: ["Uniformitätsregel, Spaltungsregel, Unabhängigkeitsregel", "Nur eine Regel", "Drei Regeln zur Fortpflanzung", "Regeln der Zellteilung"], correct: 0, hint: "Gregor Mendel, Erbsen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Genotyp?", answers: ["Das äußere Erscheinungsbild", "Die genetische Zusammensetzung eines Individuums", "Die Anzahl der Chromosomen", "Die DNA-Sequenz"], correct: 1, hint: "Erbanlagen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Phänotyp?", answers: ["Die genetische Zusammensetzung", "Das äußere Erscheinungsbild", "Die Chromosomenzahl", "Der Zellkern"], correct: 1, hint: "Aussehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Mitose?", answers: ["Zellteilung mit identischen Tochterzellen", "Bildung von Geschlechtszellen", "Verschmelzung von Zellen", "Zelltod"], correct: 0, hint: "Körperzellteilung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Meiose?", answers: ["Bildung von Keimzellen mit halbem Chromosomensatz", "Einfache Zellverdopplung", "Verschmelzung von Geschlechtszellen", "Zellwachstum"], correct: 0, hint: "Reduktionsteilung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Kreuze AA mit aa. Wie ist der Genotyp der F1-Generation?", answers: ["Alle Aa", "Alle AA", "50% AA, 50% aa", "Alle aa"], correct: 0, hint: "Uniformitätsregel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Mutation?", answers: ["Eine dauerhafte Veränderung der DNA", "Ein neues Gen", "Ein Chromosomenfehler", "Ein Proteinfehler"], correct: 0, hint: "Ursache: Strahlung, Chemikalien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen DNA und RNA?", answers: ["RNA hat Uracil statt Thymin", "Kein Unterschied", "DNA ist einzelsträngig", "RNA enthält Proteine"], correct: 0, hint: "Basen: A-T vs. A-U", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie erfolgt die Vererbung des Geschlechts beim Menschen?", answers: ["XX = weiblich, XY = männlich", "XY = weiblich, XX = männlich", "XX = männlich, YY = weiblich", "Nur X-Chromosom zahlt"], correct: 0, hint: "23. Chromosomenpaar", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];