window.__subjectData_bio_9g_nerven_hormone = [
    { question: "Was ist die Aufgabe von Hormonen?", answers: ["Nur Verdauung", "Steuerung von Körperfunktionen", "Sauerstofftransport", "Muskelbewegung"], correct: 1, hint: "Chemische Botenstoffe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist das Zentralnervensystem?", answers: ["Nur das Gehirn", "Gehirn und Rückenmark", "Alle Nerven im Körper", "Nur die Wirbelsäule"], correct: 1, hint: "Zentrale Steuerung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Teil des Gehirns steuert das Gleichgewicht?", answers: ["Großhirn", "Kleinhirn", "Hirnstamm", "Zwischenhirn"], correct: 1, hint: "Koordination", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie werden Signale zwischen Nervenzellen übertragen?", answers: ["Elektrisch über Synapsen mit Neurotransmittern", "Nur elektrisch", "Nur chemisch", "Über das Blut"], correct: 0, hint: "Synaptischer Spalt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Reflex?", answers: ["Eine bewusste Handlung", "Eine schnelle, unwillkürliche Reaktion", "Ein Gedanke", "Ein Gefühl"], correct: 1, hint: "Patellarsehnenreflex", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie verläuft ein Reflexbogen?", answers: ["Rezeptor -> Sensorisches Neuron -> Rückenmark -> Motorisches Neuron -> Effektor", "Nur über das Gehirn", "Direkt vom Muskel zum Gehirn", "Ohne Beteiligung des Rückenmarks"], correct: 0, hint: "Schnellster Weg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Hormon reguliert den Blutzuckerspiegel?", answers: ["Insulin und Glukagon", "Adrenalin", "Wachstumshormon", "Schilddrüsenhormon"], correct: 0, hint: "Bauchspeicheldrüse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Ausschüttung von Adrenalin?", answers: ["Der Körper wird in Alarmbereitschaft versetzt", "Verdauung wird angeregt", "Der Blutzucker sinkt", "Man wird müde"], correct: 0, hint: "Fight-or-Flight", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist das periphere Nervensystem?", answers: ["Alle Nerven außerhalb von Gehirn und Rückenmark", "Das Rückenmark", "Das Gehirn", "Die Wirbelsäule"], correct: 0, hint: "Verbindet ZNS mit Körper", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Synapse?", answers: ["Kontaktstelle zwischen zwei Nervenzellen", "Ein Nerv", "Ein Muskel", "Ein Rezeptor"], correct: 0, hint: "Signalübertragung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Hormon wird bei Stress ausgeschüttet?", answers: ["Insulin", "Adrenalin / Cortisol", "Melatonin", "Thyroxin"], correct: 1, hint: "Nebenniere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was steuert der Hypothalamus?", answers: ["Körpertemperatur, Hunger, Durst", "Nur den Schlaf", "Nur die Verdauung", "Nur das Wachstum"], correct: 0, hint: "Zwischenhirn", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind 'Neurotransmitter'?", answers: ["Botenstoffe an den Synapsen", "Hormone im Blut", "Enzyme im Magen", "Nerven"], correct: 0, hint: "z.B. Dopamin, Serotonin", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Wirkung hat das Hormon Melatonin?", answers: ["Reguliert den Schlaf-Wach-Rhythmus", "Erhöht den Blutdruck", "Fördert das Wachstum", "Reguliert die Verdauung"], correct: 0, hint: "Zirbeldrüse", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];