window.__subjectData_bio_9g_oekologie = [
    { question: "Was versteht man unter 'Treibhauseffekt'?", answers: ["Wärme bleibt in der Atmosphäre", "Die Erde kühlt ab", "Der Mond wird wärmer", "Die Ozeane gefrieren"], correct: 0, hint: "CO2 und Methan", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Biodiversität?", answers: ["Die Anzahl der Bienen", "Die Vielfalt der Arten", "Die Menge an CO2", "Die Waldfläche"], correct: 1, hint: "Biologische Vielfalt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Kohlenstoffkreislauf?", answers: ["Austausch von CO2 zwischen Atmosphäre, Ozeanen und Lebewesen", "Nur die Fotosynthese", "Die Verbrennung von Kohle", "Die Zersetzung von Toten"], correct: 0, hint: "Kreislauf des Kohlenstoffs", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Eutrophierung'?", answers: ["Überdüngung von Gewässern", "Erwärmung der Ozeane", "Verschmutzung durch Plastik", "Regenwaldrodung"], correct: 0, hint: "Algenblüte, Sauerstoffmangel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Hauptursache für den Rückgang der Biodiversität?", answers: ["Menschliche Aktivitäten (Zerstörung von Lebensräumen)", "Naturkatastrophen", "Jahreszeiten", "Tierwanderungen"], correct: 0, hint: "Landnutzung, Klimawandel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der 'ökologische Fußabdruck'?", answers: ["Die Fläche, die ein Mensch für seinen Lebensstil benötigt", "Die Fläche eines Waldes", "Ein Maß für CO2-Ausstoß", "Die Größe eines Tieres"], correct: 0, hint: "Ressourcenverbrauch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist nachhaltige Entwicklung?", answers: ["Wirtschaftswachstum um jeden Preis", "Entwicklung, die die Bedürfnisse der Gegenwart erfüllt, ohne die Zukunft zu gefährden", "Nur Umweltschutz", "Nur Wirtschaftswachstum"], correct: 1, hint: "Drei Säulen: Ökonomie, Ökologie, Soziales", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Gas ist das wichtigste Treibhausgas?", answers: ["Sauerstoff", "Kohlendioxid (CO2)", "Stickstoff", "Wasserstoff"], correct: 1, hint: "Verbrennung fossiler Brennstoffe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Renaturierung'?", answers: ["Rückführung von Flächen in einen naturnahen Zustand", "Neue Technologien", "Abholzung", "Stadtentwicklung"], correct: 0, hint: "Wiederherstellung von Ökosystemen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'invasive Arten'?", answers: ["Gebietsfremde Arten, die einheimische verdrängen", "Wandernde Vögel", "Neue Haustiere", "Alte Bäume"], correct: 0, hint: "Neozoen / Neophyten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielen Wälder für das Klima?", answers: ["Sie produzieren Sauerstoff und speichern CO2", "Sie erwärmen die Erde", "Sie haben keinen Einfluss", "Sie produzieren CO2"], correct: 0, hint: "Fotosynthese", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der 'Saure Regen'?", answers: ["Regen durch Verschmutzung mit Schwefeldioxid und Stickoxiden", "Regen mit pH 7", "Saurer Nebel", "Gewitterregen"], correct: 0, hint: "Schwefel- und Stickstoffverbindungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Biotopverbund'?", answers: ["Vernetzung von Lebensräumen für den Artenschutz", "Eine Liste von Biotopen", "Ein Zoo", "Eine Tierart"], correct: 0, hint: "Grüne Korridore", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche erneuerbare Energiequelle steht indirekt durch die Sonne zur Verfügung?", answers: ["Alle (Wind, Wasser, Solar, Biomasse)", "Nur Solar", "Nur Wind", "Nur Wasser"], correct: 0, hint: "Sonnenenergie = Ursprung", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];