window.__subjectData_math_6r_brueche = [ { question: "Wie viel Prozent sind 3/4?", answers: ["25%", "50%", "75%", "80%"], correct: 2, hint: "3 ÷ 4 = 0,75", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 0,25 als Bruch?", answers: ["1/2", "1/3", "1/4", "1/5"], correct: 2, hint: "0,25 = 25/100", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 5/8 als Dezimalzahl?", answers: ["0,58", "0,625", "0,8", "0,85"], correct: 1, hint: "5 ÷ 8", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 1/2 + 1/4?", answers: ["1/6", "2/6", "3/4", "1"], correct: 2, hint: "Gleicher Nenner: 2/4 + 1/4", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 3/4 von 100?", answers: ["25", "50", "75", "100"], correct: 2, hint: "100 × 3/4", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 1/5 als Dezimalzahl?", answers: ["0,15", "0,2", "0,5", "0,25"], correct: 1, hint: "1 ÷ 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 2/3 - 1/3?", answers: ["1/3", "1/6", "1/9", "2/3"], correct: 0, hint: "Gleicher Nenner", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 0,5 als Bruch?", answers: ["1/3", "1/4", "1/2", "2/3"], correct: 2, hint: "Die Hälfte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert beim Erweitern eines Bruchs?", answers: ["Der Wert wird größer", "Der Wert wird kleiner", "Der Wert bleibt gleich", "Der Zähler wird kleiner"], correct: 2, hint: "Zähler und Nenner mit gleicher Zahl malnehmen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Kürze 12/16 so weit wie möglich.", answers: ["6/8", "3/4", "1/2", "2/3"], correct: 1, hint: "Durch 4 teilen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 1/3 von 60?", answers: ["10", "20", "30", "40"], correct: 1, hint: "60 ÷ 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viel ist 0,1 + 0,2 + 0,3?", answers: ["0,3", "0,5", "0,6", "6,0"], correct: 2, hint: "Addition von Dezimalzahlen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Bruch ist größer: 1/2 oder 1/3?", answers: ["1/2", "1/3", "Beide gleich", "Kommt auf den Zähler an"], correct: 0, hint: "Je kleiner der Nenner, desto größer das Stück", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Kehrbruch von 2/5?", answers: ["5/2", "2/5", "-2/5", "1/2"], correct: 0, hint: "Oben und unten vertauschen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Berechne: 0,4 × 0,2", answers: ["0,8", "0,08", "8,0", "0,008"], correct: 1, hint: "4*2 = 8, dann 2 Kommastellen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'echter Bruch'?", answers: ["Zähler > Nenner", "Zähler < Nenner", "Zähler = Nenner", "Ein Bruch mit Komma"], correct: 1, hint: "Kleiner als 1 Ganzes", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wandle 1 1/2 in einen unechten Bruch um.", answers: ["1/2", "2/2", "3/2", "4/2"], correct: 2, hint: "Ein Ganzes sind zwei Halbe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 10% als Bruch?", answers: ["1/10", "1/100", "10/1", "1/2"], correct: 0, hint: "10 von 100", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Berechne: 1/4 + 1/4", answers: ["1/8", "2/8", "1/2", "1"], correct: 2, hint: "2/4 = 1/2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 0,75 - 0,25?", answers: ["0,25", "0,5", "0,55", "1,0"], correct: 1, hint: "75 Cent - 25 Cent", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 1/2 + 1/4?", answers: ["2/4", "3/4", "1/6", "2/6"], correct: 1, hint: "Gleichnamig machen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was sind 50% von 200?", answers: ["50", "100", "150", "20"], correct: 1, hint: "Die Hälfte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zahl ist der Kehrwert von 3/4?", answers: ["3/4", "4/3", "1/3", "4/1"], correct: 1, hint: "Tauschen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
