window.__subjectData_math_6r_gleichungen = [ { question: "Löse: x + 5 = 12", answers: ["5", "6", "7", "8"], correct: 2, hint: "x = 12 - 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 2x = 10", answers: ["4", "5", "6", "8"], correct: 1, hint: "x = 10 ÷ 2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: x - 3 = 7", answers: ["4", "8", "9", "10"], correct: 3, hint: "x = 7 + 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: x/4 = 3", answers: ["7", "10", "12", "16"], correct: 2, hint: "x = 3 × 4", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 3x + 2 = 14", answers: ["3", "4", "5", "6"], correct: 1, hint: "3x = 12, dann x = 4", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 5x - 10 = 15", answers: ["3", "4", "5", "6"], correct: 2, hint: "5x = 25", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 2x + 5 = x + 10", answers: ["2", "3", "4", "5"], correct: 3, hint: "x = 10 - 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 4(x - 2) = 12", answers: ["3", "4", "5", "6"], correct: 2, hint: "x - 2 = 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 10 - x = 4", answers: ["4", "6", "10", "14"], correct: 1, hint: "10 - 4 = x", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist x in der Gleichung: x + x + x = 30?", answers: ["3", "10", "15", "30"], correct: 1, hint: "3x = 30", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 0,5x = 4", answers: ["2", "4", "8", "16"], correct: 2, hint: "Hälfte von x ist 4", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 20 ÷ x = 5", answers: ["2", "4", "5", "100"], correct: 1, hint: "Wie oft passt 5 in 20?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was muss man bei x - 100 = 200 auf beiden Seiten tun?", answers: ["100 abziehen", "100 addieren", "Durch 100 teilen", "Mal 100 nehmen"], correct: 1, hint: "Gegenteil von minus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 3x - 1 = 20", answers: ["6", "7", "8", "21"], correct: 1, hint: "3x = 21", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: x/2 + 5 = 10", answers: ["5", "10", "15", "20"], correct: 1, hint: "x/2 = 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Wert für x ist eine Lösung von x² = 25?", answers: ["2,5", "5", "12,5", "50"], correct: 1, hint: "5 * 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist x in: x + 5 = 10?", answers: ["3", "4", "5", "6"], correct: 2, hint: "Gegenoperation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist x in: 2 * x = 8?", answers: ["3", "4", "5", "6"], correct: 1, hint: "Geteilt rechnen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist x in: x - 3 = 7?", answers: ["8", "9", "10", "11"], correct: 2, hint: "Plus rechnen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
