window.__subjectData_math_6r_zahlen = [ { question: "Was ist der kleinste gemeinsame Teiler von 12 und 18?", answers: ["2", "3", "6", "9"], correct: 2, hint: "KGV", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die nächste Primzahl nach 7?", answers: ["9", "10", "11", "13"], correct: 2, hint: "Nur durch 1 und sich selbst teilbar", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zahl ist größer: -3 oder -5?", answers: ["-3", "-5", "Beide gleich", "Kommt darauf an"], correct: 0, hint: "Minus-Zahlen: Je näher bei 0, desto größer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist |-5|?", answers: ["-5", "0", "5", "10"], correct: 2, hint: "Betrag = Abstand von 0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 2⁻³?", answers: ["-6", "-8", "1/8", "8"], correct: 2, hint: "Negativer Exponent = Kehrbruch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Quersumme von 123?", answers: ["3", "6", "9", "12"], correct: 1, hint: "1 + 2 + 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zahl ist durch 3 teilbar?", answers: ["13", "16", "21", "22"], correct: 2, hint: "Quersumme durch 3 teilbar", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die größte einstellige Primzahl?", answers: ["5", "7", "9", "11"], correct: 1, hint: "Nur durch 1 und sich selbst teilbar", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ist 0 eine natürliche Zahl (in der Schule meistens)?", answers: ["Ja", "Nein", "Nur am Wochenende", "Nur in Bayern"], correct: 0, hint: "N0 Menge", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ergibt -10 + 15?", answers: ["-25", "-5", "5", "25"], correct: 2, hint: "Rechne von -10 nach rechts", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Ziffer steht an der Zehntelstelle bei 123,456?", answers: ["1", "3", "4", "5"], correct: 2, hint: "Erste Stelle nach dem Komma", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die kleinste Primzahl?", answers: ["0", "1", "2", "3"], correct: 2, hint: "Die einzige gerade Primzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woran erkennt man Zahlen, die durch 5 teilbar sind?", answers: ["Enden auf 0 oder 5", "Enden auf 5", "Quersumme ist 5", "Sind ungerade"], correct: 0, hint: "5er-Reihe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Nullen hat eine Million?", answers: ["3", "6", "9", "12"], correct: 1, hint: "Tausend mal Tausend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Ergebnis von 5 - (-3)?", answers: ["2", "8", "-2", "-8"], correct: 1, hint: "Minus und Minus wird Plus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Runde 4,567 auf zwei Dezimalstellen.", answers: ["4,56", "4,57", "4,60", "5,00"], correct: 1, hint: "Dritte Stelle ist 7 -> aufrunden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Vorgänger von 999?", answers: ["998", "900", "990", "997"], correct: 0, hint: "Minus eins", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die größte dreistellige Zahl?", answers: ["1000", "999", "900", "998"], correct: 1, hint: "Höchster Wert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man die Zahl 'fünftausenddreihundert'?", answers: ["5030", "5300", "5003", "530"], correct: 1, hint: "Zahlenschreibung", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
