window.__subjectData_lat_8g_vokabeln = [ { question: "Was bedeutet 'amicus'?", answers: ["Feind", "Bruder", "Freund", "Vater"], correct: 2, hint: "Gegenteil von inimicus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bellum'?", answers: ["schön", "Krieg", "Glocke", "Hund"], correct: 1, hint: "Gegenteil von pax", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pax'?", answers: ["Packung", "Friede", "Krieg", "Stadt"], correct: 1, hint: "Pax Romana", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'urbs'?", answers: ["Dorf", "Land", "Stadt (Rom)", "Welt"], correct: 2, hint: "urban", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hostis'?", answers: ["Gast", "Wirt", "Feind", "Heer"], correct: 2, hint: "feindlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'imperator'?", answers: ["Bauer", "Feldherr/Kaiser", "Sklave", "Händler"], correct: 1, hint: "Befehlshaber", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'videre'?", answers: ["siegen", "sehen", "leben", "geben"], correct: 1, hint: "Video", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'venire'?", answers: ["verkaufen", "kommen", "winden", "gewinnen"], correct: 1, hint: "Veni, vidi, vici", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'magnus'?", answers: ["klein", "groß", "stark", "schlecht"], correct: 1, hint: "Magnum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'multis'?", answers: ["viel", "wenig", "alle", "keine"], correct: 0, hint: "Multiple Choice", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'homo'?", answers: ["Gott", "Mensch", "Haus", "Wald"], correct: 1, hint: "Homo sapiens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'deus'?", answers: ["Mensch", "Gott", "Himmel", "Erde"], correct: 1, hint: "Gottheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'aqua'?", answers: ["Feuer", "Erde", "Wasser", "Luft"], correct: 2, hint: "Aquarium", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ignis'?", answers: ["Wasser", "Eis", "Feuer", "Licht"], correct: 2, hint: "Ignition", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'liber'?", answers: ["Sklave", "frei (oder: Buch)", "gefangen", "tot"], correct: 1, hint: "Liberty", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'servus'?", answers: ["Herr", "Sklave/Diener", "Freund", "König"], correct: 1, hint: "Service", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'regere'?", answers: ["schreiben", "lenken/regieren", "laufen", "schlafen"], correct: 1, hint: "Regierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'nomen'?", answers: ["Zahl", "Name", "Satz", "Wort"], correct: 1, hint: "Nominativ", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'audire'?", answers: ["sehen", "hören", "fühlen", "schmecken"], correct: 1, hint: "Audio", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tempus'?", answers: ["Ort", "Zeit", "Wetter", "Sturm"], correct: 1, hint: "Tempo", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'scire'?", answers: ["glauben", "wissen", "hoffen", "fürchten"], correct: 1, hint: "Science", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mittere'?", answers: ["nehmen", "schicken", "bleiben", "gehen"], correct: 1, hint: "Mission", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'capere'?", answers: ["lassen", "fangen/fassen/nehmen", "töten", "lieben"], correct: 1, hint: "kapern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mors'?", answers: ["Leben", "Tod", "Geburt", "Krankheit"], correct: 1, hint: "mortal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'periculum'?", answers: ["Sicherheit", "Gefahr", "Weg", "Abenteuer"], correct: 1, hint: "gefährlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'solere'?", answers: ["gewohnt sein", "verlassen", "allein sein", "scheinen"], correct: 0, hint: "Semi-Deponens im Perfekt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fieri'?", answers: ["machen", "gemacht werden / geschehen / werden", "fliehen", "vertrauen"], correct: 1, hint: "Passiv zu facere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vincire' (nicht vincere!)?", answers: ["siegen", "fesseln", "kommen", "leben"], correct: 1, hint: "i-Konjugation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gens'?", answers: ["Geist", "Volk / Stamm / Geschlecht", "Knie", "Garten"], correct: 1, hint: "Genitiv: gentis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'adhuc'?", answers: ["hierher", "bis jetzt / noch", "von dort", "damals"], correct: 1, hint: "Adverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'proficisci'?", answers: ["ankommen", "aufbrechen / marschieren", "sprechen", "glauben"], correct: 1, hint: "Ein Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was heißt 'puella' auf Deutsch?", answers: ["Junge", "Mädchen", "Frau", "Lehrerin"], correct: 1, hint: "Das Mädchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was heißt 'pater' auf Deutsch?", answers: ["Mutter", "Sohn", "Bruder", "Vater"], correct: 3, hint: "Das Familienoberhaupt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'loqui'?", answers: ["hören", "sprechen", "laufen", "schlafen"], correct: 1, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'uti' (mit Ablativ)?", answers: ["besuchen", "benutzen / gebrauchen", "lieben", "hassen"], correct: 1, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'arbitrari'?", answers: ["entscheiden", "meinen / glauben", "arbeiten", "siegen"], correct: 1, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'videtur'?", answers: ["er sieht", "er scheint / es scheint gut", "er wird gesehen", "er kommt"], correct: 1, hint: "Passiv von videre.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'praestare'?", answers: ["da sein", "übertreffen / leisten", "bitten", "stehen"], correct: 1, hint: "prae + stare.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'consilium'?", answers: ["Rat / Plan / Beschluss", "Trost", "Gefahr", "Krieg"], correct: 0, hint: "Überlegung.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'occidere' (mit kurzem i)?", answers: ["töten", "untergehen / umkommen", "fallen", "schneiden"], correct: 1, hint: "cadere steckt darin.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'facinus'?", answers: ["Gesicht", "Tat / Untat", "Leichtigkeit", "Glück"], correct: 1, hint: "Von facere.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'acer, acris, acre'?", answers: ["scharf / heftig / tapfer", "hoch", "tief", "breit"], correct: 0, hint: "Adjektiv der 3. Dekl.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vis' (Akk. vim, Abl. vi)?", answers: ["Kraft / Gewalt", "Leben", "Weg", "Mann"], correct: 0, hint: "Unregelmäßig.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'oratio'?", answers: ["Gebet", "Rede", "Gold", "Mund"], correct: 1, hint: "Von orare.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'egredi'?", answers: ["hinausgehen", "eintreten", "schreiten", "fürchten"], correct: 0, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'casus'?", answers: ["Haus", "Fall / Zufall / Unglück", "Käse", "Ursache"], correct: 1, hint: "u-Deklination.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gravis, e'?", answers: ["schwer / ernst / bedeutend", "dankbar", "grau", "schlank"], correct: 0, hint: "3. Deklination.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pati'?", answers: ["leiden / ertragen / zulassen", "sprechen", "glauben", "folgen"], correct: 0, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sequi'?", answers: ["schweigen", "folgen", "wissen", "suchen"], correct: 1, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'malle'?", answers: ["nicht wollen", "lieber wollen", "wollen", "schlecht sein"], correct: 1, hint: "magis + velle.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'nolle'?", answers: ["nicht wollen", "wollen", "lieber wollen", "dürfen"], correct: 0, hint: "non + velle.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'audere'?", answers: ["hören", "wagen", "freuen", "verlassen"], correct: 1, hint: "Semideponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gaudere'?", answers: ["sich freuen", "laufen", "spielen", "singen"], correct: 0, hint: "Semideponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fieri'?", answers: ["machen", "werden / geschehen", "fliehen", "vertrauen"], correct: 1, hint: "Passiv zu facere.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'interficere'?", answers: ["dazwischen sein", "töten", "machen", "verstehen"], correct: 1, hint: "inter + facere.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'uterque'?", answers: ["jeder von beiden", "wer auch immer", "keiner von beiden", "beide"], correct: 0, hint: "Pronominaladjektiv.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'coepisse'?", answers: ["beenden", "anfangen / begonnen haben", "wollen", "können"], correct: 1, hint: "Defektives Verb.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vereri'?", answers: ["sprechen", "fürchten / verehren", "scheinen", "folgen"], correct: 1, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'progredi'?", answers: ["hinausgehen", "vorrücken / weitergehen", "eintreten", "aufbrechen"], correct: 1, hint: "pro + gradi.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'morari'?", answers: ["sterben", "verweilen / verzögern", "erinnern", "bewundern"], correct: 1, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mirari'?", answers: ["bewundern / sich wundern", "ansehen", "schicken", "bleiben"], correct: 0, hint: "Deponens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'reliquus'?", answers: ["heilig", "übrig / künftig", "alt", "neu"], correct: 1, hint: "Adjektiv.", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
