// ============================================
// ENGLISCH - LernApp Daten (8. Klasse Gymnasium Bayern)
// ============================================
const eng8gData = {
    name: "Englisch (8G)",
    icon: "🇺🇸",
    color: "#ef4444",
    description: "English 8th Grade - USA, Grammar and Vocabulary",
    categories: {
        grammar: { name: "Grammar", icon: "📝", color: "#3b82f6", desc: "Gerunds, Participles, Passive & Conditionals" },
        usa: { name: "USA", icon: "🏙️", color: "#f59e0b", desc: "American History, Geography and Culture" },
        vocabulary: { name: "Vocabulary", icon: "📖", color: "#10b981", desc: "Advanced Word Power & Phrasal Verbs" },
        media: { name: "Media & Tech", icon: "📱", color: "#8b5cf6", desc: "Digital Life and Technology" }
    },
    questions: {
        grammar: [ { question: "Which form is a gerund?", answers: ["to swim", "swimming", "swam", "swims"], correct: 1, hint: "Verb acting as a noun", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which participle is used for the passive voice?", answers: ["Present Participle", "Past Participle", "Gerund", "Infinitive"], correct: 1, hint: "3rd column", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Complete: If I ___ rich, I would buy a boat.", answers: ["am", "will be", "were", "have been"], correct: 2, hint: "Conditional II (Hypothetical)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "The book ___ in 1990.", answers: ["wrote", "was written", "writes", "is written"], correct: 1, hint: "Passive voice (past simple)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which one is a participle construction?", answers: ["I like swimming", "Having finished my lunch, I went out", "I will go out", "I have gone out"], correct: 1, hint: "Shortened clause replacing 'After I had...'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "I'm looking forward to ___ you.", answers: ["see", "seen", "seeing", "saw"], correct: 2, hint: "Fixed expression 'to' + gerund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Passive: 'They build houses.'", answers: ["Houses are built", "Houses are build", "Houses built", "Houses were built"], correct: 0, hint: "Present passive (am/is/are + 3rd form)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Conditional I: If it rains, we ___ inside.", answers: ["stay", "will stay", "would stay", "stayed"], correct: 1, hint: "Will-future in the main clause", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "He stopped ___ (smoke).", answers: ["smoke", "to smoke", "smoking", "smoked"], correct: 2, hint: "Meaning: He doesn't do it anymore", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "She forgot ___ (lock) the door.", answers: ["lock", "to lock", "locking", "locked"], correct: 1, hint: "Infinitive after forget for an action to be done", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which modal verb expresses 'Verbot'?", answers: ["must", "mustn't", "needn't", "can"], correct: 1, hint: "Must not", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Passive: 'Shakespeare wrote Hamlet.'", answers: ["Hamlet was written by S.", "Hamlet is written by S.", "Hamlet wrote by S.", "S. was written by Hamlet"], correct: 0, hint: "Past passive", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "The boy ___ is standing there is my brother.", answers: ["which", "who", "whose", "whom"], correct: 1, hint: "Relative clause (people)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "The car ___ I bought is red.", answers: ["who", "whose", "which", "whom"], correct: 2, hint: "Relative clause (objects)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Question tags: You are British, ___?", answers: ["are you", "aren't you", "do you", "don't you"], correct: 1, hint: "Positive statement -> negative tag", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Question tags: He likes pizza, ___?", answers: ["doesn't he", "does he", "isn't he", "hasn't he"], correct: 0, hint: "Main verb like -> use do-auxiliary", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the past perfect of 'go'?", answers: ["went", "had gone", "has gone", "gone"], correct: 1, hint: "had + past participle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Indirect speech: He said, 'I am happy.'", answers: ["He said that he was happy", "He said that he is happy", "He says he was happy", "He said he happy"], correct: 0, hint: "Backshift of tenses", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Gerund after preposition: I'm good at ___.", answers: ["draw", "to draw", "drawing", "drew"], correct: 2, hint: "'at' is a preposition", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Conditional III: If I ___ (study), I would have passed.", answers: ["studied", "had studied", "study", "would study"], correct: 1, hint: "Past perfect in the if-clause", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Passive: 'They are playing football.'", answers: ["Football is being played", "Football is played", "Football was played", "Football playing"], correct: 0, hint: "Present progressive passive", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "He's the man ___ car was stolen.", answers: ["who", "which", "whose", "whom"], correct: 2, hint: "Possession", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "I'm used to ___ up early.", answers: ["get", "got", "getting", "gets"], correct: 2, hint: "'to be used to' + gerund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "___ the book, she turned off the light.", answers: ["Closed", "Closing", "Having closing", "To close"], correct: 1, hint: "Present participle for simultaneous actions", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Modal verbs in the past: She ___ (muss gegangen sein).", answers: ["must go", "must have gone", "had to go", "must gone"], correct: 1, hint: "Speculation about the past", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "I suggest ___ (go) to the cinema.", answers: ["go", "to go", "going", "goes"], correct: 2, hint: "Verb followed by gerund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "She is the girl ___ I met yesterday.", answers: ["who", "which", "whose", "who's"], correct: 0, hint: "Relative pronoun for people", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "I look forward to ___ (meet) you.", answers: ["meet", "to meet", "meeting", "met"], correct: 2, hint: "Gerund after certain expressions", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "If I ___ (be) you, I wouldn't do that.", answers: ["was", "were", "am", "will be"], correct: 1, hint: "Subjunctive 'were' in Conditional II", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "The house ___ (clean) every day.", answers: ["is cleaned", "was cleaned", "cleans", "is cleaning"], correct: 0, hint: "Present simple passive", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the correct form: 'If she ___ (study) hard, she will pass.'?", answers: ["studies", "will study", "studied", "study"], correct: 0, hint: "Conditional I", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which sentence is in the Passive Voice?", answers: ["He eats an apple.", "The apple is eaten by him.", "He is eating an apple.", "He ate an apple."], correct: 1, hint: "be + past participle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the correct relative pronoun for a person?", answers: ["which", "who", "where", "whose"], correct: 1, hint: "Person", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        usa: [ { question: "Who was the first US President?", answers: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John F. Kennedy"], correct: 1, hint: "On the 1-dollar bill", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "In which city is the 'Big Apple'?", answers: ["Los Angeles", "Chicago", "New York City", "San Francisco"], correct: 2, hint: "Statue of Liberty", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the capital of the USA?", answers: ["New York", "Washington D.C.", "Chicago", "Philadelphia"], correct: 1, hint: "White House location", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "When is Independence Day?", answers: ["May 1st", "July 4th", "Oct 31st", "Dec 25th"], correct: 1, hint: "Summer holiday", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "How many states are in the USA?", answers: ["48", "50", "51", "52"], correct: 1, hint: "Stars on the flag", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which river flows through the Grand Canyon?", answers: ["Mississippi", "Hudson", "Colorado River", "Rio Grande"], correct: 2, hint: "In Arizona", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Where is Hollywood located?", answers: ["Miami", "Las Vegas", "Los Angeles", "New York"], correct: 2, hint: "California", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What was the 'Civil War' mainly about?", answers: ["Taxes", "Slavery & Union", "Gold", "Independence"], correct: 1, hint: "North vs South", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which president was assassinated in 1963?", answers: ["Obama", "Kennedy", "Roosevelt", "Nixon"], correct: 1, hint: "JFK", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the largest state by area?", answers: ["Texas", "California", "Alaska", "Florida"], correct: 2, hint: "The cold north", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Who was Martin Luther King Jr.?", answers: ["A king", "Civil rights leader", "An actor", "A scientist"], correct: 1, hint: "'I have a dream'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which ocean is on the West Coast?", answers: ["Atlantic", "Indian", "Pacific", "Arctic"], correct: 2, hint: "California side", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What was the 'Mayflower'?", answers: ["A hotel", "A flower", "The ship of the Pilgrims", "A city"], correct: 2, hint: "1620 journey", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the 'Bill of Rights'?", answers: ["A menu", "The first 10 amendments", "A law about money", "A type of tax"], correct: 1, hint: "Protects individual freedoms", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the currency of the USA?", answers: ["Pound", "Euro", "Dollar", "Yen"], correct: 2, hint: "Green bills", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Where is the 'Liberty Bell'?", answers: ["Washington", "New York", "Philadelphia", "Boston"], correct: 2, hint: "Symbol of independence", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'Ellis Island' famous for?", answers: ["A prison", "A movie set", "Immigration history", "Space launches"], correct: 2, hint: "Gateway to America", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which state is an island group?", answers: ["Florida", "Hawaii", "Alaska", "Rhode Island"], correct: 1, hint: "In the Pacific", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Who is the head of the US government?", answers: ["The Queen", "The President", "The Prime Minister", "The Chancellor"], correct: 1, hint: "Executive branch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What are the two main political parties?", answers: ["Labour & Tory", "Democrats & Republicans", "Greens & Liberals", "Left & Right"], correct: 1, hint: "Two-party system", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the 'Midwest'?", answers: ["A region in Canada", "A region in the US", "A movie", "A famous road"], correct: 1, hint: "Breadbasket of America", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the 'Statue of Liberty' holding?", answers: ["A torch", "A sword", "A flag", "A baby"], correct: 0, hint: "Symbol of enlightenment", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which city is known as 'Windy City'?", answers: ["New York", "Chicago", "Miami", "Seattle"], correct: 1, hint: "On Lake Michigan", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'Thanksgiving'?", answers: ["A race", "A harvest festival", "A winter holiday", "A birthday"], correct: 1, hint: "Turkey dinner", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the 'Ghetto' usually associated with in US history?", answers: ["Parks", "Poor city areas", "Farms", "Schools"], correct: 1, hint: "Urban segregation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the capital of the USA?", answers: ["New York", "Washington, D.C.", "Los Angeles", "Chicago"], correct: 1, hint: "Seat of government", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "How many states does the USA have?", answers: ["48", "50", "52", "45"], correct: 1, hint: "Stars on the flag", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the Statue of Liberty a symbol of?", answers: ["freedom", "war", "wealth", "nature"], correct: 0, hint: "Gift from France", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        vocabulary: [ { question: "What is the opposite of 'polite'?", answers: ["nice", "rude", "friendly", "quiet"], correct: 1, hint: "Bad manners", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Another word for 'huge'?", answers: ["small", "gigantic", "tiny", "average"], correct: 1, hint: "Very big", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'garbage' in British English?", answers: ["trash", "rubbish", "sweets", "flat"], correct: 1, hint: "Waste", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to survive'?", answers: ["to die", "to live through", "to sleep", "to eat"], correct: 1, hint: "Stay alive", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'sidewalk' in British English?", answers: ["pavement", "street", "motorway", "lift"], correct: 0, hint: "Where you walk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'challenging'?", answers: ["easy", "difficult/demanding", "boring", "useless"], correct: 1, hint: "Tests your abilities", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'pollution'?", answers: ["cleaning", "contamination", "fresh air", "nature"], correct: 1, hint: "Environment damage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'opportunity'?", answers: ["problem", "chance", "idea", "work"], correct: 1, hint: "Good moment to do something", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What does 'diverse' mean?", answers: ["the same", "varied", "small", "limited"], correct: 1, hint: "Different types", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to appreciate'?", answers: ["to hate", "to value", "to ignore", "to lose"], correct: 1, hint: "Recognize the worth", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'landmark'?", answers: ["A map", "A recognizable feature/building", "A road", "A forest"], correct: 1, hint: "Famous point of interest", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'common'?", answers: ["rare", "frequent/usual", "strange", "expensive"], correct: 1, hint: "Found often", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is an 'apartment' in BE?", answers: ["flat", "house", "garden", "room"], correct: 0, hint: "Living space", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to increase'?", answers: ["to drop", "to grow/rise", "to stay", "to break"], correct: 1, hint: "Get bigger/more", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to look for'?", answers: ["to find", "to search", "to hide", "to watch"], correct: 1, hint: "Try to find something", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to take part in'?", answers: ["to watch", "to participate", "to leave", "to win"], correct: 1, hint: "Join an activity", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What does 'ancient' mean?", answers: ["modern", "very old", "new", "fast"], correct: 1, hint: "From a long time ago", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to avoid'?", answers: ["to seek", "to keep away from", "to like", "to use"], correct: 1, hint: "Stay away on purpose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to succeed'?", answers: ["to fail", "to manage to do something", "to try", "to wait"], correct: 1, hint: "Get the desired result", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'candy' in British English?", answers: ["biscuits", "sweets", "chips", "crisps"], correct: 1, hint: "Sugar treats", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to depend on'?", answers: ["to need", "to rely on/be decided by", "to hate", "to see"], correct: 1, hint: "abhängen von", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'significant'?", answers: ["small", "important/meaningful", "boring", "red"], correct: 1, hint: "Having a great effect", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to disappear'?", answers: ["to arrive", "to vanish", "to stay", "to grow"], correct: 1, hint: "Cannot be seen anymore", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'vacation' in BE?", answers: ["trip", "holiday", "break", "weekend"], correct: 1, hint: "Time off from work/school", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to be interested in'?", answers: ["to ignore", "to like finding out about", "to hate", "to know"], correct: 1, hint: "Show curiosity", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the synonym of 'fast'?", answers: ["slow", "quick", "happy", "long"], correct: 1, hint: "Speed", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the antonym of 'hard'?", answers: ["difficult", "soft", "easy", "long"], correct: 1, hint: "Opposite of hard", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "How to say 'einfach' in English?", answers: ["easy", "hard", "fast", "slow"], correct: 0, hint: "Not difficult", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        media: [ { question: "What is 'social media'?", answers: ["TV", "Online platforms for networking", "Newspapers", "Radio"], correct: 1, hint: "Instagram, TikTok, etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to post'?", answers: ["to send a letter", "to publish online", "to read", "to call"], correct: 1, hint: "Upload content", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'cyberbullying'?", answers: ["Gaming", "Harassing others online", "Coding", "Shopping"], correct: 1, hint: "Mean behavior on the web", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'viral'?", answers: ["sick", "spreading quickly online", "slow", "old"], correct: 1, hint: "Getting many views very fast", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is an 'influencer'?", answers: ["A scientist", "A person with many followers", "A pilot", "A doctor"], correct: 1, hint: "Has impact on social media", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'privacy'?", answers: ["Public life", "Protection of personal data", "A party", "Gaming"], correct: 1, hint: "Keeping things secret", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to subscribe'?", answers: ["to buy", "to sign up for content", "to delete", "to like"], correct: 1, hint: "Follow a channel regularly", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'fake news'?", answers: ["True stories", "False information", "History", "The weather"], correct: 1, hint: "Manipulated reports", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'smartphone'?", answers: ["Old phone", "Mobile computer/phone", "TV", "Radio"], correct: 1, hint: "Modern device", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'addicted'?", answers: ["free", "unable to stop", "happy", "tired"], correct: 1, hint: "Hooked on something", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'streaming'?", answers: ["Downloading", "Playing content via internet", "Printing", "Sleeping"], correct: 1, hint: "Netflix, Spotify", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to download'?", answers: ["to send", "to get data from the web", "to break", "to fix"], correct: 1, hint: "Save locally", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is an 'app'?", answers: ["A fruit", "Application software", "A screen", "A cable"], correct: 1, hint: "Short for application", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'password'?", answers: ["Username", "Secret security code", "Email", "Nickname"], correct: 1, hint: "Don't share it", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'wireless'?", answers: ["with cables", "without cables", "slow", "broken"], correct: 1, hint: "Wi-Fi, Bluetooth", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to share'?", answers: ["to keep", "to let others see/use", "to hide", "to sell"], correct: 1, hint: "Teilen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'content'?", answers: ["Information/material on media", "A container", "Nothing", "Boring"], correct: 0, hint: "Videos, articles, etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'digital footprint'?", answers: ["Shoe size", "Record of online activity", "Computer", "Speed"], correct: 1, hint: "Trace you leave online", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'profile'?", answers: ["Face", "User info page", "A game", "A book"], correct: 1, hint: "Your account page", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to scroll'?", answers: ["to read", "to move content up/down", "to click", "to print"], correct: 1, hint: "Move through a feed", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'instant messaging'?", answers: ["Emails", "Real-time text chat", "Phone calls", "Letters"], correct: 1, hint: "WhatsApp, etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'global'?", answers: ["local", "worldwide", "small", "near"], correct: 1, hint: "Around the world", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'blog'?", answers: ["A brick", "An online journal", "Software", "A virus"], correct: 1, hint: "Short for weblog", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to search'?", answers: ["to find", "to look for info", "to lose", "to buy"], correct: 1, hint: "Google something", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'broadband'?", answers: ["Radio", "High-speed internet", "TV", "Cable"], correct: 1, hint: "Fast connection", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is social media?", answers: ["a type of food", "electronic platforms for communication", "a kind of sport", "a school subject"], correct: 1, hint: "Platform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'fake news'?", answers: ["real reports", "misleading information", "a movie", "a song"], correct: 1, hint: "Falsehood", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What does 'to upload' mean?", answers: ["to delete", "to transfer data to a network", "to download", "to watch"], correct: 1, hint: "Sending data", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};