// ============================================
// ENGLISCH - LernApp Daten (6. Klasse Realschule Bayern)
// ============================================

const english6rData = {
    name: "Englisch",
    icon: "🇬🇧",
    color: "#6366f1",
    description: "Englisch lernen mit Vokabeln und Grammatik - 6. Klasse Realschule",
    
    categories: {
        everyday: { name: "Alltagswörter", icon: "🏠", color: "#10b981", desc: "Wörter für den täglichen Gebrauch" },
        school: { name: "Schule", icon: "📚", color: "#3b82f6", desc: "Schulfächer und Unterricht" },
        family: { name: "Familie", icon: "👨‍👩‍👧‍👦", color: "#ec4899", desc: "Familie und Freunde" },
        food: { name: "Essen & Trinken", icon: "🍕", color: "#f59e0b", desc: "Lebensmittel" },
        body: { name: "Körper", icon: "💪", color: "#ef4444", desc: "Körperteile und Gesundheit" },
        clothes: { name: "Kleidung", icon: "👕", color: "#ec4899", desc: "Anziehsachen" },
        animals: { name: "Tiere", icon: "🦁", color: "#8b5cf6", desc: "Tierarten" },
        nature: { name: "Natur", icon: "🌳", color: "#22c55e", desc: "Wetter und Umwelt" },
        hobbies: { name: "Hobbys", icon: "🎮", color: "#f97316", desc: "Freizeit" },
        travel: { name: "Reisen", icon: "✈️", color: "#06b6d4", desc: "Verkehr und Urlaub" },
        present_simple: { name: "Present Simple", icon: "📅", color: "#10b981", desc: "Gegenwart" },
        past_simple: { name: "Past Simple", icon: "⏮️", color: "#3b82f6", desc: "Vergangenheit" },
        present_continuous: { name: "Present Continuous", icon: "▶️", color: "#f59e0b", desc: "Verlaufsform" },
        going_to: { name: "Going to", icon: "🎯", color: "#ec4899", desc: "Zukunft" },
        comparatives: { name: "Comparatives", icon: "⚖️", color: "#8b5cf6", desc: "Vergleiche" },
        prepositions: { name: "Präpositionen", icon: "📍", color: "#22c55e", desc: "Ort und Richtung" },
        pronouns: { name: "Pronomen", icon: "👤", color: "#6366f1", desc: "Fürwörter" }
    },

    questions: {
        everyday: [
            { question: "Was bedeutet 'house'?", answers: ["Haus", "Tür", "Fenster", "Zimmer"], correct: 0, hint: "Wohnort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'door'?", answers: ["Haus", "Tür", "Fenster", "Tisch"], correct: 1, hint: "Eingang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'window'?", answers: ["Tür", "Dach", "Fenster", "Wand"], correct: 2, hint: "Lichtquelle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'table'?", answers: ["Stuhl", "Tisch", "Schrank", "Bett"], correct: 1, hint: "Möbelstück", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chair'?", answers: ["Tisch", "Stuhl", "Sofa", "Bank"], correct: 1, hint: "Sitzmöbel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'book'?", answers: ["Heft", "Buch", "Zeitung", "Block"], correct: 1, hint: "Lesestoff", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'clock'?", answers: ["Uhr", "Kalender", "Zeit", "Minute"], correct: 0, hint: "Zeitmesser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'phone'?", answers: ["Computer", "Telefon", "Fernseher", "Radio"], correct: 1, hint: "Kommunikation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'computer'?", answers: ["Computer", "Laptop", "Tablet", "Handy"], correct: 0, hint: "Elektronik", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'car'?", answers: ["Bus", "Auto", "Zug", "Fahrrad"], correct: 1, hint: "Fahrzeug", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'room'?", answers: ["Raum", "Haus", "Wohnung", "Garten"], correct: 0, hint: "Zimmer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bed'?", answers: ["Sofa", "Bett", "Stuhl", "Matratze"], correct: 1, hint: "Schlafmöbel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'kitchen'?", answers: ["Küche", "Keller", "Bad", "Flur"], correct: 0, hint: "Hier kocht man", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bathroom'?", answers: ["Schlafzimmer", "Badezimmer", "Küche", "Garten"], correct: 1, hint: "Zähneputzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'garden'?", answers: ["Park", "Wald", "Garten", "Hof"], correct: 2, hint: "Draußen am Haus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'floor'?", answers: ["Dach", "Wand", "Boden", "Fenster"], correct: 2, hint: "Darauf steht man", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'wall'?", answers: ["Wand", "Tür", "Boden", "Decke"], correct: 0, hint: "Grenzt den Raum ab", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shelf'?", answers: ["Schrank", "Regal", "Kommode", "Tisch"], correct: 1, hint: "Für Bücher", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mirror'?", answers: ["Lampe", "Spiegel", "Bild", "Fenster"], correct: 1, hint: "Sich selbst sehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'curtain'?", answers: ["Teppich", "Vorhang", "Tapete", "Rollo"], correct: 1, hint: "Am Fenster", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'carpet'?", answers: ["Fliese", "Parkett", "Teppich", "Decke"], correct: 2, hint: "Weich am Boden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'neighbor'?", answers: ["Freund", "Nachbar", "Onkel", "Gast"], correct: 1, hint: "Wohnt nebenan", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'village'?", answers: ["Stadt", "Dorf", "Land", "Insel"], correct: 1, hint: "Kleiner als eine Stadt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'street'?", answers: ["Platz", "Gasse", "Straße", "Weg"], correct: 2, hint: "Wo Autos fahren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'town'?", answers: ["Dorf", "Land", "Stadt", "Haus"], correct: 2, hint: "Größer als ein Dorf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shop'?", answers: ["Laden", "Schule", "Kino", "Park"], correct: 0, hint: "Einkaufen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'money'?", answers: ["Zeit", "Geld", "Arbeit", "Glück"], correct: 1, hint: "Bezahlen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'key'?", answers: ["Schloss", "Schlüssel", "Tür", "Kiste"], correct: 1, hint: "Öffnet Türen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'living room'?", answers: ["Küche", "Wohnzimmer", "Bad", "Keller"], correct: 1, hint: "Sofa und TV", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'garage'?", answers: ["Garten", "Garage", "Dachboden", "Flur"], correct: 1, hint: "Für das Auto", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        school: [
            { question: "Was bedeutet 'school'?", answers: ["Schule", "Klasse", "Lehrer", "Schüler"], correct: 0, hint: "Lernort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'teacher'?", answers: ["Schüler", "Lehrer", "Direktor", "Eltern"], correct: 1, hint: "Unterrichtender", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'student'?", answers: ["Lehrer", "Schüler", "Professor", "Dozent"], correct: 1, hint: "Lernender", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'classroom'?", answers: ["Schule", "Klassenzimmer", "Lehrerzimmer", "Bibliothek"], correct: 1, hint: "Unterrichtsraum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'blackboard'?", answers: ["Tafel", "Whiteboard", "Papier", "Buch"], correct: 0, hint: "Schreibfläche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pen'?", answers: ["Bleistift", "Stift", "Buch", "Heft"], correct: 1, hint: "Schreibgerät", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'exercise book'?", answers: ["Buch", "Heft", "Block", "Tasche"], correct: 1, hint: "Schulmaterial", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'test'?", answers: ["Prüfung", "Hausaufgabe", "Unterricht", "Pause"], correct: 0, hint: "Leistungskontrolle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'homework'?", answers: ["Schularbeit", "Hausaufgabe", "Klassenarbeit", "Test"], correct: 1, hint: "Arbeit zu Hause", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'break'?", answers: ["Unterricht", "Pause", "Schule", "Ferien"], correct: 1, hint: "Freizeit in der Schule", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'subject'?", answers: ["Fach", "Klasse", "Note", "Lehrer"], correct: 0, hint: "Unterrichtsfach", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'grade'?", answers: ["Klasse", "Note", "Schule", "Lehrer"], correct: 1, hint: "Bewertung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pencil case'?", answers: ["Rucksack", "Mäppchen", "Heft", "Stift"], correct: 1, hint: "Für Stifte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ruler'?", answers: ["Schere", "Lineal", "Radiergummi", "Kleber"], correct: 1, hint: "Zum Messen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'rubber'?", answers: ["Stift", "Lineal", "Radiergummi", "Schere"], correct: 2, hint: "Löscht Bleistift", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'timetable'?", answers: ["Kalender", "Uhr", "Stundenplan", "Notizbuch"], correct: 2, hint: "Wann ist was?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gym'?", answers: ["Klassenzimmer", "Turnhalle", "Schulhof", "Kantine"], correct: 1, hint: "Sportunterricht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'library'?", answers: ["Labor", "Büro", "Bibliothek", "Kiosk"], correct: 2, hint: "Viele Bücher", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'canteen'?", answers: ["Kiosk", "Kantine", "Café", "Markt"], correct: 1, hint: "Hier isst man", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'to learn'?", answers: ["lehren", "fragen", "lernen", "antworten"], correct: 2, hint: "Wissen aufnehmen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mark'?", answers: ["Zahl", "Markierung", "Note", "Name"], correct: 2, hint: "Bewertung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'scissors'?", answers: ["Mäppchen", "Schere", "Zirkel", "Lineal"], correct: 1, hint: "Zum Schneiden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'glue'?", answers: ["Farbe", "Kleber", "Papier", "Stift"], correct: 1, hint: "Hält Dinge zusammen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'felt-tip'?", answers: ["Füller", "Filzstift", "Buntstift", "Bleistift"], correct: 1, hint: "Bunter Stift", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'desk'?", answers: ["Stuhl", "Tisch", "Schreibtisch", "Bank"], correct: 2, hint: "Arbeitsplatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'assembly'?", answers: ["Hausaufgabe", "Versammlung", "Ausflug", "Projekt"], correct: 1, hint: "Alle in der Halle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'playground'?", answers: ["Sportplatz", "Schulhof", "Wiese", "Park"], correct: 1, hint: "Draußen spielen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'PE' (Physical Education)?", answers: ["Physik", "Sport", "Erdkunde", "Kunst"], correct: 1, hint: "Bewegung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ICT'?", answers: ["Mathe", "Deutsch", "Informatik", "Musik"], correct: 2, hint: "Computer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dictionary'?", answers: ["Atlas", "Wörterbuch", "Kalender", "Heft"], correct: 1, hint: "Zum Nachschlagen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        family: [
            { question: "Was bedeutet 'mother'?", answers: ["Mutter", "Vater", "Schwester", "Oma"], correct: 0, hint: "weibliches Elternteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'father'?", answers: ["Mutter", "Vater", "Bruder", "Opa"], correct: 1, hint: "männliches Elternteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sister'?", answers: ["Bruder", "Schwester", "Cousin", "Freundin"], correct: 1, hint: "weibliches Geschwister", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'brother'?", answers: ["Schwester", "Bruder", "Cousin", "Freund"], correct: 1, hint: "männliches Geschwister", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'grandmother'?", answers: ["Mutter", "Tante", "Oma", "Schwester"], correct: 2, hint: "Mutter der Eltern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'grandfather'?", answers: ["Vater", "Onkel", "Opa", "Bruder"], correct: 2, hint: "Vater der Eltern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'aunt'?", answers: ["Mutter", "Schwester", "Tante", "Oma"], correct: 2, hint: "Schwester der Eltern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'uncle'?", answers: ["Vater", "Bruder", "Onkel", "Opa"], correct: 2, hint: "Bruder der Eltern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'baby'?", answers: ["Kind", "Baby", "Jugendlicher", "Erwachsener"], correct: 1, hint: "Säugling", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'parents'?", answers: ["Eltern", "Großeltern", "Geschwister", "Kinder"], correct: 0, hint: "Mutter und Vater", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'family'?", answers: ["Freunde", "Familie", "Nachbarn", "Verwandte"], correct: 1, hint: "Verwandtschaft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cousin'?", answers: ["Bruder", "Neffe", "Cousin", "Enkel"], correct: 2, hint: "Kind von Tante/Onkel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'son'?", answers: ["Sohn", "Tochter", "Kind", "Junge"], correct: 0, hint: "Männliches Kind", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'daughter'?", answers: ["Sohn", "Tochter", "Kind", "Mädchen"], correct: 1, hint: "Weibliches Kind", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'wife'?", answers: ["Ehefrau", "Ehemann", "Mutter", "Frau"], correct: 0, hint: "Verheiratet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'husband'?", answers: ["Ehefrau", "Ehemann", "Vater", "Mann"], correct: 1, hint: "Verheiratet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'best friend'?", answers: ["Bekannter", "Bester Freund", "Klassenkamerad", "Nachbar"], correct: 1, hint: "Wichtigste Person", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'stepmother'?", answers: ["Stiefmutter", "Schwiegermutter", "Patin", "Tante"], correct: 0, hint: "Neue Frau des Vaters", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'twins'?", answers: ["Brüder", "Schwestern", "Zwillinge", "Paar"], correct: 2, hint: "Zwei gleichzeitig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'only child'?", answers: ["Lieblingskind", "Einzelkind", "Waisenkind", "Kleinkind"], correct: 1, hint: "Keine Geschwister", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        food: [
            { question: "Was bedeutet 'apple'?", answers: ["Banane", "Apfel", "Orange", "Traube"], correct: 1, hint: "Obst", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bread'?", answers: ["Kuchen", "Brot", "Brötchen", "Keks"], correct: 1, hint: "Grundnahrungsmittel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'water'?", answers: ["Saft", "Wasser", "Milch", "Tee"], correct: 1, hint: "Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'milk'?", answers: ["Wasser", "Saft", "Milch", "Kaffee"], correct: 2, hint: "Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pizza'?", answers: ["Pasta", "Pizza", "Burger", "Salat"], correct: 1, hint: "italienisches Essen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cake'?", answers: ["Keks", "Kuchen", "Torte", "Pudding"], correct: 1, hint: "Süßspeise", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'meat'?", answers: ["Fisch", "Fleisch", "Gemüse", "Obst"], correct: 1, hint: "tierisches Protein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vegetables'?", answers: ["Obst", "Fleisch", "Gemüse", "Getreide"], correct: 2, hint: "pflanzliche Nahrung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chocolate'?", answers: ["Bonbon", "Schokolade", "Keks", "Kuchen"], correct: 1, hint: "Süßigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'coffee'?", answers: ["Tee", "Kakao", "Kaffee", "Milch"], correct: 2, hint: "koffeinhaltiges Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'soup'?", answers: ["Salat", "Suppe", "Soße", "Eintopf"], correct: 1, hint: "flüssiges Essen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'salad'?", answers: ["Suppe", "Salat", "Gemüse", "Obst"], correct: 1, hint: "Gemüsegericht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cheese'?", answers: ["Ei", "Milch", "Käse", "Wurst"], correct: 2, hint: "Gelb und herzhaft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'egg'?", answers: ["Ei", "Apfel", "Keks", "Nuss"], correct: 0, hint: "Vom Huhn", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'butter'?", answers: ["Margarine", "Öl", "Butter", "Schmalz"], correct: 2, hint: "Aufs Brot", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'juice'?", answers: ["Wasser", "Saft", "Tee", "Cola"], correct: 1, hint: "Aus Früchten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tea'?", answers: ["Kaffee", "Tee", "Kakao", "Saft"], correct: 1, hint: "Britisches Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'banana'?", answers: ["Apfel", "Birne", "Banane", "Kirsche"], correct: 2, hint: "Gelbe Frucht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'carrot'?", answers: ["Gurke", "Karotte", "Tomate", "Erbse"], correct: 1, hint: "Oranges Gemüse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'potato'?", answers: ["Kartoffel", "Tomate", "Zwiebel", "Reis"], correct: 0, hint: "Für Pommes", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sugar'?", answers: ["Salz", "Mehl", "Zucker", "Pfeffer"], correct: 2, hint: "Süß", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'salt'?", answers: ["Zucker", "Salz", "Essig", "Öl"], correct: 1, hint: "Weiß und würzig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'honey'?", answers: ["Marmelade", "Honig", "Sirup", "Zucker"], correct: 1, hint: "Von Bienen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fruit'?", answers: ["Gemüse", "Obst", "Fleisch", "Brot"], correct: 1, hint: "Äpfel, Birnen etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chips' (BE)?", answers: ["Chips", "Pommes", "Kekse", "Nüsse"], correct: 1, hint: "Fish and ...", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        body: [
            { question: "Was bedeutet 'head'?", answers: ["Hand", "Kopf", "Fuß", "Bein"], correct: 1, hint: "Ganz oben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'arm'?", answers: ["Bein", "Arm", "Hand", "Finger"], correct: 1, hint: "Obere Extremität", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'leg'?", answers: ["Arm", "Fuß", "Bein", "Kopf"], correct: 2, hint: "Zum Laufen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hand'?", answers: ["Fuß", "Finger", "Hand", "Arm"], correct: 2, hint: "Hat fünf Finger", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'foot'?", answers: ["Hand", "Fuß", "Zeh", "Bein"], correct: 1, hint: "Im Schuh", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'eye'?", answers: ["Ohr", "Nase", "Auge", "Mund"], correct: 2, hint: "Zum Sehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ear'?", answers: ["Auge", "Ohr", "Nase", "Zahn"], correct: 1, hint: "Zum Hören", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'nose'?", answers: ["Ohr", "Mund", "Nase", "Kinn"], correct: 2, hint: "Zum Riechen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mouth'?", answers: ["Zahn", "Mund", "Lippe", "Zunge"], correct: 1, hint: "Zum Essen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tooth'?", answers: ["Zahn", "Mund", "Hals", "Kinn"], correct: 0, hint: "Weiß im Mund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'back'?", answers: ["Bauch", "Rücken", "Brust", "Schulter"], correct: 1, hint: "Hinterseite", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'stomach'?", answers: ["Herz", "Lunge", "Magen", "Leber"], correct: 2, hint: "Wo das Essen hingeht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'knee'?", answers: ["Ellbogen", "Knie", "Knöchel", "Hüfte"], correct: 1, hint: "Mitte des Beins", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shoulder'?", answers: ["Hals", "Arm", "Schulter", "Rücken"], correct: 2, hint: "Oben am Rumpf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'finger'?", answers: ["Zeh", "Daumen", "Finger", "Nagel"], correct: 2, hint: "An der Hand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'toe'?", answers: ["Finger", "Zeh", "Fuß", "Ferse"], correct: 1, hint: "Am Fuß", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hair'?", answers: ["Haut", "Haare", "Zähne", "Augen"], correct: 1, hint: "Auf dem Kopf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'face'?", answers: ["Kopf", "Gesicht", "Hals", "Stirn"], correct: 1, hint: "Vorderseite Kopf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'neck'?", answers: ["Hals", "Nacken", "Kehle", "Alle"], correct: 3, hint: "Verbindung Kopf-Körper", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'body'?", answers: ["Geist", "Seele", "Körper", "Haut"], correct: 2, hint: "Alles zusammen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        clothes: [
            { question: "Was bedeutet 'shirt'?", answers: ["Hose", "Hemd", "Jacke", "Hut"], correct: 1, hint: "Oberteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'trousers'?", answers: ["Rock", "Hose", "Kleid", "Schal"], correct: 1, hint: "An den Beinen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shoes'?", answers: ["Socken", "Stiefel", "Schuhe", "Handschuhe"], correct: 2, hint: "An den Füßen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hat'?", answers: ["Mütze", "Hut", "Helm", "Kappe"], correct: 1, hint: "Auf dem Kopf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'coat'?", answers: ["Jacke", "Mantel", "Pullover", "Hemd"], correct: 1, hint: "Für draußen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'skirt'?", answers: ["Kleid", "Hose", "Rock", "Bluse"], correct: 2, hint: "Für Mädchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dress'?", answers: ["Rock", "Bluse", "Kleid", "Hemd"], correct: 2, hint: "Einteiler", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'socks'?", answers: ["Schuhe", "Socken", "Hosen", "Handschuhe"], correct: 1, hint: "In den Schuhen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sweater'?", answers: ["Jacke", "Mantel", "Pullover", "T-Shirt"], correct: 2, hint: "Warmes Oberteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'jacket'?", answers: ["Hemd", "Mantel", "Jacke", "Bluse"], correct: 2, hint: "Kurzes Oberteil für draußen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cap'?", answers: ["Hut", "Mütze", "Kappe", "Schal"], correct: 2, hint: "Baseball ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'scarf'?", answers: ["Handschuh", "Mütze", "Schal", "Tuch"], correct: 2, hint: "Um den Hals", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gloves'?", answers: ["Schuhe", "Socken", "Handschuhe", "Hüte"], correct: 2, hint: "Für die Hände", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'belt'?", answers: ["Ring", "Gürtel", "Kette", "Uhr"], correct: 1, hint: "Hält die Hose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'jeans'?", answers: ["Hose", "Jeans", "Stoffhose", "Shorts"], correct: 1, hint: "Blaue Hose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'boots'?", answers: ["Schuhe", "Sandalen", "Stiefel", "Turnschuhe"], correct: 2, hint: "Hohe Schuhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pyjamas'?", answers: ["Anzug", "Schlafanzug", "Unterwäsche", "Kleid"], correct: 1, hint: "Zum Schlafen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shorts'?", answers: ["Hose", "Kurze Hose", "Rock", "Badehose"], correct: 1, hint: "Für den Sommer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'blouse'?", answers: ["Hemd", "T-Shirt", "Bluse", "Top"], correct: 2, hint: "Damenoberteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tie'?", answers: ["Gürtel", "Schal", "Krawatte", "Fliege"], correct: 2, hint: "Zum Anzug", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        animals: [
            { question: "Was bedeutet 'dog'?", answers: ["Katze", "Hund", "Maus", "Vogel"], correct: 1, hint: "Haustier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cat'?", answers: ["Hund", "Katze", "Hamster", "Kaninchen"], correct: 1, hint: "Haustier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bird'?", answers: ["Fisch", "Vogel", "Schmetterling", "Biene"], correct: 1, hint: "fliegt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fish'?", answers: ["Hai", "Fisch", "Wal", "Delfin"], correct: 1, hint: "schwimmt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'horse'?", answers: ["Esel", "Pferd", "Pony", "Zebra"], correct: 1, hint: "Reittier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'lion'?", answers: ["Tiger", "Löwe", "Leopard", "Gepard"], correct: 1, hint: "König der Tiere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'elephant'?", answers: ["Nashorn", "Elefant", "Nilpferd", "Giraffe"], correct: 1, hint: "größtes Landtier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'snake'?", answers: ["Eidechse", "Schlange", "Wurm", "Krokodil"], correct: 1, hint: "kriecht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bear'?", answers: ["Wolf", "Bär", "Hund", "Fuchs"], correct: 1, hint: "großes Säugetier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'rabbit'?", answers: ["Maus", "Hase", "Hamster", "Meerschweinchen"], correct: 1, hint: "hat lange Ohren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fox'?", answers: ["Wolf", "Fuchs", "Kojote", "Hund"], correct: 1, hint: "schlaues Tier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'wolf'?", answers: ["Hund", "Wolf", "Kojote", "Schakal"], correct: 1, hint: "Rudeltier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'monkey'?", answers: ["Affe", "Gorilla", "Schimpanse", "Orang-Utan"], correct: 0, hint: "Klettert gern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cow'?", answers: ["Schaf", "Schwein", "Kuh", "Ziege"], correct: 2, hint: "Gibt Milch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sheep'?", answers: ["Ziege", "Schaf", "Lamm", "Kuh"], correct: 1, hint: "Hat Wolle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pig'?", answers: ["Hund", "Schaf", "Schwein", "Esel"], correct: 2, hint: "Ist rosa", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chicken'?", answers: ["Hahn", "Henne", "Huhn", "Vogel"], correct: 2, hint: "Gibt Eier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mouse' (Plural: mice)?", answers: ["Ratte", "Maus", "Hamster", "Eichhörnchen"], correct: 1, hint: "Klienes Nagetier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'duck'?", answers: ["Gans", "Ente", "Schwan", "Vogel"], correct: 1, hint: "Schwimmt auf dem Teich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'spider'?", answers: ["Wurm", "Spinne", "Käfer", "Fliege"], correct: 1, hint: "Hat acht Beine", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        nature: [
            { question: "Was bedeutet 'tree'?", answers: ["Blume", "Baum", "Strauch", "Pflanze"], correct: 1, hint: "wächst im Wald", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'flower'?", answers: ["Baum", "Blume", "Gras", "Blatt"], correct: 1, hint: "blüht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sun'?", answers: ["Mond", "Sonne", "Stern", "Wolke"], correct: 1, hint: "scheint am Tag", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'moon'?", answers: ["Sonne", "Mond", "Stern", "Planet"], correct: 1, hint: "scheint in der Nacht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'star'?", answers: ["Planet", "Stern", "Komet", "Mond"], correct: 1, hint: "funktelt am Himmel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mountain'?", answers: ["Hügel", "Berg", "Tal", "Wiese"], correct: 1, hint: "hohe Erhebung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'river'?", answers: ["See", "Fluss", "Meer", "Bach"], correct: 1, hint: "fließendes Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sea'?", answers: ["See", "Fluss", "Meer", "Ozean"], correct: 2, hint: "große Wasserfläche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'forest'?", answers: ["Wiese", "Wald", "Park", "Garten"], correct: 1, hint: "viele Bäume", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cloud'?", answers: ["Nebel", "Wolke", "Rauch", "Dampf"], correct: 1, hint: "am Himmel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'rain'?", answers: ["Schnee", "Regen", "Hagel", "Nebel"], correct: 1, hint: "fällt vom Himmel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'snow'?", answers: ["Regen", "Schnee", "Eis", "Hagel"], correct: 1, hint: "weiß und kalt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'weather'?", answers: ["Klima", "Wetter", "Temperatur", "Luft"], correct: 1, hint: "Sonne, Regen...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hot'?", answers: ["kalt", "warm", "heiß", "kühl"], correct: 2, hint: "Gegenteil von cold", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cold'?", answers: ["heiß", "warm", "kühl", "kalt"], correct: 3, hint: "Im Winter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'windy'?", answers: ["stürmisch", "windig", "regnerisch", "bewölkt"], correct: 1, hint: "Viel Wind", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sunny'?", answers: ["schön", "warm", "sonnig", "hell"], correct: 2, hint: "Viel Sonne", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'storm'?", answers: ["Regen", "Wind", "Sturm", "Gewitter"], correct: 2, hint: "Heftiges Wetter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'island'?", answers: ["Land", "Insel", "Kontinent", "Küste"], correct: 1, hint: "Land im Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'lake'?", answers: ["Meer", "Fluss", "Bach", "See"], correct: 3, hint: "Stehendes Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        hobbies: [
            { question: "Was bedeutet 'play football'?", answers: ["Fußball spielen", "Basketball spielen", "Tennis spielen", "Handball spielen"], correct: 0, hint: "Sport", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'read'?", answers: ["schreiben", "lesen", "malen", "zeichnen"], correct: 1, hint: "Bücher", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'make music'?", answers: ["singen", "musizieren", "tanzen", "spielen"], correct: 1, hint: "Instrument", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'swim'?", answers: ["laufen", "schwimmen", "radfahren", "wandern"], correct: 1, hint: "im Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cycle'?", answers: ["laufen", "schwimmen", "radfahren", "wandern"], correct: 2, hint: "Fahrrad", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'paint'?", answers: ["zeichnen", "malen", "basteln", "kleben"], correct: 1, hint: "Farben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dance'?", answers: ["singen", "spielen", "tanzen", "springen"], correct: 2, hint: "Bewegung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cook'?", answers: ["backen", "kochen", "braten", "schmoren"], correct: 1, hint: "Essen zubereiten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'play'?", answers: ["arbeiten", "spielen", "lernen", "schlafen"], correct: 1, hint: "Spaß haben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hike'?", answers: ["laufen", "wandern", "klettern", "campen"], correct: 1, hint: "in der Natur", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'watch TV'?", answers: ["lesen", "schreiben", "fernsehen", "spielen"], correct: 2, hint: "Bildschirm", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'computer games'?", answers: ["Brettspiele", "Kartenspiele", "Computerspiele", "Sportspiele"], correct: 2, hint: "Am PC", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sing'?", answers: ["tanzen", "singen", "lachen", "rufen"], correct: 1, hint: "Mit der Stimme", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'meet friends'?", answers: ["Freunde einladen", "Freunde treffen", "Freunde suchen", "Freunde anrufen"], correct: 1, hint: "Zusammenkommen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'travel'?", answers: ["fahren", "fliegen", "reisen", "wandern"], correct: 2, hint: "Andere Orte besuchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'climb'?", answers: ["laufen", "springen", "klettern", "fallen"], correct: 2, hint: "Am Berg oder Baum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'jog'?", answers: ["schnell gehen", "joggen/laufen", "rennen", "stehen"], correct: 1, hint: "Langsames Rennen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'take photos'?", answers: ["malen", "zeichnen", "fotografieren", "filmen"], correct: 2, hint: "Kamera nutzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'listen to music'?", answers: ["Musik machen", "Musik hören", "Musik kaufen", "Musik tanzen"], correct: 1, hint: "Mit den Ohren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'collect'?", answers: ["geben", "tauschen", "sammeln", "verkaufen"], correct: 2, hint: "Zusammenbringen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        travel: [
            { question: "Was bedeutet 'plane'?", answers: ["Zug", "Flugzeug", "Auto", "Schiff"], correct: 1, hint: "fliegt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'train'?", answers: ["Bus", "Zug", "Auto", "Fahrrad"], correct: 1, hint: "auf Schienen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'car'?", answers: ["Bus", "Zug", "Auto", "Schiff"], correct: 2, hint: "fährt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bus'?", answers: ["Zug", "Bus", "Auto", "Flugzeug"], correct: 1, hint: "öffentlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ship'?", answers: ["Boot", "Schiff", "U-Boot", "Kanu"], correct: 1, hint: "auf dem Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'holiday'?", answers: ["Wochenende", "Urlaub", "Ferien", "Freizeit"], correct: 1, hint: "Freizeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hotel'?", answers: ["Restaurant", "Hotel", "Pension", "Hostel"], correct: 1, hint: "Unterkunft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'map'?", answers: ["Kompass", "Karte", "Plan", "Buch"], correct: 1, hint: "Orientierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ticket'?", answers: ["Pass", "Ticket", "Visum", "Karte"], correct: 1, hint: "Eintritt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'journey'?", answers: ["Ausflug", "Reise", "Trip", "Tour"], correct: 1, hint: "Trip", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'suitcase'?", answers: ["Tasche", "Rucksack", "Koffer", "Beutel"], correct: 2, hint: "Gepäckstück", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'passport'?", answers: ["Visum", "Reisepass", "Ausweis", "Ticket"], correct: 1, hint: "Dokument", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'airport'?", answers: ["Bahnhof", "Hafen", "Flughafen", "Parkplatz"], correct: 2, hint: "Wo Flugzeuge landen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'station'?", answers: ["Hafen", "Bahnhof", "Flughafen", "Bushaltestelle"], correct: 1, hint: "Zug-Stopp", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'beach'?", answers: ["Wald", "Wiese", "Strand", "Berg"], correct: 2, hint: "Am Meer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tourist'?", answers: ["Einheimischer", "Tourist", "Führer", "Gast"], correct: 1, hint: "Reisende Person", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'visit'?", answers: ["sehen", "bleiben", "besuchen", "wohnen"], correct: 2, hint: "Jemanden aufsuchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'flight'?", answers: ["Fahrt", "Reise", "Flug", "Gang"], correct: 2, hint: "In der Luft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'museum'?", answers: ["Kino", "Theater", "Museum", "Galerie"], correct: 2, hint: "Alte Dinge ansehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'souvenir'?", answers: ["Geschenk", "Essen", "Andenken", "Kleidung"], correct: 2, hint: "Mitbringsel", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        present_simple: [
            { question: "Wie lautet: 'Ich spiele Fußball.'?", answers: ["I play football.", "I plays football.", "I am play football.", "I played football."], correct: 0, hint: "Basisform für I", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Sie liest ein Buch.'?", answers: ["She read a book.", "She reads a book.", "She reading a book.", "She is reads a book."], correct: 1, hint: "He, she, it - das -s muss mit!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Wir gehen zur Schule.'?", answers: ["We goes to school.", "We going to school.", "We go to school.", "We gone to school."], correct: 2, hint: "Plural: Grundform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Er trinkt Wasser.'?", answers: ["He drink water.", "He drinks water.", "He drinking water.", "He is drink water."], correct: 1, hint: "3. Person Singular: -s", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Die Sonne scheint.'?", answers: ["The sun shine.", "The sun shines.", "The sun shining.", "The sun is shine."], correct: 1, hint: "Tatsache: Present Simple", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet die Verneinung von: 'I like pizza'?", answers: ["I not like pizza.", "I don't like pizza.", "I doesn't like pizza.", "I am not like pizza."], correct: 1, hint: "Hilfsverb do", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet die Verneinung von: 'He likes pizza'?", answers: ["He not likes pizza.", "He don't like pizza.", "He doesn't like pizza.", "He doesn't likes pizza."], correct: 2, hint: "Das -s wandert zu does", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ you play tennis?'", answers: ["Are", "Do", "Does", "Is"], correct: 1, hint: "Fragebildung bei you", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ she speak English?'", answers: ["Do", "Does", "Speak", "Is"], correct: 1, hint: "Fragebildung bei she", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Signalwort für Present Simple?", answers: ["Now", "At the moment", "Usually", "Yesterday"], correct: 2, hint: "Gewohnheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Signalwort für Present Simple?", answers: ["Look!", "Always", "Next week", "In 2010"], correct: 1, hint: "Regelmäßigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form ist korrekt?", answers: ["They has a dog.", "They have a dog.", "They haves a dog.", "They are have a dog."], correct: 1, hint: "Plural von have", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form ist korrekt?", answers: ["She have a cat.", "She has a cat.", "She haves a cat.", "She is has a cat."], correct: 1, hint: "Singular von have", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'They ___ (not go) to London.'", answers: ["don't go", "doesn't go", "not go", "are not go"], correct: 0, hint: "Plural Hilfsverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'It ___ (not rain) here.'", answers: ["don't rain", "doesn't rain", "not rains", "doesn't rains"], correct: 1, hint: "Singular Hilfsverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: 'Where ___ you live?'", answers: ["are", "do", "does", "is"], correct: 1, hint: "You-Frage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: 'When ___ the film start?'", answers: ["do", "is", "does", "starts"], correct: 2, hint: "The film = it", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Satz ist eine Gewohnheit?", answers: ["I am eating now.", "I eat breakfast every day.", "I will eat later.", "I ate an apple."], correct: 1, hint: "Every day", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "He ___ (wash) his car every week.", answers: ["wash", "washs", "washes", "washing"], correct: 2, hint: "Besonderheit bei Endung -sh", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "She ___ (try) very hard.", answers: ["trys", "tryes", "tries", "try"], correct: 2, hint: "y wird zu ie", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        past_simple: [
            { question: "Wie lautet: 'Ich spielte gestern Fußball.'?", answers: ["I play football yesterday.", "I played football yesterday.", "I playing football yesterday.", "I plays football yesterday."], correct: 1, hint: "Regelmäßig: -ed", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Sie ging nach Hause.' (go)?", answers: ["She goed home.", "She went home.", "She going home.", "She goes home."], correct: 1, hint: "Unregelmäßig: go - went", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Wir waren im Kino.'?", answers: ["We are at the cinema.", "We were at the cinema.", "We was at the cinema.", "We being at the cinema."], correct: 1, hint: "to be im Plural", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'I ___ (not watch) TV.'", answers: ["not watched", "didn't watch", "didn't watched", "don't watched"], correct: 1, hint: "didn't + Grundform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'He ___ (not see) me.'", answers: ["didn't saw", "not saw", "didn't see", "not see"], correct: 2, hint: "didn't + Grundform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ you have fun?'", answers: ["Do", "Did", "Were", "Had"], correct: 1, hint: "Hilfsverb in der Vergangenheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: 'What ___ she buy?'", answers: ["did", "does", "bought", "do"], correct: 0, hint: "Fragebildung Vergangenheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Signalwort für Past Simple?", answers: ["Often", "Now", "Two days ago", "Never"], correct: 2, hint: "Zeitpunkt zurückliegend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Signalwort für Past Simple?", answers: ["Last year", "Next year", "Every year", "Usually"], correct: 0, hint: "Letztes Jahr", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Vergangenheit von 'be' (she)?", answers: ["were", "was", "been", "is"], correct: 1, hint: "Einzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Vergangenheit von 'be' (they)?", answers: ["was", "were", "been", "are"], correct: 1, hint: "Mehrzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'make'?", answers: ["maked", "maden", "made", "makes"], correct: 2, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'take'?", answers: ["taked", "taken", "took", "takes"], correct: 2, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'eat'?", answers: ["eated", "ate", "aten", "eats"], correct: 1, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'drink'?", answers: ["drinked", "drank", "drunk", "drinks"], correct: 1, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'see'?", answers: ["seed", "seen", "saw", "sees"], correct: 2, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'do'?", answers: ["doed", "done", "did", "does"], correct: 2, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'have'?", answers: ["haved", "has", "had", "haves"], correct: 2, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'run'?", answers: ["runned", "ran", "runs", "run"], correct: 1, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Past von 'come'?", answers: ["comed", "came", "comes", "come"], correct: 1, hint: "Unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        present_continuous: [
            { question: "Wie lautet: 'Ich spiele gerade Fußball.'?", answers: ["I play football.", "I am playing football.", "I playing football.", "I plays football."], correct: 1, hint: "am + -ing", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Sie liest gerade ein Buch.'?", answers: ["She reads a book.", "She is reading a book.", "She reading a book.", "She are reading a book."], correct: 1, hint: "is + -ing", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Wir gehen gerade zur Schule.'?", answers: ["We go to school.", "We are going to school.", "We going to school.", "We is going to school."], correct: 1, hint: "are + -ing", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'I ___ (not sleep).'", answers: ["not sleeping", "don't sleeping", "am not sleeping", "doesn't sleep"], correct: 2, hint: "am + not + -ing", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'He ___ (not work).'", answers: ["isn't working", "doesn't working", "not working", "aren't working"], correct: 0, hint: "isn't + -ing", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ you listening?'", answers: ["Do", "Are", "Is", "Does"], correct: 1, hint: "Are + -ing", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: 'What ___ they doing?'", answers: ["is", "are", "do", "does"], correct: 1, hint: "Are + -ing (Plural)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Signalwort für Present Continuous?", answers: ["Usually", "Often", "Right now", "Every day"], correct: 2, hint: "Genau jetzt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Signalwort für Present Continuous?", answers: ["Look!", "Always", "Yesterday", "Last week"], correct: 0, hint: "Aufforderung hinzusehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'They ___ (not play).'", answers: ["isn't playing", "aren't playing", "not playing", "don't playing"], correct: 1, hint: "Plural Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schreibweise: 'I am ___ (sit) here.'", answers: ["siting", "sitting", "sitted", "sits"], correct: 1, hint: "Verdopplung des Konsonanten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schreibweise: 'She is ___ (swim) now.'", answers: ["swiming", "swimming", "swims", "swimmed"], correct: 1, hint: "Verdopplung des Konsonanten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schreibweise: 'He is ___ (write) a letter.'", answers: ["writeing", "writing", "writes", "writed"], correct: 1, hint: "Stummes e fällt weg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schreibweise: 'They are ___ (make) pizza.'", answers: ["makeing", "making", "makes", "maked"], correct: 1, hint: "Stummes e fällt weg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ it raining?'", answers: ["Do", "Does", "Is", "Are"], correct: 2, hint: "Einzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: 'Why ___ you crying?'", answers: ["do", "is", "are", "did"], correct: 2, hint: "You-Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form ist korrekt?", answers: ["Listen! Someone sings.", "Listen! Someone is singing.", "Listen! Someone is sing.", "Listen! Someone singing."], correct: 1, hint: "Gerade jetzt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form ist korrekt?", answers: ["I am doing my homework now.", "I do my homework now.", "I doing my homework now.", "I does my homework now."], correct: 0, hint: "Gerade jetzt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'We ___ (not use) the computer.'", answers: ["aren't use", "isn't using", "aren't using", "not using"], correct: 2, hint: "Mehrzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passt: 'Be quiet! The baby ___.'", answers: ["sleeps", "sleeping", "is sleeping", "is sleeps"], correct: 2, hint: "Gerade in diesem Moment", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        going_to: [
            { question: "Wie lautet: 'Ich werde Fußball spielen.'?", answers: ["I play football.", "I am going to play football.", "I going to play football.", "I will playing football."], correct: 1, hint: "Absicht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Sie wird ein Buch lesen.'?", answers: ["She reads a book.", "She is going to read a book.", "She going to read a book.", "She will reads a book."], correct: 1, hint: "Plan", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet: 'Wir werden zur Schule gehen.'?", answers: ["We go to school.", "We are going to go to school.", "We going to go to school.", "We will going to school."], correct: 1, hint: "Mehrzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'I ___ (not buy) that.'", answers: ["not going to buy", "am not going to buy", "don't going to buy", "won't going to buy"], correct: 1, hint: "am not going to", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Verneinung: 'They ___ (not help) us.'", answers: ["aren't going to help", "not going to help", "isn't going to help", "don't going to help"], correct: 0, hint: "aren't going to", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ you going to watch the film?'", answers: ["Do", "Are", "Is", "Will"], correct: 1, hint: "Are + going to", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: '___ she going to call you?'", answers: ["Is", "Are", "Does", "Will"], correct: 0, hint: "Is + going to", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form ist eine Vorhersage?", answers: ["Look! It is going to rain.", "It rains every day.", "It rained yesterday.", "It rain."], correct: 0, hint: "Anzeichen vorhanden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Frage: 'When ___ they going to arrive?'", answers: ["is", "do", "are", "will"], correct: 2, hint: "Mehrzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Satz ist eine Absicht?", answers: ["I play tennis.", "I am going to play tennis.", "I am playing tennis.", "I played tennis."], correct: 1, hint: "Absicht", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        comparatives: [
            { question: "Steigerung von 'tall'?", answers: ["more tall", "taller", "tallest", "taler"], correct: 1, hint: "kurzes Wort: -er", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'big'?", answers: ["biger", "bigger", "more big", "bigest"], correct: 1, hint: "kurzer Vokal: Konsonant verdoppeln", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'interesting'?", answers: ["interestinger", "more interesting", "most interesting", "more interestinger"], correct: 1, hint: "langes Wort: more", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'good'?", answers: ["gooder", "better", "best", "more good"], correct: 1, hint: "Unregelmäßig!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'bad'?", answers: ["badder", "worse", "worst", "more bad"], correct: 1, hint: "Unregelmäßig!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'small'?", answers: ["smaller", "more small", "smallest", "smaler"], correct: 0, hint: "-er", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'difficult'?", answers: ["difficulter", "more difficult", "most difficult", "more difficulter"], correct: 1, hint: "more", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Vergleich: 'She is older ___ me.'", answers: ["as", "then", "than", "so"], correct: 2, hint: "als", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'nice'?", answers: ["nicer", "more nice", "nicest", "niceer"], correct: 0, hint: "Nur ein r anhängen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigerung von 'happy'?", answers: ["happyer", "more happy", "happier", "happyer"], correct: 2, hint: "y wird zu i", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        prepositions: [
            { question: "Wo ist 'in'?", answers: ["auf", "unter", "in/im", "neben"], correct: 2, hint: "Drinnen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo ist 'on'?", answers: ["in", "auf", "hinter", "zwischen"], correct: 1, hint: "Oben drauf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo ist 'under'?", answers: ["über", "neben", "vor", "unter"], correct: 3, hint: "Unten drunter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo ist 'behind'?", answers: ["hinter", "vor", "neben", "an"], correct: 0, hint: "Rückseite", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo ist 'in front of'?", answers: ["neben", "hinter", "an", "vor"], correct: 3, hint: "Vorderseite", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo ist 'next to'?", answers: ["zwischen", "neben", "auf", "unter"], correct: 1, hint: "Seitlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo ist 'between'?", answers: ["an", "neben", "zwischen", "hinter"], correct: 2, hint: "In der Mitte von zwei", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Präposition: 'The book is ___ the table.'", answers: ["in", "on", "at", "behind"], correct: 1, hint: "auf dem Tisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Präposition: 'I am ___ school.'", answers: ["at", "on", "under", "between"], correct: 0, hint: "an der Schule (Ort)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Präposition: 'The cat is ___ the chair.'", answers: ["under", "between", "at", "in"], correct: 0, hint: "unter dem Stuhl", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        pronouns: [
            { question: "Objektpronomen von 'I'?", answers: ["my", "mine", "me", "myself"], correct: 2, hint: "Give ___ the book.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Objektpronomen von 'he'?", answers: ["his", "him", "he", "himself"], correct: 1, hint: "I see ___.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Objektpronomen von 'she'?", answers: ["her", "hers", "she", "herself"], correct: 0, hint: "Listen to ___.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Besitzanzeigendes Pronomen (my/your...) von 'we'?", answers: ["our", "ours", "us", "we"], correct: 0, hint: "This is ___ house.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Besitzanzeigendes Pronomen von 'they'?", answers: ["their", "theirs", "them", "they"], correct: 0, hint: "It is ___ dog.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Objektpronomen von 'we'?", answers: ["our", "us", "we", "ours"], correct: 1, hint: "Help ___.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Objektpronomen von 'they'?", answers: ["their", "them", "they", "theirs"], correct: 1, hint: "I like ___.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passt: '___ am a student.'", answers: ["Me", "My", "I", "Mine"], correct: 2, hint: "Subjektpronomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passt: 'This is ___ pen.' (mein)", answers: ["me", "my", "mine", "I"], correct: 1, hint: "Possessivbegleiter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passt: 'He is talking to ___.' (dir)", answers: ["you", "your", "yours", "yourselves"], correct: 0, hint: "Objektpronomen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};
