// ============================================
// DEUTSCH - LernApp Daten (6. Klasse Realschule Bayern)
// ============================================

const german6rData = {
    name: "Deutsch",
    icon: "📚",
    color: "#ec4899",
    description: "Deutsch üben mit Grammatik und Rechtschreibung",
    
    categories: {
        grammatik: {
            name: "Grammatik",
            icon: "📝",
            color: "#10b981",
            desc: "Satzglieder und Zeitformen"
        },
        rechtschreibung: {
            name: "Rechtschreibung",
            icon: "✍️",
            color: "#f59e0b",
            desc: "Groß/Klein, s-Laute, Dehnung"
        },
        wortarten: {
            name: "Wortarten",
            icon: "🔤",
            color: "#8b5cf6",
            desc: "Nomen, Verben, Adjektive etc."
        },
        satzzeichen: {
            name: "Satzzeichen",
            icon: "❓",
            color: "#3b82f6",
            desc: "Kommasetzung und mehr"
        },
        stilmittel: {
            name: "Stilmittel",
            icon: "🎭",
            color: "#ec4899",
            desc: "Metaphern, Vergleiche, Personifikation"
        }
    },

    // Fragen nach Kategorien
    questions: {
        grammatik: [
            { question: "Was ist ein Synonym für 'schön'?", answers: ["Hässlich", "Hübsch", "Groß", "Klein"], correct: 1, hint: "Ähnliche Bedeutung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort ist ein Verb?", answers: ["Tisch", "Laufen", "Rot", "Schnell"], correct: 1, hint: "Tun-Wort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Subjekt: 'Mein kleiner Bruder schläft.'", answers: ["Mein kleiner Bruder", "schläft", "Bruder", "kleiner"], correct: 0, hint: "Wer oder was?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform ist 'er lachte'?", answers: ["Präsens", "Präteritum", "Perfekt", "Plusquamperfekt"], correct: 1, hint: "Einfache Vergangenheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Prädikat: 'Wir haben heute viel gelacht.'", answers: ["Wir", "haben gelacht", "heute", "viel"], correct: 1, hint: "Was tun sie?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fall ist 'des Lehrers'?", answers: ["Nominativ", "Genitiv", "Dativ", "Akkusativ"], correct: 1, hint: "Wessen?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform ist 'du wirst gehen'?", answers: ["Präsens", "Perfekt", "Futur I", "Futur II"], correct: 2, hint: "Zukunft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bilde das Perfekt von 'singen' (ich).", answers: ["ich singe", "ich sang", "ich habe gesungen", "ich hatte gesungen"], correct: 2, hint: "Hilfsverb + Partizip II", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Dativobjekt: 'Sie schenkt ihrer Mutter Blumen.'", answers: ["Sie", "ihrer Mutter", "Blumen", "schenkt"], correct: 1, hint: "Wem?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Satzglied ist 'in der Schule'?", answers: ["Subjekt", "Prädikat", "Adverbiale Bestimmung des Ortes", "Akkusativobjekt"], correct: 2, hint: "Wo?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Plusquamperfekt von 'ich renne'?", answers: ["ich rannte", "ich bin gerannt", "ich war gerannt", "ich werde rennen"], correct: 2, hint: "Vorvergangenheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Akkusativobjekt: 'Der Junge wirft den Ball.'", answers: ["Der Junge", "wirft", "den Ball", "Junge"], correct: 2, hint: "Wen oder was?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform nutzt man für Erzählungen in Romanen meistens?", answers: ["Präsens", "Präteritum", "Perfekt", "Plusquamperfekt"], correct: 1, hint: "Erzählzeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Hilfsverb braucht 'schwimmen' im Perfekt?", answers: ["haben", "sein", "werden", "können"], correct: 1, hint: "Bewegung von A nach B", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme die Adverbiale der Zeit: 'Morgen fahren wir weg.'", answers: ["Morgen", "fahren", "wir", "weg"], correct: 0, hint: "Wann?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie fragt man nach dem Prädikat?", answers: ["Wer oder was?", "Wessen?", "Was tut das Subjekt?", "Wann?"], correct: 2, hint: "Handlung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die 2. Person Singular Präsens von 'lesen'?", answers: ["ich lese", "du liest", "er liest", "ihr lest"], correct: 1, hint: "Du...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform ist 'er war gewesen'?", answers: ["Präteritum", "Perfekt", "Plusquamperfekt", "Präsens"], correct: 2, hint: "Vorvergangenheit von sein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man die Adverbiale Bestimmung der Art und Weise?", answers: ["Lokaladverbiale", "Temporaladverbiale", "Modaladverbiale", "Kausaladverbiale"], correct: 2, hint: "Wie?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Subjekt: 'Gestern hat es stark geregnet.'", answers: ["Gestern", "es", "stark", "geregnet"], correct: 1, hint: "Wer oder was?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Partizip II von 'sehen'?", answers: ["gesehen", "gesieht", "geseht", "sah"], correct: 0, hint: "ich habe ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fall ist 'die Kinder' (Plural) als Subjekt?", answers: ["Nominativ", "Genitiv", "Dativ", "Akkusativ"], correct: 0, hint: "Wer?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Adverbiale antwortet auf 'Warum?'", answers: ["Lokal", "Temporal", "Kausal", "Modal"], correct: 2, hint: "Grund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bilde das Futur I von 'lernen' (wir).", answers: ["wir lernten", "wir haben gelernt", "wir werden lernen", "wir werden gelernt haben"], correct: 2, hint: "werden + Infinitiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Satzgefüge'?", answers: ["Zwei Hauptsätze", "Hauptsatz und Nebensatz", "Nur ein Hauptsatz", "Nur Nebensätze"], correct: 1, hint: "HS + NS", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Genitivobjekt: 'Wir gedenken der Toten.'", answers: ["Wir", "gedenken", "der Toten", "Toten"], correct: 2, hint: "Wessen?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Zeitformen gibt es im Deutschen?", answers: ["4", "5", "6", "8"], correct: 2, hint: "Präsens bis Futur II", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Prädikat in einem Fragesatz meistens?", answers: ["Am Ende", "An 1. Stelle", "An 2. Stelle", "In der Mitte"], correct: 1, hint: "Verberststellung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme die Wortart von 'weil'?", answers: ["Adverb", "Konjunktion", "Präposition", "Nomen"], correct: 1, hint: "Bindewort für Nebensätze", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie fragt man nach dem Dativobjekt?", answers: ["Wer?", "Wessen?", "Wem?", "Wen?"], correct: 2, hint: "3. Fall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Grundform (Infinitiv) von 'sangst'?", answers: ["singen", "gesungen", "sang", "singst"], correct: 0, hint: "Tunwort im Wörterbuch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform ist 'wir hatten gegessen'?", answers: ["Perfekt", "Plusquamperfekt", "Futur I", "Präteritum"], correct: 1, hint: "hatten + Partizip II", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme die Adverbiale des Ortes: 'Dort oben steht ein Haus.'", answers: ["Dort oben", "steht", "ein Haus", "Haus"], correct: 0, hint: "Wo?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Satz ist eine Satzreihe?", answers: ["Ich lerne, weil ich will.", "Ich lerne und ich lese.", "Lernst du?", "Ich lerne."], correct: 1, hint: "HS + HS", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Aussagesatz'?", answers: ["Frage", "Befehl", "Schilderung eines Sachverhalts", "Wunsch"], correct: 2, hint: "Punkt am Ende", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form ist die 3. Person Plural Präsens von 'laufen'?", answers: ["er läuft", "ihr lauft", "sie laufen", "wir laufen"], correct: 2, hint: "Sie (viele)...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Prädikat: 'Komm schnell her!'", answers: ["Komm her", "schnell", "her", "Komm"], correct: 0, hint: "Zweiteiliges Verb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Stamm von 'lachen'?", answers: ["lach-", "lache-", "-en", "lachen"], correct: 0, hint: "Wort ohne Endung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bilde den Imperativ Singular von 'laufen'.", answers: ["Lauf!", "Lauft!", "Laufen Sie!", "Läufst!"], correct: 0, hint: "Befehl an eine Person", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Vollverb'?", answers: ["haben", "sein", "lernen", "werden"], correct: 2, hint: "Kann allein das Prädikat bilden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Kasus folgt auf 'wegen' meistens?", answers: ["Nominativ", "Genitiv", "Dativ", "Akkusativ"], correct: 1, hint: "Wegen des Regens...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme die Adverbiale der Art und Weise: 'Sie singt wunderschön.'", answers: ["Sie", "singt", "wunderschön", "wunder"], correct: 2, hint: "Wie?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Konjunktion leitet einen Kausalsatz ein?", answers: ["obwohl", "da/weil", "indem", "damit"], correct: 1, hint: "Begründung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Subjekt im Passivsatz: 'Der Apfel wird gegessen.'", answers: ["Der Apfel", "wird", "gegessen", "wird gegessen"], correct: 0, hint: "Wer oder was?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Modalverb'?", answers: ["gehen", "müssen", "sehen", "hören"], correct: 1, hint: "Drückt Möglichkeit/Zwang aus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie bildet man das Futur II (Grobform)?", answers: ["werden + Infinitiv", "werden + Partizip II + haben/sein", "haben + Partizip II", "Präsens"], correct: 1, hint: "Vollendete Zukunft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Satzteil steht im 1. Fall?", answers: ["Subjekt", "Genitivobjekt", "Dativobjekt", "Akkusativobjekt"], correct: 0, hint: "Nominativ", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Satzteil steht im 4. Fall?", answers: ["Subjekt", "Genitivobjekt", "Dativobjekt", "Akkusativobjekt"], correct: 3, hint: "Wen oder was?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Prädikat: 'Ich räume mein Zimmer auf.'", answers: ["Ich", "räume auf", "Zimmer", "mein"], correct: 1, hint: "Satzklammer beachten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform ist 'ich werde gelernt haben'?", answers: ["Futur I", "Futur II", "Perfekt", "Plusquamperfekt"], correct: 1, hint: "Abgeschlossen in Zukunft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Kopula'?", answers: ["Vollverb", "Hilfsverb wie 'sein' oder 'werden'", "Nomen", "Adjektiv"], correct: 1, hint: "Verbindungsverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme das Dativobjekt: 'Wir folgen dem Pfad.'", answers: ["Wir", "folgen", "dem Pfad", "Pfad"], correct: 2, hint: "Wem folgen wir?", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        rechtschreibung: [
            { question: "Wie schreibt man 'Fahrrad' richtig?", answers: ["Farad", "Fahrrad", "Fahrad", "Farrad"], correct: 1, hint: "Fahren + Rad", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann schreibt man 'ss'?", answers: ["Nach langem Vokal", "Nach kurzem Vokal", "Immer am Ende", "Nie"], correct: 1, hint: "Fluss, Schloss", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort schreibt man groß?", answers: ["heute", "laufen", "morgen (der Tag)", "schnell"], correct: 2, hint: "Nomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt die Regel für 'das' oder 'dass'?", answers: ["Immer dass", "Dieses, jenes, welches = das", "Nach Komma immer dass", "Es gibt keine Regel"], correct: 1, hint: "Ersatzprobe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Schifffahrt' heute (nach neuer RS)?", answers: ["Schiffahrt", "Schifffahrt", "Schiff-Fahrt", "Schiff fahrt"], correct: 1, hint: "Drei f", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort ist richtig getrennt?", answers: ["Mu-tter", "Mut-ter", "Mutt-er", "M-utter"], correct: 1, hint: "Zwischen Konsonanten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Dehnungs-h'?", answers: ["h nach kurzem Vokal", "h nach langem Vokal", "h am Wortanfang", "h in 'Hund'"], correct: 1, hint: "Stummer Buchstabe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'viele' richtig?", answers: ["viele", "fiele", "fihle", "viehle"], correct: 0, hint: "Vogel-v", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann schreibt man 'ß'?", answers: ["Nach kurzem Vokal", "Nach Diphthong (ei, au) oder langem Vokal", "Am Wortanfang", "Immer bei Verben"], correct: 1, hint: "Fuß, beißen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort ist richtig?", answers: ["Rhythmus", "Rhytmus", "Rythmus", "Rytmus"], correct: 0, hint: "Schwieriges Fremdwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was kennzeichnet die Schärfung?", answers: ["Doppelter Konsonant", "Dehnungs-h", "Großschreibung", "Punkt am Ende"], correct: 0, hint: "Kurzer Vokal davor", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'darauf' bei Trennung?", answers: ["da-rauf", "dar-auf", "dara-uf", "d-arauf"], correct: 1, hint: "Präfix beachten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort hat ein 'i' statt 'ie'?", answers: ["Liebe", "Maschine", "Lied", "Dieb"], correct: 1, hint: "Ausnahme bei langem i", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wird 'Angst' in 'Angst haben' groß oder klein geschrieben?", answers: ["Groß", "Klein", "Beides möglich", "Nur am Satzanfang"], correct: 0, hint: "Nomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Eis laufen' als Substantivierung?", answers: ["eislaufen", "Eislaufen", "Eis Laufen", "Eis-Laufen"], correct: 1, hint: "Das ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die korrekte Schreibweise?", answers: ["widersehen", "wiedersehen", "wiedersähen", "wider sähn"], correct: 1, hint: "noch einmal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schreibt man 'Anfang' in 'von Anfang an' groß?", answers: ["Ja", "Nein", "Kommt darauf an", "Nur in Bayern"], correct: 0, hint: "Nach Präposition + Artikelprobe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Stopp' richtig?", answers: ["Stop", "Stopp", "Stob", "Stoppe"], correct: 1, hint: "Kurzer Vokal o", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Endung haben Nomen oft?", answers: ["-heit, -keit, -ung", "-ig, -lich, -sam", "-st, -te, -en", "-er, -est"], correct: 0, hint: "Signale für Nomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'V-Wort'?", answers: ["Vogel", "Vase", "Viel", "Alle"], correct: 3, hint: "Wörter mit v", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Gitarre'?", answers: ["Gitarre", "Gitarre", "Gitarre", "Gitarre"], correct: 0, hint: "Doppel-r", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'Getrenntschreibung'?", answers: ["Zwei Wörter", "Ein Wort", "Mit Bindestrich", "Gibt es nicht"], correct: 0, hint: "spazieren gehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Recht haben'?", answers: ["rechthaben", "Recht haben", "recht haben", "Rechthaben"], correct: 1, hint: "Nomen + Verb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann schreibt man 'e' statt 'ä'?", answers: ["Stammwort mit a", "Stammwort mit e", "Immer bei Plural", "Nie"], correct: 1, hint: "Verwandte Wörter suchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort ist richtig?", answers: ["Kemie", "Chemie", "Schemie", "Schämie"], correct: 1, hint: "Fremdwortanfang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'nämlich'?", answers: ["nämlich", "nehmlich", "nämlich", "nemlich"], correct: 0, hint: "Wer nämlich mit h schreibt...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort hat einen Doppelvokal?", answers: ["Saal", "Sahl", "Sal", "Sall"], correct: 0, hint: "Aa", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Silben-h'?", answers: ["Steht zwischen zwei Vokalen", "Am Wortende", "Am Wortanfang", "Gibt es nicht"], correct: 0, hint: "gehen, sehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'vielleicht'?", answers: ["fielleicht", "viel leicht", "vielleicht", "vieleicht"], correct: 2, hint: "viel + leicht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Homonym'?", answers: ["Gleiches Wort, andere Bedeutung", "Gegenteil", "Synonym", "Fremdwort"], correct: 0, hint: "Die Bank (Sitz / Geld)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Hexe'?", answers: ["Hekse", "Hexe", "Heckse", "Hegse"], correct: 1, hint: "mit x", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit 'tz' bei Trennung?", answers: ["t-z", "Bleibt zusammen", "Wird zu z-z", "t fällt weg"], correct: 1, hint: "Ka-tze", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit 'ck' bei Trennung?", answers: ["c-k", "Bleibt zusammen", "Wird zu k-k", "c fällt weg"], correct: 1, hint: "Zu-cker", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'abends' (als Adverb)?", answers: ["Abends", "abends", "Abend's", "a bends"], correct: 1, hint: "Wann?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort ist korrekt?", answers: ["Gallerie", "Galerie", "Galarie", "Gallarie"], correct: 1, hint: "Ein l", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Herzlich'?", answers: ["hertzlich", "herzlich", "herzlich", "härzlich"], correct: 1, hint: "von Herz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schreibt man 'Deutsch' in 'auf Deutsch' groß?", answers: ["Ja", "Nein", "Nur nach Punkt", "Nur als Nomen"], correct: 0, hint: "Substantivierung der Sprache", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Standard'?", answers: ["Standard", "Standart", "Standat", "Standarth"], correct: 0, hint: "mit d am Ende", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches ist richtig?", answers: ["Maschiene", "Maschine", "Maschiene", "Maschine"], correct: 1, hint: "Ausnahme langes i", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'E-Mail'?", answers: ["Email", "E-Mail", "email", "E-mail"], correct: 1, hint: "Duden-Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann schreibt man 'einen' statt 'ein'?", answers: ["Akkusativ maskulin", "Dativ", "Nominativ", "Feminin"], correct: 0, hint: "Ich sehe ... Hund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Zuhause' (als Nomen)?", answers: ["zuhause", "Zuhause", "zu Hause", "Beide (B und C)"], correct: 3, hint: "Substantiv oder Fügung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die korrekte Form?", answers: ["Gauckler", "Gaukler", "Gauckeler", "Gauckler"], correct: 1, hint: "ohne c", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort hat ein Doppel-s?", answers: ["Ku-", "Fla-", "Flu-", "Schlo-"], correct: 3, hint: "Schloss", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Interesse'?", answers: ["Interesse", "Interresse", "Interresse", "Intresse"], correct: 0, hint: "ein r", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Voraus'?", answers: ["Vorraus", "Voraus", "Vohrhaus", "Vor aus"], correct: 1, hint: "ein r", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Wort ist richtig?", answers: ["Packet", "Paket", "Packett", "Pakeet"], correct: 1, hint: "ohne c", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Brillant'?", answers: ["Brilliant", "Brillant", "Briliant", "Briljant"], correct: 1, hint: "ohne i nach dem l", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Schreibung von 'Müsli'?", answers: ["Mühsli", "Müesli", "Müsli", "Müssli"], correct: 2, hint: "mit ü", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie schreibt man 'Adresse'?", answers: ["Adresse", "Addresse", "Addresse", "Adreße"], correct: 0, hint: "ein d", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        wortarten: [
            { question: "Welche Wortart ist 'Haus'?", answers: ["Verb", "Nomen", "Adjektiv", "Artikel"], correct: 1, hint: "Namenwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'rennen'?", answers: ["Nomen", "Verb", "Adjektiv", "Pronomen"], correct: 1, hint: "Tunwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'grün'?", answers: ["Nomen", "Verb", "Adjektiv", "Präposition"], correct: 2, hint: "Eigenschaftswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'ich'?", answers: ["Artikel", "Verb", "Personalpronomen", "Konjunktion"], correct: 2, hint: "Fürwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'auf'?", answers: ["Nomen", "Präposition", "Adjektiv", "Verb"], correct: 1, hint: "Verhältniswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'und'?", answers: ["Konjunktion", "Interjektion", "Adverb", "Numerale"], correct: 0, hint: "Bindewort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'unbestimmter Artikel'?", answers: ["der", "die", "ein", "das"], correct: 2, hint: "Einer von vielen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'bestimmter Artikel'?", answers: ["eine", "der", "man", "jemand"], correct: 1, hint: "Genau dieser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'heute'?", answers: ["Nomen", "Adverb", "Adjektiv", "Konjunktion"], correct: 1, hint: "Umstandswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'drei'?", answers: ["Adjektiv", "Numerale", "Nomen", "Verb"], correct: 1, hint: "Zahlwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Abstraktum'?", answers: ["Anfassbares Nomen", "Nicht sichtbares Nomen (Gefühl/Idee)", "Verb", "Adjektiv"], correct: 1, hint: "Liebe, Glück, Zeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Konkretum'?", answers: ["Anfassbares Nomen", "Gefühl", "Verb", "Pronomen"], correct: 0, hint: "Tisch, Baum, Hund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart beschreibt Nomen näher?", answers: ["Verb", "Adjektiv", "Artikel", "Adverb"], correct: 1, hint: "Wie ist etwas?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man Verben, die ein Hilfsverb brauchen?", answers: ["Vollverben", "Hilfsverben", "Modalverben", "Starke Verben"], correct: 1, hint: "haben, sein, werden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'mein'?", answers: ["Personalpronomen", "Possessivpronomen", "Relativpronomen", "Demonstrativpronomen"], correct: 1, hint: "besitzanzeigend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'dieser'?", answers: ["Personalpronomen", "Demonstrativpronomen", "Indefinitpronomen", "Interrogativpronomen"], correct: 1, hint: "hinweisend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'jemand'?", answers: ["Personalpronomen", "Indefinitpronomen", "Relativpronomen", "Possessivpronomen"], correct: 1, hint: "unbestimmt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'wer?'", answers: ["Personalpronomen", "Interrogativpronomen", "Relativpronomen", "Indefinitpronomen"], correct: 1, hint: "fragend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'welcher' in 'der Mann, welcher...'?", answers: ["Personalpronomen", "Relativpronomen", "Demonstrativpronomen", "Possessivpronomen"], correct: 1, hint: "beziehend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was sind 'Partikeln'?", answers: ["Veränderbare Wörter", "Unveränderbare Wörter", "Nomen", "Verben"], correct: 1, hint: "Präpositionen, Konjunktionen etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'Aua!'?", answers: ["Konjunktion", "Interjektion", "Adverb", "Präposition"], correct: 1, hint: "Ausrufewort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'sehr'?", answers: ["Gradadverb", "Lokaladverb", "Temporaladverb", "Modaladverb"], correct: 0, hint: "Verstärkung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Eigenname'?", answers: ["Baum", "München", "laufen", "schön"], correct: 1, hint: "Spezifischer Name", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man die Beugung von Nomen?", answers: ["Konjugation", "Deklination", "Steigerung", "Komparation"], correct: 1, hint: "In Fälle setzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man die Beugung von Verben?", answers: ["Deklination", "Konjugation", "Komparation", "Flexion"], correct: 1, hint: "In Personen setzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der 'Positiv' bei Adjektiven?", answers: ["Grundstufe", "1. Steigerung", "2. Steigerung", "Gegenteil"], correct: 0, hint: "schnell", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der 'Komparativ'?", answers: ["Grundstufe", "1. Steigerungsstufe", "Höchststufe", "Gegenteil"], correct: 1, hint: "schneller", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der 'Superlativ'?", answers: ["Grundstufe", "1. Steigerung", "Höchststufe", "Vergleich"], correct: 2, hint: "am schnellsten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Zusammengesetztes Nomen'?", answers: ["Kompositum", "Derivat", "Simplex", "Präfix"], correct: 0, hint: "Haustür", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'vielleicht'?", answers: ["Nomen", "Adverb", "Adjektiv", "Verb"], correct: 1, hint: "Umstandswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Suffix'?", answers: ["Vorsilbe", "Nachsilbe", "Wortstamm", "Endung"], correct: 1, hint: "-heit, -ung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Präfix'?", answers: ["Vorsilbe", "Nachsilbe", "Wortstamm", "Endung"], correct: 0, hint: "be-, ver-", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'doch'?", answers: ["Modalpartikel", "Nomen", "Verb", "Artikel"], correct: 0, hint: "Füllwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Singularetantum'?", answers: ["Wort nur im Singular", "Wort nur im Plural", "Wort ohne Fälle", "Unregelmäßiges Wort"], correct: 0, hint: "Durst, Milch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Pluraletantum'?", answers: ["Wort nur im Singular", "Wort nur im Plural", "Zahlwort", "Adjektiv"], correct: 1, hint: "Ferien, Eltern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'weil'?", answers: ["Nebenordnende Konjunktion", "Unterordnende Konjunktion", "Adverb", "Präposition"], correct: 1, hint: "Leitet Nebensätze ein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'und'?", answers: ["Nebenordnende Konjunktion", "Unterordnende Konjunktion", "Pronomen", "Artikel"], correct: 0, hint: "Verbindet Gleichwertiges", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'reflexives Pronomen'?", answers: ["ich", "mein", "sich", "dieser"], correct: 2, hint: "rückbezüglich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'genug'?", answers: ["Indefinitpronomen", "Adverb", "Numerale", "Konjunktion"], correct: 1, hint: "Mengenangabe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Funktion von Adjektiven?", answers: ["Benennen von Dingen", "Beschreiben von Eigenschaften", "Ausdrücken von Handlungen", "Verbinden von Sätzen"], correct: 1, hint: "Wie-Wörter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Funktion von Verben?", answers: ["Beschreiben", "Handlungen/Zustände ausdrücken", "Benennen", "Begleiten"], correct: 1, hint: "Tun-Wörter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'hinter'?", answers: ["Präposition", "Nomen", "Verb", "Artikel"], correct: 0, hint: "Verhältniswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'oh!'?", answers: ["Interjektion", "Konjunktion", "Adverb", "Pronomen"], correct: 0, hint: "Empfindungswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'man'?", answers: ["Personalpronomen", "Indefinitpronomen", "Relativpronomen", "Nomen"], correct: 1, hint: "unbestimmte Person", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Kollektivum'?", answers: ["Sammelname (z.B. Herde)", "Einzelname", "Verb", "Adjektiv"], correct: 0, hint: "Vielzahl als Einheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'dessen'?", answers: ["Relativpronomen", "Personalpronomen", "Interrogativpronomen", "Indefinitpronomen"], correct: 0, hint: "beziehend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'morgen' (Zeitpunkt)?", answers: ["Nomen", "Adverb", "Adjektiv", "Verb"], correct: 1, hint: "Temporaladverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'erstens'?", answers: ["Ordinalzahl", "Adverb", "Numerale", "Konjunktion"], correct: 1, hint: "Ordnungsadverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Wortart ist 'beide'?", answers: ["Numerale", "Adjektiv", "Nomen", "Pronomen"], correct: 0, hint: "Zahlwort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 'Flexion'?", answers: ["Wortbildung", "Beugung von Wörtern", "Satzbau", "Rechtschreibung"], correct: 1, hint: "Überbegriff für Dekl. & Konj.", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        satzzeichen: [
            { question: "Wo setzt man ein Komma?", answers: ["Vor 'und'", "Bei Aufzählungen", "Am Satzanfang", "Nach jedem Wort"], correct: 1, hint: "Äpfel, Birnen...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Zeichen steht vor der wörtlichen Rede?", answers: ["Punkt", "Ausrufezeichen", "Doppelpunkt", "Fragezeichen"], correct: 2, hint: "Er sagte: ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Satzzeichen beendet einen Fragesatz?", answers: [".", "!", "?", ","], correct: 2, hint: "Interrogativzeichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann setzt man ein Komma bei 'und'?", answers: ["Immer", "Nie", "Bei einem neuen Hauptsatz (optional)", "Nur bei Nomen"], correct: 2, hint: "Satzreihe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo stehen die Anführungszeichen am Ende der Rede?", answers: ["Unten", "Oben", "In der Mitte", "Gar nicht"], correct: 1, hint: "Gänsefüßchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was trennt das Komma in einem Satzgefüge?", answers: ["Zwei Hauptsätze", "Hauptsatz und Nebensatz", "Zwei Wörter", "Nomen und Verb"], correct: 1, hint: "Struktur", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Zeichen nutzt man für Einschübe?", answers: ["Punkt", "Gedankenstrich", "Ausrufezeichen", "Fragezeichen"], correct: 1, hint: "Pause im Satz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann setzt man ein Komma vor 'aber'?", answers: ["Immer", "Nie", "Nur am Satzanfang", "Bei Aufzählungen"], correct: 0, hint: "Gegensatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Setzt man ein Komma vor 'weil'?", answers: ["Ja", "Nein", "Nur manchmal", "Nur bei Fragen"], correct: 0, hint: "Nebensatzeinleitung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Zeichen steht am Ende eines Befehls?", answers: [".", "?", "!", ":"], correct: 2, hint: "Ausrufezeichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man das Zeichen ';'?", answers: ["Doppelpunkt", "Semikolon", "Komma", "Apostroph"], correct: 1, hint: "Strichpunkt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo setzt man den Apostroph?", answers: ["Bei Auslassungen (z.B. Wie's geht)", "Bei jedem s", "Bei jedem Namen", "Nie"], correct: 0, hint: "Auslassungszeichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann wird ein Doppelpunkt noch verwendet?", answers: ["Vor Aufzählungen", "Nach jedem Komma", "Vor dem Subjekt", "Am Satzende"], correct: 0, hint: "Ankündigung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Setzt man ein Komma vor 'dass'?", answers: ["Ja", "Nein", "Nur nach Verben", "Nur bei Nomen"], correct: 0, hint: "Bindewort für Nebensatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Funktion des Punktes?", answers: ["Frage markieren", "Satz beenden", "Wort trennen", "Satz verbinden"], correct: 1, hint: "Satzendezeichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie setzt man Anführungszeichen am Anfang der wörtlichen Rede?", answers: ["Oben", "Unten", "Rechts", "Links"], correct: 1, hint: "In Deutschland", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Zeichen trennt Telefonvorwahl und Nummer oft?", answers: ["/", "-", ".", ":"], correct: 1, hint: "Bindestrich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Setzt man ein Komma bei 'sowohl ... als auch'?", answers: ["Ja", "Nein", "Nur bei Nomen", "Immer"], correct: 1, hint: "Mehrteilige Konjunktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Setzt man ein Komma bei 'entweder ... oder'?", answers: ["Ja", "Nein", "Nur bei Verben", "Immer"], correct: 1, hint: "Alternative ohne Komma", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was steht nach dem Begleitsatz 'Er fragte:'?", answers: ["Anführungszeichen oben", "Anführungszeichen unten", "Kein Zeichen", "Punkt"], correct: 1, hint: "Beginn der Rede", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        stilmittel: [
            { question: "Was ist eine 'Metapher'?", answers: ["Bildhafter Vergleich ohne 'wie'", "Wortwiederholung", "Vermenschlichung", "Gegensatz"], correct: 0, hint: "Rabeneltern, Mauer des Schweigens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Vergleich'?", answers: ["Wortwiederholung", "Verknüpfung mit 'wie' oder 'als'", "Übertreibung", "Satzende"], correct: 1, hint: "Stark wie ein Löwe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Personifikation'?", answers: ["Ein Mensch wird zum Tier", "Sachen/Tiere handeln wie Menschen", "Ein Reim", "Eine Frage"], correct: 1, hint: "Die Sonne lacht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Alliteration'?", answers: ["Gleicher Anlaut benachbarter Wörter", "Gleicher Endreim", "Gleicher Rhythmus", "Gleiche Wortart"], correct: 0, hint: "Milch macht müde Männer munter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Hyperbel'?", answers: ["Untertreibung", "Starke Übertreibung", "Wiederholung", "Vergleich"], correct: 1, hint: "Ein Meer von Tränen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Symbol'?", answers: ["Ein Satz", "Ein Zeichen mit tieferer Bedeutung", "Ein Verb", "Ein Punkt"], correct: 1, hint: "Herz für Liebe, Taube für Friede", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Lautmalerei' (Onomatopoesie)?", answers: ["Musik im Text", "Nachahmung von Geräuschen", "Bunte Buchstaben", "Reime"], correct: 1, hint: "Kuckuck, rums, zisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Anapher'?", answers: ["Wiederholung am Satzanfang", "Wiederholung am Satzende", "Gegensatz", "Frage"], correct: 0, hint: "Wiederholung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'rhetorische Frage'?", answers: ["Frage ohne erwartete Antwort", "Sehr schwere Frage", "Höfliche Frage", "Wissenschaftliche Frage"], correct: 0, hint: "Wer glaubt das schon?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Ironie'?", answers: ["Lüge", "Gegenteil des Gemeinten sagen", "Witz", "Ernsthafte Aussage"], correct: 1, hint: "Das hast du ja toll gemacht! (wenn etwas kaputt ist)", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        bedeutung: [
            { question: "Was ist ein 'Antonym'?", answers: ["Gleiches Wort", "Gegenteil", "Ähnliches Wort", "Zusammengesetztes Wort"], correct: 1, hint: "groß - klein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Synonym'?", answers: ["Gegenteil", "Wort mit ähnlicher Bedeutung", "Fremdwort", "Satzglied"], correct: 1, hint: "gehen - laufen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Wortfeld'?", answers: ["Wörter mit gleichem Stamm", "Wörter mit ähnlicher Bedeutung zu einem Thema", "Wörter in einem Feld", "Alphabetische Liste"], correct: 1, hint: "Sagen: flüstern, rufen, schreien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Wortfamilie'?", answers: ["Wörter mit gleichem Wortstamm", "Wörter im selben Satz", "Nomen und Verben", "Synonyme"], correct: 0, hint: "fahren: Fahrer, Fahrt, Abfahrt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'objektiv'?", answers: ["Voreingenommen", "Sachlich/Neutral", "Persönlich", "Falsch"], correct: 1, hint: "unparteiisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'subjektiv'?", answers: ["Sachlich", "Persönlich gefärbt", "Wahr", "Gerecht"], correct: 1, hint: "eigene Meinung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Lehnwort'?", answers: ["Geliehenes Wort aus anderer Sprache", "Altes deutsches Wort", "Erfundenes Wort", "Verb"], correct: 0, hint: "Computer, Pizza", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chronologisch'?", answers: ["Alphabetisch", "Nach zeitlicher Reihenfolge", "Nach Wichtigkeit", "Zufällig"], correct: 1, hint: "Zeitstrahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Redewendung'?", answers: ["Ein Gesetz", "Feste Wortverbindung mit übertragener Bedeutung", "Ein langer Satz", "Eine Frage"], correct: 1, hint: "Jemanden einen Bären aufbinden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'präzise'?", answers: ["Ungenau", "Genau/Exakt", "Viel", "Wenig"], correct: 1, hint: "punktgenau", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};
