// ============================================
// LATEIN - LernApp Daten (8. Klasse Gymnasium Bayern)
// ============================================
const lat8gData = {
    name: "Latein (8G)",
    icon: "🏛️",
    color: "#8b5cf6",
    description: "Latein 8. Klasse Gymnasium - Grammatik, Vokabeln und römische Kultur",
    categories: {
        grammatik: { name: "Grammatik", icon: "📜", color: "#f59e0b", desc: "AcI, PC, AblAbs und Konjunktive" },
        vokabeln: { name: "Vokabeln", icon: "📖", color: "#3b82f6", desc: "Wortschatz Erweiterung" },
        geschichte: { name: "Röm. Geschichte", icon: "⚔️", color: "#ef4444", desc: "Von Hannibal bis Augustus" },
        kultur: { name: "Alltag & Staat", icon: "🏛️", color: "#8b5cf6", desc: "Ämter, Sklaven und Götter" }
    },
    questions: {
        grammatik: [ { question: "Was bedeutet 'AcI'?", answers: ["Akkusativ mit Infinitiv", "Ablativ mit Infinitiv", "Akkusativ mit Imperativ", "Adverb mit Infinitiv"], correct: 0, hint: "Subjektsakkusativ", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Endung hat ein PPP im Nominativ Maskulin?", answers: ["-ans", "-us", "-ur", "-um"], correct: 1, hint: "Partizip Perfekt Passiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie übersetzt man einen AcI oft im Deutschen?", answers: ["Mit einem 'dass'-Satz", "Mit 'weil'", "Gar nicht", "Mit einem Relativsatz"], correct: 0, hint: "Audio Marcum venire - Ich höre, dass...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein PC (Participium Coniunctum)?", answers: ["Computer von Caesar", "Verbundenes Partizip", "Passiv-Zukunft", "Ein Fall"], correct: 1, hint: "Bezieht sich auf ein Substantiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fall ist 'urbis'?", answers: ["Nominativ", "Genitiv Singular", "Dativ", "Akkusativ Plural"], correct: 1, hint: "3. Deklination", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet die Endung '-ba-'?", answers: ["Präsens", "Imperfekt", "Perfekt", "Futur"], correct: 1, hint: "Kennzeichen der Vergangenheit (Dauer)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Endung der 1. Person Plural (wir)?", answers: ["-o", "-s", "-t", "-mus"], correct: 3, hint: "Konjugation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vince-re'?", answers: ["siegen", "besiegen", "kommen", "sehen"], correct: 1, hint: "Infinitive Präsens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Konjugation ist 'amare'?", answers: ["a-Konjugation", "e-Konjugation", "i-Konjugation", "Konsonantisch"], correct: 0, hint: "Vokal vor -re", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet '-isse-' in einer Verbform?", answers: ["Perfekt", "Plusquamperfekt (Konj.)", "Präsens", "Futur II"], correct: 1, hint: "Zeitform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Imperativ?", answers: ["Eine Frage", "Ein Befehl", "Ein Wunsch", "Eine Verneinung"], correct: 1, hint: "Veni! Veni!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fall folgt oft auf 'in' (wo?)?", answers: ["Akkusativ", "Ablativ", "Genitiv", "Dativ"], correct: 1, hint: "Frage: Wo?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fall folgt auf 'in' (wohin?)?", answers: ["Akkusativ", "Ablativ", "Genitiv", "Dativ"], correct: 0, hint: "Frage: Wohin?", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Vokativ'?", answers: ["Fall zum Rufen/Ansprechen", "Ein Zeitwort", "Eine Vorsilbe", "Ein Passiv"], correct: 0, hint: "Et tu, Brute!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Endung hat der Dativ Singular der o-Deklination?", answers: ["-is", "-o", "-um", "-i"], correct: 1, hint: "servo, domino", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'posse'?", answers: ["trinken", "können", "wollen", "eilen"], correct: 1, hint: "Unregelmäßiges Verb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die 3. Stammform von 'venire'?", answers: ["venio", "veni", "ventum", "venit"], correct: 1, hint: "Perfektstamm", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'Passiv'?", answers: ["Subjekt handelt selbst", "Mit dem Subjekt geschieht etwas", "Vergangenheit", "Zukunft"], correct: 1, hint: "Leideform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Endung der 1. Pers. Sing. Passiv?", answers: ["-o", "-or", "-m", "-r"], correct: 1, hint: "amor = ich werde geliebt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Relativpronomen?", answers: ["ich, du, er", "der, die, das (welcher)", "mein, dein", "dieser, jene"], correct: 1, hint: "qui, quae, quod", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cum' mit Ablativ?", answers: ["während", "als", "mit", "weil"], correct: 2, hint: "Präposition", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vobis'?", answers: ["uns", "euch", "ihnen", "sich"], correct: 1, hint: "Personalpronomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein PPA?", answers: ["Partizip Präsens Aktiv", "Passiv-Agent", "Plural-Art", "Präsens-Amt"], correct: 0, hint: "Endung -ns, -ntis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie übersetzt man ein PPP?", answers: ["-end", "ge- ... -t", "wird ... werden", "muss ..."], correct: 1, hint: "Beispiel: amatus - geliebt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Zeitform ist 'amavi'?", answers: ["Präsens", "Imperfekt", "Perfekt", "Plusquamperfekt"], correct: 2, hint: "v-Perfekt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Übersetze den AcI: 'Dico te errare.'", answers: ["Ich sage, dass du dich irrst.", "Du sagst, dass ich mich irre.", "Ich sage dir den Irrtum.", "Spreche ich von Fehlern?"], correct: 0, hint: "Subjektsakkusativ 'te'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Zeitverhältnis beim Infinitiv Perfekt im AcI?", answers: ["Gleichzeitigkeit", "Vorzeitigkeit", "Nachzeitigkeit", "Gibt es nicht"], correct: 1, hint: "Handlung geschah davor", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Ablativus Absolutus'?", answers: ["Losgelöster Ablativ", "Falscher Ablativ", "Verbundener Ablativ", "Fragefall"], correct: 0, hint: "Satzwertige Konstruktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'malle'?", answers: ["schlecht sein", "lieber wollen", "nicht wollen", "wollen"], correct: 1, hint: "magis + velle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Endung kennzeichnet den Konjunktiv Imperfekt?", answers: ["-ba-", "-eri-", "-re- + Personalendung", "-isse-"], correct: 2, hint: "Infinitiv + m,s,t...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Deponens'?", answers: ["Passivische Form, aktive Bedeutung", "Aktivische Form, passivische Bedeutung", "Wort ohne Endung", "Ein Adjektiv"], correct: 0, hint: "loqui, hortari", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie übersetzt man 'cum' mit Konjunktiv oft?", answers: ["mit", "als/da/obwohl", "wenn/sobald", "und"], correct: 1, hint: "Cum narrativum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'noli me tangere'?", answers: ["Rühr mich nicht an!", "Lauf nicht weg!", "Hör mir nicht zu!", "Sieh mich nicht an!"], correct: 0, hint: "Verneinter Imperativ", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fall ist 'diei'?", answers: ["Nominativ Plural", "Genitiv/Dativ Singular (e-Dekl.)", "Akkusativ", "Vokativ"], correct: 1, hint: "dies, diei", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der 'Genitivus partitivus'?", answers: ["Besitz", "Teil eines Ganzen (z.B. multi eorum)", "Eigenschaft", "Zweck"], correct: 1, hint: "ein Teil von...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'oportet'?", answers: ["man darf", "es ist nötig/gehört sich", "es ist erlaubt", "man kann"], correct: 1, hint: "Unpersönlicher Ausdruck", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt das Futur I von 'esse' (3. Pers. Sing.)?", answers: ["est", "erat", "erit", "fuit"], correct: 2, hint: "er/sie/es wird sein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das PPP von 'facere'?", answers: ["facitus", "factus", "faciendus", "fecit"], correct: 1, hint: "getan, gemacht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Bedeutung hat 'ut' mit Konjunktiv im Finalsatz?", answers: ["wie", "dass/damit", "obwohl", "als"], correct: 1, hint: "Absicht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Gerundivum' mit 'esse'?", answers: ["Vergangenheit", "Notwendigkeit (müssen)", "Möglichkeit", "Wunsch"], correct: 1, hint: "Hoc faciendum est", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Endung hat der Ablativ Singular bei der u-Deklination (Mask.)?", answers: ["-o", "-u", "-i", "-e"], correct: 1, hint: "manus, portus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ne' am Satzanfang eines Hauptsatzes mit Konjunktiv?", answers: ["nicht", "damit nicht", "vielleicht", "wirklich"], correct: 0, hint: "Verneinung eines Wunsches/Befehls", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie erkennt man einen PFA (Partizip Futur Aktiv)?", answers: ["-nd-", "-nt-", "-tur-", "-iss-"], correct: 2, hint: "venturus - einer, der kommen wird", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Stamm von 'corporis'?", answers: ["corp-", "corpo-", "corpor-", "corps-"], correct: 2, hint: "Genitivendung abziehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hic, haec, hoc'?", answers: ["dieser, diese, dieses", "jener, jene, jenes", "derjenige", "selbst"], correct: 0, hint: "Demonstrativpronomen (nah)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Dativus finalis'?", answers: ["Besitz", "Zweck/Wirkung (z.B. auxilio venire)", "Ort", "Begleiter"], correct: 1, hint: "dienen zu...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Kennzeichen des Konjunktiv Präsens bei der a-Konjugation?", answers: ["-a-", "-e-", "-i-", "-u-"], correct: 1, hint: "am-e-m", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'velle'?", answers: ["nicht wollen", "lieber wollen", "wollen", "können"], correct: 2, hint: "unregelmäßig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der Genitiv von 'is' (er)?", answers: ["eum", "ei", "eius", "eo"], correct: 2, hint: "dessen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'interea'?", answers: ["inzwischen", "unterdessen", "beides ist richtig", "vorher"], correct: 2, hint: "Adverb der Zeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Nominativ Singular von 'amicus'?", answers: ["amici", "amicum", "amicus", "amico"], correct: 2, hint: "Grundform", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Konjugation hat 'amare'?", answers: ["a-Konjugation", "e-Konjugation", "i-Konjugation", "konsonantische Konjugation"], correct: 0, hint: "Endet auf -are", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt 'sein' auf Latein?", answers: ["esse", "amare", "habere", "videre"], correct: 0, hint: "Wichtigstes Verb", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        vokabeln: [ { question: "Was bedeutet 'amicus'?", answers: ["Feind", "Bruder", "Freund", "Vater"], correct: 2, hint: "Gegenteil von inimicus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bellum'?", answers: ["schön", "Krieg", "Glocke", "Hund"], correct: 1, hint: "Gegenteil von pax", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pax'?", answers: ["Packung", "Friede", "Krieg", "Stadt"], correct: 1, hint: "Pax Romana", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'urbs'?", answers: ["Dorf", "Land", "Stadt (Rom)", "Welt"], correct: 2, hint: "urban", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hostis'?", answers: ["Gast", "Wirt", "Feind", "Heer"], correct: 2, hint: "feindlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'imperator'?", answers: ["Bauer", "Feldherr/Kaiser", "Sklave", "Händler"], correct: 1, hint: "Befehlshaber", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'videre'?", answers: ["siegen", "sehen", "leben", "geben"], correct: 1, hint: "Video", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'venire'?", answers: ["verkaufen", "kommen", "winden", "gewinnen"], correct: 1, hint: "Veni, vidi, vici", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'magnus'?", answers: ["klein", "groß", "stark", "schlecht"], correct: 1, hint: "Magnum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'multis'?", answers: ["viel", "wenig", "alle", "keine"], correct: 0, hint: "Multiple Choice", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'homo'?", answers: ["Gott", "Mensch", "Haus", "Wald"], correct: 1, hint: "Homo sapiens", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'deus'?", answers: ["Mensch", "Gott", "Himmel", "Erde"], correct: 1, hint: "Gottheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'aqua'?", answers: ["Feuer", "Erde", "Wasser", "Luft"], correct: 2, hint: "Aquarium", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ignis'?", answers: ["Wasser", "Eis", "Feuer", "Licht"], correct: 2, hint: "Ignition", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'liber'?", answers: ["Sklave", "frei (oder: Buch)", "gefangen", "tot"], correct: 1, hint: "Liberty", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'servus'?", answers: ["Herr", "Sklave/Diener", "Freund", "König"], correct: 1, hint: "Service", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'regere'?", answers: ["schreiben", "lenken/regieren", "laufen", "schlafen"], correct: 1, hint: "Regierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'nomen'?", answers: ["Zahl", "Name", "Satz", "Wort"], correct: 1, hint: "Nominativ", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'audire'?", answers: ["sehen", "hören", "fühlen", "schmecken"], correct: 1, hint: "Audio", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tempus'?", answers: ["Ort", "Zeit", "Wetter", "Sturm"], correct: 1, hint: "Tempo", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'scire'?", answers: ["glauben", "wissen", "hoffen", "fürchten"], correct: 1, hint: "Science", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mittere'?", answers: ["nehmen", "schicken", "bleiben", "gehen"], correct: 1, hint: "Mission", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'capere'?", answers: ["lassen", "fangen/fassen/nehmen", "töten", "lieben"], correct: 1, hint: "kapern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mors'?", answers: ["Leben", "Tod", "Geburt", "Krankheit"], correct: 1, hint: "mortal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'periculum'?", answers: ["Sicherheit", "Gefahr", "Weg", "Abenteuer"], correct: 1, hint: "gefährlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'solere'?", answers: ["gewohnt sein", "verlassen", "allein sein", "scheinen"], correct: 0, hint: "Semi-Deponens im Perfekt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fieri'?", answers: ["machen", "gemacht werden / geschehen / werden", "fliehen", "vertrauen"], correct: 1, hint: "Passiv zu facere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vincire' (nicht vincere!)?", answers: ["siegen", "fesseln", "kommen", "leben"], correct: 1, hint: "i-Konjugation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gens'?", answers: ["Geist", "Volk / Stamm / Geschlecht", "Knie", "Garten"], correct: 1, hint: "Genitiv: gentis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'adhuc'?", answers: ["hierher", "bis jetzt / noch", "von dort", "damals"], correct: 1, hint: "Adverb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was heißt 'amicus' auf Deutsch?", answers: ["Feind", "Bruder", "Freund", "Vater"], correct: 2, hint: "Guter Kumpel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was heißt 'puella' auf Deutsch?", answers: ["Junge", "Mädchen", "Frau", "Lehrerin"], correct: 1, hint: "Das Mädchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was heißt 'pater' auf Deutsch?", answers: ["Mutter", "Sohn", "Bruder", "Vater"], correct: 3, hint: "Das Familienoberhaupt", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        geschichte: [ { question: "Wer gründete Rom laut Sage?", answers: ["Caesar", "Romulus & Remus", "Augustus", "Nero"], correct: 1, hint: "Wölfin", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann wurde Rom angeblich gegründet?", answers: ["500 v. Chr.", "753 v. Chr.", "100 n. Chr.", "476 n. Chr."], correct: 1, hint: "7-5-3 Rom schlüpft aus dem Ei", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Gegen wen kämpfte Rom in den Punischen Kriegen?", answers: ["Griechen", "Karthager (Hannibal)", "Gallier", "Ägypter"], correct: 1, hint: "Elefanten über die Alpen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'SPQR'?", answers: ["Rom ist super", "Senat und Volk von Rom", "Caesar ist König", "Gesetz des Staates"], correct: 1, hint: "Senatus Populusque Romanus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer wurde an den Iden des März ermordet?", answers: ["Nero", "Augustus", "Julius Caesar", "Cicero"], correct: 2, hint: "Diktator auf Lebenszeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war der 'Limes'?", answers: ["Ein Getränk", "Grenzwall gegen Germanen", "Ein Marktplatz", "Ein Tempel"], correct: 1, hint: "Schutzwall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie hieß der erste echte Kaiser?", answers: ["Caesar", "Augustus", "Tiberius", "Trajan"], correct: 1, hint: "Prinzipat", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Kolosseum?", answers: ["Ein Bad", "Ein Amphitheater", "Ein Palast", "Ein Rathaus"], correct: 1, hint: "Gladiatorenkämpfe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passierte 476 n. Chr.?", answers: ["Gründung Roms", "Untergang Westroms", "Bau der Mauer", "Geburt Jesu"], correct: 1, hint: "Ende der Antike", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Forum'?", answers: ["Ein Garten", "Markt- und Versammlungsplatz", "Ein Gefängnis", "Ein Schiff"], correct: 1, hint: "Zentrum der Stadt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war Hannibal?", answers: ["Römischer Konsul", "Karthagischer Feldherr", "Griechischer Dichter", "Sklavenanführer"], correct: 1, hint: "Antagonist Roms", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Triumphzug'?", answers: ["Eine Beerdigung", "Ehrenzug für siegreiche Feldherren", "Ein Markttag", "Ein Marathon"], correct: 1, hint: "Durch den Triumphbogen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie hießen die einfachen Bürger Roms?", answers: ["Patrizier", "Plebejer", "Sklaven", "Senatoren"], correct: 1, hint: "Die Mehrheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war Spartacus?", answers: ["Kaiser", "Anführer eines Sklavenaufstands", "Philosoph", "Dichter"], correct: 1, hint: "Gladiator", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Aquädukt'?", answers: ["Brücke", "Wasserleitung", "Abwasserkanal", "Kriegsschiff"], correct: 1, hint: "Transportiert Frischwasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war der 'Senat'?", answers: ["Eine Sportstätte", "Rat der Ältesten (Adligen)", "Ein Theater", "Ein Heerlager"], correct: 1, hint: "Machtzentrum der Republik", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'Pax Romana'?", answers: ["Römischer Krieg", "Römischer Friede", "Römische Straße", "Römische Steuer"], correct: 1, hint: "Lange Friedenszeit unter Augustus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer waren die Patrizier?", answers: ["Arme Bauern", "Der römische Adel", "Fremde Händler", "Befreite Sklaven"], correct: 1, hint: "Die Oberschicht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fluss fließt durch Rom?", answers: ["Donau", "Tiber", "Rhein", "Nil"], correct: 1, hint: "Italien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Konsul?", answers: ["Höchster Beamter der Republik", "Ein Priester", "Ein Lehrer", "Ein Sklave"], correct: 0, hint: "Zwei wurden jährlich gewählt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was geschah im Jahr 44 v. Chr.?", answers: ["Gründung Roms", "Ermordung Caesars", "Vesuvausbruch", "Christentum wird Staatsreligion"], correct: 1, hint: "Iden des März", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie hieß die Provinz, die Caesar eroberte?", answers: ["Britannien", "Gallien (heute Frankreich)", "Ägypten", "Griechenland"], correct: 1, hint: "Asterix...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war eine 'Legion'?", answers: ["Ein Schiff", "Eine militärische Einheit (ca. 5000 Mann)", "Ein Festessen", "Ein Tempelbau"], correct: 1, hint: "Römisches Heer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Veto?", answers: ["Ein Segen", "'Ich verbiete' (Einspruchsrecht)", "Ein Opfer", "Ein Tanz"], correct: 1, hint: "Recht der Volkstribune", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war das 'Zwölftafelgesetz'?", answers: ["Ein Kochbuch", "Erste schriftliche Gesetze Roms", "Ein Menü", "Ein Kalender"], correct: 1, hint: "Rechtssicherheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war der erste Kaiser von Rom?", answers: ["Augustus", "Caesar", "Nero", "Trajan"], correct: 0, hint: "Adoptivsohn Caesars", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war der 'Senat'?", answers: ["Ein Theater", "Die Volksversammlung", "Die römische Ratsversammlung", "Ein Tempel"], correct: 2, hint: "Politische Versammlung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war Julius Caesar?", answers: ["Ein Gott", "Ein römischer Feldherr", "Ein griechischer Philosoph", "Ein Kaufmann"], correct: 1, hint: "Berühmter Herrscher", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        kultur: [ { question: "Wer ist der höchste Gott der Römer?", answers: ["Merkur", "Jupiter", "Mars", "Neptun"], correct: 1, hint: "Gott des Blitzes (Zeus)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer ist die Göttin der Liebe?", answers: ["Juno", "Minerva", "Venus", "Diana"], correct: 2, hint: "Griechisch Aphrodite", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was sind 'Thermen'?", answers: ["Schulen", "Öffentliche Badeanlagen", "Kasernen", "Bibliotheken"], correct: 1, hint: "Wellness der Antike", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Sprache sprachen die Römer?", answers: ["Italienisch", "Griechisch", "Latein", "Gallisch"], correct: 2, hint: "Lingua Latina", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Villa'?", answers: ["Ein Mietshaus", "Ein vornehmens Landhaus", "Ein Zelt", "Ein Stall"], correct: 1, hint: "Wohnhaus der Reichen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was trugen römische Männer (Bürger)?", answers: ["Hosen", "Toga", "Kleid", "Anzug"], correct: 1, hint: "Großes Wolltuch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war der Gott des Meeres?", answers: ["Pluto", "Neptun", "Vulkan", "Bacchus"], correct: 1, hint: "Dreizack", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Kardinal'?", answers: ["Ein Vogel", "Kein Begriff aus dem alten Rom", "Ein Richter", "Ein Soldat"], correct: 1, hint: "Späterer kirchlicher Begriff", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer bewachte das Herdfeuer?", answers: ["Venus", "Vesta", "Ceres", "Juno"], correct: 1, hint: "Vestalinnen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'panem et circenses'?", answers: ["Krieg und Frieden", "Brot und Spiele", "Wein und Gesang", "Arbeit und Ruhe"], correct: 1, hint: "Unterhaltung für das Volk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo fanden Wagenrennen statt?", answers: ["Kolosseum", "Circus Maximus", "Theater", "Forum"], correct: 1, hint: "Ben Hur", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Atrium'?", answers: ["Küche", "Zentraler Innenhof im Haus", "Schlafzimmer", "Keller"], correct: 1, hint: "Mit Wasserbecken", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war der Gott des Krieges?", answers: ["Amor", "Mars", "Saturn", "Janus"], correct: 1, hint: "Roter Planet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Stola'?", answers: ["Schuh", "Gewand der römischen Frau", "Hut", "Waffe"], correct: 1, hint: "Überkleid", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war der Gott der Unterwelt?", answers: ["Jupiter", "Pluto", "Merkur", "Apollo"], correct: 1, hint: "Hades", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Mosaik'?", answers: ["Ein Buch", "Bild aus vielen kleinen Steinen", "Ein Lied", "Ein Gesetz"], correct: 1, hint: "Bodenverzierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was aßen Römer oft (Grundnahrungsmittel)?", answers: ["Kartoffeln", "Getreidebrei (Puls) / Brot", "Mais", "Reis"], correct: 1, hint: "Getreide", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Sklave' im alten Rom?", answers: ["Ein Angestellter", "Ein Mensch ohne Rechte (Sache)", "Ein Soldat", "Ein Politiker"], correct: 1, hint: "Unfreiheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war der Götterbote?", answers: ["Mars", "Merkur", "Vulkan", "Jupiter"], correct: 1, hint: "Flügelschuhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Basilika'?", answers: ["Ein Garten", "Markt- oder Gerichtshalle", "Ein Schiff", "Ein Gefängnis"], correct: 1, hint: "Später Kirchentyp", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war die Göttin der Weisheit?", answers: ["Venus", "Minerva", "Diana", "Vesta"], correct: 1, hint: "Griechisch Athene", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war ein 'Tutor'?", answers: ["Ein Lehrer/Vormund", "Ein Sklave", "Ein Gott", "Ein Soldat"], correct: 0, hint: "Schutzherr", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das 'Pantheon'?", answers: ["Ein Grab", "Tempel für alle Götter", "Ein Theater", "Ein Bad"], correct: 1, hint: "Kuppelbau in Rom", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer war der Gott des Weines?", answers: ["Mars", "Bacchus", "Neptun", "Pluto"], correct: 1, hint: "Dionysos", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Zenturie'?", answers: ["10 Jahre", "Militärische Einheit von ca. 80-100 Mann", "Ein Tempel", "Ein Schiff"], correct: 1, hint: "Befehlshaber Zenturio", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war das Colosseum?", answers: ["Ein Tempel", "Ein Amphitheater", "Ein Badehaus", "Ein Palast"], correct: 1, hint: "Gladiatorenkämpfe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was trugen römische Bürger meistens?", answers: ["Hose", "Toga", "Jacke", "Rock"], correct: 1, hint: "Wickelgewand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was war ein 'Thermopolium'?", answers: ["Eine Schule", "Eine Garküche", "Ein Marktplatz", "Eine Bibliothek"], correct: 1, hint: "Fast food der Römer", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};