const math8gData = {
    name: "Mathematik (8G)",
    icon: "📈",
    color: "#3b82f6",
    description: "Mathe 8. Klasse Gymnasium - Funktionen und Gleichungen",
    categories: {
        funktionen: { name: "Lineare Funktionen", icon: "📈", color: "#10b981", desc: "Geraden im Koordinatensystem" },
        systeme: { name: "Gleichungssysteme", icon: "⚖️", color: "#8b5cf6", desc: "Zwei Gleichungen mit zwei Unbekannten" },
        geometrie: { name: "Geometrie", icon: "📐", color: "#f59e0b", desc: "Prismen und Zylinder" },
        stochastik: { name: "Stochastik", icon: "🎲", color: "#ec4899", desc: "Wahrscheinlichkeitsrechnung" }
    },
    questions: {
        funktionen: [
            { question: "Wie lautet die allgemeine Geradengleichung?", answers: ["y = ax²", "y = mx + t", "y = sin(x)", "y = 1/x"], correct: 1, hint: "m ist die Steigung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was gibt 't' in y = mx + t an?", answers: ["Steigung", "Nullstelle", "y-Achsenabschnitt", "Krümmung"], correct: 2, hint: "Schnittpunkt mit der vertikalen Achse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Steigung hat eine waagrechte Gerade?", answers: ["m = 1", "m = 0", "m = -1", "Nicht definiert"], correct: 1, hint: "Kein Anstieg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie berechnet man die Steigung m durch zwei Punkte P1(x1|y1) und P2(x2|y2)?", answers: ["(x2-x1)/(y2-y1)", "(y2-y1)/(x2-x1)", "y1/x1", "x2*y2"], correct: 1, hint: "Differenzenquotient (Delta y / Differenz x)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Nullstelle einer Funktion?", answers: ["Schnittpunkt mit der y-Achse", "Schnittpunkt mit der x-Achse", "Der Punkt (0|0)", "Der höchste Punkt"], correct: 1, hint: "y muss 0 sein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Zwei Geraden sind parallel, wenn...", answers: ["t1 = t2", "m1 = m2", "m1 * m2 = -1", "m1 = -m2"], correct: 1, hint: "Gleiche Neigung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Zwei Geraden stehen senkrecht (orthogonal) aufeinander, wenn...", answers: ["m1 = m2", "m1 * m2 = -1", "t1 = t2", "m1 + m2 = 0"], correct: 1, hint: "Produkt der Steigungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Steigung hat die Gerade y = -3x + 4?", answers: ["3", "-3", "4", "-4"], correct: 1, hint: "Zahl vor dem x", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo schneidet y = 2x - 5 die y-Achse?", answers: ["(2|0)", "(0|2)", "(0|-5)", "(-5|0)"], correct: 2, hint: "t-Wert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Steigung einer fallenden Geraden?", answers: ["Positiv", "Null", "Negativ", "Immer -1"], correct: 2, hint: "y-Werte werden kleiner", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Berechne die Nullstelle von y = 2x - 4.", answers: ["x = 2", "x = -2", "x = 4", "x = 0"], correct: 0, hint: "Setze y = 0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Eine Ursprungsgerade hat immer welchen t-Wert?", answers: ["t = 1", "t = 0", "t beliebig", "Kein t"], correct: 1, hint: "Geht durch (0|0)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man das Dreieck zur Bestimmung der Steigung?", answers: ["Steigungsdreieck", "Rechtwinkliges Dreieck", "Mathe-Dreieck", "Punkt-Dreieck"], correct: 0, hint: "Delta y und Delta x", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Liegt der Punkt (1|5) auf der Geraden y = 3x + 2?", answers: ["Ja", "Nein", "Nur wenn x=0", "Vielleicht"], correct: 0, hint: "Punktprobe: Setze 1 für x ein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit der Geraden, wenn m größer wird?", answers: ["Sie wird flacher", "Sie wird steiler", "Sie verschiebt sich nach oben", "Nichts"], correct: 1, hint: "Größerer Anstieg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'direkte Proportionalität' grafisch?", answers: ["Eine Parabel", "Eine Ursprungsgerade", "Ein Kreis", "Eine waagrechte Linie"], correct: 1, hint: "y = m*x", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Steigung m=0,5 bedeutet: Gehe 2 nach rechts und...", answers: ["0,5 nach oben", "1 nach oben", "2 nach oben", "0,5 nach unten"], correct: 1, hint: "m = Delta y / Delta x", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet die Gleichung der Winkelhalbierenden des I. Quadranten?", answers: ["y = x", "y = -x", "y = 0", "x = 0"], correct: 0, hint: "m=1, t=0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Bestimme m für P1(0|0) und P2(2|6).", answers: ["m = 2", "m = 3", "m = 6", "m = 0,33"], correct: 1, hint: "6/2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Gerade ist parallel zu y = 5x - 2?", answers: ["y = -5x + 2", "y = 5x + 10", "y = 0,2x - 2", "y = x/5"], correct: 1, hint: "Gleiches m", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist x in y = mx + t?", answers: ["Die abhängige Variable", "Die unabhängige Variable", "Die Steigung", "Der Achsenabschnitt"], correct: 1, hint: "Argument der Funktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was beschreibt eine lineare Funktion?", answers: ["Gleichmäßige Änderung", "Beschleunigte Änderung", "Periodische Änderung", "Zufällige Änderung"], correct: 0, hint: "Konstante Steigung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Form hat der Graph von y = 3?", answers: ["Steigend", "Fallend", "Waagerecht", "Senkrecht"], correct: 2, hint: "Steigung 0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Schnittpunkt von y = x und y = 2? ", answers: ["(1|1)", "(2|2)", "(2|1)", "(0|2)"], correct: 1, hint: "Gleichsetzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Eine Gerade fällt durch (0|4) und (2|0). Gleichung?", answers: ["y = 2x + 4", "y = -2x + 4", "y = -0,5x + 4", "y = 4x + 2"], correct: 1, hint: "t=4, m = -4/2", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        systeme: [
            { question: "Welches ist KEIN Verfahren für LGS?", answers: ["Einsetzungsverfahren", "Gleichsetzungsverfahren", "Additionsverfahren", "Wurzelverfahren"], correct: 3, hint: "LGS = Lineare Gleichungssysteme", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was sucht man beim Lösen eines LGS mit zwei Geraden grafisch?", answers: ["Die Nullstellen", "Den Schnittpunkt", "Die y-Achsenabschnitte", "Den Abstand"], correct: 1, hint: "Gemeinsamer Punkt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Lösungen kann ein LGS mit zwei Variablen haben?", answers: ["Genau eine", "Keine oder eine", "Keine, eine oder unendlich viele", "Immer zwei"], correct: 2, hint: "Lage von zwei Geraden zueinander", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann hat ein LGS keine Lösung?", answers: ["Geraden sind identisch", "Geraden sind parallel (aber nicht identisch)", "Geraden schneiden sich", "Eine Gerade ist waagerecht"], correct: 1, hint: "Kein gemeinsamer Punkt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann hat ein LGS unendlich viele Lösungen?", answers: ["Parallel", "Orthogonal", "Identisch", "Kein Schnittpunkt"], correct: 2, hint: "Liegen aufeinander", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: x + y = 10 und x - y = 2.", answers: ["(4|6)", "(6|4)", "(5|5)", "(7|3)"], correct: 1, hint: "Additionsverfahren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Verfahren bietet sich an, wenn eine Gleichung nach y aufgelöst ist?", answers: ["Einsetzungsverfahren", "Additionsverfahren", "Multiplikationsverfahren", "Divisionsverfahren"], correct: 0, hint: "Substituieren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: y = 2x und y = x + 3.", answers: ["(1|2)", "(3|6)", "(2|4)", "(0|0)"], correct: 1, hint: "Gleichsetzen: 2x = x + 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Beim Additionsverfahren möchte man erreichen, dass...", answers: ["Beide Variablen wegfallen", "Eine Variable wegfällt", "Beide Gleichungen 0 ergeben", "x = y wird"], correct: 1, hint: "Elimination", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein LGS mit 0 = 5 als Ergebnis bedeutet:", answers: ["Lösung ist x=5", "Lösung ist (0|5)", "Keine Lösung", "Unendlich viele Lösungen"], correct: 2, hint: "Falsche Aussage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein LGS mit 0 = 0 als Ergebnis bedeutet:", answers: ["Lösung ist x=0", "Keine Lösung", "Unendlich viele Lösungen", "Lösung ist (0|0)"], correct: 2, hint: "Wahre Aussage (identisch)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 2x + y = 5 und y = 1.", answers: ["(2|1)", "(4|1)", "(1|2)", "(5|1)"], correct: 0, hint: "Einsetzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wenn x=2 in x+y=5 eingesetzt wird, ist y=?", answers: ["2", "3", "7", "-3"], correct: 1, hint: "Subtraktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der erste Schritt beim Gleichsetzungsverfahren?", answers: ["Addieren", "Beide Gleichungen nach derselben Variable auflösen", "Wurzel ziehen", "x=0 setzen"], correct: 1, hint: "Vorbereitung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Gleichungen braucht man mindestens für zwei Unbekannte (eindeutig)?", answers: ["1", "2", "3", "4"], correct: 1, hint: "Anzahl Unbekannte = Anzahl Gleichungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: x + 2y = 8 und x = 2y.", answers: ["(4|2)", "(2|4)", "(4|4)", "(2|2)"], correct: 0, hint: "Einsetzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Darf man eine Gleichung im LGS mit -1 multiplizieren?", answers: ["Nein", "Ja, das ändert die Lösungsmenge nicht", "Nur beim Additionsverfahren", "Nur die linke Seite"], correct: 1, hint: "Äquivalenzumformung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Widerspruch' im LGS?", answers: ["Wenn man sich verrechnet", "Eine mathematisch falsche Endzeile (z.B. 4=7)", "Wenn x negativ ist", "Wenn y=0"], correct: 1, hint: "Leere Lösungsmenge", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Verfahren ist meist am schnellsten, wenn x und y auf einer Seite stehen?", answers: ["Einsetzungsverfahren", "Additionsverfahren", "Zeichnen", "Raten"], correct: 1, hint: "Gleichungen untereinander schreiben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Löse: 3x = 9 und x + y = 5.", answers: ["(3|2)", "(3|8)", "(9|1)", "(3|5)"], correct: 0, hint: "Erst x bestimmen, dann einsetzen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        geometrie: [
            { question: "Wie berechnet man das Volumen eines Prismas?", answers: ["V = G * h", "V = 1/3 * G * h", "V = 2 * G + M", "V = G + h"], correct: 0, hint: "Grundfläche mal Höhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Zylinder geometrisch?", answers: ["Ein spitz zulaufender Körper", "Ein Prisma mit kreisförmiger Grundfläche", "Ein Viereck", "Eine Kugel"], correct: 1, hint: "Wie eine Dose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet die Formel für die Grundfläche eines Zylinders?", answers: ["G = 2 * pi * r", "G = pi * r²", "G = pi * d", "G = a * b"], correct: 1, hint: "Kreisinhalt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was gehört zur Oberfläche eines Körpers?", answers: ["Nur die Seitenflächen", "Grundfläche + Deckfläche + Mantelfläche", "Nur das Volumen", "Nur die Höhe"], correct: 1, hint: "Die gesamte 'Haut'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie berechnet man den Umfang eines Kreises?", answers: ["U = pi * r²", "U = 2 * pi * r", "U = G * h", "U = d / pi"], correct: 1, hint: "Länge des Randes", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie groß ist das Volumen, wenn G=10cm² und h=5cm?", answers: ["15 cm³", "50 cm³", "25 cm³", "50 cm²"], correct: 1, hint: "10 * 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Mantel eines Zylinders (ausgebreitet)?", answers: ["Ein Kreis", "Ein Dreieck", "Ein Rechteck", "Ein Trapez"], correct: 2, hint: "Umfang * Höhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Einheit hat das Volumen?", answers: ["cm", "cm²", "cm³", "kg"], correct: 2, hint: "Hoch 3", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein Prisma hat eine dreieckige Grundfläche. Wie viele Kanten hat es?", answers: ["3", "6", "9", "12"], correct: 2, hint: "3 unten, 3 oben, 3 stehend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie ändert sich das Volumen eines Prismas, wenn man die Höhe verdoppelt?", answers: ["Es bleibt gleich", "Es verdoppelt sich", "Es vervierfacht sich", "Es wird achtmal so groß"], correct: 1, hint: "Linearer Zusammenhang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Berechne G eines Zylinders mit r = 10 cm (pi ca. 3,14).", answers: ["31,4 cm²", "314 cm²", "100 cm²", "62,8 cm²"], correct: 1, hint: "3,14 * 10²", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt das Cavalieri-Prinzip?", answers: ["Volumen hängt nur von Farbe ab", "Körper mit gleichen Querschnittsflächen in allen Höhen haben gleiches Volumen", "Spitze Körper sind immer größer", "Ein Kreis ist ein Quadrat"], correct: 1, hint: "Stapel von Münzen/Scheiben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Deckfläche eines Prismas?", answers: ["Die Seite", "Die Fläche gegenüber der Grundfläche", "Der Mantel", "Die Höhe"], correct: 1, hint: "Oben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Ecken hat ein Prisma mit sechseckiger Grundfläche?", answers: ["6", "12", "18", "8"], correct: 1, hint: "2 * 6", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'gerades' Prisma?", answers: ["Ein Prisma ohne Ecken", "Seitenkanten stehen senkrecht auf der Grundfläche", "Ein Prisma mit nur 4 Seiten", "Ein Prisma das nicht wackelt"], correct: 1, hint: "90 Grad Winkel zur Basis", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        stochastik: [
            { question: "Wie groß ist die Wahrscheinlichkeit, mit einem Würfel eine 6 zu werfen?", answers: ["1/2", "1/4", "1/6", "1/1"], correct: 2, hint: "Eine von sechs Möglichkeiten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Laplace-Experiment'?", answers: ["Ein schweres Experiment", "Alle Ergebnisse sind gleich wahrscheinlich", "Experiment mit nur zwei Ausgängen", "Ein misslungenes Experiment"], correct: 1, hint: "Fairer Würfel / Münze", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man die Menge aller möglichen Ergebnisse?", answers: ["Lösungsmenge", "Ergebnismenge (Omega)", "Zufallsraum", "Trefferquote"], correct: 1, hint: "Griechisches Symbol Ω", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wahrscheinlichkeit für 'Kopf' beim Münzwurf?", answers: ["0%", "25%", "50%", "100%"], correct: 2, hint: "Hälfte-Hälfte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt die Summenregel bei Pfadregeln?", answers: ["Pfade werden multipliziert", "Wahrscheinlichkeiten von Pfaden, die zum selben Ereignis gehören, werden addiert", "Ergebnis ist immer 1", "Zufall gibt es nicht"], correct: 1, hint: "Zweig-Enden zusammenzählen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt die Produktregel (1. Pfadregel)?", answers: ["Addiere die Werte am Pfad", "Multipliziere die Wahrscheinlichkeiten entlang eines Pfades", "Subtrahiere die Werte", "Pfadende ist wichtig"], correct: 1, hint: "Entlang des Weges", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Zweimal würfeln: P(6,6)?", answers: ["1/6", "1/12", "1/36", "2/6"], correct: 2, hint: "1/6 * 1/6", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie groß ist die Summe aller Wahrscheinlichkeiten eines Zufallsexperiments?", answers: ["0", "0,5", "1 (oder 100%)", "Unendlich"], correct: 2, hint: "Das sichere Ereignis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein 'Gegenereignis' zu 'Es regnet'?", answers: ["Es schneit", "Es regnet nicht", "Die Sonne scheint", "Es ist windig"], correct: 1, hint: "Nicht A", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "P(A) + P(nicht A) = ?", answers: ["0", "0,5", "1", "2"], correct: 2, hint: "Komplementärwahrscheinlichkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Urne mit 3 roten und 7 blauen Kugeln. P(rot)?", answers: ["0,3", "0,7", "3/7", "1/10"], correct: 0, hint: "3 von 10", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Pfade hat ein Baumdiagramm bei 2-maligem Wurf einer Münze?", answers: ["2", "4", "6", "8"], correct: 1, hint: "2 * 2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet P(E) = 0?", answers: ["Mögliches Ereignis", "Unmögliches Ereignis", "Sicheres Ereignis", "Gutes Ergebnis"], correct: 1, hint: "Tritt nie ein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Würfel: P(Gerade Zahl)?", answers: ["1/6", "2/6", "3/6 (1/2)", "4/6"], correct: 2, hint: "2, 4, 6", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das 'Gesetz der großen Zahlen'?", answers: ["Große Zahlen sind besser", "Bei vielen Wiederholungen nähert sich die relative Häufigkeit der theoretischen Wahrscheinlichkeit an", "Der Zufall verschwindet", "Mathe ist schwer"], correct: 1, hint: "Stabilisierung der Werte", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};