// ============================================
// MINECRAFT - LernApp Daten (6. Klasse Spezial)
// ============================================

const minecraft6rData = {
    name: "Minecraft",
    icon: "⛏️",
    color: "#4e7d1d",
    description: "Alles über Minecraft: Blöcke, Crafting, Kreaturen, Technik und Biome",
    
    categories: {
        blocks: { name: "Blöcke & Erze", icon: "🧱", color: "#8b4513", desc: "Materialien und Erze" },
        crafting: { name: "Crafting", icon: "⚒️", color: "#f59e0b", desc: "Rezepte und Werkzeuge" },
        mobs: { name: "Kreaturen", icon: "🧟", color: "#ef4444", desc: "Mobs und Tiere" },
        dimensions: { name: "Dimensionen", icon: "🌌", color: "#8b5cf6", desc: "Nether und Ende" },
        redstone: { name: "Redstone", icon: "🔌", color: "#dc2626", desc: "Logik und Technik" },
        biomes: { name: "Welt & Biome", icon: "🌳", color: "#22c55e", desc: "Strukturen und Natur" },
        items: { name: "Items", icon: "🍎", color: "#3b82f6", desc: "Ausrüstung und Essen" }
    },

    questions: {
        blocks: [
            { question: "Aus welchem Erz gewinnt man Diamanten?", answers: ["Eisen", "Gold", "Diamanterz", "Kohle"], correct: 2, hint: "Es leuchtet blau", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block ist am schwierigsten abzubauen?", answers: ["Stein", "Holz", "Obsidian", "Erde"], correct: 2, hint: "Man braucht eine Diamantspitzhacke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus gewinnt man Glas?", answers: ["Kies", "Sand", "Erde", "Stein"], correct: 1, hint: "Schmelzen im Ofen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block fällt nach unten, wenn nichts darunter ist?", answers: ["Holz", "Stein", "Kies", "Wolle"], correct: 2, hint: "Hat Schwerkraft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der unterste, unzerstörbare Block?", answers: ["Obsidian", "Grundgestein (Bedrock)", "Tiefenschiefer", "Granit"], correct: 1, hint: "Schutz am Boden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Erz benötigt man für Stromkreise?", answers: ["Eisen", "Smaragd", "Redstone", "Kupfer"], correct: 2, hint: "Rote Leitungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus besteht ein Schneemann?", answers: ["Eis", "Wolle", "Schnee", "Quarz"], correct: 2, hint: "Kalt und weiß", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welchen Block findet man oft in Ozeanmonumenten?", answers: ["Sandstein", "Schwamm", "Netherrack", "Basalt"], correct: 1, hint: "Saugt Wasser auf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der weiße Block aus dem Nether?", answers: ["Wolle", "Schnee", "Quarz", "Stein"], correct: 2, hint: "Glänzt ein bisschen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Aus was wird Netherit gewonnen?", answers: ["Gold", "Antiker Schrott", "Obsidian", "Diamant"], correct: 1, hint: "Sehr selten im Nether", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt das hellgrüne Erz aus dem Ende?", answers: ["Smaragd", "Enderperle", "Chorusfrucht", "Gibt es nicht"], correct: 3, hint: "Im Ende gibt es keine Standard-Erze", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus bestehen die Säulen im Ende?", answers: ["Eisen", "Obsidian", "Tiefenschiefer", "Granit"], correct: 1, hint: "Dunkel und hart", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block ist der Hauptbestandteil der Oberwelt-Wüsten?", answers: ["Kies", "Dreck", "Sand", "Ton"], correct: 2, hint: "Gelb und rieselig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welchen Block erhält man, wenn Wasser auf einen Lava-Quellblock trifft?", answers: ["Pflasterstein", "Obsidian", "Stein", "Basalt"], correct: 1, hint: "Dunkel lila/schwarz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Aus welchem Holz bestehen die dunklen Bäume im Sumpf?", answers: ["Eiche", "Schwarzeiche", "Fichte", "Mangrove"], correct: 3, hint: "Neuere Holzart", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit Kupferblöcken über Zeit?", answers: ["Sie schmelzen", "Sie oxidieren (werden grün)", "Sie verschwinden", "Sie werden zu Gold"], correct: 1, hint: "Wie in der echten Welt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block wird zum Brauen von Tränken als Basis benötigt?", answers: ["Glas", "Lohenstaub", "Braustand", "Wasserkessel"], correct: 2, hint: "Das Arbeitsgerät", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der glühende Block aus dem Meer?", answers: ["Seelaterne", "Glowstone", "Fackel", "Magma"], correct: 0, hint: "In Ozeanmonumenten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block verlangsamt Mobs und Spieler?", answers: ["Eis", "Seelensand", "Schleim", "Honig"], correct: 1, hint: "Im Nether zu finden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus besteht ein Bücherregal?", answers: ["Holz und Papier", "Holz und Bücher", "Nur Papier", "Stöcke und Leder"], correct: 1, hint: "Man braucht 3 Bücher", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der Stein im Nether, der wie Gold aussieht?", answers: ["Glowstone", "Nethergold-Erz", "Pyrit", "Gelber Stein"], correct: 1, hint: "Gibt Goldklumpen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was findet man in Verliesen (Dungeons) oft?", answers: ["Betten", "Monster-Spawner", "Endportale", "Diamantblöcke"], correct: 1, hint: "Erzeugt unendlich Mobs", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block leitet Redstone-Signale nach oben?", answers: ["Glas", "Redstone-Fackel", "Beobachter", "Kolben"], correct: 1, hint: "Invertiert das Signal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Erz findet man am häufigsten in hohen Bergen?", answers: ["Eisen", "Kohle", "Smaragd", "Kupfer"], correct: 2, hint: "Grünes Juwel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus bestehen die Wolken in Minecraft?", answers: ["Wolle", "Schnee", "Nichts (sind 2D/Shader)", "Glas"], correct: 2, hint: "Sind Teil des Himmels", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block brennt im Nether ewig?", answers: ["Holz", "Netherrack", "Basalt", "Kies"], correct: 1, hint: "Der rote Stein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der Block, den man aus 4 Amethystsplittern macht?", answers: ["Amethystblock", "Kristall", "Glas", "Lichtblock"], correct: 0, hint: "Dekorativer Block", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block schützt vor Creeper-Explosionen am besten?", answers: ["Glas", "Erde", "Obsidian", "Sandstein"], correct: 2, hint: "Sehr hohe Explosionsresistenz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit Sand, wenn man ihn schmilzt?", answers: ["Er wird zu Stein", "Er wird zu Glas", "Er wird zu Ton", "Er verschwindet"], correct: 1, hint: "Durchsichtig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block gibt Licht ab und wächst unter Wasser?", answers: ["Fackel", "Seelaterne", "Meeresgurke", "Glowstone"], correct: 2, hint: "Kann bis zu 4 pro Block sein", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        crafting: [
            { question: "Wie viele Holzbretter braucht man für eine Werkbank?", answers: ["2", "3", "4", "6"], correct: 2, hint: "Ein volles kleines Quadrat", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man neben einem Stock für eine Fackel?", answers: ["Eisen", "Kohle", "Gold", "Lava"], correct: 1, hint: "Brennt gut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus craftet man Papier?", answers: ["Holz", "Blätter", "Zuckerrohr", "Stöcke"], correct: 2, hint: "Wächst am Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Weizen braucht man für ein Brot?", answers: ["1", "2", "3", "4"], correct: 2, hint: "In einer Reihe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was benötigt man für einen Zaubertisch?", answers: ["Gold, Eisen, Glas", "Obsidian, Diamanten, Buch", "Stein, Holz, Redstone", "Smaragde, Gold, Buch"], correct: 1, hint: "Magische Materialien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus macht man ein Bett?", answers: ["Wolle und Bretter", "Leder und Federn", "Stoff und Stöcke", "Eisen und Wolle"], correct: 0, hint: "Weich zum Schlafen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie stellt man einen Eimer her?", answers: ["3 Holz", "3 Eisenbarren", "3 Goldbarren", "3 Glas"], correct: 1, hint: "V-Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man für einen Kompass?", answers: ["Gold und Redstone", "Eisen und Redstone", "Diamant und Eisen", "Glas und Gold"], correct: 1, hint: "Zeigt zum Spawn", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus macht man eine Angel?", answers: ["Stöcke und Fäden", "Eisen und Stöcke", "Stöcke und Leder", "Bambus und Faden"], correct: 0, hint: "Zum Fische fangen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Barren braucht man für eine Brustplatte?", answers: ["6", "7", "8", "9"], correct: 2, hint: "Fast voll", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie craftet man einen Ofen?", answers: ["8 Holz", "8 Pflasterstein", "8 Eisen", "8 Sand"], correct: 1, hint: "Ein Ring aus Stein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ergibt 3 Zuckerrohr in einer Reihe?", answers: ["Zucker", "Papier", "Kuchen", "Buch"], correct: 1, hint: "Schreibmaterial", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus macht man ein Boot?", answers: ["5 Eisen", "5 Wolle", "5 Holzbretter", "5 Gold"], correct: 2, hint: "U-Form aus Holz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Diamanten braucht man für eine Spitzhacke?", answers: ["1", "2", "3", "4"], correct: 2, hint: "Oben waagerecht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus bestehen Stöcke?", answers: ["Holzstämme", "Holzbretter", "Blätter", "Setzlinge"], correct: 1, hint: "2 Bretter übereinander", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie stellt man eine Schere her?", answers: ["2 Steine", "2 Eisenbarren", "2 Stöcke", "2 Feuersteine"], correct: 1, hint: "Diagonal im Grid", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man für einen Kuchen?", answers: ["Milch, Zucker, Ei, Weizen", "Mehl, Wasser, Apfel", "Zucker, Honig, Beeren", "Milch, Kakao, Weizen"], correct: 0, hint: "Kompliziertes Rezept", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie macht man eine goldene Karotte?", answers: ["Goldbarren und Karotte", "Goldklumpen und Karotte", "Golderz und Karotte", "Gelbe Farbe und Karotte"], correct: 1, hint: "Karotte umringt von Klumpen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus besteht ein TNT-Block?", answers: ["Sand und Schwarzpulver", "Kies und Kohle", "Erde und Feuerwerk", "Stein und Redstone"], correct: 0, hint: "Explosiv!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie craftet man ein Schild (Waffe)?", answers: ["Holz und Eisen", "Leder und Stöcke", "Nur Eisen", "Nur Stein"], correct: 0, hint: "Holz-Form mit 1 Eisen oben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man für eine Armbrust?", answers: ["Stöcke, Faden, Eisen, Haken", "Holz, Gold, Leder", "Stöcke, Spinnenauge, Eisen", "Nur Fäden"], correct: 0, hint: "Teurer als ein Bogen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie stellt man eine Karte her?", answers: ["9 Papier", "8 Papier und 1 Kompass", "1 Papier und 1 Tinte", "8 Leder und 1 Papier"], correct: 1, hint: "Papier rund um den Kompass", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus wird ein Beacons (Leuchtfeuer) gemacht?", answers: ["Glas, Obsidian, Netherstern", "Diamant, Gold, Smaragd", "Netherit, Eisen, Glas", "Lichtstein, Quarz, Glas"], correct: 0, hint: "Sehr teuer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Eisenbarren braucht man für einen Amboss?", answers: ["3 Blöcke und 4 Barren (31)", "9 Barren", "5 Barren", "10 Barren"], correct: 0, hint: "Sehr viel Eisen nötig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man für ein Endauge?", answers: ["Enderperle und Lohenstaub", "Enderperle und Diamant", "Lohenrute und Glas", "Auge einer Spinne"], correct: 0, hint: "Zutaten aus Festung und Ende", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Diamanten braucht man für ein komplettes Set Rüstung?", answers: ["20", "24", "26", "28"], correct: 1, hint: "Helm, Brust, Hose, Schuhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus macht man ein Lagerfeuer?", answers: ["Stöcke, Kohle, Stämme", "Bretter und Kohle", "Steine und Stöcke", "Wolle und Holz"], correct: 0, hint: "3 Stöcke, 1 Kohle, 3 Stämme", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man für eine Lore (Minecart)?", answers: ["5 Eisenbarren", "5 Holzbretter", "5 Goldbarren", "5 Stein"], correct: 0, hint: "U-Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie stellt man einen klebrigen Kolben her?", answers: ["Kolben + Honig", "Kolben + Schleimball", "Kolben + Faden", "Kolben + Wolle"], correct: 1, hint: "Vom Slime", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus besteht ein Feuerwerk?", answers: ["Papier und Schwarzpulver", "Papier und Redstone", "Schwarzpulver und Sand", "Glas und Gold"], correct: 0, hint: "Zum Fliegen mit Elytren", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        mobs: [
            { question: "Welches Tier gibt Wolle?", answers: ["Schwein", "Kuh", "Schaf", "Huhn"], correct: 2, hint: "Mäh!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer explodiert, wenn er dir zu nahe kommt?", answers: ["Zombie", "Skelett", "Creeper", "Spinne"], correct: 2, hint: "Er ist grün und zischt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer verbrennt bei Sonnenlicht?", answers: ["Zombie & Skelett", "Creeper & Spinne", "Enderman & Slime", "Schwein & Kuh"], correct: 0, hint: "Untote", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Mob kann sich teleportieren?", answers: ["Ghast", "Enderman", "Wither", "Lohe"], correct: 1, hint: "Ist sehr groß und schwarz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit zähmt man einen Wolf?", answers: ["Fleisch", "Apfel", "Knochen", "Fisch"], correct: 2, hint: "Wird zum Hund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Mob handelt mit Smaragden?", answers: ["Hexe", "Plünderer", "Dorfbewohner", "Zombie"], correct: 2, hint: "Lebt im Dorf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer beschützt die Dorfbewohner?", answers: ["Eisengolem", "Schneegolem", "Spieler", "Hunde"], correct: 0, hint: "Groß und aus Metall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer schießt Feuerbälle im Nether?", answers: ["Enderman", "Ghast", "Lohe (Blaze)", "Piglin"], correct: 1, hint: "Fliegt und weint", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Tier kann man reiten?", answers: ["Kuh", "Pferd", "Wolf", "Schaf"], correct: 1, hint: "Braucht einen Sattel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Boss-Mob lebt im Ende?", answers: ["Wither", "Enderdrache", "Warden", "Großer Wächter"], correct: 1, hint: "Das Ziel des Spiels", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man die feindlichen Dorfbewohner?", answers: ["Zombies", "Plünderer (Illager)", "Skelette", "Endermen"], correct: 1, hint: "Greifen Dörfer an", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Mob hat am meisten Leben?", answers: ["Enderdrache", "Warden", "Wither", "Eisengolem"], correct: 1, hint: "Hütet die antiken Städte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was essen Schweine am liebsten?", answers: ["Weizen", "Karotten", "Äpfel", "Brot"], correct: 1, hint: "Orangefarbenes Gemüse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Tier gibt Milch?", answers: ["Schaf", "Schwein", "Kuh", "Pferd"], correct: 2, hint: "Braucht einen Eimer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer schießt Pfeile?", answers: ["Zombie", "Skelett", "Spinne", "Creeper"], correct: 1, hint: "Knochenmann", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Mob spawnt nur im Wasser?", answers: ["Slime", "Tintenfisch", "Schaf", "Hase"], correct: 1, hint: "Gibt Tinte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie zähmt man eine Katze?", answers: ["Milch", "Fisch", "Fleisch", "Zucker"], correct: 1, hint: "Roh", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was hinterlässt ein Creeper, wenn er durch ein Skelett stirbt?", answers: ["Diamanten", "Schallplatte", "Gold", "TNT"], correct: 1, hint: "Musik-Item", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der dreiköpfige Boss?", answers: ["Ghast", "Wither", "Zerberus", "Enderdrache"], correct: 1, hint: "Muss beschworen werden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Mob klaut Blöcke?", answers: ["Creeper", "Zombie", "Enderman", "Silberfischchen"], correct: 2, hint: "Lila Augen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer gibt beim Tod Lohenruten?", answers: ["Wither-Skelett", "Piglin", "Lohe (Blaze)", "Magmacube"], correct: 2, hint: "Im Nether in Festungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit lockt man Hühner an?", answers: ["Weizen", "Samen", "Karotten", "Brot"], correct: 1, hint: "Vogelfutter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was fürchtet der Creeper?", answers: ["Hunde", "Ozelots/Katzen", "Wasser", "Licht"], correct: 1, hint: "Hausraubtiere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der Wächter der Ozeanmonumente?", answers: ["Hai", "Großer Wächter (Elder Guardian)", "Drowned", "Krake"], correct: 1, hint: "Einteiliges Auge, schießt Laser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus bestehen Slimes?", answers: ["Wasser", "Schleimbälle", "Wolle", "Gelee"], correct: 1, hint: "Grün und hüpfend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Fisch kann den Spieler vergiften?", answers: ["Lachs", "Kabeljau", "Kugelfisch", "Tintenfisch"], correct: 2, hint: "Bläht sich auf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was lässt eine Hexe oft fallen?", answers: ["Bücher", "Tränke", "Essen", "Rüstung"], correct: 1, hint: "Chemische Flaschen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Köpfe braucht man, um einen Wither zu beschwören?", answers: ["1", "2", "3", "4"], correct: 2, hint: "Wither-Skelett-Schädel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Tier hilft beim Suchen von Schätzen im Ozean?", answers: ["Delfin", "Schildkröte", "Hai", "Wal"], correct: 0, hint: "Gib ihm Fisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wer schießt mit Armbrüsten während eines Überfalls?", answers: ["Zombies", "Plünderer", "Endermen", "Skelette"], correct: 1, hint: "Illager-Gruppe", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        dimensions: [
            { question: "Wie heißt die Dimension, in der der Enderdrache lebt?", answers: ["Nether", "Das Ende", "Oberwelt", "Aether"], correct: 1, hint: "Dort gibt es Endermen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus baut man das Portal zum Nether?", answers: ["Stein", "Eisen", "Obsidian", "Gold"], correct: 2, hint: "Dunkler Block", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der rote Stein, aus dem der Nether-Boden besteht?", answers: ["Netherrack", "Basalt", "Seelensand", "Magma"], correct: 0, hint: "Brennt ewig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit aktiviert man ein Netherportal?", answers: ["Fackel", "Feuerzeug", "Redstone", "Lava"], correct: 1, hint: "Eisen + Feuerstein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Struktur findet man im Ende nach dem Drachenkampf?", answers: ["Dörfer", "Endstädte", "Minen", "Tempel"], correct: 1, hint: "Hier gibt es Elytren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der sandige Block im Nether, der verlangsamt?", answers: ["Sand", "Kies", "Seelensand", "Dreck"], correct: 2, hint: "Gibt es im Seelensand-Tal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item lässt der Enderdrache fallen?", answers: ["Diamanten", "Drachenei", "Elytren", "Netherit"], correct: 1, hint: "Trophäe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo findet man die Lohen (Blazes)?", answers: ["Bastionen", "Netherfestungen", "Dörfer", "Wüsten"], correct: 1, hint: "Dunkle Ziegel-Gebäude", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie kommt man zurück zur Oberwelt aus dem Ende?", answers: ["Portal bauen", "Springen", "Zentrales Portal nutzen", "Schlafen"], correct: 2, hint: "Mitte der Insel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Kann man im Nether ein Bett benutzen?", answers: ["Ja", "Nein (es explodiert)", "Nur nachts", "Nur mit Wolle"], correct: 1, hint: "Gefährlich!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der Wald im Nether mit den blauen Bäumen?", answers: ["Karmesinwald", "Wirrwald", "Seelensand-Tal", "Basaltdeltas"], correct: 1, hint: "Blau/Türkis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine Bastion?", answers: ["Ein Dorf im Nether", "Festung der Piglins", "Ein Endschiff", "Eine Unterwasserstadt"], correct: 1, hint: "Dort gibt es viel Gold", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt das Material, aus dem Endstädte gebaut sind?", answers: ["Endstein", "Purpurblock", "Quarz", "Weißer Beton"], correct: 1, hint: "Lila Farbe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches fliegende Fortbewegungsmittel findet man in Endstädten?", answers: ["Drachen", "Endschiff", "Elytren-Flugzeug", "Heißluftballon"], correct: 1, hint: "Hängt in der Luft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert, wenn man Wasser im Nether platzieren will?", answers: ["Es wird zu Eis", "Es verdampft sofort", "Es fließt normal", "Es wird zu Lava"], correct: 1, hint: "Es ist zu heiß dort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Augen braucht ein Endportal maximal?", answers: ["8", "10", "12", "14"], correct: 2, hint: "Ein Dutzend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Mob tauscht Items gegen Gold im Nether?", answers: ["Zombifizierter Piglin", "Piglin", "Hoglin", "Ghast"], correct: 1, hint: "Liebt glänzendes Metall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 'The Void'?", answers: ["Der Nether", "Der Weltraum", "Die Leere unter der Welt", "Ein neuer Mob"], correct: 2, hint: "Dort stirbt man sofort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt der Wald im Nether mit roten Bäumen?", answers: ["Wirrwald", "Karmesinwald", "Feuerwald", "Hoglinwald"], correct: 1, hint: "Rot", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was sind Shulker?", answers: ["Blöcke im Nether", "Mobs im Ende, die wie Blöcke aussehen", "Fische", "Pflanzen"], correct: 1, hint: "Lassen dich schweben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item braucht man, um den Enderdrachen erneut zu beschwören?", answers: ["Diamantblock", "Endkristall", "Drachenei", "Goldener Apfel"], correct: 1, hint: "4 Stück auf dem Portal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie groß ist der Nether im Vergleich zur Oberwelt?", answers: ["1:1", "1:4", "1:8", "1:10"], correct: 2, hint: "Wichtig für schnelles Reisen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert beim Schlafen im Ende?", answers: ["Man wacht in der Oberwelt auf", "Das Bett explodiert", "Man regeneriert Leben", "Nichts"], correct: 1, hint: "Gleicher Effekt wie im Nether", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit fängt man den Atem des Drachen ein?", answers: ["Eimer", "Glasflasche", "Schüssel", "Netherit-Flasche"], correct: 1, hint: "Für Tränke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block ist der Hauptbestandteil der Ende-Inseln?", answers: ["Sandstein", "Endstein", "Quarz", "Weißer Stein"], correct: 1, hint: "Hellgelb", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        redstone: [
            { question: "Woraus gewinnt man Redstone?", answers: ["Kohle", "Redstone-Erz", "Eisen", "Holz"], correct: 1, hint: "Gibt rotes Pulver", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie weit leitet Redstone-Staub ein Signal ohne Verstärker?", answers: ["10 Blöcke", "15 Blöcke", "20 Blöcke", "Unendlich"], correct: 1, hint: "Danach wird es zu schwach", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item verstärkt ein Redstone-Signal?", answers: ["Fackel", "Verstärker (Repeater)", "Kolben", "Hebel"], correct: 1, hint: "Setzt die Signalstärke auf 15 zurück", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block sendet ein Signal aus, wenn er eine Veränderung bemerkt?", answers: ["Hebel", "Beobachter (Observer)", "Knopf", "Trichter"], correct: 1, hint: "Hat ein 'Gesicht'", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man ein Redstone-Signal invertieren (umkehren)?", answers: ["Redstone-Fackel", "Hebel", "Block", "Staub"], correct: 0, hint: "An der Seite eines Blocks platziert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Block kann Items transportieren?", answers: ["Trichter (Hopper)", "Kolben", "Werfer", "Spender"], correct: 0, hint: "Wie ein Metalltrichter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was macht ein Komparator?", answers: ["Vergleicht Signalstärken", "Verstärkt Signale", "Löscht Signale", "Explodiert"], correct: 0, hint: "Hat 3 Fackeln oben drauf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Schiene beschleunigt Loren?", answers: ["Normale Schiene", "Antriebsschiene", "Aktivierungsschiene", "Detektorschiene"], correct: 1, hint: "Braucht Redstone-Power", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Redstone drahtlos (kurze Distanz) übertragen?", answers: ["Fackeln", "Redstone-Blöcke", "Kalibrierter Sculk-Sensor", "Wolle"], correct: 2, hint: "Reagiert auf Geräusche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert, wenn ein Kolben ein Signal erhält?", answers: ["Er brennt", "Er fährt aus", "Er geht kaputt", "Er leuchtet"], correct: 1, hint: "Bewegt Blöcke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie viele Stufen Verzögerung kann ein Verstärker maximal haben?", answers: ["1", "2", "3", "4"], correct: 3, hint: "Rechtsklick zum Ändern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Druckplatte reagiert nur auf Spieler?", answers: ["Holz", "Stein", "Gold", "Eisen"], correct: 1, hint: "Graue Farbe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Licht automatisch einschalten, wenn es dunkel wird?", answers: ["Hebel", "Tageslichtsensor", "Knopf", "Fackel"], correct: 1, hint: "Kann invertiert werden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'Clock' in Redstone?", answers: ["Eine echte Uhr", "Ein sich wiederholendes Signal", "Ein Zeitmesser", "Ein kaputtes Kabel"], correct: 1, hint: "Blinkendes Signal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert, wenn ein Werfer (Dispenser) mit einem Wassereimer aktiviert wird?", answers: ["Er wirft den Eimer aus", "Er platziert eine Wasserquelle", "Er explodiert", "Nichts"], correct: 1, hint: "Er 'benutzt' das Item im Inneren", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        biomes: [
            { question: "In welchem Biom findet man Kakteen?", answers: ["Wald", "Wüste", "Dschungel", "Eiswüste"], correct: 1, hint: "Heiß und trocken", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "In welchem Biom wachsen Chorusfrüchte?", answers: ["Nether", "Ende", "Oberwelt", "Ozean"], correct: 1, hint: "Lila Pflanzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Struktur findet man im Dschungel?", answers: ["Wüstentempel", "Dschungeltempel", "Bastion", "Dorf"], correct: 1, hint: "Aus Pflasterstein und Moos", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo findet man Eisbären?", answers: ["Dschungel", "Eisbiome", "Wüste", "Savanne"], correct: 1, hint: "Wo es kalt ist", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt das Biom mit den riesigen Pilzen?", answers: ["Pilzinsel", "Sumpf", "Wald", "Birkenwald"], correct: 0, hint: "Hier spawnen keine Monster", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo findet man Papageien?", answers: ["Wald", "Eiswüste", "Dschungel", "Ebene"], correct: 2, hint: "Bunte Vögel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Biom hat leuchtendes Gras und rosa Partikel?", answers: ["Kirschblütenhain", "Sumpf", "Dunkler Wald", "Savanne"], correct: 0, hint: "Neu in 1.20", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt die gefährliche Struktur tief unter der Erde mit dem Warden?", answers: ["Mine", "Festung", "Antike Stadt (Ancient City)", "Verlies"], correct: 2, hint: "Sculk-Blöcke überall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "In welchem Biom findet man Terracotta-Berge?", answers: ["Wüste", "Badlands (Mesa)", "Ebene", "Sumpf"], correct: 1, hint: "Viel bunter Ton", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo stehen die Endstädte?", answers: ["Auf der Hauptinsel", "Auf den äußeren Inseln im Ende", "Im Nether", "Unter Wasser"], correct: 1, hint: "Weit weg vom Drachen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Biom hat hellgrünes Wasser?", answers: ["Ozean", "Sumpf", "Fluss", "Eissee"], correct: 1, hint: "Hier gibt es Hexenhütten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo findet man Korallenriffe?", answers: ["Tiefer Ozean", "Warmer Ozean", "Eismeer", "Flüsse"], correct: 1, hint: "Sehr bunte Blöcke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie heißt die Struktur im Dorf, in der der Schmied arbeitet?", answers: ["Kirche", "Schmiede", "Bibliothek", "Haus"], correct: 1, hint: "Hat oft eine Kiste mit Loot", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Biom hat die höchsten Bäume?", answers: ["Wald", "Birkenwald", "Dschungel", "Schwarzeichenwald"], correct: 2, hint: "Tropisches Klima", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wo spawnen Schleime am häufigsten an der Oberfläche?", answers: ["Wüste", "Sumpf", "Eiswüste", "Berge"], correct: 1, hint: "Besonders bei Vollmond", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        items: [
            { question: "Welches Item lässt dich fliegen?", answers: ["Mantel", "Elytren", "Umhang", "Flügel"], correct: 1, hint: "Findet man in Endschiffen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Werkzeuge reparieren?", answers: ["Amboss", "Werkbank", "Ofen", "Truhe"], correct: 0, hint: "Braucht Erfahrungspunkte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item rettet dich vor dem Tod?", answers: ["Goldapfel", "Totem der Unsterblichkeit", "Diamant", "Schild"], correct: 1, hint: "Man muss es in der Hand halten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Blöcke aus der Ferne abbauen?", answers: ["Bogen", "Spitzhacke", "Gibt es nicht", "TNT"], correct: 2, hint: "Abbauen geht nur nah", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Essen heilt am meisten Hunger?", answers: ["Apfel", "Gebratenes Schweinefleisch", "Keks", "Melone"], correct: 1, hint: "Fleisch sättigt gut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man unter Wasser atmen?", answers: ["Trank der Unterwasseratmung", "Eimer", "Fackel", "Nichts"], correct: 0, hint: "Gebraut mit Kugelfisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item zeigt dir den Weg nach Hause (Spawn)?", answers: ["Uhr", "Kompass", "Karte", "Fernglas"], correct: 1, hint: "Hat eine rote Nadel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Tiere anleinen?", answers: ["Faden", "Leine", "Seil", "Kette"], correct: 1, hint: "Craftet man aus Fäden und Schleimball", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item wird zum Handeln mit Piglins benutzt?", answers: ["Diamant", "Goldbarren", "Smaragd", "Eisen"], correct: 1, hint: "Glänzt gelb", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was braucht man, um Wolle zu färben?", answers: ["Farbstoff", "Wasser", "Pinsel", "Blumen"], correct: 0, hint: "Kann man aus Blumen machen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man eine Schallplatte abspielen?", answers: ["Notenblock", "Plattenspieler (Jukebox)", "Lautsprecher", "Radio"], correct: 1, hint: "Braucht einen Diamanten zum Craften", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item erhält man von einer Lohe (Blaze)?", answers: ["Feuerball", "Lohenrute", "Netherstern", "Glowstone"], correct: 1, hint: "Wichtig für Braustände", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Items benennen?", answers: ["Werkbank", "Amboss", "Schild", "Buch"], correct: 1, hint: "Kostet Level", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Item braucht man für ein Endportal?", answers: ["Enderperle", "Enderauge", "Feuerauge", "Magierkugel"], correct: 1, hint: "Muss in den Rahmen gesetzt werden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Womit kann man Fische fangen?", answers: ["Eimer", "Angel", "Netz", "Beide (A und B)"], correct: 3, hint: "Angel oder Eimer für Lebendfische", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};
