// ============================================
// PHYSIK - LernApp Daten (8. Klasse Gymnasium Bayern)
// ============================================

const phys8gData = {
    name: "Physik (8G)",
    icon: "⚛️",
    color: "#6366f1",
    description: "Physik 8. Klasse Gymnasium - Energie, Mechanik und Optik",
    categories: {
        mechanik: { name: "Mechanik", icon: "⚙️", color: "#10b981", desc: "Kraft, Masse und Bewegung" },
        energie: { name: "Energie", icon: "⚡", color: "#f59e0b", desc: "Energieformen und Erhaltung" },
        optik: { name: "Optik", icon: "👓", color: "#3b82f6", desc: "Licht, Linsen und Reflexion" },
        waermelehre: { name: "Wärmelehre", icon: "🔥", color: "#ef4444", desc: "Teilchenmodell und Temperatur" }
    },
    questions: {
        mechanik: [
            { question: "In welcher Einheit wird die Kraft gemessen?", answers: ["Joule", "Watt", "Newton", "Pascal"], correct: 2, hint: "Sir Isaac...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Formelzeichen für die Masse?", answers: ["F", "m", "a", "s"], correct: 1, hint: "Mass", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie berechnet man den Druck p?", answers: ["p = F/A", "p = m*g", "p = m/V", "p = W/t"], correct: 0, hint: "Kraft pro Fläche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt das Trägheitsgesetz?", answers: ["Körper wollen in Ruhe bleiben", "Körper fallen immer nach unten", "Kraft gleich Gegenkraft", "Energie bleibt erhalten"], correct: 0, hint: "Newton I", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Einheit hat die Arbeit W?", answers: ["Newton", "Watt", "Joule", "Pascal"], correct: 2, hint: "W = F * s", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie groß ist die Erdbeschleunigung g ungefähr?", answers: ["1,6 m/s²", "9,81 m/s²", "100 m/s²", "300.000 km/s"], correct: 1, hint: "Nahe 10", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist mechanische Leistung?", answers: ["Kraft mal Weg", "Arbeit pro Zeit", "Masse mal Beschleunigung", "Druck pro Fläche"], correct: 1, hint: "P = W/t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Einheit hat die Leistung P?", answers: ["Joule", "Newton", "Watt", "Hertz"], correct: 2, hint: "Bekannt von Glühbirnen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was misst man in Pascal (Pa)?", answers: ["Kraft", "Energie", "Druck", "Leistung"], correct: 2, hint: "Barometer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 1 Newtonmeter (Nm) auch?", answers: ["1 Watt", "1 Joule", "1 Pascal", "1 Tesla"], correct: 1, hint: "Einheit der Arbeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt das Hookesche Gesetz?", answers: ["F = m * a", "F = D * s", "p = rho * g * h", "W = F * s"], correct: 1, hint: "Federdehnung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Reibungsart ist am größten?", answers: ["Gleitreibung", "Rollreibung", "Haftreibung", "Luftreibung"], correct: 2, hint: "Bevor sich etwas bewegt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie berechnet man die Dichte rho?", answers: ["m * V", "m / V", "V / m", "F / A"], correct: 1, hint: "Masse pro Volumen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Schweredruck?", answers: ["Druck durch Gewicht einer Flüssigkeitssäule", "Luftdruck", "Reifendruck", "Magnetdruck"], correct: 0, hint: "Abhängig von der Tiefe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit einem U-Boot, wenn es Ballastwasser aufnimmt?", answers: ["Dichte steigt", "Dichte sinkt", "Masse sinkt", "Volumen steigt"], correct: 0, hint: "Es sinkt ab", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Einheit des Drehmoments?", answers: ["Newton", "Joule", "Newtonmeter", "Watt"], correct: 2, hint: "Kraft mal Hebelarm", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine 'feste Rolle'?", answers: ["Kraftwandler", "Richtungswandler", "Energiespeicher", "Masse"], correct: 1, hint: "Spart keine Kraft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie ändert sich der Luftdruck mit der Höhe?", answers: ["Er steigt", "Er bleibt gleich", "Er sinkt", "Er schwankt zufällig"], correct: 2, hint: "Dünne Luft am Berg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist das Archimedische Prinzip?", answers: ["Fallgesetz", "Auftriebskraft = Gewichtskraft der verdrängten Flüssigkeit", "Kraft = Gegenkraft", "Lichtbrechung"], correct: 1, hint: "Heureka!", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wovon hängt die Gleitreibung ab?", answers: ["Flächeninhalt", "Normalkraft und Oberflächenbeschaffenheit", "Geschwindigkeit", "Farbe"], correct: 1, hint: "mu * Fn", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein Körper hat 500g auf der Erde. Wie groß ist seine Masse auf dem Mond?", answers: ["weniger", "mehr", "genau 500g", "0g"], correct: 2, hint: "Masse ist ortsunabhängig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine schiefe Ebene physikalisch?", answers: ["Ein Hindernis", "Ein Kraftwandler", "Ein Wellentyp", "Ein Teilchen"], correct: 1, hint: "Längerer Weg, weniger Kraft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was misst man mit einer Balkenwaage?", answers: ["Gewichtskraft", "Masse", "Volumen", "Dichte"], correct: 1, hint: "Vergleich mit Urgewichten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Warum sinkt ein Stein im Wasser?", answers: ["F_Auftrieb > F_Gewicht", "F_Gewicht > F_Auftrieb", "Er ist nass", "Wasser hat keine Kraft"], correct: 1, hint: "Kräftevergleich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie berechnet man mechanische Arbeit?", answers: ["F / s", "F * s", "P * t", "m * g"], correct: 1, hint: "Kraft längs eines Weges", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        energie: [
            { question: "Was ist die Einheit der Energie?", answers: ["Newton", "Joule", "Watt", "Volt"], correct: 1, hint: "Abkürzung J", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Energie hat ein gespannter Bogen?", answers: ["Lageenergie", "Spannenergie", "Bewegungsenergie", "Wärmeenergie"], correct: 1, hint: "Elastizität", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt der Energieerhaltungssatz?", answers: ["Energie kann erzeugt werden", "Energie geht verloren", "Energie kann nur umgewandelt werden", "Energie ist unendlich"], correct: 2, hint: "Grundgesetz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist kinetische Energie?", answers: ["Lageenergie", "Bewegungsenergie", "Kernenergie", "Strahlungsenergie"], correct: 1, hint: "kinesis = Bewegung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet die Formel für die Lageenergie?", answers: ["m * v", "m * g * h", "1/2 * m * v²", "F * s"], correct: 1, hint: "Masse, Erdbeschleunigung, Höhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie lautet die Formel für die Bewegungsenergie?", answers: ["m * g * h", "1/2 * m * v²", "F * s", "P * t"], correct: 1, hint: "v² ist wichtig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Wirkungsgrad?", answers: ["Nutzen / Aufwand", "Aufwand / Nutzen", "Kraft / Weg", "Energie * Zeit"], correct: 0, hint: "Immer kleiner als 1", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Warum ist ein Wirkungsgrad nie 100%?", answers: ["Wegen Reibung/Wärme", "Wegen Schwerkraft", "Wegen der Zeit", "Wegen Magnetismus"], correct: 0, hint: "Energieentwertung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Energieentwertung?", answers: ["Energie verschwindet", "Umwandlung in nicht nutzbare Wärmeenergie", "Energie wird billiger", "Batterie ist leer"], correct: 1, hint: "Zunahme der Entropie", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Energieform nutzt eine Solarzelle?", answers: ["Wärme", "Strahlungsenergie", "Wind", "Chemische Energie"], correct: 1, hint: "Licht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Primärenergie?", answers: ["Strom", "Energie in Rohstoffen (Kohle, Sonne, Holz)", "Bewegungsenergie", "Abwärme"], correct: 1, hint: "Natürliche Vorkommen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Basiseinheit der Leistung?", answers: ["Joule", "Newtonmeter", "Watt", "PS"], correct: 2, hint: "J/s", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "In welcher Form speichern Akkus Energie?", answers: ["Elektrisch", "Mechanisch", "Chemisch", "Thermisch"], correct: 2, hint: "Elektrochemische Reaktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Hubarbeit?", answers: ["W = m*g*h", "W = 1/2*D*s²", "W = F*v", "W = P/t"], correct: 0, hint: "Gegen die Gewichtskraft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Energieform hat ein Liter Benzin?", answers: ["Lageenergie", "Bewegungsenergie", "Chemische Energie", "Kernenergie"], correct: 2, hint: "Brennstoff", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein Gerät mit 1000W läuft 1 Stunde. Wie viel Energie verbraucht es?", answers: ["1 J", "1000 J", "1 kWh", "1000 Wh/s"], correct: 2, hint: "Kilowattstunde", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Kraftwerk nutzt Bewegungsenergie der Luft?", answers: ["Solaranlage", "Windkraftanlage", "Geothermie", "Wasserkraft"], correct: 1, hint: "Windrad", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert bei der Kernspaltung?", answers: ["Atome verschmelzen", "Atome werden geteilt", "Atome brennen", "Atome leuchten"], correct: 1, hint: "Kernkraftwerk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist regenerative Energie?", answers: ["Energie aus Kohle", "Energie aus unerschöpflichen Quellen", "Energie aus Batterien", "Energie aus Erdgas"], correct: 1, hint: "Sonne, Wind, Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Einheit der mechanischen Arbeit?", answers: ["Watt", "Newton", "Newtonmeter (Joule)", "Kilogramm"], correct: 2, hint: "F * s", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Leistung physikalisch?", answers: ["Viel Kraft haben", "Arbeit pro Zeit", "Energie mal Zeit", "Weg pro Geschwindigkeit"], correct: 1, hint: "P = W / t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Sekundärenergie?", answers: ["Kohle", "Sonne", "Strom (umgewandelt aus Primärenergie)", "Holz"], correct: 2, hint: "Veredelte Energie", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was beschreibt der Begriff 'E_pot'?", answers: ["Bewegungsenergie", "Lageenergie", "Elektrische Energie", "Dampfenergie"], correct: 1, hint: "Potentielle Energie", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Perpetuum Mobile?", answers: ["Ein schnelles Auto", "Eine Maschine, die ohne Energiezufuhr ewig arbeitet (unmöglich)", "Ein Satellit", "Ein Fahrrad"], correct: 1, hint: "Verletzt Energieerhaltung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Energieform hat fließendes Wasser?", answers: ["Lageenergie", "Bewegungsenergie", "Beide", "Keine"], correct: 2, hint: "Höhe und Geschwindigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        optik: [
            { question: "Wie schnell ist das Licht ungefähr?", answers: ["300 m/s", "1200 km/h", "300.000 km/s", "1 Mrd. km/h"], correct: 2, hint: "Vakuumlichtgeschwindigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was besagt das Reflexionsgesetz?", answers: ["Einfallswinkel = Ausfallswinkel", "Licht wird verschluckt", "Licht wird immer blau", "Winkel sind egal"], correct: 0, hint: "Alpha = Beta", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Linse bündelt Lichtstrahlen?", answers: ["Konkavlinse", "Konvexlinse (Sammellinse)", "Flachlinse", "Streulinse"], correct: 1, hint: "Nach außen gewölbt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert bei der Brechung?", answers: ["Licht ändert die Richtung beim Mediumswechsel", "Licht geht kaputt", "Licht wird reflektiert", "Licht wird dunkel"], correct: 0, hint: "Luft - Glas", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Brennpunkt?", answers: ["Punkt, an dem parallele Strahlen nach einer Sammellinse zusammenlaufen", "Wo es brennt", "Mitte des Spiegels", "Lichtquelle"], correct: 0, hint: "Fokus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Totalreflexion?", answers: ["Licht wird 100% reflektiert beim Übergang zu dünnerem Medium", "Spiegelbild", "Schatten", "Absorption"], correct: 0, hint: "Glasfaserkabel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "In welcher Einheit gibt man die Brechkraft an?", answers: ["Meter", "Watt", "Dioptrie", "Newton"], correct: 2, hint: "Brillenpass", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist weißes Licht physikalisch?", answers: ["Eine eigene Farbe", "Mischung aus allen Spektralfarben", "Licht ohne Farbe", "Dunkles Licht"], correct: 1, hint: "Prisma-Versuch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Bild liefert eine Lochkamera?", answers: ["aufrecht, seitenrichtig", "umgekehrt, seitenverkehrt", "gar kein Bild", "immer scharfes, riesiges Bild"], correct: 1, hint: "Strahlenausbreitung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Dispersion?", answers: ["Lichtbeugung", "Lichtzerlegung in Farben (z.B. am Prisma)", "Lichtreflexion", "Lichtgeschwindigkeit"], correct: 1, hint: "Regenbogenfarben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie nennt man Linsen, die in der Mitte dünner sind?", answers: ["Sammellinsen", "Zerstreuungslinsen (Konkav)", "Brennlinsen", "Flachlinsen"], correct: 1, hint: "Wölbung nach innen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie breitet sich Licht aus?", answers: ["In Kurven", "Geradlinig", "Zick-Zack", "Nur nach oben"], correct: 1, hint: "Lichtstrahlen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Farbe hat die kleinste Wellenlänge im sichtbaren Bereich?", answers: ["Rot", "Gelb", "Grün", "Violett"], correct: 3, hint: "Hochenergetisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein virtuelles Bild?", answers: ["Ein Bild auf einem Schirm", "Ein Bild, das nur im Auge/Spiegel erscheint", "Ein Bild am Computer", "Ein echtes Bild"], correct: 1, hint: "Ebenen Spiegel betrachten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wodurch entsteht ein Regenbogen?", answers: ["Reflexion und Brechung in Wassertropfen", "Malerei am Himmel", "Schatten der Wolken", "Wind"], correct: 0, hint: "Optisches Phänomen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Akkommodation?", answers: ["Farbenblindheit", "Scharfeinstellung des Auges durch Linsenverformung", "Pupillenweite", "Lidschlag"], correct: 1, hint: "Anpassung an Entfernungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was korrigiert eine Zerstreuungslinse?", answers: ["Kurzsichtigkeit", "Weitsichtigkeit", "Blindheit", "Nichts"], correct: 0, hint: "Augapfel zu lang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist die Pupille?", answers: ["Linse", "Loch in der Iris", "Glaskörper", "Nerv"], correct: 1, hint: "Regelt Lichteinfall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert, wenn Licht vom Wasser in Luft übertritt (schräg)?", answers: ["Es wird zum Lot hin gebrochen", "Es wird vom Lot weg gebrochen", "Es wird nicht gebrochen", "Es verschwindet"], correct: 1, hint: "Optisch dünneres Medium", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welches Bauteil im Auge wandelt Licht in Nervensignale?", answers: ["Linse", "Iris", "Netzhaut (Retina)", "Hornhaut"], correct: 2, hint: "Ganz hinten im Auge", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist UV-Licht?", answers: ["Sichtbares blaues Licht", "Ultraviolette Strahlung (energiereicher als Licht)", "Wärmestrahlung", "Röntgenstrahlung"], correct: 1, hint: "Verursacht Sonnenbrand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Infrarot-Strahlung?", answers: ["UV-Licht", "Wärmestrahlung", "Grünes Licht", "Laser"], correct: 1, hint: "Unterhalb von Rot", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist ein Schattenspiel?", answers: ["Lichtbeugung", "Anwendung der geradlinigen Lichtausbreitung", "Reflexion", "Brechung"], correct: 1, hint: "Schattenwurf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wann sieht man einen Gegenstand?", answers: ["Wenn man ihn anstarrt", "Wenn Licht vom Gegenstand ins Auge fällt", "Wenn es hell ist", "Gar nicht"], correct: 1, hint: "Lichtweg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Warum ist der Himmel blau?", answers: ["Wegen des Ozeans", "Streuung des Sonnenlichts in der Atmosphäre", "Es gibt blaue Gase", "Optische Täuschung"], correct: 1, hint: "Rayleigh-Streuung", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ],
        waermelehre: [
            { question: "Was ist Temperatur physikalisch?", answers: ["Ein Stoff", "Ein Maß für die mittlere ungeordnete Teilchenbewegung", "Ein Strahl", "Flüssiges Wasser"], correct: 1, hint: "Teilchenmodell", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie groß ist der absolute Nullpunkt?", answers: ["0 °C", "-100 °C", "-273,15 °C", "-459 °C"], correct: 2, hint: "0 Kelvin", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert mit den meisten Körpern bei Erwärmung?", answers: ["Sie schrumpfen", "Sie dehnen sich aus", "Sie werden schwerer", "Sie werden magnetisch"], correct: 1, hint: "Teilchenabstand vergrößert sich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist 0 Grad Celsius in Kelvin?", answers: ["0 K", "100 K", "273,15 K", "373 K"], correct: 2, hint: "Eispunkt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welche Arten der Wärmeübertragung gibt es?", answers: ["Leitung, Strömung, Strahlung", "Licht, Gas, Feststoff", "Kalt, Warm, Heiß", "Strom, Funk, Magnetismus"], correct: 0, hint: "Transportwege", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine Anomalie des Wassers?", answers: ["Es brennt", "Höchste Dichte bei 4 °C", "Es ist immer durchsichtig", "Es dehnt sich beim Schmelzen aus"], correct: 1, hint: "Eis schwimmt oben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "In welcher Einheit wird Temperatur im SI-System gemessen?", answers: ["Celsius", "Fahrenheit", "Kelvin", "Joule"], correct: 2, hint: "Basisgröße", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert beim Schmelzen auf Teilchenebene?", answers: ["Teilchen stehen still", "Gitterbindungen werden aufgebrochen", "Teilchen verschwinden", "Teilchen werden kleiner"], correct: 1, hint: "Phasenübergang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Verdampfen?", answers: ["Gas zu Flüssig", "Flüssig zu Gas", "Fest zu Gas", "Flüssig zu Fest"], correct: 1, hint: "Wasserkocher", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Stoff ist ein guter Wärmeleiter?", answers: ["Holz", "Luft", "Kupfer", "Styropor"], correct: 2, hint: "Metalle leiten gut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Wärmestrahlung?", answers: ["Wärmetransport über elektromagnetische Wellen", "Heißer Wind", "Leitung im Metall", "Fließen von Wasser"], correct: 0, hint: "Sonne", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist spezifische Wärmekapazität?", answers: ["Energie zum Erwärmen von 1kg um 1K", "Energiegehalt von Kohle", "Höchste Temperatur", "Wärmeleitfähigkeit"], correct: 0, hint: "Stoffeigenschaft c", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Warum dehnen sich Gase stärker aus als Festkörper?", answers: ["Sie sind leichter", "Geringe Bindungskräfte zwischen Teilchen", "Sie sind heißer", "Teilchen sind größer"], correct: 1, hint: "Teilchenabstand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Brownsche Bewegung?", answers: ["Fließen von Schlamm", "Unregelmäßige Zitterbewegung kleiner Teilchen", "Magnetische Kraft", "Lichtbrechung"], correct: 1, hint: "Beweis für Atome", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Sublimation?", answers: ["Flüssig zu Gas", "Fest direkt zu Gas", "Gas zu Fest", "Schmelzen"], correct: 1, hint: "Trockeneis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Woraus besteht ein Bimetall?", answers: ["Ein Metall", "Zwei Streifen unterschiedlicher Metalle", "Flüssiges Metall", "Magnet"], correct: 1, hint: "Thermostat", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist Konvektion?", answers: ["Wärmeleitung", "Wärmemitführung durch strömende Medien", "Wärmestrahlung", "Isolation"], correct: 1, hint: "Wärmeströmung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie ändert sich die Temperatur beim Sieden?", answers: ["Sie steigt", "Sie sinkt", "Sie bleibt konstant", "Sie schwankt"], correct: 2, hint: "Zufuhr von Verdampfungswärme", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Welcher Stoff isoliert am besten?", answers: ["Eisen", "Wasser", "Luft (ruhend)", "Glas"], correct: 2, hint: "Geringe Teilchendichte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist der Kondensationspunkt?", answers: ["Übergang Flüssig zu Fest", "Übergang Gas zu Flüssig", "Gefrierpunkt", "Siedepunkt"], correct: 1, hint: "Dampf wird zu Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was passiert beim Erstarren?", answers: ["Energie wird frei", "Energie wird benötigt", "Teilchen bewegen sich schneller", "Masse nimmt zu"], correct: 0, hint: "Kristallisation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Warum platzen Wasserleitungen im Winter?", answers: ["Metall wird brüchig", "Volumenausdehnung von Wasser beim Gefrieren", "Kälte drückt", "Luftdruck"], correct: 1, hint: "Dichteanomalie", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was ist eine Vakuum-Isolation?", answers: ["Dicke Schicht Wolle", "Entzug von Teilchen zur Verhinderung von Wärmetransport", "Anstrich", "Magnetfeld"], correct: 1, hint: "Thermoskanne", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wofür steht das Symbol Q in der Wärmelehre?", answers: ["Temperatur", "Wärmemenge (Energie)", "Druck", "Dichte"], correct: 1, hint: "Einheit Joule", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wie berechnet man die Mischungstemperatur (einfach)?", answers: ["Richmannsche Mischungsregel", "Pythagoras", "Ohm'sches Gesetz", "Reflexionsgesetz"], correct: 0, hint: "Wärmebilanz", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ]
    }
};
