window.__subjectData_math_9g_quadratische_funktionen = [
    { question: "Welche Form hat der Graph einer quadratischen Funktion?", answers: ["Eine Gerade", "Eine Parabel", "Ein Kreis", "Eine Hyperbel"], correct: 1, hint: "f(x) = x²", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Nullstellen kann eine quadratische Funktion haben?", answers: ["0, 1 oder 2", "Immer 2", "Immer 1", "Keine"], correct: 0, hint: "Abhängig von der Diskriminante", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die allgemeine Form einer quadratischen Funktion?", answers: ["f(x) = ax + b", "f(x) = ax² + bx + c", "f(x) = ax³ + bx²", "f(x) = a/x"], correct: 1, hint: "Grad 2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was gibt die Diskriminante D = b² - 4ac an?", answers: ["Die Steigung", "Die Anzahl der Nullstellen", "Den Scheitelpunkt", "Y-Achsenabschnitt"], correct: 1, hint: "D > 0 = 2, D = 0 = 1, D < 0 = 0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie berechnet man den Scheitelpunkt einer Parabel?", answers: ["S = (-b/(2a) | f(-b/(2a)))", "S = (0 | c)", "S = (b | c)", "S = (-c | a)"], correct: 0, hint: "x-Koordinate = -b/(2a)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Parabel ist nach oben geöffnet?", answers: ["f(x) = -x² + 2x - 1", "f(x) = x² - 3x + 2", "f(x) = -2x² + 5", "f(x) = -0,5x²"], correct: 1, hint: "a > 0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Normalform einer quadratischen Funktion?", answers: ["f(x) = a(x - d)² + e", "f(x) = ax² + bx + c", "f(x) = x² + px + q", "f(x) = (x - a)(x - b)"], correct: 2, hint: "p/q-Form", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Löse x² + 6x + 9 = 0:", answers: ["x = 3", "x = -3", "x = ±3", "x = 0"], correct: 1, hint: "(x + 3)² = 0", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Lösungsformel für x² + px + q = 0?", answers: ["x = -p/2 ± √((p/2)² - q)", "x = -b ± √(b² - 4ac)", "x = p ± q", "x = -p ± √q"], correct: 0, hint: "pq-Formel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Aussage zum Scheitelpunkt S(2|3) einer Parabel stimmt?", answers: ["Der Graph hat bei x=2 einen Tiefpunkt", "Der Graph hat bei x=2 einen Hochpunkt", "Der Scheitel ist bei (0|0)", "Die Parabel ist nach unten geöffnet"], correct: 0, hint: "Scheitel: tiefster oder höchster Punkt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Lösungen hat x² + 1 = 0?", answers: ["Keine (in ℝ)", "Eine", "Zwei", "Unendlich viele"], correct: 0, hint: "x² = -1", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bewirkt der Parameter c bei f(x) = ax² + bx + c?", answers: ["Verschiebung nach links/rechts", "Verschiebung nach oben/unten", "Öffnung der Parabel", "Streckung"], correct: 1, hint: "c = y-Achsenabschnitt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Bestimme die Nullstellen von f(x) = (x-2)(x+3):", answers: ["x = 2 und x = -3", "x = -2 und x = 3", "x = 2 und x = 3", "x = 0"], correct: 0, hint: "Ein Produkt ist null, wenn ein Faktor null ist", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen einer Parabel und einer Geraden?", answers: ["Eine Parabel ist gekrümmt, eine Gerade ist gerade", "Beide sind gleich", "Eine Gerade ist gekrümmt", "Eine Parabel hat keine Steigung"], correct: 0, hint: "Grad 2 vs. Grad 1", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];