window.__subjectData_math_9g_textaufgaben_verstehen = [
    { mode: "question_clarity", question: "📋 FRAGE vereinfachen!", fullText: "Ein Ball wird aus 20m Höhe fallen gelassen. Er springt jeden Aufprall auf 3/4 der vorherigen Höhe zurück.", simplifiedVersions: ["Nach wie vielen Sprüngen ist er unter 5m?", "Wie schwer ist der Ball?", "Welche Farbe hat der Ball?"], answers: ["Nach wie vielen Sprüngen ist er unter 5m?", "Wie schwer ist der Ball?", "Welche Farbe hat der Ball?"], correct: 0, hint: "Die Frage nach der Höhe macht Sinn.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Kapital von 2000€ wird zu 3% Zinsen angelegt. Die Inflation beträgt 2%. Der Anlagezeitraum ist 5 Jahre.", secondaryQuestion: "Welche Info brauchst du für den Zinsertrag nach 5 Jahren NICHT?", answers: ["2000€", "3%", "Inflation 2%", "5 Jahre"], correct: 2, hint: "Inflation mindert die Kaufkraft, nicht den Zinsertrag", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Auto beschleunigt gleichmäßig von 0 auf 100 km/h in 8 Sekunden. Die Strecke beträgt 200 Meter.", possibleQuestions: ["Welche Farbe hat das Auto?", "Wie groß ist die Beschleunigung?", "Wer hat das Auto gebaut?"], answers: ["Welche Farbe hat das Auto?", "Wie groß ist die Beschleunigung?", "Wer hat das Auto gebaut?"], correct: 1, hint: "a = v / t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Kredit von 10.000€ wird zu 5% Zinsen aufgenommen. Monatliche Rate: 200€. Laufzeit: 5 Jahre.", secondaryQuestion: "Welche Infos brauchst du für die Gesamtzahlung?", answers: ["200€/Monat, 5 Jahre", "10.000€, 5%", "10.000€, 200€/Monat", "5%, 5 Jahre"], correct: 0, hint: "Rate × Monate", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Eine Bakterienkultur wächst exponentiell: Start 500, nach 1h 800.", possibleQuestions: ["Wie hoch ist die Wachstumsrate?", "Wie heißen die Bakterien?", "Sind die Bakterien gefährlich?"], answers: ["Wie hoch ist die Wachstumsrate?", "Wie heißen die Bakterien?", "Sind die Bakterien gefährlich?"], correct: 0, hint: "800/500 = 1,6", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "units_detective", question: "📏 EINHEITEN kontrollieren!", fullText: "Eine Parabel hat die Gleichung f(x) = ax² + bx + c. Der Flug eines Balls dauert 3. Die Höhe wird in gemessen.", secondaryQuestion: "Welche Einheit passt?", answers: ["s, m", "h, km", "min, cm", "s, km"], correct: 0, hint: "Zeit in s, Höhe in m", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT -> TERM!", fullText: "Ein Baum ist 12 m hoch. Er wächst jedes Jahr um 8%.", secondaryQuestion: "Welcher Term berechnet die Höhe nach 5 Jahren?", answers: ["12 × 1,08⁵", "12 + 0,08×5", "12 × 0,08⁵", "12 + 12×0,08×5"], correct: 0, hint: "Exponentielles Wachstum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein rechtwinkliges Dreieck hat die Katheten 6 cm und 8 cm. Die Hypotenuse ist 10 cm. Der Flächeninhalt beträgt 24 cm².", secondaryQuestion: "Welche Info brauchst du für den Umfang NICHT?", answers: ["6 cm", "8 cm", "24 cm²", "10 cm"], correct: 2, hint: "Umfang = Summe aller Seiten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "f(x) = 2x² - 4x + 1. Berechne die Nullstellen mit der pq-Formel.", possibleQuestions: ["Wie lauten die Nullstellen?", "Wie lautet die erste Ableitung?", "Welche Farbe hat der Graph?"], answers: ["Wie lauten die Nullstellen?", "Wie lautet die erste Ableitung?", "Welche Farbe hat der Graph?"], correct: 0, hint: "Zuerst Normalform herstellen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Würfel hat eine Kantenlänge von 5 cm. Er wird aus einem Material mit Dichte 2,5 g/cm³ hergestellt.", secondaryQuestion: "Welche Infos brauchst du für die Masse?", answers: ["5 cm, 2,5 g/cm³", "5 cm, Würfel", "2,5 g/cm³", "5 cm Kantenlänge"], correct: 0, hint: "Masse = Volumen × Dichte", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];