window.__subjectData_math_9g_wachstum = [
    { question: "Ein Wert wächst jeden Monat um 10%. Nach einem Monat hast du 110. Was war der Startwert?", answers: ["90", "100", "110", "120"], correct: 1, hint: "100 × 1,10 = 110", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Wachstum ist exponentiell?", answers: ["+10 pro Monat", "×1,1 pro Monat", "immer gleich", "−5 pro Monat"], correct: 1, hint: "Prozentuales Wachstum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Formel beschreibt exponentielles Wachstum?", answers: ["B(t) = B₀ × (1 + p)ᵗ", "B(t) = B₀ + p×t", "B(t) = B₀ × t", "B(t) = B₀ × p"], correct: 0, hint: "B₀ = Startwert, p = Wachstumsrate", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Kapital von 500€ wird zu 4% angelegt. Wie viel nach 2 Jahren?", answers: ["520€", "540,80€", "540€", "508€"], correct: 1, hint: "500 × 1,04²", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen linearem und exponentiellem Wachstum?", answers: ["Linear: +konstant, Exponentiell: ×konstant", "Linear: ×konstant, Exponentiell: +konstant", "Kein Unterschied", "Beide sind gleich schnell"], correct: 0, hint: "Arithmetisch vs. geometrisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Eine Bakterienkultur verdoppelt sich jede Stunde. Start: 100. Wie viele nach 4 Stunden?", answers: ["400", "800", "1600", "3200"], correct: 2, hint: "100 × 2⁴", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'exponentieller Zerfall'?", answers: ["Wachstum mit negativer Rate", "Abnahme mit konstantem Faktor", "Gleichbleibender Wert", "Lineare Abnahme"], correct: 1, hint: "Z.B. radioaktiver Zerfall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Wert von 200 sinkt jährlich um 5%. Nach 3 Jahren?", answers: ["170", "172,90", "185", "190,50"], correct: 1, hint: "200 × 0,95³", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Graph zeigt exponentielles Wachstum?", answers: ["Eine Gerade", "Eine steil ansteigende Kurve", "Eine fallende Gerade", "Eine horizontale Linie"], correct: 1, hint: "Je länger, desto steiler", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Halbwertszeit?", answers: ["Die Zeit, bis ein Wert auf 0 sinkt", "Die Zeit, bis die Hälfte zerfallen ist", "Die Zeit bis zur Verdopplung", "Die Hälfte der Gesamtzeit"], correct: 1, hint: "Radioaktiver Zerfall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Handy verliert jährlich 20% an Wert. Kaufpreis 800€. Wert nach 2 Jahren?", answers: ["640€", "512€", "480€", "600€"], correct: 1, hint: "800 × 0,8²", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches ist KEIN Beispiel für exponentielles Wachstum?", answers: ["Bevölkerungswachstum", "Zinseszins", "Ein Glas Wasser füllen", "Bakterienvermehrung"], correct: 2, hint: "Konstante Geschwindigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Die Verdopplungszeit einer Population ist 10 Jahre. Start: 1000. Wie viele nach 30 Jahren?", answers: ["3000", "4000", "8000", "6000"], correct: 2, hint: "1000 × 2³", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Faktor beschreibt eine Abnahme um 15%?", answers: ["0,85", "1,15", "0,15", "1,85"], correct: 0, hint: "100% - 15% = 85%", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];