window.__subjectData_eng_8g_vocabulary = [ { question: "What is the opposite of 'polite'?", answers: ["nice", "rude", "friendly", "quiet"], correct: 1, hint: "Bad manners", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Another word for 'huge'?", answers: ["small", "gigantic", "tiny", "average"], correct: 1, hint: "Very big", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'garbage' in British English?", answers: ["trash", "rubbish", "sweets", "flat"], correct: 1, hint: "Waste", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to survive'?", answers: ["to die", "to live through", "to sleep", "to eat"], correct: 1, hint: "Stay alive", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'sidewalk' in British English?", answers: ["pavement", "street", "motorway", "lift"], correct: 0, hint: "Where you walk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'challenging'?", answers: ["easy", "difficult/demanding", "boring", "useless"], correct: 1, hint: "Tests your abilities", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'pollution'?", answers: ["cleaning", "contamination", "fresh air", "nature"], correct: 1, hint: "Environment damage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'opportunity'?", answers: ["problem", "chance", "idea", "work"], correct: 1, hint: "Good moment to do something", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What does 'diverse' mean?", answers: ["the same", "varied", "small", "limited"], correct: 1, hint: "Different types", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to appreciate'?", answers: ["to hate", "to value", "to ignore", "to lose"], correct: 1, hint: "Recognize the worth", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'landmark'?", answers: ["A map", "A recognizable feature/building", "A road", "A forest"], correct: 1, hint: "Famous point of interest", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'common'?", answers: ["rare", "frequent/usual", "strange", "expensive"], correct: 1, hint: "Found often", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is an 'apartment' in BE?", answers: ["flat", "house", "garden", "room"], correct: 0, hint: "Living space", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to increase'?", answers: ["to drop", "to grow/rise", "to stay", "to break"], correct: 1, hint: "Get bigger/more", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to look for'?", answers: ["to find", "to search", "to hide", "to watch"], correct: 1, hint: "Try to find something", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to take part in'?", answers: ["to watch", "to participate", "to leave", "to win"], correct: 1, hint: "Join an activity", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What does 'ancient' mean?", answers: ["modern", "very old", "new", "fast"], correct: 1, hint: "From a long time ago", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to avoid'?", answers: ["to seek", "to keep away from", "to like", "to use"], correct: 1, hint: "Stay away on purpose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to succeed'?", answers: ["to fail", "to manage to do something", "to try", "to wait"], correct: 1, hint: "Get the desired result", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'candy' in British English?", answers: ["biscuits", "sweets", "chips", "crisps"], correct: 1, hint: "Sugar treats", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to depend on'?", answers: ["to need", "to rely on/be decided by", "to hate", "to see"], correct: 1, hint: "abhängen von", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'significant'?", answers: ["small", "important/meaningful", "boring", "red"], correct: 1, hint: "Having a great effect", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to disappear'?", answers: ["to arrive", "to vanish", "to stay", "to grow"], correct: 1, hint: "Cannot be seen anymore", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'vacation' in BE?", answers: ["trip", "holiday", "break", "weekend"], correct: 1, hint: "Time off from work/school", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to be interested in'?", answers: ["to ignore", "to like finding out about", "to hate", "to know"], correct: 1, hint: "Show curiosity", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the synonym of 'fast'?", answers: ["slow", "quick", "happy", "long"], correct: 1, hint: "Speed", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the antonym of 'hard'?", answers: ["difficult", "soft", "easy", "long"], correct: 1, hint: "Opposite of hard", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "How to say 'einfach' in English?", answers: ["easy", "hard", "fast", "slow"], correct: 0, hint: "Not difficult", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'football' in American English?", answers: ["soccer", "football", "rugby", "baseball"], correct: 0, hint: "Played with the feet.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to take care of'?", answers: ["to look after", "to ignore", "to forget", "to hate"], correct: 0, hint: "Sich kümmern.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'truck' in British English?", answers: ["lorry", "van", "car", "bus"], correct: 0, hint: "Big transport vehicle.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'rural'?", answers: ["countryside", "city", "sea", "space"], correct: 0, hint: "Not urban.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Opposite of 'permanent'?", answers: ["temporary", "forever", "long", "stable"], correct: 0, hint: "Short term.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to struggle'?", answers: ["to fight/try hard", "to sleep", "to win easily", "to play"], correct: 0, hint: "Have difficulties.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'gas' in British English?", answers: ["petrol", "oil", "water", "air"], correct: 0, hint: "Fuel for cars.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'reliable'?", answers: ["trustworthy", "fast", "broken", "angry"], correct: 0, hint: "You can count on them.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Opposite of 'ancient'?", answers: ["modern", "old", "broken", "slow"], correct: 0, hint: "New style.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to refuse'?", answers: ["to say no", "to accept", "to help", "to go"], correct: 0, hint: "Ablehnen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'cookie' in British English?", answers: ["biscuit", "cake", "bread", "sweet"], correct: 0, hint: "Small sweet snack.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'to research'?", answers: ["to study/find out", "to lose", "to buy", "to hide"], correct: 0, hint: "Investigate.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'environment'?", answers: ["surroundings/nature", "building", "work", "school"], correct: 0, hint: "Umwelt.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Meaning of 'prejudice'?", answers: ["unfair opinion", "fact", "help", "friend"], correct: 0, hint: "Vorurteil.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the BE word for 'subway'?", answers: ["Underground / Tube", "Metro", "Train", "Highway"], correct: 0, hint: "London transportation.", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
