window.__subjectData_phys_9g_atomphysik = [
    { question: "Aus welchen Teilchen besteht der Atomkern?", answers: ["Protonen und Neutronen", "Protonen und Elektronen", "Neutronen und Elektronen", "Nur Protonen"], correct: 0, hint: "Kernbausteine", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Alpha-Strahlung?", answers: ["Elektronen", "Heliumkerne", "Photonen", "Neutronen"], correct: 1, hint: "Zwei Protonen, zwei Neutronen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Beta-Strahlung?", answers: ["Heliumkerne", "Schnelle Elektronen", "Gammastrahlen", "Neutronen"], correct: 1, hint: "β⁻ = Elektron", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Gamma-Strahlung?", answers: ["Teilchenstrahlung", "Elektromagnetische Wellen", "Heliumkerne", "Elektronen"], correct: 1, hint: "Hochenergetische Photonen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Strahlung hat die größte Reichweite?", answers: ["Alpha", "Beta", "Gamma", "Alle gleich"], correct: 2, hint: "Durchdringendste Strahlung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Abschirmung stoppt Alpha-Strahlung?", answers: ["Ein Blatt Papier", "Ein Bleiblock", "Eine Betonwand", "Wasser"], correct: 0, hint: "Alpha hat geringe Reichweite", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Halbwertszeit?", answers: ["Die Zeit, bis alle Atome zerfallen sind", "Die Zeit, bis die Hälfte der Atome zerfallen ist", "Die halbe Lebensdauer", "Die doppelte Zerfallszeit"], correct: 1, hint: "Radioaktiver Zerfall", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Kernspaltung?", answers: ["Ein schwerer Kern spaltet sich in leichtere", "Zwei leichte Kerne verschmelzen", "Ein Kern gibt Alpha-Teilchen ab", "Ein Kern absorbiert Elektronen"], correct: 0, hint: "Uran-235", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Kernfusion?", answers: ["Schwere Kerne spalten sich", "Leichte Kerne verschmelzen zu schwereren", "Kerne geben Gamma-Strahlung ab", "Kerne zerfallen"], correct: 1, hint: "Sonne, Wasserstoff zu Helium", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Teilchen hat keine Ladung?", answers: ["Proton", "Elektron", "Neutron", "Positron"], correct: 2, hint: "Im Atomkern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie nennt man Atome desselben Elements mit unterschiedlicher Neutronenzahl?", answers: ["Ionen", "Isotope", "Isomere", "Moleküle"], correct: 1, hint: "Verschiedene Massenzahl", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie groß ist ein Atom ungefähr?", answers: ["10⁻⁶ m", "10⁻¹⁰ m", "10⁻¹² m", "10⁻¹⁵ m"], correct: 1, hint: "0,1 Nanometer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Strahlung ionisiert am stärksten?", answers: ["Alpha", "Beta", "Gamma", "Röntgen"], correct: 0, hint: "Große Masse, langsam", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Geiger-Müller-Zählrohr'?", answers: ["Ein Gerät zum Nachweis radioaktiver Strahlung", "Ein Teilchenbeschleuniger", "Ein Kernreaktor", "Ein Röntgengerät"], correct: 0, hint: "Zählt Impulse", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];