window.__subjectData_phys_9g_elektrik = [
    { question: "Welcher Zusammenhang gilt für den elektrischen Widerstand?", answers: ["R = U + I", "R = U × I", "R = U / I", "R = I / U"], correct: 2, hint: "Ohmsches Gesetz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Reihenschaltung?", answers: ["Alle Bauteile haben die gleiche Spannung", "Alle Bauteile liegen hintereinander", "Bauteile sind parallel verbunden", "Die Stromstärke teilt sich auf"], correct: 1, hint: "Ein Strompfad", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie verhält sich der Gesamtwiderstand in einer Parallelschaltung?", answers: ["Rges = R1 + R2", "Rges ist kleiner als der kleinste Einzelwiderstand", "Rges = R1 × R2", "Rges = U / I"], correct: 1, hint: "Mehr Pfade = weniger Gesamtwiderstand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die elektrische Leistung?", answers: ["P = U × I", "P = U / I", "P = I / U", "P = U² × I"], correct: 0, hint: "Watt = Volt × Ampere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Gerät hat 230 V und 2 A. Welche Leistung?", answers: ["115 W", "230 W", "460 W", "920 W"], correct: 2, hint: "230 × 2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert mit dem Gesamtwiderstand, wenn man einen weiteren Widerstand in Reihe schaltet?", answers: ["Er wird kleiner", "Er bleibt gleich", "Er wird größer", "Er wird null"], correct: 2, hint: "Rges = R1 + R2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Berechne den Strom: U = 12 V, R = 4 Ω", answers: ["3 A", "48 A", "0,33 A", "8 A"], correct: 0, hint: "I = U / R", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Bauteil wandelt elektrische Energie in Bewegung um?", answers: ["Widerstand", "Elektromotor", "Kondensator", "Transformator"], correct: 1, hint: "Bewegungsenergie", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Transformator?", answers: ["Ein Gerät zur Spannungsumwandlung", "Ein Widerstand", "Eine Batterie", "Ein Schalter"], correct: 0, hint: "Primär- und Sekundärspule", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wovon hängt die übertragene Spannung eines Transformators ab?", answers: ["Vom Material der Spule", "Vom Windungsverhältnis", "Von der Temperatur", "Von der Kabellänge"], correct: 1, hint: "U1/U2 = N1/N2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Spannungsart kommt aus der Steckdose?", answers: ["Gleichspannung", "Wechselspannung", "Pulsspannung", "Keine Spannung"], correct: 1, hint: "50 Hz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was misst ein Multimeter?", answers: ["Nur Spannung", "Spannung, Stromstärke und Widerstand", "Nur Stromstärke", "Nur Temperatur"], correct: 1, hint: "Universalmessgerät", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein 5 Ω-Widerstand liegt an 10 V. Welcher Strom fließt?", answers: ["0,5 A", "2 A", "5 A", "50 A"], correct: 1, hint: "I = U / R", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wozu dient ein Sicherungsautomat?", answers: ["Strom zu sparen", "Bei Überstrom den Stromkreis zu unterbrechen", "Spannung zu erhöhen", "Licht einzuschalten"], correct: 1, hint: "Schutz vor Überlast", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];