window.__subjectData_phys_9g_energie = [
    { question: "Welche Einheit hat Energie?", answers: ["Watt", "Joule", "Volt", "Newton"], correct: 1, hint: "Nach dem Physiker James Joule", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was besagt der Energieerhaltungssatz?", answers: ["Energie kann erzeugt werden", "Energie kann nicht verloren gehen", "Energie gibt es nur als Wärme", "Energie ist immer elektrisch"], correct: 1, hint: "Energie wird umgewandelt, nicht vernichtet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Energieform hat ein bewegtes Auto?", answers: ["Lageenergie", "Bewegungsenergie (kinetisch)", "Wärmeenergie", "Chemische Energie"], correct: 1, hint: "E = ½mv²", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Energieform hat ein Wasserkraftwerk als Ausgangspunkt?", answers: ["Kernenergie", "Lageenergie (potentielle Energie)", "Elektrische Energie", "Wärmeenergie"], correct: 1, hint: "Wasser in höherer Lage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Berechne die kinetische Energie: m = 1000 kg, v = 20 m/s", answers: ["10.000 J", "20.000 J", "200.000 J", "400.000 J"], correct: 2, hint: "E = ½ × 1000 × 20²", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Wirkungsgrad?", answers: ["Nutzenergie / zugeführte Energie", "zugeführte Energie / Nutzenergie", "Nutzenergie × zugeführte Energie", "Nutzenergie - Verlustenergie"], correct: 0, hint: "η < 1, meist in %", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Energieform ist in einer Batterie gespeichert?", answers: ["Elektrische Energie", "Chemische Energie", "Wärmeenergie", "Kernenergie"], correct: 1, hint: "Elektrochemische Reaktionen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Motor hat einen Wirkungsgrad von 80%. 1000 J werden zugeführt. Wie viel Nutzenergie?", answers: ["200 J", "800 J", "1000 J", "80 J"], correct: 1, hint: "1000 × 0,80", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die potenzielle Energie eines 2 kg schweren Buchs in 1,5 m Höhe?", answers: ["3 J", "15 J", "29,4 J", "30 J"], correct: 2, hint: "E = m × g × h (g = 9,81)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Energieumwandlung findet in einer Glühlampe statt?", answers: ["Chemisch → Licht", "Elektrisch → Wärme + Licht", "Kinetisch → Elektrisch", "Wärme → Kinetisch"], correct: 1, hint: "Wärme ist das Hauptprodukt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Leistung' in der Physik?", answers: ["Energie pro Zeit", "Kraft pro Weg", "Arbeit pro Strecke", "Spannung mal Strom"], correct: 0, hint: "P = E / t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein 60 W-Gerät läuft 2 Stunden. Wieviel Energie?", answers: ["30 Wh", "120 Wh", "432.000 J", "60 J"], correct: 2, hint: "60 × 2 × 3600", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "In welche Energie wird elektrische Energie in einem Toaster umgewandelt?", answers: ["Kinetisch", "Wärme", "Licht", "Chemisch"], correct: 1, hint: "Heizdraht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen Energie und Leistung?", answers: ["Leistung = Energie / Zeit", "Energie = Leistung / Zeit", "Kein Unterschied", "Leistung ist eine Energieform"], correct: 0, hint: "kW vs. kWh", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];