window.__subjectData_phys_9g_magnetismus = [
    { question: "Was ist elektromagnetische Induktion?", answers: ["Strom erzeugt Wärme", "Bewegung im Magnetfeld erzeugt Spannung", "Magnet zieht Eisen an", "Elektronen kreisen um den Kern"], correct: 1, hint: "Faraday, Generator", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wovon hängt die Induktionsspannung ab?", answers: ["Nur von der Temperatur", "Von der Änderungsgeschwindigkeit des Magnetfelds", "Vom Material der Spule", "Von der Farbe des Kabels"], correct: 1, hint: "Je schneller, desto höher", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Größe beeinflusst die Induktionsspannung?", answers: ["Windungszahl, Magnetstärke, Geschwindigkeit", "Nur die Windungszahl", "Nur die Magnetstärke", "Nur die Geschwindigkeit"], correct: 0, hint: "Drei Faktoren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Generator?", answers: ["Ein Gerät, das Bewegung in Strom umwandelt", "Ein Gerät, das Strom in Bewegung umwandelt", "Ein Widerstand", "Eine Batterie"], correct: 0, hint: "Induktion nutzen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen Generator und Elektromotor?", answers: ["Generator: Bewegung→Strom, Motor: Strom→Bewegung", "Kein Unterschied", "Generator: Strom→Bewegung, Motor: Bewegung→Strom", "Beide wandeln in Wärme um"], correct: 0, hint: "Energieflussrichtung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie kann man die Induktionsspannung erhöhen?", answers: ["Schnellere Bewegung, mehr Windungen, stärkerer Magnet", "Langsamere Bewegung", "Weniger Windungen", "Kupferkabel durch Aluminium ersetzen"], correct: 0, hint: "Mehr Änderung pro Zeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Lenzsche Regel?", answers: ["Die induzierte Spannung wirkt ihrer Ursache entgegen", "Strom fließt immer im Kreis", "Spannung ist proportional zum Strom", "Magnetfelder sind immer kreisförmig"], correct: 0, hint: "Gegenwirkung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert, wenn ein Magnet in eine Spule bewegt wird?", answers: ["Es entsteht ein Strom in der Spule", "Nichts", "Die Spule wird warm", "Der Magnet schmilzt"], correct: 0, hint: "Induktion bei Bewegung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielt Eisen im Elektromagneten?", answers: ["Verstärkt das Magnetfeld der Spule", "Leitet den Strom besser", "Schützt vor Überhitzung", "Isoliert die Spule"], correct: 0, hint: "Weichmagnetischer Kern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Farbe hat der Nordpol eines Magneten oft?", answers: ["Grün", "Rot", "Blau", "Gelb"], correct: 1, hint: "Nordpol ist meist rot markiert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'magnetischem Fluss'?", answers: ["Die Anzahl der Feldlinien durch eine Fläche", "Die Bewegung von Magneten", "Der Strom in einer Spule", "Die Wärme eines Magneten"], correct: 0, hint: "Φ = B × A", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wovon hängt die Lorentzkraft ab?", answers: ["Ladung, Geschwindigkeit, Magnetfeld", "Nur von der Ladung", "Nur vom Magnetfeld", "Nur von der Geschwindigkeit"], correct: 0, hint: "F = q × v × B", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "In welcher Einheit misst man die magnetische Flussdichte?", answers: ["Tesla", "Volt", "Ampere", "Weber"], correct: 0, hint: "T", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie erzeugt man Gleichstrom in einem Generator?", answers: ["Mit einem Kommutator (Stromwender)", "Mit einem Transformator", "Mit einem Kondensator", "Mit einem Widerstand"], correct: 0, hint: "Wechselt die Stromrichtung mechanisch", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];