window.__subjectData_phys_9g_textaufgaben_verstehen = [
    { mode: "units_detective", question: "📏 EINHEITEN kontrollieren!", fullText: "Eine Glühbirne hat 60 Watt und brennt 5 Stunden. Berechne die Energie.", unitInfo: "W = Joule pro Sekunde", answers: ["300 J", "300 Wh", "12 Wh", "1.080.000 J"], correct: 3, hint: "60 W × 5 h × 3600 s", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Auto mit 1200 kg beschleunigt von 0 auf 30 m/s in 10 Sekunden. Die Motorleistung beträgt 150 kW.", possibleQuestions: ["Wie groß ist die Beschleunigung?", "Welche Farbe hat das Auto?", "Wer hat den Motor gebaut?"], answers: ["Wie groß ist die Beschleunigung?", "Welche Farbe hat das Auto?", "Wer hat den Motor gebaut?"], correct: 0, hint: "a = Δv / Δt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Eine Heizplatte hat 2000 W, Wirkungsgrad 90%. Sie erhitzt 1 Liter Wasser von 20°C auf 100°C. Wärmekapazität Wasser: 4,2 kJ/(kg×K).", secondaryQuestion: "Welche Infos brauchst du für die benötigte Zeit?", answers: ["2000 W, 90%, 1kg, 80K, 4,2 kJ/(kg×K)", "2000 W, 90%, 1 Liter", "1 Liter, 80K, 4,2", "2000 W, 1 Liter, 80K"], correct: 0, hint: "E = P×t×η, E = m×c×ΔT", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Kernkraftwerk hat eine Leistung von 1400 MW. Der Wirkungsgrad beträgt 33%. Es verbraucht 3 g Uran-235 pro Sekunde.", secondaryQuestion: "Welche Info ist für die elektrische Nutzleistung NICHT nötig?", answers: ["1400 MW", "Wirkungsgrad 33%", "3 g Uran-235/s", "Leistung"], correct: 2, hint: "Uranverbrauch ist für die elektrische Leistungsangabe irrelevant", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT -> TERM!", fullText: "Ein Elektroauto hat 400 kg Batterie mit 0,25 kWh/kg. Es verbraucht 15 kWh/100 km.", secondaryQuestion: "Welcher Term berechnet die Reichweite?", answers: ["400 × 0,25 / 15 × 100", "400 × 0,25 × 15 / 100", "400 / 0,25 × 15", "400 × 15 / 0,25"], correct: 0, hint: "Energie ÷ Verbrauch × 100", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Generator erzeugt 400 V und 50 A. Das Kabel hat einen Widerstand von 0,5 Ω.", possibleQuestions: ["Welche Spannung hat der Generator?", "Wie viel Leistung geht im Kabel verloren?", "Wie lang ist das Kabel?"], answers: ["Welche Spannung hat der Generator?", "Wie viel Leistung geht im Kabel verloren?", "Wie lang ist das Kabel?"], correct: 1, hint: "Pverlust = I² × R", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Transformator hat 500 Primärwindungen und 50 Sekundärwindungen. Die Eingangsspannung beträgt 230 V.", secondaryQuestion: "Welche Info brauchst du für die Ausgangsspannung NICHT?", answers: ["500 Windungen", "50 Windungen", "230 V", "Nennleistung des Trafos"], correct: 3, hint: "U1/U2 = N1/N2", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Ball von 0,5 kg wird aus 10 m Höhe fallen gelassen. g = 9,81 m/s².", possibleQuestions: ["Welche kinetische Energie hat der Ball am Boden?", "Wie heißt der Ball?", "Welche Farbe hat der Ball?"], answers: ["Welche kinetische Energie hat der Ball am Boden?", "Wie heißt der Ball?", "Welche Farbe hat der Ball?"], correct: 0, hint: "Ekin = Epot = m×g×h", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Wasserfall hat 50 m Höhe. 500 m³ Wasser stürzen pro Sekunde herab. Dichte: 1000 kg/m³, g = 9,81.", secondaryQuestion: "Welche Infos brauchst du für die maximale Leistung?", answers: ["50 m, 500 m³/s, 1000 kg/m³, 9,81", "50 m, 500 m³/s", "50 m, 9,81", "500 m³/s, 1000 kg/m³"], correct: 0, hint: "P = m×g×h / t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Atom zerfällt mit einer Halbwertszeit von 10 Jahren. Startmasse: 80 g.", possibleQuestions: ["Nach wie vielen Jahren sind 10 g übrig?", "Wie heißt das Atom?", "Welche Farbe hat das Atom?"], answers: ["Nach wie vielen Jahren sind 10 g übrig?", "Wie heißt das Atom?", "Welche Farbe hat das Atom?"], correct: 0, hint: "80 → 40 → 20 → 10 (3 Halbwertszeiten)", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];