window.__subjectData_phys_7r_akustik = [
    { question: "Wie breitet sich Schall aus?", answers: ["Als Welle", "Als Teilchenstrom", "Gar nicht", "Nur im Wasser"], correct: 0, hint: "Schwingungen in der Luft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "In welcher Einheit misst man die Lautstärke?", answers: ["Volt", "Dezibel", "Grad", "Watt"], correct: 1, hint: "dB", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "In welchem Medium breitet sich Schall am schnellsten aus?", answers: ["Luft", "Wasser", "Festkörper (z.B. Metall)", "Vakuum"], correct: 2, hint: "Teilchen sind dichter gepackt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bestimmt die Tonhöhe?", answers: ["Die Lautstärke", "Die Frequenz", "Die Geschwindigkeit", "Der Luftdruck"], correct: 1, hint: "Hz (Hertz)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Echo'?", answers: ["Verstärkung des Tons", "Reflexion des Schalls", "Absorption des Schalls", "Neuer Ton"], correct: 1, hint: "Schall wird zurückgeworfen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Infraschall'?", answers: ["Schall mit sehr hoher Frequenz", "Schall unter 16 Hz (für Menschen nicht hörbar)", "Schall im Hörbereich", "Sehr lauter Schall"], correct: 1, hint: "Frequenz zu niedrig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Ultraschall'?", answers: ["Schall über 20.000 Hz", "Schall unter 16 Hz", "Sehr leiser Schall", "Schall im Wasser"], correct: 0, hint: "Für Menschen nicht hörbar, aber für Hunde", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wovon hängt die Lautstärke ab?", answers: ["Von der Frequenz", "Von der Amplitude (Schwingungsweite)", "Von der Wellenlänge", "Vom Material"], correct: 1, hint: "Größere Ausschläge = lauter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie fast ertönt ein lauter Ton in Dezibel?", answers: ["20-40 dB", "60-80 dB", "90-120 dB", "200-300 dB"], correct: 2, hint: "Schmerzgrenze ca. 120 dB", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Schallquelle?", answers: ["Ein Gegenstand, der Schall aufnimmt", "Ein Gegenstand, der Schall erzeugt", "Ein Instrument", "Ein Lautsprecher"], correct: 1, hint: "Gitarre, Stimme, Motor", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie kann man Lärm reduzieren?", answers: ["Schalldämmung und Schallschluckung", "Lauter sprechen", "Fenster öffnen"], correct: 0, hint: "Dämmstoffe, Ohrstöpsel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Hörbereich'?", answers: ["Der Frequenzbereich, den ein Lebewesen hören kann", "Die maximale Lautstärke", "Die Entfernung zu einer Schallquelle", "Der Ort des Hörens"], correct: 0, hint: "Mensch: 16-20.000 Hz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Instrument erzeugt Töne durch Saitenschwingung?", answers: ["Trompete", "Gitarre", "Flöte", "Trommel"], correct: 1, hint: "Zupfinstrument", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Warum hört man einen Knall, wenn ein Überschallflugzeug die Schallmauer durchbricht?", answers: ["Weil es schneller ist als der Schall", "Weil der Motor explodiert", "Weil die Luft plötzlich stoppt", "Weil es sehr laut ist"], correct: 0, hint: "Überschallgeschwindigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];