window.__subjectData_phys_7r_elektrizitaet = [
    { question: "Welche Einheit hat die elektrische Spannung?", answers: ["Ampere", "Volt", "Ohm", "Watt"], correct: 1, hint: "Abkürzung: V", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Stromkreis braucht eine...", answers: ["Unterbrechung", "Geschlossene Leitung", "Nur eine Batterie", "Ein Kabel"], correct: 1, hint: "Strom kann nur fließen, wenn ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Einheit hat die Stromstärke?", answers: ["Volt", "Ampere", "Ohm", "Watt"], correct: 1, hint: "A", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Leiter?", answers: ["Ein Material, das Strom leitet", "Ein Material, das Strom isoliert", "Ein Schalter", "Eine Batterie"], correct: 0, hint: "Metalle sind gute ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Isolator?", answers: ["Ein Material, das Strom leitet", "Ein Material, das Strom nicht leitet", "Ein Sicherungskasten", "Ein Kabel"], correct: 1, hint: "Plastik, Gummi, Holz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie werden Batterien in einer Reihenschaltung geschaltet?", answers: ["Nebeneinander", "Hintereinander (Plus an Minus)", "Parallel", "Kreuzweise"], correct: 1, hint: "Spannung addiert sich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei einem Kurzschluss?", answers: ["Der Stromkreis ist unterbrochen", "Strom fließt auf direktem Weg ohne Verbraucher", "Die Lampe leuchtet heller", "Nichts passiert"], correct: 1, hint: "Gefährlich! Hoher Stromfluss", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bauteile gehören zu einem einfachen Stromkreis?", answers: ["Batterie, Lampe, Kabel, Schalter", "Nur Batterie und Lampe", "Batterie, Lampe, Motor", "Lampe, Kabel, Schalter"], correct: 0, hint: "Stromquelle, Verbraucher, Leitung, Steuerung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was misst man mit einem Voltmeter?", answers: ["Stromstärke", "Spannung", "Widerstand", "Leistung"], correct: 1, hint: "Parallel geschaltet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was misst man mit einem Amperemeter?", answers: ["Spannung", "Stromstärke", "Widerstand", "Leistung"], correct: 1, hint: "In Reihe geschaltet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Spannung hat eine normale Haushaltssteckdose in Deutschland?", answers: ["12 V", "110 V", "230 V", "400 V"], correct: 2, hint: "Wechselspannung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Widerstand?", answers: ["Ein Verbraucher, der Strom in Wärme umwandelt", "Ein Schalter", "Eine Batterie", "Ein Kabel"], correct: 0, hint: "Ohmsches Gesetz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Schaltung leuchtet heller: Zwei gleiche Lampen in Reihe oder parallel?", answers: ["Reihe", "Parallel", "Gleich hell", "Kommt auf die Batterie an"], correct: 1, hint: "Jede Lampe bekommt volle Spannung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist elektrische Energie?", answers: ["Die Fähigkeit, Arbeit zu verrichten", "Die Anzahl der Elektronen", "Die Spannung", "Der Widerstand"], correct: 0, hint: "E = P × t", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];