window.__subjectData_phys_7r_magnetismus = [
    { question: "Welches Metall wird von Magneten angezogen?", answers: ["Kupfer", "Eisen", "Aluminium", "Gold"], correct: 1, hint: "Ferromagnetisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ein Magnet hat immer...", answers: ["Nur einen Nordpol", "Zwei Pole", "Nur einen Südpol", "Vier Pole"], correct: 1, hint: "Nord- und Südpol", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Gleiche Pole eines Magneten...", answers: ["Ziehen sich an", "Stoßen sich ab", "Heben sich auf", "Verstärken sich"], correct: 1, hint: "Nord-Nord oder Süd-Süd", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Ungleiche Pole eines Magneten...", answers: ["Ziehen sich an", "Stoßen sich ab", "Heben sich auf", "Verstärken sich"], correct: 0, hint: "Nord-Süd", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Elektromagnet?", answers: ["Ein permanenter Magnet", "Eine Spule mit Eisenkern, die durch Strom magnetisch wird", "Ein Magnet aus Kunststoff", "Ein Supraleiter"], correct: 1, hint: "Strom erzeugt Magnetfeld", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie kann man die Stärke eines Elektromagneten erhöhen?", answers: ["Mehr Windungen auf der Spule", "Weniger Strom", "Kürzeres Kabel", "Kleineren Eisenkern"], correct: 0, hint: "Mehr Windungen = stärkeres Feld", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wofür verwendet man Magnete im Alltag?", answers: ["Nur Spielzeug", "Motoren, Lautsprecher, Kühlschrankmagnete", "Nur in der Medizin", "Nur in Kraftwerken"], correct: 1, hint: "Viele elektrische Geräte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was zeigt ein Kompass an?", answers: ["Die Temperatur", "Die Himmelsrichtung", "Die Höhe", "Die Geschwindigkeit"], correct: 1, hint: "Magnetnadel zeigt nach Norden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Das Magnetfeld der Erde...", answers: ["Gibt es nicht", "Schützt uns vor Sonnenwinden", "Wird schwächer, je höher man kommt", "Ist überall gleich stark"], correct: 1, hint: "Van-Allen-Gürtel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Stoffe sind nicht magnetisch?", answers: ["Nickel", "Eisen", "Kobalt", "Kupfer"], correct: 3, hint: "Nur ferromagnetische Stoffe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert, wenn man einen Magneten durchschneidet?", answers: ["Er verliert seinen Magnetismus", "Es entstehen zwei Magnete mit je Nord- und Südpol", "Es entsteht ein Nordpol und ein Südpol getrennt", "Er explodiert"], correct: 1, hint: "Jedes Teilstück ist ein vollständiger Magnet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie kann man einen Magneten entmagnetisieren?", answers: ["Durch starke Hitze oder Hammerschläge", "Durch Kälte", "Durch Wasser", "Durch Isolierung"], correct: 0, hint: "Zerstörung der Elementarmagnete", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Magnetfeld?", answers: ["Ein Feld, das eine Kraft bewegte Ladungen ausübt", "Ein Feld, das nur Eisen anzieht", "Ein Bereich ohne Schwerkraft", "Ein Energiefeld"], correct: 0, hint: "Unsichtbar, aber nachweisbar", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Tiere nutzen das Erdmagnetfeld zur Orientierung?", answers: ["Hunde", "Zugvögel", "Katzen", "Fische"], correct: 1, hint: "Sie fliegen tausende Kilometer", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];