window.__subjectData_phys_7r_optik = [
    { question: "Wie bewegt sich Licht fort?", answers: ["Im Kreis", "Geradlinig", "Im Zickzack", "Es steht still"], correct: 1, hint: "Lichtstrahlen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert mit Licht an einem Spiegel?", answers: ["Absorption", "Reflexion", "Brechung", "Beugung"], correct: 1, hint: "Licht wird zurückgeworfen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert mit Licht an einer Linse?", answers: ["Reflexion", "Brechung", "Absorption", "Beugung"], correct: 1, hint: "Sammel- und Zerstreuungslinsen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Farben hat das Licht eines Regenbogens?", answers: ["Alle Farben", "Nur Rot und Blau", "Nur Gelb und Grün", "Nur drei Farben"], correct: 0, hint: "Spektralfarben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der 'Einfallswinkel' bei der Reflexion?", answers: ["Winkel zwischen Lichtstrahl und Spiegel", "Winkel zwischen einfallendem Strahl und Lot", "Winkel zwischen Spiegel und Lot", "Der Winkel im Dreieck"], correct: 1, hint: "Winkel zum Lot", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Linse sammelt Licht?", answers: ["Zerstreuungslinse", "Sammellinse (konvex)", "Konkavlinse", "Planscheibe"], correct: 1, hint: "Nach außen gewölbt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Lichtgeschwindigkeit'?", answers: ["Licht ist sehr schnell", "ca. 300.000 km/s", "ca. 3000 km/s", "ca. 300 km/s"], correct: 1, hint: "Schnellste Geschwindigkeit im Universum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Farbe hat Licht mit der größten Wellenlänge?", answers: ["Blau", "Rot", "Grün", "Gelb"], correct: 1, hint: "Langsamste Lichtfarbe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie entsteht ein Schatten?", answers: ["Durch Brechung", "Wenn Licht durch ein Objekt blockiert wird", "Durch Reflexion", "Durch Wärme"], correct: 1, hint: "Licht kann nicht um Gegenstände herum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Lochkamera?", answers: ["Ein Apparat mit einer Linse", "Ein abgedunkelter Raum mit einem kleinen Loch", "Ein Spiegel", "Ein Fernglas"], correct: 1, hint: "Einfachste Form einer Kamera", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert mit Licht, das auf eine weiße Fläche fällt?", answers: ["Es wird absorbiert", "Es wird fast vollständig reflektiert", "Es wird gebrochen", "Es wird ausgelöscht"], correct: 1, hint: "Weiß reflektiert alle Farben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Brille korrigiert Kurzsichtigkeit?", answers: ["Sammellinse", "Zerstreuungslinse (konkav)", "Prisma", "Keine Brille"], correct: 1, hint: "Konkavlinse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Brechung?", answers: ["Rückkehr des Lichts", "Richtungsänderung beim Übergang zwischen Medien", "Verschlucken des Lichts", "Verstärkung des Lichts"], correct: 1, hint: "Wasser -> Luft, Glas -> Luft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Spiegel erzeugt ein vergrößertes Bild?", answers: ["Ebenenspiegel", "Hohlspiegel (konkav)", "Konvexspiegel", "Rückspiegel"], correct: 1, hint: "Nach innen gewölbt", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];