window.__subjectData_phys_7r_textaufgaben_verstehen = [
    { mode: "units_detective", question: "📏 EINHEITEN kontrollieren!", fullText: "Ein Elektrogerät hat eine Leistung von 2000 Watt. Es läuft 3 Stunden.", unitInfo: "Leistung (W) × Zeit (h) = Energie (Wh)", answers: ["2000 Wh", "6000 Wh", "2003 Wh", "2000 W"], correct: 1, hint: "2000 W × 3 h = 6000 Wh", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Auto fährt 120 km/h. Es braucht 2,5 Stunden für eine Strecke. Der Tank fasst 50 Liter.", possibleQuestions: ["Wie weit ist die Strecke?", "Welche Farbe hat das Auto?", "Wie viele Türen hat das Auto?"], answers: ["Wie weit ist die Strecke?", "Welche Farbe hat das Auto?", "Wie viele Türen hat das Auto?"], correct: 0, hint: "s = v × t", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Kühlschrank hat eine Leistung von 150 W und läuft 10 Stunden pro Tag. Strom kostet 0,30€ pro kWh.", secondaryQuestion: "Welche Infos brauchst du für die täglichen Stromkosten?", answers: ["150 W, 10 h, 0,30€/kWh", "150 W, 0,30€/kWh", "10 h, 0,30€/kWh", "150 W, 10 h"], correct: 0, hint: "Energie = Leistung × Zeit, dann × Preis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Ball fällt aus 20 m Höhe. Er wiegt 200 g und hat einen Durchmesser von 10 cm. Die Erdbeschleunigung ist 9,81 m/s².", secondaryQuestion: "Welche Info brauchst du für die Fallzeit NICHT?", answers: ["20 m Höhe", "200 g", "9,81 m/s²", "Fallzeit = √(2h/g)"], correct: 1, hint: "Die Masse ist irrelevant für die Fallzeit (im Vakuum)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->TERM übersetzen!", fullText: "Ein Wasserkocher hat 2000 W und erhitzt Wasser in 3 Minuten von 20°C auf 100°C.", secondaryQuestion: "Welcher Term berechnet die elektrische Energie?", answers: ["2000 × 3 × 60", "2000 × 3", "2000 / 3", "2000 + 3"], correct: 0, hint: "Energie = Leistung × Zeit (in Sekunden)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Eine Glühbirne hat 60 W und brennt 5 Stunden pro Tag. Eine LED-Lampe hat 10 W bei gleicher Helligkeit.", possibleQuestions: ["Welche Farbe hat die Lampe?", "Wie viel Energie spart die LED pro Tag?", "Wer hat die Glühbirne erfunden?"], answers: ["Welche Farbe hat die Lampe?", "Wie viel Energie spart die LED pro Tag?", "Wer hat die Glühbirne erfunden?"], correct: 1, hint: "(60 - 10) × 5", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "units_detective", question: "📏 EINHEITEN kontrollieren!", fullText: "Ein LKW fährt 80 km in 60. Ein Zug fährt 300 in 2 Stunden. Ein Fahrradfahrer fährt 15 pro Stunde.", secondaryQuestion: "Welche Einheit passt in alle Lücken?", answers: ["km, Minuten, km/h", "km/h, km, km", "Minuten, km, km/h", "km, km/h, km"], correct: 0, hint: "Strecke in km, Zeit in Minuten / Stunden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Ein Generator erzeugt 500 V Spannung. Die Turbine dreht sich mit 3000 U/min. Der Generator wiegt 2 Tonnen.", secondaryQuestion: "Welche Info brauchst du für die erzeugte Leistung NICHT?", answers: ["500 V", "3000 U/min", "2 Tonnen", "Stromstärke I"], correct: 2, hint: "P = U × I (Gewicht ist irrelevant)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Ein Solarmodul hat 300 W Leistung und scheint 4 Stunden am Tag mit voller Sonne. Eine Lampe braucht 50 W.", secondaryQuestion: "Welche Infos brauchst du für 'Wie viele Lampen können 4 Stunden betrieben werden?'", answers: ["300 W, 4 h, 50 W pro Lampe", "300 W, 50 W", "4 h, 300 W", "300 W, 4 h"], correct: 0, hint: "Gesamtenergie ÷ Energie pro Lampe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Heizlüfter hat 2000 W und läuft 30 Minuten. Der Strompreis beträgt 0,25€ pro kWh.", possibleQuestions: ["Wie viel kostet der Betrieb?", "Wer hat den Heizlüfter gebaut?", "Welche Farbe hat das Gerät?"], answers: ["Wie viel kostet der Betrieb?", "Wer hat den Heizlüfter gebaut?", "Welche Farbe hat das Gerät?"], correct: 0, hint: "1,0 kWh × 0,25€", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->TERM übersetzen!", fullText: "Ein Fahrrad fährt 18 km/h und braucht 20 Minuten für den Schulweg.", secondaryQuestion: "Welcher Term berechnet den Schulweg?", answers: ["18 × 20/60", "18 + 20", "18 / 20", "18 × 20"], correct: 0, hint: "s = v × t (t in Stunden)", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];