window.__subjectData_math_8g_textaufgaben_verstehen = [ { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Die lineare Funktion y = -2x + 10 beschreibt den Wasserstand. Der Pool ist blau gestrichen. Die Messung fand an einem Dienstag um 14 Uhr statt. Wann ist der Pool leer (y=0)?", secondaryQuestion: "Welche Info ist NICHT relevant für die Berechnung?", answers: ["Die Funktion y = -2x + 10", "Die blaue Farbe & Uhrzeit", "Der Zielwert y=0", "Die Variable x"], correct: 1, hint: "Mathematische Modelle ignorieren ästhetische Details.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Ein Kapital von 2000€ wird mit 3% verzinst. Die Bank hat 5 Filialen in der Stadt. Die Zinsen werden nach einem Jahr gutgeschrieben.", possibleQuestions: ["Wie viele Mitarbeiter hat die Bank?", "Wie hoch ist das Kapital nach 12 Monaten?", "In welcher Währung wird gespart?"], answers: ["Wie viele Mitarbeiter hat die Bank?", "Wie hoch ist das Kapital nach 12 Monaten?", "In welcher Währung wird gespart?"], correct: 1, hint: "Fragen müssen mit den gegebenen Zahlen (K, p, t) lösbar sein.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { mode: "info_jigsaw", question: "🧩 WICHTIGE Sätze wählen!", fullText: "Satz 1: Ein Prisma hat eine Trapez-Grundfläche. | Satz 2: Das Trapez hat die Seiten a=5, c=3 und die Höhe h_t=4. | Satz 3: Das Prisma ist 10cm hoch (h_p). | Satz 4: Das Prisma wiegt 500g. | Frage: Berechne das Volumen.", possibleAnswers: ["Sätze 1, 2, 3", "Sätze 1, 2, 4", "Sätze 2, 3, 4", "Alle Sätze"], answers: ["Sätze 1, 2, 3", "Sätze 1, 2, 4", "Sätze 2, 3, 4", "Alle Sätze"], correct: 0, hint: "Für das Volumen brauchst du nur die Geometrie (G und h_p), nicht das Gewicht.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { mode: "units_detective", question: "📏 EINHEITEN kontrollieren!", fullText: "Ein x-y-Koordinatensystem hat die Achseneinteilung 1 LE = 1 cm. Eine Gerade hat die Steigung m = 0,5. Wie viele cm geht man nach oben, wenn man 4 cm nach rechts geht?", unitInfo: "Steigung m = Delta y / Delta x", answers: ["0,5 cm", "2 cm", "4 cm", "8 cm"], correct: 1, hint: "Rechnung: 4 * 0,5 = 2.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { mode: "question_clarity", question: "📋 FRAGE vereinfachen!", fullText: "Zwei Geraden g1: y = 2x + 3 und g2: y = -x + 9 schneiden sich in einem Punkt P. Welche Information wird eigentlich gesucht, wenn man nach den Koordinaten von P fragt?", simplifiedVersions: ["Wann ist 2x + 3 = -x + 9?", "Wo liegt P?", "Was ist m1 und m2?"], answers: ["Wann ist 2x + 3 = -x + 9?", "Wo liegt P?", "Was ist m1 und m2?"], correct: 0, hint: "Ein Schnittpunkt ist die Lösung des Gleichsetzungsverfahrens.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein Zug fährt 80 km in einer Stunde. Wie weit fährt er in 3 Stunden?", answers: ["80 km", "160 km", "240 km", "320 km"], correct: 2, hint: "Mal rechnen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Ein Produkt kostet 20% weniger als 50€. Was ist der neue Preis?", answers: ["40€", "45€", "30€", "48€"], correct: 0, hint: "Prozentrechnung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Wenn 5 Äpfel 2,50€ kosten, was kostet ein Apfel?", answers: ["0,25€", "0,50€", "0,75€", "1,00€"], correct: 1, hint: "Einheiten", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
