window.__subjectData_lat_9g_grammatik = [
    { question: "Was ist ein Participium Coniunctum (PC)?", answers: ["Ein Hauptsatz", "Ein Partizip, das sich auf ein Subjekt bezieht", "Eine Zeitform", "Ein Verb im Infinitiv"], correct: 1, hint: "Mittelwort + Bezugswort", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie übersetzt man einen AcI?", answers: ["Dass-Satz", "Hauptsatz", "Nebensatz mit 'weil'", "Relativsatz"], correct: 0, hint: "Accusativus cum Infinitivo", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie übersetzt man ein PPP als PC?", answers: ["Nachdem ... worden war", "Während", "Bevor", "Weil"], correct: 0, hint: "Passiv, Vorzeitigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie übersetzt man ein PPA als PC?", answers: ["Während / Im Begriff zu ...", "Nachdem", "Bevor", "Weil"], correct: 0, hint: "Aktiv, Gleichzeitigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Ablativus Absolutus (Abl. Abs.)?", answers: ["Ein Partizip mit Bezugswort im Ablativ", "Ein Hauptsatz", "Ein AcI", "Ein Finalsatz"], correct: 0, hint: "Unabhängige Partizipialkonstruktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Funktion kann ein nd-Form (Gerundium) haben?", answers: ["Subjekt / Objekt mit 'zu'", "Nur Objekt", "Nur Subjekt", "Nur Adverb"], correct: 0, hint: "Ars amandi = Die Kunst zu lieben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Gerundivum?", answers: ["Ein verbaladjektiv mit passiver Bedeutung ('zu + Partizip')", "Ein Verb im Futur", "Ein Partizip Präsens", "Ein Infinitiv"], correct: 0, hint: "Gerundivum mit esse = Notwendigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie übersetzt man einen Finalsatz im Lateinischen?", answers: ["ut / ne + Konjunktiv", "quod + Indikativ", "cum + Konjunktiv", "dum + Indikativ"], correct: 0, hint: "Damit / damit nicht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was drückt der Konjunktiv im Hauptsatz aus?", answers: ["Wunsch, Aufforderung, Möglichkeit", "Realität, Tatsache", "Nur Vergangenheit", "Nur Zukunft"], correct: 0, hint: "Adhortativ, Jussiv, Optativ", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann verwendet man 'cum narrativum'?", answers: ["cum + Konjunktiv = während, nachdem, weil", "cum + Indikativ", "cum + Infinitiv", "cum + Gerundiv"], correct: 0, hint: "Erzählendes cum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Relativsatz der Charakteristik'?", answers: ["Relativsatz mit Konjunktiv zur Beschreibung einer Eigenschaft", "Relativsatz mit Indikativ", "Ein Hauptsatz", "Ein AcI"], correct: 0, hint: "qui + Konjunktiv", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie werden indirekte Fragesätze eingeleitet?", answers: ["Fragepronomen / -adverb + Konjunktiv", "Nur mit ut", "Nur mit ne", "Mit quod"], correct: 0, hint: "Frage im Nebensatz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Consecutio Temporum'?", answers: ["Die Zeitenfolge im Konjunktiv", "Die Deklination", "Die Steigerung", "Die Wortstellung"], correct: 0, hint: "Abhängigkeit der Zeiten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie wird ein Konditionalsatz im Lateinischen gebildet?", answers: ["si + Konjunktiv (Irrealis) oder Indikativ (Real)", "si + Infinitiv", "si + Gerundiv", "si + Partizip"], correct: 0, hint: "Real, Potential, Irrealis", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];