window.__subjectData_lat_9g_roemische_geschichte = [
    { question: "Wer war der erste römische Kaiser?", answers: ["Julius Caesar", "Augustus", "Nero", "Trajan"], correct: 1, hint: "Begründer des Prinzipats", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Ereignis gilt als Ende des Weströmischen Reichs?", answers: ["Schlacht im Teutoburger Wald", "Absetzung des letzten Kaisers 476 n.Chr.", "Eroberung durch Hannibal", "Brand Roms"], correct: 1, hint: "Romulus Augustulus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann wurde Rom der Legende nach gegründet?", answers: ["753 v. Chr.", "509 v. Chr.", "27 v. Chr.", "476 n. Chr."], correct: 0, hint: "Romulus und Remus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Römische Republik'?", answers: ["Eine Staatsform ohne König mit gewählten Beamten", "Eine Monarchie", "Eine Diktatur", "Eine Theokratie"], correct: 0, hint: "Res publica = öffentliche Sache", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Krieg zwischen Rom und Karthago war der bekannteste?", answers: ["Zweiter Punischer Krieg (Hannibal)", "Erster Punischer Krieg", "Dritter Punischer Krieg", "Makedonischer Krieg"], correct: 0, hint: "Hannibal über die Alpen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was waren die 'Punischen Kriege'?", answers: ["Kriege Roms gegen Karthago", "Kriege Roms gegen Griechenland", "Bürgerkriege Roms", "Kriege Roms gegen Gallien"], correct: 0, hint: "264–146 v. Chr.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wer führte die Reformen der Gracchen durch?", answers: ["Tiberius und Gaius Gracchus", "Caesar und Pompeius", "Sulla und Marius", "Augustus und Agrippa"], correct: 0, hint: "Landreform, 2. Jh. v. Chr.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Schlacht im Teutoburger Wald' (9 n. Chr.)?", answers: ["Vernichtung von drei römischen Legionen durch Germanen", "Ein römischer Sieg", "Eine Seeschlacht", "Eine Belagerung"], correct: 0, hint: "Varus, Arminius", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wer ermordete Julius Caesar?", answers: ["Verschwörer um Brutus und Cassius", "Seine Frau", "Der Senat", "Sklaven"], correct: 0, hint: "44 v. Chr. Iden des März", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Pax Romana'?", answers: ["Eine lange Friedensperiode unter Augustus", "Ein Krieg", "Ein Vertrag", "Eine Revolte"], correct: 0, hint: "Römischer Frieden, ca. 27 v. Chr.–180 n. Chr.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bedeutung hatten die 'römischen Aquädukte'?", answers: ["Wasserversorgung der Städte", "Schiffskanäle", "Straßenbau", "Befestigungsanlagen"], correct: 0, hint: "Wasserleitungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was waren Gladiatoren?", answers: ["Bewaffnete Kämpfer in Arenen zur Unterhaltung", "Römische Soldaten", "Politische Redner", "Sklaven in der Landwirtschaft"], correct: 0, hint: "Colosseum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war das 'Römische Recht'?", answers: ["Ein fortschrittliches Rechtssystem, das viele heutige Systeme beeinflusste", "Nur Strafrecht", "Nur Zivilrecht", "Ein religiöses Gesetz"], correct: 0, hint: "Corpus Iuris Civilis", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielte das Christentum im späten Römischen Reich?", answers: ["Es wurde unter Konstantin zur erlaubten Religion", "Es wurde immer verfolgt", "Es hatte keinen Einfluss", "Es war die einzige Religion"], correct: 0, hint: "Mailänder Vereinbarung 313 n. Chr.", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];