window.__subjectData_lat_9g_vokabeln = [
    { question: "Was bedeutet 'caedere'?", answers: ["fallen", "töten / schlagen", "essen", "bauen"], correct: 1, hint: "caedere = töten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'primus'?", answers: ["erster", "zweiter", "bester", "schlechter"], correct: 0, hint: "prima = die Erste", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'bellum'?", answers: ["Krieg", "Frieden", "Schönheit", "Stadt"], correct: 0, hint: "De Bello Gallico", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'ferre'?", answers: ["tragen / bringen", "kämpfen", "laufen", "sehen"], correct: 0, hint: "fero, tuli, latum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'amicus'?", answers: ["Freund", "Feind", "Kaiser", "Sklave"], correct: 0, hint: "amicus = Freund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'magnus'?", answers: ["groß", "klein", "gut", "schlecht"], correct: 0, hint: "magnus, magna, magnum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'urbs'?", answers: ["Stadt", "Land", "Haus", "Fluss"], correct: 0, hint: "Urbs Roma = Die Stadt Rom", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'capere'?", answers: ["nehmen / erobern", "geben", "sehen", "hören"], correct: 0, hint: "capere = nehmen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'senatus'?", answers: ["Senat", "Kaiser", "Volk", "Sklave"], correct: 0, hint: "Senatus Populusque Romanus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'populus'?", answers: ["Volk", "König", "Stadt", "Haus"], correct: 0, hint: "populus = Volk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'virtus'?", answers: ["Tugend / Tapferkeit", "Schönheit", "Macht", "Reichtum"], correct: 0, hint: "vir = Mann, virtus = Mannhaftigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'dare'?", answers: ["geben", "nehmen", "sagen", "machen"], correct: 0, hint: "do, dedi, datum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'hostis'?", answers: ["Feind", "Gast", "Freund", "Bürger"], correct: 0, hint: "hostis = öffentlicher Feind", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'pars'?", answers: ["Teil", "Ganzes", "Seite", "Richtung"], correct: 0, hint: "partes = die Partei / Rolle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'facere'?", answers: ["machen / handeln", "sagen", "glauben", "sehen"], correct: 0, hint: "facio, feci, factum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'vir'?", answers: ["Mann", "Frau", "Kind", "Tier"], correct: 0, hint: "vir = Mann", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'dies'?", answers: ["Tag", "Nacht", "Stunde", "Jahr"], correct: 0, hint: "dies, diei m.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'domus'?", answers: ["Haus", "Stadt", "Tempel", "Feld"], correct: 0, hint: "domi (zu Hause), domum (nach Hause)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'multus'?", answers: ["viel", "wenig", "groß", "klein"], correct: 0, hint: "multi = viele", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'omnis'?", answers: ["jeder / ganz", "keiner", "einige", "wenige"], correct: 0, hint: "omnes = alle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'rex'?", answers: ["König", "Kaiser", "Feldherr", "Sklave"], correct: 0, hint: "regis = des Königs", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'socius'?", answers: ["Verbündeter / Begleiter", "Feind", "Sklave", "Bürger"], correct: 0, hint: "socii = die Verbündeten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'finis'?", answers: ["Ende / Grenze", "Anfang", "Mitte", "Ziel"], correct: 0, hint: "finem facere = ein Ende machen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'audere'?", answers: ["wagen", "hören", "fürchten", "lieben"], correct: 0, hint: "audeo, ausus sum = ich wage", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'clamare'?", answers: ["schreien / rufen", "schweigen", "flüstern", "lachen"], correct: 0, hint: "clamor = der Lärm, der Schrei", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'debere'?", answers: ["müssen / schulden", "geben", "nehmen", "wollen"], correct: 0, hint: "debeo, debui, debitum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'egere'?", answers: ["brauchen / Mangel haben", "haben", "essen", "trinken"], correct: 0, hint: "egeo + Ablativ = Mangel haben an", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'fugere'?", answers: ["fliehen", "kämpfen", "suchen", "finden"], correct: 0, hint: "fugio, fugi, fugitum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'gaudere'?", answers: ["sich freuen", "trauern", "fürchten", "zürnen"], correct: 0, hint: "gaudeo, gavisus sum = ich freue mich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'iubere'?", answers: ["befehlen", "bitten", "fragen", "verbieten"], correct: 0, hint: "iubeo, iussi, iussum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'nocere'?", answers: ["schaden", "nützen", "helfen", "schützen"], correct: 0, hint: "noceo + Dativ = ich schade jemandem", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'parere'?", answers: ["gehorchen / erscheinen", "befehlen", "sehen", "hören"], correct: 0, hint: "pareo + Dativ = gehorchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'quaerere'?", answers: ["suchen / fragen", "finden", "geben", "antworten"], correct: 0, hint: "quaero, quaesivi, quaesitum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'oppidum'?", answers: ["befestigte Siedlung / Stadt", "Lager", "Tempel", "Haus"], correct: 0, hint: "oppidum, oppidi n.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'copiae' (Plural)?", answers: ["Truppen / Vorräte", "Geld", "Bücher", "Waffen"], correct: 0, hint: "copia (Sg.) = Menge, Vorrat", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'legio'?", answers: ["Legion (ca. 5000 Soldaten)", "Lager", "Feldherr", "Waffe"], correct: 0, hint: "legio, legionis f.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'imperator'?", answers: ["Feldherr / Kaiser", "Soldat", "Senator", "Konsul"], correct: 0, hint: "imperare = befehlen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'proelium'?", answers: ["Kampf / Schlacht", "Krieg", "Frieden", "Waffenstillstand"], correct: 0, hint: "proelium, proelii n.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'castra' (Plural)?", answers: ["Lager", "Schlösser", "Burg", "Stadt"], correct: 0, hint: "castra, castrorum n.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'miles'?", answers: ["Soldat", "Feldherr", "Feind", "Bürger"], correct: 0, hint: "miles, militis m.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'dux'?", answers: ["Führer / Feldherr", "Soldat", "Sklave", "König"], correct: 0, hint: "ducere = führen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'gloria'?", answers: ["Ruhm", "Krieg", "Schönheit", "Macht"], correct: 0, hint: "gloria, gloriae f.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'dignitas'?", answers: ["Würde / Ansehen", "Reichtum", "Macht", "Tapferkeit"], correct: 0, hint: "Dignitas Caesaris = Caesars Ehre", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'auctoritas'?", answers: ["Ansehen / Einfluss", "Geld", "Macht", "Krieg"], correct: 0, hint: "auctoritas senatus = Autorität des Senats", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'pietas'?", answers: ["Pflichtbewusstsein / Frömmigkeit", "Tapferkeit", "Schönheit", "Klugheit"], correct: 0, hint: "pius Aeneas = der pflichtbewusste Aeneas", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'fides'?", answers: ["Treue / Vertrauen", "Glaube", "Hoffnung", "Liebe"], correct: 0, hint: "fides publica = öffentliches Vertrauen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'provincia'?", answers: ["Provinz / Amtsbereich", "Stadt", "Provinzhauptstadt", "Kolonieland"], correct: 0, hint: "provincia, provinciae f.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'consul'?", answers: ["Konsul (höchstes Amt der Republik)", "Feldherr", "Senator", "Kaiser"], correct: 0, hint: "consules = die beiden jährlich gewählten höchsten Beamten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'adulescens'?", answers: ["junger Mann / Jugendlicher", "alter Mann", "Sklave", "Lehrer"], correct: 0, hint: "adulescens, adulescentis m.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'aedificium'?", answers: ["Gebäude", "Tempel", "Mauer", "Brücke"], correct: 0, hint: "aedificium, aedificii n.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'animus'?", answers: ["Geist / Mut / Sinn", "Körper", "Herz", "Leben"], correct: 0, hint: "animo audaci = mit mutigem Geist", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'civitas'?", answers: ["Staat / Bürgerschaft", "Stadt", "Haus", "Land"], correct: 0, hint: "civitas, civitatis f.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'convenire'?", answers: ["zusammenkommen / passen / übereinstimmen", "kommen", "gehen", "laufen"], correct: 0, hint: "convenit = es ist vereinbart / es passt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'exercitus'?", answers: ["Heer", "Übung", "Lager", "Waffe"], correct: 0, hint: "exercitus, exercitus m. (u-Deklination)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'gens'?", answers: ["Volk / Sippe / Geschlecht", "Stadt", "Haus", "Land"], correct: 0, hint: "gens Iulia = die julische Sippe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Graecia'?", answers: ["Griechenland", "Rom", "Gallien", "Asien"], correct: 0, hint: "Graecia, Graeciae f.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'hic, haec, hoc'?", answers: ["dieser / diese / dieses", "jener / jene / jenes", "welcher / welche / welches", "mein / meine / mein"], correct: 0, hint: "Demonstrativpronomen der Nähe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'ille, illa, illud'?", answers: ["jener / jene / jenes", "dieser / diese / dieses", "welcher / welche / welches", "dein / deine / dein"], correct: 0, hint: "Demonstrativpronomen der Ferne", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'iuvenis'?", answers: ["junger Mann", "alter Mann", "Kind", "Sklave"], correct: 0, hint: "iuvenis, iuvenis m.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'patria'?", answers: ["Vaterland", "Vater", "Haus", "Stadt"], correct: 0, hint: "patria, patriae f. = Heimatland", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];