window.__subjectData_hist_9g_erster_weltkrieg = [
    { question: "Was war der Auslöser des Ersten Weltkriegs?", answers: ["Ein Handelskonflikt", "Das Attentat von Sarajevo", "Die Russische Revolution", "Der Untergang der Lusitania"], correct: 1, hint: "1914, Franz Ferdinand", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Schlieffen-Plan'?", answers: ["Ein Friedensplan", "Ein deutscher Angriffsplan", "Ein Seeabkommen", "Ein Wirtschaftsplan"], correct: 1, hint: "Schneller Sieg über Frankreich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bündnisse standen sich im Ersten Weltkrieg gegenüber?", answers: ["Mittelmächte gegen Entente", "Alliierte gegen Achsenmächte", "NATO gegen Warschauer Pakt", "EU gegen USA"], correct: 0, hint: "Deutschland, Österreich-Ungarn vs. Frankreich, GB, Russland", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Grabenkrieg' an der Westfront?", answers: ["Ein Stellungskrieg mit Schützengräben", "Ein Seekrieg", "Ein Luftkrieg", "Ein Guerillakrieg"], correct: 0, hint: "Frankreich, Belgien 1914–1918", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche neuen Waffen wurden im Ersten Weltkrieg eingesetzt?", answers: ["Giftgas, Panzer, U-Boote, Maschinengewehre", "Nur Gewehre und Kanonen", "Atomwaffen", "Raketen"], correct: 0, hint: "Industrialisierung des Krieges", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Marneschlacht' 1914?", answers: ["Das Scheitern des Schlieffen-Plans", "Ein deutscher Sieg", "Eine Seeschlacht", "Eine Luftschlacht"], correct: 0, hint: "Wendepunkt Westfront", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Ereignis führte 1917 zum Kriegseintritt der USA?", answers: ["Der unbeschränkte U-Boot-Krieg", "Das Attentat von Sarajevo", "Die Russische Revolution", "Die Schlacht an der Somme"], correct: 0, hint: "Lusitania, Zimmermann-Depesche", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Dolchstoßlegende'?", answers: ["Die Behauptung, die deutsche Armee sei von Zuhause verraten worden", "Eine militärische Taktik", "Ein Attentat", "Ein Waffenstillstand"], correct: 0, hint: "Nachkriegs-Mythos", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der Versailler Vertrag?", answers: ["Der Friedensvertrag nach dem Ersten Weltkrieg", "Ein Bündnisvertrag", "Ein Handelsabkommen", "Eine Waffenstillstandsvereinbarung"], correct: 0, hint: "1919, Spiegelsaal", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Folgen hatte der Versailler Vertrag für Deutschland?", answers: ["Gebietsabtretungen, Reparationen, Schuldartikel", "Gebietsgewinne", "Stärkung der Armee", "Keine Folgen"], correct: 0, hint: "Artikel 231", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Tote forderte der Erste Weltkrieg?", answers: ["Ca. 10 Millionen Soldaten", "Ca. 1 Million", "Ca. 50 Millionen", "Ca. 100 Millionen"], correct: 0, hint: "Verheerendster Krieg bis dahin", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Kriegsgegner Deutschlands schied 1917 durch Revolution aus?", answers: ["Russland", "Frankreich", "Großbritannien", "Italien"], correct: 0, hint: "Februarrevolution, Oktoberrevolution", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Schlacht an der Somme' bekannt für?", answers: ["Extrem hohe Verluste bei minimalem Geländegewinn", "Den ersten Panzereinsatz", "Eine deutsche Offensive", "Eine Seeschlacht"], correct: 0, hint: "1916, 1 Mio. Tote/Verwundete", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann endete der Erste Weltkrieg?", answers: ["11. November 1918", "November 1919", "Dezember 1918", "Januar 1919"], correct: 0, hint: "Waffenstillstand von Compiègne", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];