window.__subjectData_hist_9g_imperialismus = [
    { question: "Was bedeutet 'Imperialismus'?", answers: ["Friedliche Koexistenz", "Ausdehnung der Macht über andere Länder", "Abschaffung der Monarchie", "Internationaler Handel"], correct: 1, hint: "Kolonialmächte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Berliner Kongokonferenz' 1884/85?", answers: ["Die Aufteilung Afrikas", "Die Gründung der UN", "Ein Friedensvertrag", "Eine Wissenschaftskonferenz"], correct: 0, hint: "Europa teilt Afrika auf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche europäische Nation hatte um 1900 das größte Kolonialreich?", answers: ["Großbritannien", "Frankreich", "Deutschland", "Portugal"], correct: 0, hint: "Sun never sets", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter dem 'Wettlauf um Afrika'?", answers: ["Europäische Mächte eroberten innerhalb weniger Jahrzehnte fast ganz Afrika", "Ein Sportwettkampf in Afrika", "Eine Expedition", "Ein Wissenschaftswettbewerb"], correct: 0, hint: "1880–1914", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Land blieb im 'Wettlauf um Afrika' unabhängig?", answers: ["Äthiopien", "Kongo", "Nigeria", "Südafrika"], correct: 0, hint: "Schlacht von Adwa 1896", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war 'Sozialdarwinismus'?", answers: ["Die Anwendung von Darwins Theorien auf Gesellschaften", "Eine sozialistische Partei", "Eine Kolonialverwaltung", "Eine Religion"], correct: 0, hint: "Überlegenheit bestimmter Rassen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche wirtschaftlichen Motive trieben den Imperialismus?", answers: ["Rohstoffe und Absatzmärkte", "Religion", "Bildung", "Tourismus"], correct: 0, hint: "Industrielle Revolution", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Boxeraufstand'?", answers: ["Ein Aufstand in China gegen ausländische Einflussnahme", "Ein Sportaufstand", "Eine Revolution in Japan", "Ein Arbeiterstreik"], correct: 0, hint: "1900, China", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielte Cecil Rhodes im Imperialismus?", answers: ["Er baute das britische Kolonialreich in Afrika aus", "Er gründete die UN", "Er erfand das Maschinengewehr", "Er war König von England"], correct: 0, hint: "Rhodesien (Simbabwe)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'indirekter Herrschaft' im Kolonialismus?", answers: ["Einheimische Eliten wurden als Vermittler eingesetzt", "Direkte Militärverwaltung", "Kolonialisierung ohne Menschen", "Handel ohne Besiedlung"], correct: 0, hint: "Indirect Rule (Großbritannien)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Konflikt führte zum Burenkrieg?", answers: ["Briten gegen Buren in Südafrika", "Briten gegen Franzosen", "Deutsche gegen Briten", "Franzosen gegen Spanier"], correct: 0, hint: "1899–1902", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche imperialistische Macht dominierte in Indien?", answers: ["Großbritannien", "Frankreich", "Portugal", "Niederlande"], correct: 0, hint: "Crown Jewel of the Empire", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Politik der offenen Tür' in China?", answers: ["Alle Mächte sollten gleichen Zugang zu China haben", "China öffnete seine Grenzen", "Eine chinesische Reform", "Ein Handelsabkommen"], correct: 0, hint: "USA, 1899", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann endete die Hochphase des Imperialismus?", answers: ["Nach dem Ersten Weltkrieg", "Nach dem Zweiten Weltkrieg", "Nach der Französischen Revolution", "Nach dem Kalten Krieg"], correct: 0, hint: "Zerfall der Kolonialreiche ab 1918", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];