window.__subjectData_hist_9g_nachkriegszeit = [
    { question: "Wann wurde die Bundesrepublik Deutschland gegründet?", answers: ["1945", "1949", "1955", "1961"], correct: 1, hint: "Gründungsjahr der BRD", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Kalte Krieg'?", answers: ["Ein Weltkrieg mit Atomwaffen", "Ein Systemgegensatz zwischen Ost und West", "Ein Handelskrieg", "Ein Krieg in der Antarktis"], correct: 1, hint: "USA vs. UdSSR ohne direkte Kämpfe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Marshallplan'?", answers: ["Ein US-Hilfsprogramm zum Wiederaufbau Europas", "Ein Militärbündnis", "Ein Friedensvertrag", "Ein Handelsabkommen"], correct: 0, hint: "European Recovery Program", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Berliner Blockade' 1948/49?", answers: ["Die UdSSR blockierte West-Berlin", "Eine US-Blockade", "Eine deutsche Blockade", "Eine Seeblockade gegen die UdSSR"], correct: 0, hint: "Luftbrücke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Berliner Luftbrücke'?", answers: ["Die Versorgung West-Berlins durch Flugzeuge", "Ein Tunnel unter Berlin", "Eine Autobrücke", "Ein Eisenbahntunnel"], correct: 0, hint: "Rosinenbomber", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann wurde die Mauer in Berlin gebaut?", answers: ["1949", "1961", "1969", "1955"], correct: 1, hint: "13. August 1961", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'DDR'?", answers: ["Die Deutsche Demokratische Republik", "Die Deutsche Diktatur", "Der Deutsche Rat", "Die Deutsche Regierung"], correct: 0, hint: "Ostdeutschland", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'NATO'?", answers: ["Das Nordatlantikpakt-Organisation (Militärbündnis)", "Eine Handelsorganisation", "Eine humanitäre Hilfe", "Ein Friedensbündnis"], correct: 0, hint: "Gründung 1949", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Warschauer Pakt'?", answers: ["Das Militärbündnis der Ostblockstaaten", "Ein Handelsabkommen", "Ein Reiseabkommen", "Ein Kulturabkommen"], correct: 0, hint: "Gegengewicht zur NATO", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war das 'Wirtschaftswunder' in der BRD?", answers: ["Der schnelle wirtschaftliche Aufschwung ab den 1950ern", "Ein Naturphänomen", "Eine landwirtschaftliche Revolution", "Ein Bauprojekt"], correct: 0, hint: "Soziale Marktwirtschaft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Ostpolitik' der BRD?", answers: ["Eine Entspannungspolitik gegenüber dem Osten unter Brandt", "Eine aggressive Ostexpansion", "Eine Handelsblockade", "Eine Militäroffensive"], correct: 0, hint: "Willy Brandt, Kniefall von Warschau", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann fiel die Berliner Mauer?", answers: ["9. November 1989", "3. Oktober 1990", "August 1961", "Dezember 1989"], correct: 0, hint: "Friedliche Revolution", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann fand die deutsche Wiedervereinigung statt?", answers: ["3. Oktober 1990", "9. November 1989", "Januar 1991", "Dezember 1989"], correct: 0, hint: "Tag der Deutschen Einheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Stasi'?", answers: ["Der Staatssicherheitsdienst der DDR", "Die DDR-Regierung", "Eine westdeutsche Behörde", "Eine Schule"], correct: 0, hint: "Überwachung und Repression", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];