window.__subjectData_hist_9g_ns_zeit = [
    { question: "Wann kamen die Nationalsozialisten an die Macht?", answers: ["1923", "1933", "1939", "1945"], correct: 1, hint: "30. Januar 1933", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Wannseekonferenz'?", answers: ["Die Planung des Völkermords an den Juden", "Ein Friedensgipfel", "Eine Sportveranstaltung", "Eine Wirtschaftskonferenz"], correct: 0, hint: "1942, organisatorische Besprechung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Ermächtigungsgesetz' von 1933?", answers: ["Ein Gesetz, das Hitler die Alleinherrschaft ermöglichte", "Ein Gesetz zur Aufrüstung", "Ein Steuergesetz", "Ein Friedensgesetz"], correct: 0, hint: "Ermächtigung der Regierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Reichspogromnacht' 1938?", answers: ["Ein koordinierter Angriff auf jüdische Einrichtungen", "Ein nächtliches Fest", "Eine Militärparade", "Ein Sportevent"], correct: 0, hint: "9./10. November 1938", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was besagten die 'Nürnberger Gesetze' von 1935?", answers: ["Sie schlossen Juden aus der Gesellschaft aus", "Sie erklärten den Krieg", "Sie regelten die Wirtschaft", "Sie reformierten das Bildungssystem"], correct: 0, hint: "Reichsbürgergesetz, Blutschutzgesetz", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war die 'Blitzkrieg'-Strategie?", answers: ["Schnelle, konzentrierte Angriffe mit Panzern und Luftwaffe", "Langer Stellungskrieg", "Seeblockade", "Guerillakrieg"], correct: 0, hint: "Polen 1939, Frankreich 1940", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Ereignis markiert den Beginn des Zweiten Weltkriegs?", answers: ["Der Überfall auf Polen am 1. September 1939", "Die Annexion Österreichs", "Der Angriff auf Pearl Harbor", "Die Invasion der Sowjetunion"], correct: 0, hint: "Beginn am 1. Sept 1939", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Holocaust'?", answers: ["Der systematische Völkermord an ca. 6 Millionen Juden", "Ein militärischer Feldzug", "Ein Wirtschaftsprogramm", "Eine Naturkatastrophe"], correct: 0, hint: "Shoa", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war das 'Unternehmen Barbarossa'?", answers: ["Der deutsche Angriff auf die Sowjetunion 1941", "Die Landung in der Normandie", "Ein U-Boot-Einsatz", "Die Evakuierung von Städten"], correct: 0, hint: "22. Juni 1941", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Atlantikwall'?", answers: ["Ein deutsches Befestigungssystem entlang der Küste Westeuropas", "Ein Handelsabkommen", "Eine Seemauer", "Eine Grenze"], correct: 0, hint: "Abwehr einer Invasion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wer war der 'Führer' im Nationalsozialismus?", answers: ["Adolf Hitler", "Joseph Goebbels", "Hermann Göring", "Heinrich Himmler"], correct: 0, hint: "Führer und Reichskanzler", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Ort ist symbolisch für die Teilung Deutschlands nach dem Krieg?", answers: ["Brandenburger Tor", "Reichstag", "Checkpoint Charlie", "München"], correct: 2, hint: "Grenzübergang Berlin", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was war der 'Widerstand' im NS-Staat?", answers: ["Personen und Gruppen, die sich dem NS-Regime widersetzten", "Die offizielle Opposition", "Eine ausländische Armee", "Eine Naturkatastrophe"], correct: 0, hint: "Stauffenberg, Weiße Rose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wann endete der Zweite Weltkrieg in Europa?", answers: ["8. Mai 1945", "September 1945", "Dezember 1945", "August 1944"], correct: 0, hint: "VE Day", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];