window.__subjectData_geo_7r_bevoelkerung = [
    { question: "Was versteht man unter 'Bevölkerungswachstum'?", answers: ["Die Anzahl der Geburten", "Die Zunahme der Einwohnerzahl", "Die Anzahl der Sterbefälle", "Die Zuwanderung"], correct: 1, hint: "Mehr Menschen = ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Migration?", answers: ["Wanderung von Menschen", "Wetterphänomen", "Eine Pflanzenart", "Ein Stein"], correct: 0, hint: "Menschen ziehen um", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Babyboomer'-Generation?", answers: ["Geburtenrückgang", "Geburtenstarke Jahrgänge nach dem Krieg", "Eine neue Tierart", "Eine Migrationswelle"], correct: 1, hint: "1950er-1960er Jahre", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Faktor beeinflusst die Bevölkerungsdichte am stärksten?", answers: ["Klima und Wirtschaft", "Die Hautfarbe", "Die Sprache", "Die Politik des Nachbarlands"], correct: 0, hint: "Lebensbedingungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'natürliche Bevölkerungsentwicklung'?", answers: ["Geburten minus Sterbefälle", "Zuwanderung minus Abwanderung", "Nur die Geburten", "Nur die Sterbefälle"], correct: 0, hint: "Saldo ohne Migration", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "In welchem Kontinent wächst die Bevölkerung am schnellsten?", answers: ["Europa", "Afrika", "Asien", "Nordamerika"], correct: 1, hint: "Hohe Geburtenraten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Push-Faktor' bei Migration?", answers: ["Ein Grund, der Menschen zur Auswanderung bewegt", "Ein Grund, in der Heimat zu bleiben", "Ein Reiseziel", "Eine Transportart"], correct: 0, hint: "Krieg, Armut, Verfolgung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Pull-Faktor' bei Migration?", answers: ["Ein Grund wegzugehen", "Ein Grund, der Menschen anzieht", "Eine Naturkatastrophe", "Eine Grenze"], correct: 1, hint: "Arbeit, Sicherheit, Freiheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'demografischer Wandel'?", answers: ["Veränderung der Altersstruktur", "Wechsel der Regierung", "Klimaveränderung", "Sprachwandel"], correct: 0, hint: "Gesellschaft altert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Problem entsteht durch eine alternde Gesellschaft?", answers: ["Mehr Geburten", "Weniger Arbeitskräfte, höhere Rentenkosten", "Jüngere Bevölkerung", "Mehr Schulen"], correct: 1, hint: "Immer mehr Rentner", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Menschen leben ungefähr auf der Erde?", answers: ["4 Milliarden", "8 Milliarden", "12 Milliarden", "2 Milliarden"], correct: 1, hint: "Stand 2024", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Bevölkerungspyramide'?", answers: ["Eine Altersstruktur-Grafik", "Ein Gebäude", "Eine Klimakurve", "Eine Wirtschaftsform"], correct: 0, hint: "zeigt Altersaufbau der Bevölkerung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Region Europas hat die höchste Bevölkerungsdichte?", answers: ["Skandinavien", "Mitteleuropa (z.B. Deutschland, Niederlande)", "Südeuropa", "Osteuropa"], correct: 1, hint: "Viele Großstädte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Urbanisierung'?", answers: ["Landflucht / Verstädterung", "Rückkehr auf das Land", "Bevölkerungsrückgang", "Klimawandel"], correct: 0, hint: "Menschen ziehen in Städte", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];