window.__subjectData_geo_7r_klima_vegetation = [
    { question: "Welche Klimazone hat Deutschland?", answers: ["Tropen", "Subtropen", "Gemäßigte Zone", "Polarzone"], correct: 2, hint: "Vier Jahreszeiten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist Tundra?", answers: ["Eine Wüste", "Eine baumlose Kältesteppe", "Ein Regenwald", "Eine Savanne"], correct: 1, hint: "In der Arktis und im Hochgebirge", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Klima herrscht im Mittelmeerraum?", answers: ["Kontinentalklima", "Mittelmeerklima (subtropisch)", "Polarklima", "Hochgebirgsklima"], correct: 1, hint: "Heiße, trockene Sommer und milde, feuchte Winter", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Vegetationszone in den Tropen?", answers: ["Laubwald", "Regenwald", "Nadelwald", "Steppe"], correct: 1, hint: "Immergrün und artenreich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wodurch wird das Klima in Mitteleuropa beeinflusst?", answers: ["Durch den Golfstrom", "Durch die Wüsten Afrikas", "Durch den Monsun", "Durch die Eiszeit"], correct: 0, hint: "Warme Meeresströmung aus dem Atlantik", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Unterschied zwischen Wetter und Klima?", answers: ["Wetter ist kurz, Klima lang", "Wetter ist lang, Klima kurz", "Es gibt keinen Unterschied", "Wetter ist global, Klima lokal"], correct: 0, hint: "Wetter = aktuell, Klima = Durchschnitt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Klimazone liegt um den Äquator?", answers: ["Gemäßigte Zone", "Tropen", "Polarzone", "Subtropen"], correct: 1, hint: "Immer feucht und heiß", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Savanne?", answers: ["Ein dichter Wald", "Eine Graslandschaft mit Bäumen", "Eine Eiswüste", "Ein Gebirge"], correct: 1, hint: "Übergangszone zwischen Regenwald und Wüste", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Vegetation findet man in der Polarzone?", answers: ["Regenwald", "Nadelwald", "Flechten und Moose", "Laubwald"], correct: 2, hint: "Karge Vegetation", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Kontinentalklima'?", answers: ["Milde Winter, kühle Sommer", "Heiße Sommer, kalte Winter", "Immer gleich warm", "Sehr viel Niederschlag"], correct: 1, hint: "Inlandsklima ohne Meeresnähe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Faktor beeinflusst das Klima am stärksten?", answers: ["Die Windrichtung", "Die geografische Breite", "Die Bodenbeschaffenheit", "Die Tierwelt"], correct: 1, hint: "Sonnenstrahlung abhängig vom Breitengrad", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Waldtyp ist typisch für die gemäßigte Zone?", answers: ["Regenwald", "Mischwald", "Dornstrauchsavanne", "Mangrovenwald"], correct: 1, hint: "Laub- und Nadelbäume", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Treibhauseffekt?", answers: ["Abkühlung der Erde", "Natürliche Erwärmung durch Treibhausgase", "Neue Pflanzenart", "Ein Ozeanphänomen"], correct: 1, hint: "CO2 und Methan in der Atmosphäre", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Klima herrscht in Sibirien?", answers: ["Mittelmeerklima", "Kontinentalklima (kalt)", "Tropisches Klima", "Maritimes Klima"], correct: 1, hint: "Sehr kalte Winter, kurze Sommer", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];