window.__subjectData_geo_7r_landwirtschaft = [
    { question: "Was ist 'konventionelle Landwirtschaft'?", answers: ["Landwirtschaft mit Chemie und Maschinen", "Nur Handarbeit", "Städtischer Gemüseanbau", "Fischzucht"], correct: 0, hint: "Gegenteil von biologisch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Fruchtfolge'?", answers: ["Die Reihenfolge der Ernte", "Der Wechsel der Anbaupflanzen", "Die Fruchtbarkeit des Bodens", "Eine Obstsorte"], correct: 1, hint: "Verschiedene Pflanzen nacheinander", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'biologische Landwirtschaft'?", answers: ["Anbau mit Pestiziden", "Verzicht auf chemische Mittel", "Nur Gewächshäuser", "Großflächige Monokultur"], correct: 1, hint: "Natürliche Düngung und Schädlingsbekämpfung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Getreide wird in Deutschland am meisten angebaut?", answers: ["Reis", "Weizen", "Mais", "Hafer"], correct: 1, hint: "Brotgetreide", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Viehwirtschaft'?", answers: ["Anbau von Pflanzen", "Haltung von Nutztieren", "Fischfang", "Imkerei"], correct: 1, hint: "Kühe, Schweine, Hühner", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bundesrepublik Deutschland hat den höchsten Anteil an Ackerland?", answers: ["Bayern", "Niedersachsen", "Nordrhein-Westfalen", "Schleswig-Holstein"], correct: 1, hint: "Weite Ebenen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Massentierhaltung'?", answers: ["Artgerechte Tierhaltung", "Haltung vieler Tiere auf engem Raum", "Haltung im Freien", "Haltung von Haustieren"], correct: 1, hint: "Industrielle Tierproduktion", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Nachhaltigkeit' in der Landwirtschaft?", answers: ["Nur Gewinnmaximierung", "Wirtschaftlich, ökologisch und sozial verträglich", "Nur ökologischer Anbau", "Nur Gewächshausanbau"], correct: 1, hint: "Drei-Säulen-Modell", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Nutzpflanze wird weltweit am meisten angebaut?", answers: ["Weizen", "Reis", "Mais", "Kartoffeln"], correct: 2, hint: "Auch Tierfutter und Biokraftstoff", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Monokultur'?", answers: ["Anbau vieler verschiedener Pflanzen", "Anbau nur einer Pflanzenart auf großer Fläche", "Kultureller Austausch", "Kleine Gärten"], correct: 1, hint: "Z.B. nur Mais auf einem Feld", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Folge hat übermäßiger Düngereinsatz?", answers: ["Höhere Artenvielfalt", "Gewässerverschmutzung (Eutrophierung)", "Bessere Bodenqualität", "Mehr Regenwald"], correct: 1, hint: "Überdüngung der Flüsse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Subsistenzwirtschaft'?", answers: ["Landwirtschaft zum Eigenbedarf", "Exportorientierte Landwirtschaft", "Industrielle Massenproduktion", "Fischfang"], correct: 0, hint: "Man produziert nur für sich selbst", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Land ist der größte Agrarexporteur der EU?", answers: ["Frankreich", "Deutschland", "Niederlande", "Spanien"], correct: 2, hint: "Gewächshäuser und Hightech-Landwirtschaft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Grünland'?", answers: ["Ackerfläche für Getreide", "Dauerhaft mit Gras bewachsene Fläche für Weidetiere", "Waldfläche", "Brachland"], correct: 1, hint: "Wiesen und Weiden", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];