window.__subjectData_geo_9g_deutschland = [
    { question: "Welches Bundesland hat die meisten Einwohner?", answers: ["Bayern", "Nordrhein-Westfalen", "Baden-Württemberg", "Niedersachsen"], correct: 1, hint: "Ruhrgebiet", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Strukturwandel' im Ruhrgebiet?", answers: ["Von Kohle zu Hightech", "Neue Autobahnen", "Mehr Kohleabbau", "Weniger Einwohner"], correct: 0, hint: "Wirtschaftlicher Wandel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Fluss ist der längste in Deutschland?", answers: ["Rhein", "Elbe", "Donau", "Weser"], correct: 0, hint: "Die Donau ist länger, aber nur teilweise in DE", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Metropolregion ist die größte in Deutschland?", answers: ["Rhein-Ruhr", "Berlin-Brandenburg", "München", "Hamburg"], correct: 0, hint: "Ca. 10 Mio. Einwohner", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist das 'Ruhrgebiet' bekannt für?", answers: ["Historischen Kohle- und Stahlbergbau", "Tourismus", "Landwirtschaft", "Hightech-Industrie"], correct: 0, hint: "Reviers", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie heißen die drei Stadtstaaten Deutschlands?", answers: ["Berlin, Hamburg, Bremen", "Berlin, Hamburg, München", "Hamburg, Bremen, Köln", "Berlin, Bremen, Dresden"], correct: 0, hint: "Keine Flächenländer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'demografischem Wandel' in Deutschland?", answers: ["Überalterung und sinkende Geburtenrate", "Steigende Geburtenrate", "Jüngere Bevölkerung", "Höhere Sterberate"], correct: 0, hint: "Immer weniger Junge, mehr Alte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Wirtschaftssektoren gibt es?", answers: ["Primär, Sekundär, Tertiär", "Nur Industrie", "Nur Landwirtschaft", "Nur Dienstleistung"], correct: 0, hint: "Drei-Sektoren-Modell", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Sektor dominiert die deutsche Wirtschaft?", answers: ["Dienstleistungssektor (tertiär)", "Industrie (sekundär)", "Landwirtschaft (primär)", "Alle gleich"], correct: 0, hint: "Ca. 70% der Erwerbstätigen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Agglomeration'?", answers: ["Räumliche Konzentration von Industrie und Bevölkerung", "Zerstreuung von Siedlungen", "Landflucht", "Stadtflucht"], correct: 0, hint: "Ballungsräume", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Mittlere Neckar-Region' bekannt für?", answers: ["Automobilindustrie (Daimler, Porsche, Bosch)", "Kohlebergbau", "Tourismus", "Landwirtschaft"], correct: 0, hint: "Baden-Württemberg", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielen erneuerbare Energien in Deutschland?", answers: ["Sie machen einen wachsenden Anteil der Stromproduktion aus", "Sie werden kaum genutzt", "Sie sind verboten", "Sie sind rückläufig"], correct: 0, hint: "Energiewende", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der 'Speckgürtel' einer Stadt?", answers: ["Das Umland einer Stadt mit hohem Zuzug", "Das Stadtzentrum", "Ein Industriegebiet", "Ein Naturschutzgebiet"], correct: 0, hint: "Suburbanisierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Bundesländer hat Deutschland?", answers: ["16", "15", "14", "17"], correct: 0, hint: "13 Flächenländer + 3 Stadtstaaten", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];