window.__subjectData_geo_9g_disparitaeten = [
    { question: "Was sind 'globale Disparitäten'?", answers: ["Unterschiedliche Zeitzonen", "Ungleiche Entwicklung weltweit", "Verschiedene Klimazonen", "Unterschiedliche Sprachen"], correct: 1, hint: "Armut, Bildung, Gesundheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Index misst die menschliche Entwicklung?", answers: ["BIP", "HDI", "CO2", "GPS"], correct: 1, hint: "Human Development Index", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Dimensionen fließen in den HDI ein?", answers: ["Bildung, Lebenserwartung, Einkommen", "Nur Einkommen", "Nur Umwelt", "Nur Infrastruktur"], correct: 0, hint: "Human Development Index", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Gini-Koeffizient?", answers: ["Ein Maß für Einkommensungleichheit", "Ein Maß für Klimawandel", "Ein Bevölkerungsindex", "Ein Index der Bildung"], correct: 0, hint: "0 = Gleichheit, 1 = totale Ungleichheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter dem 'Nord-Süd-Gefälle'?", answers: ["Reichere Länder im Norden, ärmere im Süden", "Temperaturunterschiede", "Kulturelle Unterschiede", "Politische Gegensätze"], correct: 0, hint: "Globale Ungleichheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Terms of Trade'?", answers: ["Das Verhältnis von Export- zu Importpreisen", "Ein Handelsabkommen", "Eine Währungsunion", "Ein Transportweg"], correct: 0, hint: "Austauschverhältnis im Handel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind 'Millenniumsziele' (MDGs)?", answers: ["Von der UN festgelegte Entwicklungsziele", "Ein Klimaabkommen", "Ein Handelsabkommen", "Ein Friedensvertrag"], correct: 0, hint: "2000–2015, Armutsbekämpfung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind die 'SDGs'?", answers: ["Sustainable Development Goals (Nachhaltigkeitsziele)", "Ein neues Währungssystem", "Ein Handelsblock", "Eine Technologie"], correct: 0, hint: "17 Ziele bis 2030", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Hunger' als globalem Problem?", answers: ["Unterernährung betrifft vor allem Länder des Globalen Südens", "Nur Naturkatastrophen", "Ein europäisches Problem", "Ein modernes Problem"], correct: 0, hint: "Ursachen: Armut, Konflikte", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Kontinent ist am stärksten von Armut betroffen?", answers: ["Asien", "Afrika", "Südamerika", "Europa"], correct: 1, hint: "Subsahara-Afrika", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Schuldenerlass'-Initiative?", answers: ["Erlass von Schulden für hochverschuldete arme Länder", "Neue Kredite", "Ein Bankensystem", "Eine Währungsreform"], correct: 0, hint: "HIPC-Initiative", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Brain Drain'?", answers: ["Abwanderung von Fachkräften aus Entwicklungsländern", "Hirnforschung", "Einbildungssystem", "Datenverlust"], correct: 0, hint: "Qualifizierte wandern ab", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie beeinflusst der Klimawandel globale Disparitäten?", answers: ["Ärmere Länder sind stärker betroffen", "Alle Länder gleich", "Reiche Länder sind stärker betroffen", "Kein Einfluss"], correct: 0, hint: "Anpassungsfähigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Faire Arbeit' (Decent Work)?", answers: ["Arbeit mit gerechter Bezahlung und sozialer Sicherheit", "Ehrenamt", "Nur Mindestlohn", "Jede bezahlte Tätigkeit"], correct: 0, hint: "SDG 8", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];