window.__subjectData_geo_9g_entwicklung = [
    { question: "Was ist ein 'Entwicklungsland'?", answers: ["Ein Land mit hohem BIP", "Ein Land mit niedrigem Lebensstandard", "Ein Land mit vielen Fabriken", "Ein Land in Europa"], correct: 1, hint: "Geringe Industrialisierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was bedeutet 'Nachhaltigkeit'?", answers: ["Nur Wirtschaftswachstum", "Ökonomie, Ökologie und Soziales im Gleichgewicht", "Nur Umweltschutz", "Nur soziale Gerechtigkeit"], correct: 1, hint: "Drei-Säulen-Modell", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Weltbank'?", answers: ["Eine internationale Organisation, die Entwicklungsländer finanziell unterstützt", "Eine Bank für Privatkunden", "Eine Bank in New York", "Ein Währungsfonds"], correct: 0, hint: "IBRD, IDA", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der 'Internationale Währungsfonds (IWF)'?", answers: ["Eine Organisation zur Sicherung der internationalen Finanzstabilität", "Eine Privatbank", "Ein Handelsabkommen", "Eine UN-Organisation"], correct: 0, hint: "Kredite an Staaten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Entwicklungshilfe'?", answers: ["Finanzielle und technische Unterstützung für Entwicklungsländer", "Kredite an reiche Länder", "Handelsabkommen", "Militärische Hilfe"], correct: 0, hint: "ODA (Official Development Assistance)", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Rostow-Entwicklungsstadien'?", answers: ["Ein Modell der wirtschaftlichen Entwicklung in 5 Stufen", "Ein Modell der Klimaentwicklung", "Ein Bevölkerungsmodell", "Ein Stadtentwicklungsmodell"], correct: 0, hint: "Traditionelle Gesellschaft -> Massenkonsum", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was besagt die 'Dependenztheorie'?", answers: ["Entwicklungsländer bleiben durch Abhängigkeit von Industrieländern unterentwickelt", "Alle Länder entwickeln sich gleich", "Entwicklung ist unvermeidbar", "Nur kulturelle Faktoren zählen"], correct: 0, hint: "Kapitalfluss vom Süden in den Norden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Mikrofinanzierung'?", answers: ["Kleine Kredite für ärmere Menschen ohne Sicherheiten", "Große Kredite an Konzerne", "Staatsanleihen", "Aktienhandel"], correct: 0, hint: "Grameen Bank, Muhammad Yunus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist 'Fair Trade'?", answers: ["Faire Handelsbedingungen für Produzenten im Süden", "Freier Handel", "Globalisierung", "Ein Zollabkommen"], correct: 0, hint: "Siegel, gerechte Preise", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielt Bildung für Entwicklung?", answers: ["Bildung ist eine Grundvoraussetzung für wirtschaftliche Entwicklung", "Bildung ist irrelevant", "Nur technische Bildung", "Nur Grundschulbildung zählt"], correct: 0, hint: "Humankapital", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Subsistenzwirtschaft'?", answers: ["Wirtschaft zur Deckung des Eigenbedarfs", "Exportorientierte Landwirtschaft", "Industrieproduktion", "Dienstleistungssektor"], correct: 0, hint: "Selbstversorgung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind 'emerging markets'?", answers: ["Schwellenländer mit schnell wachsender Wirtschaft", "Entwicklungsländer", "Industrieländer", "Krisenländer"], correct: 0, hint: "BRICS-Staaten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Faktoren beeinflussen die Entwicklung eines Landes?", answers: ["Bildung, Gesundheit, Infrastruktur, politische Stabilität", "Nur Bodenschätze", "Nur das Klima", "Nur die Bevölkerungszahl"], correct: 0, hint: "Multidimensionale Entwicklung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Capacity Building'?", answers: ["Aufbau von Kompetenzen und Institutionen in Entwicklungsländern", "Kapitalanlagen", "Bau von Gebäuden", "Militärische Ausbildung"], correct: 0, hint: "Stärkung lokaler Strukturen", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];