window.__subjectData_english_6r_animals = [ { question: "Was bedeutet 'dog'?", answers: ["Katze", "Hund", "Maus", "Vogel"], correct: 1, hint: "Haustier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cat'?", answers: ["Hund", "Katze", "Hamster", "Kaninchen"], correct: 1, hint: "Haustier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bird'?", answers: ["Fisch", "Vogel", "Schmetterling", "Biene"], correct: 1, hint: "fliegt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fish'?", answers: ["Hai", "Fisch", "Wal", "Delfin"], correct: 1, hint: "schwimmt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'horse'?", answers: ["Esel", "Pferd", "Pony", "Zebra"], correct: 1, hint: "Reittier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'lion'?", answers: ["Tiger", "Löwe", "Leopard", "Gepard"], correct: 1, hint: "König der Tiere", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'elephant'?", answers: ["Nashorn", "Elefant", "Nilpferd", "Giraffe"], correct: 1, hint: "größtes Landtier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'snake'?", answers: ["Eidechse", "Schlange", "Wurm", "Krokodil"], correct: 1, hint: "kriecht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bear'?", answers: ["Wolf", "Bär", "Hund", "Fuchs"], correct: 1, hint: "großes Säugetier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'rabbit'?", answers: ["Maus", "Hase", "Hamster", "Meerschweinchen"], correct: 1, hint: "hat lange Ohren", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fox'?", answers: ["Wolf", "Fuchs", "Kojote", "Hund"], correct: 1, hint: "schlaues Tier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'wolf'?", answers: ["Hund", "Wolf", "Kojote", "Schakal"], correct: 1, hint: "Rudeltier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'monkey'?", answers: ["Affe", "Gorilla", "Schimpanse", "Orang-Utan"], correct: 0, hint: "Klettert gern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cow'?", answers: ["Schaf", "Schwein", "Kuh", "Ziege"], correct: 2, hint: "Gibt Milch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sheep'?", answers: ["Ziege", "Schaf", "Lamm", "Kuh"], correct: 1, hint: "Hat Wolle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pig'?", answers: ["Hund", "Schaf", "Schwein", "Esel"], correct: 2, hint: "Ist rosa", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chicken'?", answers: ["Hahn", "Henne", "Huhn", "Vogel"], correct: 2, hint: "Gibt Eier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'mouse' (Plural: mice)?", answers: ["Ratte", "Maus", "Hamster", "Eichhörnchen"], correct: 1, hint: "Klienes Nagetier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'duck'?", answers: ["Gans", "Ente", "Schwan", "Vogel"], correct: 1, hint: "Schwimmt auf dem Teich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'spider'?", answers: ["Wurm", "Spinne", "Käfer", "Fliege"], correct: 1, hint: "Hat acht Beine", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "How many legs does a spider have?", answers: ["6", "8", "4", "2"], correct: 1, hint: "More than an insect", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Which animal is known as 'king of the animals'?", answers: ["tiger", "elephant", "lion", "bear"], correct: 2, hint: "Roars loud", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is the English word for 'Schwein'?", answers: ["sheep", "cow", "pig", "duck"], correct: 2, hint: "Pink farm animal", stats: { correct: 0, total: 0, difficulty: 1.0 } }
            ,
            { question: "Was bedeutet 'giraffe'?", answers: ["Nashorn", "Giraffe", "Zebra", "Elefant"], correct: 1, hint: "Sehr langer Hals", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'monkey'?", answers: ["Affe", "Tiger", "Vogel", "Hase"], correct: 0, hint: "Klettert gern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'whale'?", answers: ["Hai", "Delfin", "Wal", "Robbe"], correct: 2, hint: "Größtes Tier im Meer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shark'?", answers: ["Wal", "Hai", "Fisch", "Krabbe"], correct: 1, hint: "Hat viele Zähne", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dolphin'?", answers: ["Hai", "Wal", "Delfin", "Pinguin"], correct: 2, hint: "Sehr intelligentes Meerestier", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'penguin'?", answers: ["Vogel", "Papagei", "Pinguin", "Ente"], correct: 2, hint: "Vogel, der nicht fliegen kann", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'parrot'?", answers: ["Spatz", "Adler", "Papagei", "Eule"], correct: 2, hint: "Bunter Vogel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'owl'?", answers: ["Adler", "Eule", "Falke", "Rabe"], correct: 1, hint: "Nachtaktiver Vogel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bee'?", answers: ["Wespe", "Biene", "Fliege", "Mücke"], correct: 1, hint: "Macht Honig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'butterfly'?", answers: ["Biene", "Libelle", "Schmetterling", "Käfer"], correct: 2, hint: "War mal eine Raupe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'frog'?", answers: ["Eidechse", "Kröte", "Frosch", "Schlange"], correct: 2, hint: "Quakt im Teich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'turtle'?", answers: ["Frosch", "Eidechse", "Schildkröte", "Krokodil"], correct: 2, hint: "Hat einen Panzer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'crocodile'?", answers: ["Alligator", "Krokodil", "Echse", "Hai"], correct: 1, hint: "Großes Reptil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'zebra'?", answers: ["Pferd", "Zebra", "Esel", "Antilope"], correct: 1, hint: "Schwarz-weiß gestreift", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hippo'?", answers: ["Nashorn", "Nilpferd", "Elefant", "Bär"], correct: 1, hint: "Kurzform für Hippopotamus", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
