window.__subjectData_english_6r_clothes = [ { question: "Was bedeutet 'shirt'?", answers: ["Hose", "Hemd", "Jacke", "Hut"], correct: 1, hint: "Oberteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'trousers'?", answers: ["Rock", "Hose", "Kleid", "Schal"], correct: 1, hint: "An den Beinen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shoes'?", answers: ["Socken", "Stiefel", "Schuhe", "Handschuhe"], correct: 2, hint: "An den Füßen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hat'?", answers: ["Mütze", "Hut", "Helm", "Kappe"], correct: 1, hint: "Auf dem Kopf", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'coat'?", answers: ["Jacke", "Mantel", "Pullover", "Hemd"], correct: 1, hint: "Für draußen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'skirt'?", answers: ["Kleid", "Hose", "Rock", "Bluse"], correct: 2, hint: "Für Mädchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dress'?", answers: ["Rock", "Bluse", "Kleid", "Hemd"], correct: 2, hint: "Einteiler", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'socks'?", answers: ["Schuhe", "Socken", "Hosen", "Handschuhe"], correct: 1, hint: "In den Schuhen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sweater'?", answers: ["Jacke", "Mantel", "Pullover", "T-Shirt"], correct: 2, hint: "Warmes Oberteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'jacket'?", answers: ["Hemd", "Mantel", "Jacke", "Bluse"], correct: 2, hint: "Kurzes Oberteil für draußen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cap'?", answers: ["Hut", "Mütze", "Kappe", "Schal"], correct: 2, hint: "Baseball ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'scarf'?", answers: ["Handschuh", "Mütze", "Schal", "Tuch"], correct: 2, hint: "Um den Hals", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'gloves'?", answers: ["Schuhe", "Socken", "Handschuhe", "Hüte"], correct: 2, hint: "Für die Hände", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'belt'?", answers: ["Ring", "Gürtel", "Kette", "Uhr"], correct: 1, hint: "Hält die Hose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'jeans'?", answers: ["Hose", "Jeans", "Stoffhose", "Shorts"], correct: 1, hint: "Blaue Hose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'boots'?", answers: ["Schuhe", "Sandalen", "Stiefel", "Turnschuhe"], correct: 2, hint: "Hohe Schuhe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pyjamas'?", answers: ["Anzug", "Schlafanzug", "Unterwäsche", "Kleid"], correct: 1, hint: "Zum Schlafen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'shorts'?", answers: ["Hose", "Kurze Hose", "Rock", "Badehose"], correct: 1, hint: "Für den Sommer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'blouse'?", answers: ["Hemd", "T-Shirt", "Bluse", "Top"], correct: 2, hint: "Damenoberteil", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tie'?", answers: ["Gürtel", "Schal", "Krawatte", "Fliege"], correct: 2, hint: "Zum Anzug", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What do you wear on your hands in winter?", answers: ["shoes", "gloves", "socks", "trousers"], correct: 1, hint: "Warm hands", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is a 'blouse'?", answers: ["a skirt", "a dress", "a shirt for women", "a pair of jeans"], correct: 2, hint: "Clothes", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What do you call 'Kurze Hose' in English?", answers: ["trousers", "jeans", "shorts", "skirt"], correct: 2, hint: "Summer wear", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
