window.__subjectData_english_6r_food = [ { question: "Was bedeutet 'apple'?", answers: ["Banane", "Apfel", "Orange", "Traube"], correct: 1, hint: "Obst", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bread'?", answers: ["Kuchen", "Brot", "Brötchen", "Keks"], correct: 1, hint: "Grundnahrungsmittel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'water'?", answers: ["Saft", "Wasser", "Milch", "Tee"], correct: 1, hint: "Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'milk'?", answers: ["Wasser", "Saft", "Milch", "Kaffee"], correct: 2, hint: "Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pizza'?", answers: ["Pasta", "Pizza", "Burger", "Salat"], correct: 1, hint: "italienisches Essen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cake'?", answers: ["Keks", "Kuchen", "Torte", "Pudding"], correct: 1, hint: "Süßspeise", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'meat'?", answers: ["Fisch", "Fleisch", "Gemüse", "Obst"], correct: 1, hint: "tierisches Protein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'vegetables'?", answers: ["Obst", "Fleisch", "Gemüse", "Getreide"], correct: 2, hint: "pflanzliche Nahrung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chocolate'?", answers: ["Bonbon", "Schokolade", "Keks", "Kuchen"], correct: 1, hint: "Süßigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'coffee'?", answers: ["Tee", "Kakao", "Kaffee", "Milch"], correct: 2, hint: "koffeinhaltiges Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'soup'?", answers: ["Salat", "Suppe", "Soße", "Eintopf"], correct: 1, hint: "flüssiges Essen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'salad'?", answers: ["Suppe", "Salat", "Gemüse", "Obst"], correct: 1, hint: "Gemüsegericht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cheese'?", answers: ["Ei", "Milch", "Käse", "Wurst"], correct: 2, hint: "Gelb und herzhaft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'egg'?", answers: ["Ei", "Apfel", "Keks", "Nuss"], correct: 0, hint: "Vom Huhn", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'butter'?", answers: ["Margarine", "Öl", "Butter", "Schmalz"], correct: 2, hint: "Aufs Brot", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'juice'?", answers: ["Wasser", "Saft", "Tee", "Cola"], correct: 1, hint: "Aus Früchten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tea'?", answers: ["Kaffee", "Tee", "Kakao", "Saft"], correct: 1, hint: "Britisches Getränk", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'banana'?", answers: ["Apfel", "Birne", "Banane", "Kirsche"], correct: 2, hint: "Gelbe Frucht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'carrot'?", answers: ["Gurke", "Karotte", "Tomate", "Erbse"], correct: 1, hint: "Oranges Gemüse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'potato'?", answers: ["Kartoffel", "Tomate", "Zwiebel", "Reis"], correct: 0, hint: "Für Pommes", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sugar'?", answers: ["Salz", "Mehl", "Zucker", "Pfeffer"], correct: 2, hint: "Süß", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'salt'?", answers: ["Zucker", "Salz", "Essig", "Öl"], correct: 1, hint: "Weiß und würzig", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'honey'?", answers: ["Marmelade", "Honig", "Sirup", "Zucker"], correct: 1, hint: "Von Bienen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'fruit'?", answers: ["Gemüse", "Obst", "Fleisch", "Brot"], correct: 1, hint: "Äpfel, Birnen etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'chips' (BE)?", answers: ["Chips", "Pommes", "Kekse", "Nüsse"], correct: 1, hint: "Fish and ...", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'Gemüse' in English?", answers: ["fruit", "meat", "vegetables", "sausage"], correct: 2, hint: "Healthy plant food", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'Käse' in English?", answers: ["tea", "cheese", "milk", "butter"], correct: 1, hint: "Dairy product", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "What is 'Kartoffel' in English?", answers: ["potato", "tomato", "apple", "carrot"], correct: 0, hint: "Often used for fries", stats: { correct: 0, total: 0, difficulty: 1.0 } }
            ,
            { question: "Was bedeutet 'strawberry'?", answers: ["Himbeere", "Erdbeere", "Blaubeere", "Kirsche"], correct: 1, hint: "Rote Sommerfrucht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'cucumber'?", answers: ["Zucchini", "Gurke", "Paprika", "Tomate"], correct: 1, hint: "Grünes Gemüse für Salat", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'lemon'?", answers: ["Limette", "Zitrone", "Orange", "Grapefruit"], correct: 1, hint: "Gelb und sauer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'onion'?", answers: ["Zwiebel", "Knoblauch", "Lauch", "Karotte"], correct: 0, hint: "Macht Tränen beim Schneiden", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'garlic'?", answers: ["Zwiebel", "Schnittlauch", "Knoblauch", "Ingwer"], correct: 2, hint: "Starker Geruch", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'rice'?", answers: ["Nudeln", "Reis", "Getreide", "Mais"], correct: 1, hint: "Wichtig in Asien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'noodles'?", answers: ["Brot", "Nudeln", "Reis", "Pizza"], correct: 1, hint: "Pasta", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ham'?", answers: ["Speck", "Schinken", "Wurst", "Salami"], correct: 1, hint: "Vom Schwein", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'beef'?", answers: ["Schweinefleisch", "Hühnerfleisch", "Rindfleisch", "Lamm"], correct: 2, hint: "Vom Rind", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'delicious'?", answers: ["eklig", "scharf", "lecker", "süß"], correct: 2, hint: "Wenn das Essen gut schmeckt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hungry'?", answers: ["durstig", "müde", "hungrig", "satt"], correct: 2, hint: "Man will etwas essen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'thirsty'?", answers: ["hungrig", "durstig", "glücklich", "traurig"], correct: 1, hint: "Man will etwas trinken", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'breakfast'?", answers: ["Mittagessen", "Abendessen", "Frühstück", "Snack"], correct: 2, hint: "Die erste Mahlzeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dinner'?", answers: ["Frühstück", "Mittagessen", "Abendessen", "Nachtisch"], correct: 2, hint: "Mahlzeit am Abend", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'dessert'?", answers: ["Vorspeise", "Hauptspeise", "Nachtisch", "Getränk"], correct: 2, hint: "Etwas Süßes zum Schluss", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
