window.__subjectData_english_6r_travel = [
            { question: "Was bedeutet 'plane'?", answers: ["Zug", "Flugzeug", "Auto", "Schiff"], correct: 1, hint: "fliegt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'train'?", answers: ["Bus", "Zug", "Auto", "Fahrrad"], correct: 1, hint: "auf Schienen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'car'?", answers: ["Bus", "Zug", "Auto", "Schiff"], correct: 2, hint: "fährt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bus'?", answers: ["Zug", "Bus", "Auto", "Flugzeug"], correct: 1, hint: "öffentlich", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ship'?", answers: ["Boot", "Schiff", "U-Boot", "Kanu"], correct: 1, hint: "auf dem Wasser", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'holiday'?", answers: ["Wochenende", "Urlaub", "Alltag", "Arbeit"], correct: 1, hint: "Freizeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'hotel'?", answers: ["Restaurant", "Hotel", "Pension", "Hostel"], correct: 1, hint: "Unterkunft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'map'?", answers: ["Kompass", "Karte", "Plan", "Buch"], correct: 1, hint: "Orientierung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'ticket'?", answers: ["Pass", "Ticket", "Visum", "Karte"], correct: 1, hint: "Eintritt", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'journey'?", answers: ["Ausflug", "Reise", "Trip", "Tour"], correct: 1, hint: "Trip", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'suitcase'?", answers: ["Tasche", "Rucksack", "Koffer", "Beutel"], correct: 2, hint: "Gepäckstück", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'passport'?", answers: ["Visum", "Reisepass", "Ausweis", "Ticket"], correct: 1, hint: "Dokument", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'airport'?", answers: ["Bahnhof", "Hafen", "Flughafen", "Parkplatz"], correct: 2, hint: "Wo Flugzeuge landen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'station'?", answers: ["Hafen", "Bahnhof", "Flughafen", "Bushaltestelle"], correct: 1, hint: "Zug-Stopp", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'beach'?", answers: ["Wald", "Wiese", "Strand", "Berg"], correct: 2, hint: "Am Meer", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tourist'?", answers: ["Einheimischer", "Tourist", "Führer", "Gast"], correct: 1, hint: "Reisende Person", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'visit'?", answers: ["sehen", "bleiben", "besuchen", "wohnen"], correct: 2, hint: "Jemanden aufsuchen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'flight'?", answers: ["Fahrt", "Reise", "Flug", "Gang"], correct: 2, hint: "In der Luft", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'museum'?", answers: ["Kino", "Theater", "Museum", "Galerie"], correct: 2, hint: "Alte Dinge ansehen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'souvenir'?", answers: ["Geschenk", "Essen", "Andenken", "Kleidung"], correct: 2, hint: "Mitbringsel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'bicycle'?", answers: ["Fahrrad", "Motorrad", "Auto", "Bus"], correct: 0, hint: "Zwei Räder, kein Motor.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'travel'?", answers: ["reisen", "bleiben", "wohnen", "arbeiten"], correct: 0, hint: "Einen Trip machen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'tent'?", answers: ["Haus", "Zelt", "Hotel", "Wohnwagen"], correct: 1, hint: "Man schläft darin beim Campen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'passenger'?", answers: ["Fahrer", "Passagier", "Pilot", "Kapitän"], correct: 1, hint: "Jemand, der mitfährt.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'platform'?", answers: ["Gleis", "Zug", "Ticket", "Bahnhof"], correct: 0, hint: "Hier wartet man auf den Zug.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'arrive'?", answers: ["abfahren", "ankommen", "warten", "fliegen"], correct: 1, hint: "Das Ziel erreichen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'depart'?", answers: ["ankommen", "abfahren", "bleiben", "besuchen"], correct: 1, hint: "Einen Ort verlassen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'sightseeing'?", answers: ["Einkaufen", "Besichtigung von Sehenswürdigkeiten", "Schwimmen", "Wandern"], correct: 1, hint: "Die Stadt erkunden.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'abroad'?", answers: ["zu Hause", "im Ausland", "nebenan", "weit weg"], correct: 1, hint: "In einem anderen Land.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'underground'?", answers: ["Bus", "U-Bahn", "Taxi", "Fähre"], correct: 1, hint: "Fährt unter der Erde.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'camera'?", answers: ["Handy", "Kamera", "Computer", "Fernseher"], correct: 1, hint: "Damit macht man Fotos.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'pack'?", answers: ["kaufen", "packen (Koffer)", "tragen", "schicken"], correct: 1, hint: "Dinge in den Koffer tun.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'luggage'?", answers: ["Kleidung", "Gepäck", "Tasche", "Auto"], correct: 1, hint: "Koffer und Taschen zusammen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'lost'?", answers: ["gefunden", "verloren", "gesucht", "gekauft"], correct: 1, hint: "Den Weg nicht mehr kennen.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'guidebook'?", answers: ["Roman", "Reiseführer (Buch)", "Heft", "Atlas"], correct: 1, hint: "Buch mit Infos über den Urlaubsort.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
            { question: "Was bedeutet 'country'?", answers: ["Stadt", "Land", "Dorf", "Fluss"], correct: 1, hint: "Deutschland, Spanien, etc.", stats: { correct: 0, total: 0, difficulty: 1.0 } }
        ];
