window.__subjectData_chem_9g_atome_elemente = [
    { question: "Wie viele Protonen hat ein Wasserstoffatom?", answers: ["0", "1", "2", "4"], correct: 1, hint: "Ordnungszahl 1", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was gibt die Ordnungszahl an?", answers: ["Die Anzahl der Neutronen", "Die Anzahl der Protonen", "Die Masse des Atoms", "Die Anzahl der Elektronenschalen"], correct: 1, hint: "Position im Periodensystem", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was gibt die Massenzahl an?", answers: ["Protonen + Neutronen", "Nur Protonen", "Nur Neutronen", "Elektronen + Protonen"], correct: 0, hint: "Summe der Kernbausteine", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Isotop?", answers: ["Atom mit gleicher Protonen-, aber unterschiedlicher Neutronenzahl", "Atom mit unterschiedlicher Elektronenzahl", "Ein geladenes Atom", "Ein Molekül"], correct: 0, hint: "Gleiches Element, andere Masse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Elektronen passen auf die erste Schale?", answers: ["2", "8", "18", "4"], correct: 0, hint: "K-Schale", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Ion?", answers: ["Ein geladenes Atom oder Molekül", "Ein neutrales Atom", "Ein Atomkern", "Ein Isotop"], correct: 0, hint: "Elektronenüberschuss oder -mangel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Edelgas hat die Ordnungszahl 18?", answers: ["Helium", "Neon", "Argon", "Krypton"], correct: 2, hint: "3. Periode, 8. Hauptgruppe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie ist das Periodensystem angeordnet?", answers: ["Nach steigender Ordnungszahl und Perioden", "Nach Masse", "Nach Entdeckungsdatum", "Alphabetisch"], correct: 0, hint: "Mendelejew", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was besagt das Oktett-Oktett-Prinzip?", answers: ["Atome streben 8 Außenelektronen an", "Atome haben 8 Neutronen", "Moleküle sind 8-fach gebunden", "Es gibt 8 Hauptgruppen"], correct: 0, hint: "Edelgaskonfiguration", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Bindung tritt zwischen Metall und Nichtmetall auf?", answers: ["Ionenbindung", "Elektronenpaarbindung", "Metallbindung", "Wasserstoffbrücke"], correct: 0, hint: "Elektronenübertragung", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Molekül?", answers: ["Ein Verband aus zwei oder mehr Atomen", "Ein einzelnes Atom", "Ein Atomkern", "Ein Ion"], correct: 0, hint: "z.B. H₂O, CO₂", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Teilchen bestimmt die chemischen Eigenschaften?", answers: ["Protonen", "Elektronen", "Neutronen", "Atomkern"], correct: 1, hint: "Außenelektronen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie nennt man die Elektronen in der äußersten Schale?", answers: ["Rumpfelektronen", "Valenzelektronen", "Leitungselektronen", "Kernelektronen"], correct: 1, hint: "Bestimmen die Wertigkeit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Atomkern?", answers: ["Besteht aus Protonen und Neutronen", "Besteht nur aus Protonen", "Besteht aus Elektronen", "Besteht aus Neutronen"], correct: 0, hint: "Positive Ladung", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];