window.__subjectData_chem_9g_reaktionen = [
    { question: "Was ist eine exotherme Reaktion?", answers: ["Energie wird aufgenommen", "Energie wird freigesetzt", "Es passiert nichts", "Nur im Dunkeln"], correct: 1, hint: "Verbrennung ist ein Beispiel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Katalysator?", answers: ["Ein Stoff, der die Reaktion beschleunigt", "Ein Stoff, der die Reaktion stoppt", "Ein Reaktionsprodukt", "Ein Ausgangsstoff"], correct: 0, hint: "Bleibt unverändert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine endotherme Reaktion?", answers: ["Energie wird freigesetzt", "Wärme wird aufgenommen", "Die Reaktion findet nicht statt", "Es entsteht Licht"], correct: 1, hint: "Gegenteil von exotherm", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was besagt der Energieerhaltungssatz?", answers: ["Energie kann nicht verloren gehen, nur umgewandelt werden", "Energie entsteht neu", "Energie verschwindet", "Nur Wärme bleibt erhalten"], correct: 0, hint: "1. Hauptsatz der Thermodynamik", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Aktivierungsenergie?", answers: ["Die Energie, die zum Start einer Reaktion nötig ist", "Die freigesetzte Energie", "Die Energie der Produkte", "Die Abwärme"], correct: 0, hint: "Startschwelle", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie heißt die Reaktion von Methan mit Sauerstoff?", answers: ["Verbrennung / Oxidation", "Reduktion", "Säure-Base-Reaktion", "Neutralisation"], correct: 0, hint: "CH₄ + 2 O₂ -> CO₂ + 2 H₂O", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Redoxreaktion'?", answers: ["Gleichzeitige Oxidation und Reduktion", "Nur Oxidation", "Nur Reduktion", "Keine Elektronenübertragung"], correct: 0, hint: "Elektronenübergang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Oxidation?", answers: ["Ein Stoff gibt Elektronen ab", "Ein Stoff nimmt Elektronen auf", "Es entsteht Säure", "Es entsteht eine Base"], correct: 0, hint: "Oxidation = Elektronenabgabe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Reduktion?", answers: ["Ein Stoff gibt Elektronen ab", "Ein Stoff nimmt Elektronen auf", "Es entsteht Sauerstoff", "Es entsteht Wasser"], correct: 1, hint: "Reduktion = Elektronenaufnahme", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Faktoren beeinflussen die Reaktionsgeschwindigkeit?", answers: ["Temperatur, Konzentration, Oberfläche, Katalysator", "Nur Temperatur", "Nur der Katalysator", "Nur die Farbe"], correct: 0, hint: "Zerteilungsgrad", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Synthese?", answers: ["Zusammensetzung aus Elementen zu einer Verbindung", "Zerlegung einer Verbindung", "Austausch von Ionen", "Verbrennung"], correct: 0, hint: "A + B -> AB", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist eine Analyse?", answers: ["Zerlegung einer Verbindung in ihre Elemente", "Aufbau einer Verbindung", "Eine Neutralisation", "Eine Verbrennung"], correct: 0, hint: "AB -> A + B", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Aussage zum Katalysator ist korrekt?", answers: ["Er geht unverändert aus der Reaktion hervor", "Er wird verbraucht", "Er ändert das Produkt", "Er verhindert die Reaktion"], correct: 0, hint: "Senkt die Aktivierungsenergie", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die 'Verbrennungswärme'?", answers: ["Die bei der Verbrennung freigesetzte Wärmeenergie", "Die Temperatur der Flamme", "Die benötigte Zündenergie", "Die Abkühlung"], correct: 0, hint: "Exotherme Reaktion", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];