window.__subjectData_eng_7r_reading = [
    { question: "What is the main idea of a text?", answers: ["The title", "The most important message", "The first sentence", "The last word"], correct: 1, hint: "Think about what the text wants to tell you", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'scanning' mean in reading?", answers: ["Reading every word", "Looking for specific information", "Reading aloud", "Summarizing"], correct: 1, hint: "Fast reading technique", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a synonym for 'to summarize'?", answers: ["to describe", "to outline", "to repeat", "to translate"], correct: 1, hint: "Give the main points briefly", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the purpose of a headline?", answers: ["To give details", "To catch attention and state the topic", "To end the text", "To ask a question"], correct: 1, hint: "What you read first in an article", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'skimming' mean?", answers: ["Reading very slowly", "Reading to get a general idea", "Reading every detail", "Reading backwards"], correct: 1, hint: "Quick overview reading", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'point of view' in a story?", answers: ["The place where the story happens", "The perspective of the narrator", "The time of the story", "The main character"], correct: 1, hint: "Who tells the story", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is the best strategy to understand unknown words?", answers: ["Ignore them", "Look at the context", "Count the letters", "Skip the sentence"], correct: 1, hint: "Use surrounding words for clues", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'infer' mean?", answers: ["to read", "to guess from clues", "to write", "to delete"], correct: 1, hint: "Read between the lines", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'fact' in a text?", answers: ["An opinion", "Something that can be proven", "A feeling", "A question"], correct: 1, hint: "True information", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is an 'opinion' in a text?", answers: ["A proven fact", "A personal belief or view", "A scientific law", "A date"], correct: 1, hint: "What someone thinks", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What does 'plot' mean in a story?", answers: ["The place", "The sequence of events", "The characters", "The moral"], correct: 1, hint: "What happens in the story", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "What is a 'character trait'?", answers: ["A physical description", "A quality or feature of a person", "The character's name", "The character's job"], correct: 1, hint: "e.g. brave, honest, kind", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];