window.__subjectData_eng_7r_textaufgaben_verstehen = [
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Tom lives in London. He is 14 years old. His school starts at 8:30 am. Tom has a dog named Max.", secondaryQuestion: "Which info is NOT important for 'What time does school start?'", answers: ["London", "8:30 am", "14 years old", "Tom's dog Max"], correct: 3, hint: "Only the time matters.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "Emma buys 3 pens for £1.20 each and a notebook for £2.50. She pays with a £10 note.", possibleQuestions: ["What colour are the pens?", "How much change does Emma get?", "Where did Emma buy the pens?"], answers: ["What colour are the pens?", "How much change does Emma get?", "Where did Emma buy the pens?"], correct: 1, hint: "Look for a mathematical question.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Lisa wakes up at 7:00. She takes 20 minutes to get dressed. Breakfast takes 15 minutes. Walking to school takes 25 minutes. School starts at 8:30.", secondaryQuestion: "Which facts do you need for 'Does Lisa arrive on time?'", answers: ["Wake-up time + dressing + breakfast + walking + school start", "Only the school start time", "Walking time + breakfast time", "Dressing + breakfast"], correct: 0, hint: "Add up all morning activities.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "There are 28 students in class 7a and 25 students in class 7b. 12 students from 7a and 10 from 7b are going on a trip.", possibleQuestions: ["How many students are in class 7b?", "How many students are going on the trip in total?", "What is the name of the teacher?"], answers: ["How many students are in class 7b?", "How many students are going on the trip in total?", "What is the name of the teacher?"], correct: 1, hint: "Add the number of students on the trip.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "Sam reads 5 pages of his book on Monday, 8 pages on Tuesday, and 12 pages on Wednesday. He wants to finish 50 pages by Friday. The book has 200 pages.", secondaryQuestion: "Which info is NOT needed for 'How many pages has Sam read so far?'", answers: ["5 pages on Monday", "50 pages by Friday", "12 pages on Wednesday", "8 pages on Tuesday"], correct: 1, hint: "Only the pages already read matter.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "units_detective", question: "📏 EINHEITEN-Prüfung!", fullText: "The distance from London to Manchester is about 300. A bottle of water contains 500. My bedroom is 4 wide.", secondaryQuestion: "Which unit fits all gaps correctly?", answers: ["km, ml, m", "m, l, km", "cm, ml, m", "km, l, cm"], correct: 0, hint: "Think about typical measurements.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->TERM übersetzen!", fullText: "Anna has twice as many stickers as Ben. Ben has 15 stickers. How many stickers do they have together?", secondaryQuestion: "Which calculation is correct?", answers: ["15 + 15 × 2", "15 + (2 × 15)", "2 × 15 + 2 × 15", "15 × 2 + 15 × 2"], correct: 1, hint: "Twice as many = multiply by 2.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "info_jigsaw", question: "🧩 NÖTIGE INFOS finden!", fullText: "Max wants to buy a game that costs £45. He saves £5 per week from his pocket money. He already has £15 from his birthday.", secondaryQuestion: "What do you need to calculate how many more weeks Max needs to save?", answers: ["£45 game, £5/week, £15 saved", "£45 game, £5/week", "£15 saved, £5/week", "Only the game price"], correct: 0, hint: "Price - savings = remaining, then divide by weekly savings.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_hunter", question: "🔍 FRAGE erkennen!", fullText: "A recipe needs 200g flour, 100g sugar, 50g butter, and 2 eggs. Sarah has 500g flour, 300g sugar, 200g butter, and 6 eggs.", possibleQuestions: ["Does Sarah like cooking?", "How many portions can Sarah make?", "What colour are the eggs?"], answers: ["Does Sarah like cooking?", "How many portions can Sarah make?", "What colour are the eggs?"], correct: 1, hint: "Think about ingredients vs. available amounts.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "text_surgeon", question: "❌ ABLENKUNG erkennen!", fullText: "A train leaves at 9:15 am and arrives at 11:45 am. The train has 8 carriages and can carry 400 passengers. Tickets cost £25 per person.", secondaryQuestion: "Which info is NOT needed for 'How long is the journey?'", answers: ["9:15 am departure", "400 passengers", "11:45 am arrival", "2 hours 30 minutes"], correct: 1, hint: "Only departure and arrival times are needed.", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { mode: "question_clarity", question: "✂️ TEXT->TERM übersetzen!", fullText: "A jacket costs £80. It is on sale with 25% off. How much do you pay?", secondaryQuestion: "Which calculation is correct?", answers: ["80 - 25", "80 × 0.25", "80 × 0.75", "80 / 4"], correct: 2, hint: "25% off means you pay 75% of the price.", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];