window.__subjectData_bio_7r_oekosysteme = [
    { question: "Was ist ein Ökosystem?", answers: ["Ein Aquarium", "Ein Lebensraum mit allen Lebewesen", "Ein Tierpark", "Ein Wald"], correct: 1, hint: "Biotop + Biozönose", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind Produzenten in einem Ökosystem?", answers: ["Tiere", "Pflanzen", "Pilze", "Bakterien"], correct: 1, hint: "Sie betreiben Fotosynthese", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind Konsumenten erster Ordnung?", answers: ["Pflanzenfresser", "Fleischfresser", "Zersetzer", "Pflanzen"], correct: 0, hint: "Sie fressen Produzenten", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was sind Destruenten (Zersetzer)?", answers: ["Tiere, die Pflanzen fressen", "Bakterien und Pilze, die totes Material zersetzen", "Große Raubtiere", "Pflanzen"], correct: 1, hint: "Sie recyclen Nährstoffe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein Nahrungsnetz?", answers: ["Eine einzelne Nahrungskette", "Ein Netz aus vielen verbundenen Nahrungsketten", "Ein Netz zum Fischen", "Eine Liste von Tieren"], correct: 1, hint: "komplexere Beziehungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Biotop'?", answers: ["Alle Lebewesen eines Lebensraums", "Der Lebensraum selbst", "Ein Zoo", "Ein Aquarium"], correct: 1, hint: "Der Ort, an dem Lebewesen leben", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was versteht man unter 'Biozönose'?", answers: ["Der Lebensraum", "Die Lebensgemeinschaft aller Organismen", "Ein See", "Ein Wald"], correct: 1, hint: "Alle Tiere + Pflanzen eines Biotops", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Ökosystem hat die größte Artenvielfalt?", answers: ["Nadelwald", "Tropischer Regenwald", "Wüste", "Stadt"], correct: 1, hint: "In Äquatornähe", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert, wenn eine Art in einem Ökosystem ausstirbt?", answers: ["Das Ökosystem bleibt gleich", "Das Gleichgewicht kann gestört werden", "Alle anderen Arten sterben auch", "Nichts passiert"], correct: 1, hint: "Nahrungsnetz wird unterbrochen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Kreislauf der Stoffe' in der Natur?", answers: ["Nährstoffe werden recycelt", "Alles wird Müll", "Stoffe verschwinden", "Nur Pflanzen brauchen Nährstoffe"], correct: 0, hint: "Zersetzung, Mineralisierung, Aufnahme", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Rolle spielen Bäume im Ökosystem Wald?", answers: ["Nur Schatten", "Produzenten, Sauerstoffproduktion, Lebensraum", "Nur Lebensraum", "Nur Sauerstoff"], correct: 1, hint: "Fotosynthese", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist das 'ökologische Gleichgewicht'?", answers: ["Ein statischer Zustand", "Ein dynamisches Gleichgewicht zwischen Arten", "Immer gleich viele Tiere", "Keine Veränderung"], correct: 1, hint: "Regulation durch Wechselwirkungen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist ein 'Parasit'?", answers: ["Ein Organismus, der einem anderen schadet", "Ein Organismus, der hilft", "Ein Beutetier", "Ein Zersetzer"], correct: 0, hint: "Bandwurm, Zecke", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Ökosystem ist durch Menschen besonders bedroht?", answers: ["Hochgebirge", "Regenwald", "Tiefsee", "Wüste"], correct: 1, hint: "Abholzung und Brandrodung", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];