window.__subjectData_bio_7r_sinne = [
    { question: "Welcher Teil des Auges bündelt das Licht?", answers: ["Netzhaut", "Linse", "Pupille", "Sehnerv"], correct: 1, hint: "Sammellinse", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wo befindet sich das Gleichgewichtsorgan?", answers: ["Im Auge", "Im Ohr", "In der Nase", "In der Zunge"], correct: 1, hint: "Innenohr", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Teil des Ohrs wandelt Schall in Signale um?", answers: ["Ohrmuschel", "Hörnerv", "Gehörknöchelchen", "Trommelfell"], correct: 2, hint: "Im Innenohr", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie viele Zapfenarten hat das menschliche Auge?", answers: ["1", "2", "3", "4"], correct: 2, hint: "Rot, Grün, Blau", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wofür sind die Stäbchen im Auge zuständig?", answers: ["Farbsehen", "Hell-Dunkel-Sehen", "Sehen von Formen", "Entfernungen schätzen"], correct: 1, hint: "Bei schwachem Licht", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Sinn befindet sich in der Nase?", answers: ["Geschmack", "Geruch", "Tastsinn", "Gehör"], correct: 1, hint: "Riechschleimhaut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der Tastsinn?", answers: ["Wahrnehmung von Druck, Temperatur und Schmerz", "Nur Druck", "Nur Temperatur", "Nur Schmerz"], correct: 0, hint: "In der Haut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Geschmacksrichtungen kann der Mensch unterscheiden?", answers: ["Süß, salzig, sauer, bitter, umami", "Nur süß und salzig", "Scharf, kalt, warm", "Nur bitter"], correct: 0, hint: "Fünf Grundgeschmäcker", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei Kurzsichtigkeit?", answers: ["Das Bild entsteht hinter der Netzhaut", "Das Bild entsteht vor der Netzhaut", "Die Linse fehlt", "Der Sehnerv ist beschädigt"], correct: 1, hint: "Augapfel zu lang", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Organ wandelt Schallwellen in Gehirnsignale um?", answers: ["Trommelfell", "Gehirn", "Innenohr (Corti-Organ)", "Ohrmuschel"], correct: 2, hint: "Haarzellen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie schützt sich das Auge vor zu hellem Licht?", answers: ["Die Pupille verengt sich", "Die Linse wird dicker", "Das Auge schließt sich", "Die Netzhaut wird dunkler"], correct: 0, hint: "Regenbogenhaut steuert", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Bereich der Zunge erkennt Bitteres?", answers: ["Vorne", "Hinten", "Seiten", "Mitte"], correct: 1, hint: "Geschmacksknospen am Zungengrund", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist der blinde Fleck im Auge?", answers: ["Stelle mit den meisten Zapfen", "Austrittspunkt des Sehnervs (keine Rezeptoren)", "Die Pupille", "Der Bereich scharfes Sehens"], correct: 1, hint: "Dort gibt es keine Lichtsinneszellen", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welchen Sinn nutzt man zum Lesen einer Braille-Schrift?", answers: ["Sehsinn", "Tastsinn", "Hörsinn", "Geruchssinn"], correct: 1, hint: "Punktschrift für Blinde", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];