window.__subjectData_bio_7r_stoffwechsel = [
    { question: "Wofür ist der Dünndarm zuständig?", answers: ["Wasserentzug", "Nährstoffaufnahme", "Zerkleinerung", "Ausscheidung"], correct: 1, hint: "Nährstoffe ins Blut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Organ ist für den Gasaustausch zuständig?", answers: ["Herz", "Lunge", "Leber", "Niere"], correct: 1, hint: "Sauerstoff ins Blut, CO2 raus", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wofür ist der Magen zuständig?", answers: ["Nährstoffaufnahme", "Zerkleinerung und Vorverdauung", "Ausscheidung", "Wasserentzug"], correct: 1, hint: "Magensäure und Muskeln", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Aufgabe hat die Leber?", answers: ["Nährstoffe aufnehmen", "Giftstoffe abbauen und Speicherung", "Sauerstoff aufnehmen", "Blut pumpen"], correct: 1, hint: "Zentrales Stoffwechselorgan", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Hauptaufgabe der Nieren?", answers: ["Verdauung", "Blutreinigung und Ausscheidung von Harn", "Gasaustausch", "Nährstoffaufnahme"], correct: 1, hint: "Filter für das Blut", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welche Nährstoffe liefern am meisten Energie?", answers: ["Kohlenhydrate", "Fette", "Vitamine", "Proteine"], correct: 1, hint: "9 kcal pro Gramm", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wofür werden Proteine benötigt?", answers: ["Nur als Energielieferant", "Aufbau von Muskeln und Gewebe", "Nur für Knochen", "Nur für die Verdauung"], correct: 1, hint: "Bausteine des Körpers", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was ist die Hauptaufgabe des Dickdarms?", answers: ["Nährstoffaufnahme", "Wasserentzug aus dem Speisebrei", "Verdauung von Fetten", "Zerkleinerung"], correct: 1, hint: "Eindickung des Stuhls", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welches Vitamin wird durch Sonnenlicht in der Haut gebildet?", answers: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], correct: 2, hint: "Knochengesundheit", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Was passiert bei der Zellatmung?", answers: ["Aufnahme von Wasser", "Verbrennung von Glucose zur Energiegewinnung", "Aufnahme von Vitaminen", "Ausscheidung"], correct: 1, hint: "Mitochondrien", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wo beginnt die Verdauung von Kohlenhydraten?", answers: ["Im Magen", "Bereits im Mund (Speichel)", "Im Dünndarm", "Im Dickdarm"], correct: 1, hint: "Amylase im Speichel", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Welcher Blutbestandteil transportiert Sauerstoff?", answers: ["Weiße Blutkörperchen", "Rote Blutkörperchen", "Blutplättchen", "Blutplasma"], correct: 1, hint: "Hämoglobin", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wofür sind Ballaststoffe wichtig?", answers: ["Energie", "Verdauung und Darmgesundheit", "Muskelaufbau", "Immunsystem"], correct: 1, hint: "Pflanzliche Fasern", stats: { correct: 0, total: 0, difficulty: 1.0 } },
    { question: "Wie gelangen Nährstoffe aus dem Darm ins Blut?", answers: ["Über den Magen", "Über die Darmzotten (Villi)", "Direkt in die Leber", "Über die Bauchspeicheldrüse"], correct: 1, hint: "Vergrößerte Oberfläche", stats: { correct: 0, total: 0, difficulty: 1.0 } }
];